	.align 2
	.global DirectSoundData_082263B4
DirectSoundData_082263B4:
	.incbin "sound/direct_sound_samples/082263B4.bin"

	.align 2
	.global DirectSoundData_08227988
DirectSoundData_08227988:
	.incbin "sound/direct_sound_samples/08227988.bin"

	.align 2
	.global DirectSoundData_0822807C
DirectSoundData_0822807C:
	.incbin "sound/direct_sound_samples/0822807C.bin"

	.align 2
	.global DirectSoundData_08228C7C
DirectSoundData_08228C7C:
	.incbin "sound/direct_sound_samples/08228C7C.bin"

	.align 2
	.global DirectSoundData_0822B4DC
DirectSoundData_0822B4DC:
	.incbin "sound/direct_sound_samples/0822B4DC.bin"

	.align 2
	.global DirectSoundData_08233650
DirectSoundData_08233650:
	.incbin "sound/direct_sound_samples/08233650.bin"

	.align 2
	.global DirectSoundData_082367A8
DirectSoundData_082367A8:
	.incbin "sound/direct_sound_samples/082367A8.bin"

	.align 2
	.global DirectSoundData_0823B5FC
DirectSoundData_0823B5FC:
	.incbin "sound/direct_sound_samples/0823B5FC.bin"

	.align 2
	.global DirectSoundData_0823F698
DirectSoundData_0823F698:
	.incbin "sound/direct_sound_samples/0823F698.bin"

	.align 2
	.global DirectSoundData_08243A54
DirectSoundData_08243A54:
	.incbin "sound/direct_sound_samples/08243A54.bin"

	.align 2
	.global DirectSoundData_08247AE8
DirectSoundData_08247AE8:
	.incbin "sound/direct_sound_samples/08247AE8.bin"

	.align 2
	.global DirectSoundData_0824BBAC
DirectSoundData_0824BBAC:
	.incbin "sound/direct_sound_samples/0824BBAC.bin"

	.align 2
	.global DirectSoundData_0825305C
DirectSoundData_0825305C:
	.incbin "sound/direct_sound_samples/0825305C.bin"

	.align 2
	.global DirectSoundData_082595BC
DirectSoundData_082595BC:
	.incbin "sound/direct_sound_samples/082595BC.bin"

	.align 2
	.global DirectSoundData_08261150
DirectSoundData_08261150:
	.incbin "sound/direct_sound_samples/08261150.bin"

	.align 2
	.global DirectSoundData_08265DDC
DirectSoundData_08265DDC:
	.incbin "sound/direct_sound_samples/08265DDC.bin"

	.align 2
	.global DirectSoundData_0826CFD0
DirectSoundData_0826CFD0:
	.incbin "sound/direct_sound_samples/0826CFD0.bin"

	.align 2
	.global DirectSoundData_08274F48
DirectSoundData_08274F48:
	.incbin "sound/direct_sound_samples/08274F48.bin"

	.align 2
	.global DirectSoundData_0827BBD0
DirectSoundData_0827BBD0:
	.incbin "sound/direct_sound_samples/0827BBD0.bin"

	.align 2
	.global DirectSoundData_0827E28C
DirectSoundData_0827E28C:
	.incbin "sound/direct_sound_samples/0827E28C.bin"

	.align 2
	.global DirectSoundData_0827E640
DirectSoundData_0827E640:
	.incbin "sound/direct_sound_samples/0827E640.bin"

	.align 2
	.global DirectSoundData_08280AF0
DirectSoundData_08280AF0:
	.incbin "sound/direct_sound_samples/08280AF0.bin"

	.align 2
	.global DirectSoundData_08281974
DirectSoundData_08281974:
	.incbin "sound/direct_sound_samples/08281974.bin"

	.align 2
	.global DirectSoundData_08281DD0
DirectSoundData_08281DD0:
	.incbin "sound/direct_sound_samples/08281DD0.bin"

	.align 2
	.global DirectSoundData_08287CC4
DirectSoundData_08287CC4:
	.incbin "sound/direct_sound_samples/08287CC4.bin"

	.align 2
	.global DirectSoundData_08288F7C
DirectSoundData_08288F7C:
	.incbin "sound/direct_sound_samples/08288F7C.bin"

	.align 2
	.global DirectSoundData_08289978
DirectSoundData_08289978:
	.incbin "sound/direct_sound_samples/08289978.bin"

	.align 2
	.global DirectSoundData_0828B404
DirectSoundData_0828B404:
	.incbin "sound/direct_sound_samples/0828B404.bin"

	.align 2
	.global DirectSoundData_0828CD70
DirectSoundData_0828CD70:
	.incbin "sound/direct_sound_samples/0828CD70.bin"

	.align 2
	.global DirectSoundData_0828DDD0
DirectSoundData_0828DDD0:
	.incbin "sound/direct_sound_samples/0828DDD0.bin"

	.align 2
	.global DirectSoundData_0828F524
DirectSoundData_0828F524:
	.incbin "sound/direct_sound_samples/0828F524.bin"

	.align 2
	.global DirectSoundData_082903C8
DirectSoundData_082903C8:
	.incbin "sound/direct_sound_samples/082903C8.bin"

	.align 2
	.global DirectSoundData_08293544
DirectSoundData_08293544:
	.incbin "sound/direct_sound_samples/08293544.bin"

	.align 2
	.global DirectSoundData_082962B0
DirectSoundData_082962B0:
	.incbin "sound/direct_sound_samples/082962B0.bin"

	.align 2
	.global DirectSoundData_08296E54
DirectSoundData_08296E54:
	.incbin "sound/direct_sound_samples/08296E54.bin"

	.align 2
	.global DirectSoundData_0829918C
DirectSoundData_0829918C:
	.incbin "sound/direct_sound_samples/0829918C.bin"

	.align 2
	.global DirectSoundData_0829A1EC
DirectSoundData_0829A1EC:
	.incbin "sound/direct_sound_samples/0829A1EC.bin"

	.align 2
	.global DirectSoundData_0829ED58
DirectSoundData_0829ED58:
	.incbin "sound/direct_sound_samples/0829ED58.bin"

	.align 2
	.global DirectSoundData_082A0690
DirectSoundData_082A0690:
	.incbin "sound/direct_sound_samples/082A0690.bin"

	.align 2
	.global DirectSoundData_082A1728
DirectSoundData_082A1728:
	.incbin "sound/direct_sound_samples/082A1728.bin"

	.align 2
	.global DirectSoundData_082A7AA8
DirectSoundData_082A7AA8:
	.incbin "sound/direct_sound_samples/082A7AA8.bin"

	.align 2
	.global DirectSoundData_082A8068
DirectSoundData_082A8068:
	.incbin "sound/direct_sound_samples/082A8068.bin"

	.align 2
	.global DirectSoundData_082AC224
DirectSoundData_082AC224:
	.incbin "sound/direct_sound_samples/082AC224.bin"

	.align 2
	.global DirectSoundData_082AC868
DirectSoundData_082AC868:
	.incbin "sound/direct_sound_samples/082AC868.bin"

	.align 2
	.global DirectSoundData_082ADD3C
DirectSoundData_082ADD3C:
	.incbin "sound/direct_sound_samples/082ADD3C.bin"

	.align 2
	.global DirectSoundData_082AE988
DirectSoundData_082AE988:
	.incbin "sound/direct_sound_samples/082AE988.bin"

	.align 2
	.global DirectSoundData_082AF0B0
DirectSoundData_082AF0B0:
	.incbin "sound/direct_sound_samples/082AF0B0.bin"

	.align 2
	.global DirectSoundData_082B235C
DirectSoundData_082B235C:
	.incbin "sound/direct_sound_samples/082B235C.bin"

	.align 2
	.global DirectSoundData_082B3F54
DirectSoundData_082B3F54:
	.incbin "sound/direct_sound_samples/082B3F54.bin"

	.align 2
	.global DirectSoundData_082BA464
DirectSoundData_082BA464:
	.incbin "sound/direct_sound_samples/082BA464.bin"

	.align 2
	.global DirectSoundData_082BB7F4
DirectSoundData_082BB7F4:
	.incbin "sound/direct_sound_samples/082BB7F4.bin"

	.align 2
	.global DirectSoundData_082C0D0C
DirectSoundData_082C0D0C:
	.incbin "sound/direct_sound_samples/082C0D0C.bin"

	.align 2
	.global DirectSoundData_082C24A8
DirectSoundData_082C24A8:
	.incbin "sound/direct_sound_samples/082C24A8.bin"

	.align 2
	.global DirectSoundData_082C5874
DirectSoundData_082C5874:
	.incbin "sound/direct_sound_samples/082C5874.bin"

	.align 2
	.global DirectSoundData_082C6A4C
DirectSoundData_082C6A4C:
	.incbin "sound/direct_sound_samples/082C6A4C.bin"

	.align 2
	.global DirectSoundData_082C6DB8
DirectSoundData_082C6DB8:
	.incbin "sound/direct_sound_samples/082C6DB8.bin"

	.align 2
	.global DirectSoundData_082CAC80
DirectSoundData_082CAC80:
	.incbin "sound/direct_sound_samples/082CAC80.bin"

	.align 2
	.global DirectSoundData_082CB2F8
DirectSoundData_082CB2F8:
	.incbin "sound/direct_sound_samples/082CB2F8.bin"

	.align 2
	.global DirectSoundData_082CBE8C
DirectSoundData_082CBE8C:
	.incbin "sound/direct_sound_samples/082CBE8C.bin"

	.align 2
	.global DirectSoundData_082CD7F4
DirectSoundData_082CD7F4:
	.incbin "sound/direct_sound_samples/082CD7F4.bin"

	.align 2
	.global DirectSoundData_082CF3B0
DirectSoundData_082CF3B0:
	.incbin "sound/direct_sound_samples/082CF3B0.bin"

	.align 2
	.global DirectSoundData_082D0018
DirectSoundData_082D0018:
	.incbin "sound/direct_sound_samples/082D0018.bin"

	.align 2
	.global DirectSoundData_082D0414
DirectSoundData_082D0414:
	.incbin "sound/direct_sound_samples/082D0414.bin"

	.align 2
	.global DirectSoundData_082D0964
DirectSoundData_082D0964:
	.incbin "sound/direct_sound_samples/082D0964.bin"

	.align 2
	.global DirectSoundData_082D0C08
DirectSoundData_082D0C08:
	.incbin "sound/direct_sound_samples/082D0C08.bin"

	.align 2
	.global DirectSoundData_082D1238
DirectSoundData_082D1238:
	.incbin "sound/direct_sound_samples/082D1238.bin"

	.align 2
	.global DirectSoundData_082D1818
DirectSoundData_082D1818:
	.incbin "sound/direct_sound_samples/082D1818.bin"

	.align 2
	.global DirectSoundData_082D2050
DirectSoundData_082D2050:
	.incbin "sound/direct_sound_samples/082D2050.bin"

	.align 2
	.global DirectSoundData_082D293C
DirectSoundData_082D293C:
	.incbin "sound/direct_sound_samples/082D293C.bin"

	.align 2
	.global DirectSoundData_082D2EA4
DirectSoundData_082D2EA4:
	.incbin "sound/direct_sound_samples/082D2EA4.bin"

	.align 2
	.global DirectSoundData_082D3020
DirectSoundData_082D3020:
	.incbin "sound/direct_sound_samples/082D3020.bin"

	.align 2
	.global DirectSoundData_082D4BE4
DirectSoundData_082D4BE4:
	.incbin "sound/direct_sound_samples/082D4BE4.bin"

	.align 2
	.global DirectSoundData_082D6BA0
DirectSoundData_082D6BA0:
	.incbin "sound/direct_sound_samples/082D6BA0.bin"

	.align 2
	.global DirectSoundData_082D712C
DirectSoundData_082D712C:
	.incbin "sound/direct_sound_samples/082D712C.bin"

	.align 2
	.global DirectSoundData_082D80E0
DirectSoundData_082D80E0:
	.incbin "sound/direct_sound_samples/082D80E0.bin"

	.align 2
	.global DirectSoundData_082DB668
DirectSoundData_082DB668:
	.incbin "sound/direct_sound_samples/082DB668.bin"

	.align 2
	.global DirectSoundData_082DE9D8
DirectSoundData_082DE9D8:
	.incbin "sound/direct_sound_samples/082DE9D8.bin"

	.align 2
	.global DirectSoundData_082E2F6C
DirectSoundData_082E2F6C:
	.incbin "sound/direct_sound_samples/082E2F6C.bin"

	.align 2
	.global DirectSoundData_082E7580
DirectSoundData_082E7580:
	.incbin "sound/direct_sound_samples/082E7580.bin"

	.align 2
	.global DirectSoundData_082EA140
DirectSoundData_082EA140:
	.incbin "sound/direct_sound_samples/082EA140.bin"

	.align 2
	.global DirectSoundData_082EBA88
DirectSoundData_082EBA88:
	.incbin "sound/direct_sound_samples/082EBA88.bin"

	.align 2
	.global DirectSoundData_082ED1FC
DirectSoundData_082ED1FC:
	.incbin "sound/direct_sound_samples/082ED1FC.bin"

	.align 2
	.global DirectSoundData_082EE958
DirectSoundData_082EE958:
	.incbin "sound/direct_sound_samples/082EE958.bin"

	.align 2
	.global DirectSoundData_082F0884
DirectSoundData_082F0884:
	.incbin "sound/direct_sound_samples/082F0884.bin"

	.align 2
	.global DirectSoundData_082F21F8
DirectSoundData_082F21F8:
	.incbin "sound/direct_sound_samples/082F21F8.bin"

	.align 2
	.global DirectSoundData_082F2E14
DirectSoundData_082F2E14:
	.incbin "sound/direct_sound_samples/082F2E14.bin"

	.align 2
	.global DirectSoundData_082F4654
DirectSoundData_082F4654:
	.incbin "sound/direct_sound_samples/082F4654.bin"

	.align 2
	.global DirectSoundData_082F725C
DirectSoundData_082F725C:
	.incbin "sound/direct_sound_samples/082F725C.bin"

	.align 2
	.global DirectSoundData_082F89B8
DirectSoundData_082F89B8:
	.incbin "sound/direct_sound_samples/082F89B8.bin"

	.align 2
	.global DirectSoundData_082F9520
DirectSoundData_082F9520:
	.incbin "sound/direct_sound_samples/082F9520.bin"

	.align 2
	.global DirectSoundData_082FBF50
DirectSoundData_082FBF50:
	.incbin "sound/direct_sound_samples/082FBF50.bin"

	.align 2
	.global DirectSoundData_082FE634
DirectSoundData_082FE634:
	.incbin "sound/direct_sound_samples/082FE634.bin"

	.align 2
	.global DirectSoundData_08300664
DirectSoundData_08300664:
	.incbin "sound/direct_sound_samples/08300664.bin"

	.align 2
	.global DirectSoundData_08302860
DirectSoundData_08302860:
	.incbin "sound/direct_sound_samples/08302860.bin"

	.align 2
	.global DirectSoundData_083099E8
DirectSoundData_083099E8:
	.incbin "sound/direct_sound_samples/083099E8.bin"

	.align 2
	.global DirectSoundData_0830A05C
DirectSoundData_0830A05C:
	.incbin "sound/direct_sound_samples/0830A05C.bin"

	.align 2
	.global DirectSoundData_0830A720
DirectSoundData_0830A720:
	.incbin "sound/direct_sound_samples/0830A720.bin"

	.align 2
	.global DirectSoundData_0830DCA8
DirectSoundData_0830DCA8:
	.incbin "sound/direct_sound_samples/0830DCA8.bin"

	.align 2
	.global DirectSoundData_0830E770
DirectSoundData_0830E770:
	.incbin "sound/direct_sound_samples/0830E770.bin"

	.align 2
	.global DirectSoundData_0830F1BC
DirectSoundData_0830F1BC:
	.incbin "sound/direct_sound_samples/0830F1BC.bin"

	.align 2
	.global DirectSoundData_0830FA60
DirectSoundData_0830FA60:
	.incbin "sound/direct_sound_samples/0830FA60.bin"

	.align 2
	.global DirectSoundData_08310124
DirectSoundData_08310124:
	.incbin "sound/direct_sound_samples/08310124.bin"

	.align 2
	.global DirectSoundData_08310DDC
DirectSoundData_08310DDC:
	.incbin "sound/direct_sound_samples/08310DDC.bin"

	.align 2
	.global DirectSoundData_083116C4
DirectSoundData_083116C4:
	.incbin "sound/direct_sound_samples/083116C4.bin"

	.align 2
	.global DirectSoundData_08311AC8
DirectSoundData_08311AC8:
	.incbin "sound/direct_sound_samples/08311AC8.bin"

	.align 2
	.global DirectSoundData_0831229C
DirectSoundData_0831229C:
	.incbin "sound/direct_sound_samples/0831229C.bin"

	.align 2
	.global DirectSoundData_08312AE0
DirectSoundData_08312AE0:
	.incbin "sound/direct_sound_samples/08312AE0.bin"

	.align 2
	.global DirectSoundData_083133CC
DirectSoundData_083133CC:
	.incbin "sound/direct_sound_samples/083133CC.bin"

	.align 2
	.global DirectSoundData_08316404
DirectSoundData_08316404:
	.incbin "sound/direct_sound_samples/08316404.bin"

	.align 2
	.global DirectSoundData_08318D10
DirectSoundData_08318D10:
	.incbin "sound/direct_sound_samples/08318D10.bin"

	.align 2
	.global DirectSoundData_0831A290
DirectSoundData_0831A290:
	.incbin "sound/direct_sound_samples/0831A290.bin"

	.align 2
	.global DirectSoundData_0831AADC
DirectSoundData_0831AADC:
	.incbin "sound/direct_sound_samples/0831AADC.bin"

	.align 2
	.global DirectSoundData_0831B314
DirectSoundData_0831B314:
	.incbin "sound/direct_sound_samples/0831B314.bin"

	.align 2
	.global DirectSoundData_0831C44C
DirectSoundData_0831C44C:
	.incbin "sound/direct_sound_samples/0831C44C.bin"

	.align 2
	.global DirectSoundData_0831E954
DirectSoundData_0831E954:
	.incbin "sound/direct_sound_samples/0831E954.bin"

	.align 2
	.global DirectSoundData_08320768
DirectSoundData_08320768:
	.incbin "sound/direct_sound_samples/08320768.bin"

	.align 2
	.global DirectSoundData_08321C10
DirectSoundData_08321C10:
	.incbin "sound/direct_sound_samples/08321C10.bin"

	.align 2
	.global DirectSoundData_08325FE8
DirectSoundData_08325FE8:
	.incbin "sound/direct_sound_samples/08325FE8.bin"

	.align 2
	.global DirectSoundData_0832888C
DirectSoundData_0832888C:
	.incbin "sound/direct_sound_samples/0832888C.bin"

	.align 2
	.global DirectSoundData_0832E5F8
DirectSoundData_0832E5F8:
	.incbin "sound/direct_sound_samples/0832E5F8.bin"

	.align 2
	.global DirectSoundData_08330AFC
DirectSoundData_08330AFC:
	.incbin "sound/direct_sound_samples/08330AFC.bin"

	.align 2
	.global DirectSoundData_08331584
DirectSoundData_08331584:
	.incbin "sound/direct_sound_samples/08331584.bin"

	.align 2
	.global DirectSoundData_08331EAC
DirectSoundData_08331EAC:
	.incbin "sound/direct_sound_samples/08331EAC.bin"

	.align 2
	.global DirectSoundData_083328AC
DirectSoundData_083328AC:
	.incbin "sound/direct_sound_samples/083328AC.bin"

	.align 2
	.global DirectSoundData_08333A94
DirectSoundData_08333A94:
	.incbin "sound/direct_sound_samples/08333A94.bin"

	.align 2
	.global DirectSoundData_083355B8
DirectSoundData_083355B8:
	.incbin "sound/direct_sound_samples/083355B8.bin"

	.align 2
	.global DirectSoundData_08336F24
DirectSoundData_08336F24:
	.incbin "sound/direct_sound_samples/08336F24.bin"

	.align 2
	.global DirectSoundData_08338014
DirectSoundData_08338014:
	.incbin "sound/direct_sound_samples/08338014.bin"

	.align 2
	.global DirectSoundData_083395B8
DirectSoundData_083395B8:
	.incbin "sound/direct_sound_samples/083395B8.bin"

	.align 2
	.global DirectSoundData_0833C914
DirectSoundData_0833C914:
	.incbin "sound/direct_sound_samples/0833C914.bin"

	.align 2
	.global DirectSoundData_0833E0E8
DirectSoundData_0833E0E8:
	.incbin "sound/direct_sound_samples/0833E0E8.bin"

	.align 2
	.global DirectSoundData_0834146C
DirectSoundData_0834146C:
	.incbin "sound/direct_sound_samples/0834146C.bin"

	.align 2
	.global DirectSoundData_0834533C
DirectSoundData_0834533C:
	.incbin "sound/direct_sound_samples/0834533C.bin"

	.align 2
	.global DirectSoundData_08347BC4
DirectSoundData_08347BC4:
	.incbin "sound/direct_sound_samples/08347BC4.bin"

	.align 2
	.global DirectSoundData_0834CA04
DirectSoundData_0834CA04:
	.incbin "sound/direct_sound_samples/0834CA04.bin"

	.align 2
	.global DirectSoundData_0835186C
DirectSoundData_0835186C:
	.incbin "sound/direct_sound_samples/0835186C.bin"

	.align 2
	.global DirectSoundData_0835548C
DirectSoundData_0835548C:
	.incbin "sound/direct_sound_samples/0835548C.bin"

	.align 2
	.global DirectSoundData_083590A8
DirectSoundData_083590A8:
	.incbin "sound/direct_sound_samples/083590A8.bin"

	.align 2
	.global DirectSoundData_0835CA6C
DirectSoundData_0835CA6C:
	.incbin "sound/direct_sound_samples/0835CA6C.bin"

	.align 2
	.global DirectSoundData_08361CD0
DirectSoundData_08361CD0:
	.incbin "sound/direct_sound_samples/08361CD0.bin"

	.align 2
	.global DirectSoundData_08366110
DirectSoundData_08366110:
	.incbin "sound/direct_sound_samples/08366110.bin"

	.align 2
	.global DirectSoundData_08367F14
DirectSoundData_08367F14:
	.incbin "sound/direct_sound_samples/08367F14.bin"

	.align 2
	.global DirectSoundData_08368534
DirectSoundData_08368534:
	.incbin "sound/direct_sound_samples/08368534.bin"

	.align 2
	.global DirectSoundData_0836B504
DirectSoundData_0836B504:
	.incbin "sound/direct_sound_samples/0836B504.bin"

	.align 2
	.global DirectSoundData_0836CD24
DirectSoundData_0836CD24:
	.incbin "sound/direct_sound_samples/0836CD24.bin"

	.align 2
	.global DirectSoundData_0836EE64
DirectSoundData_0836EE64:
	.incbin "sound/direct_sound_samples/0836EE64.bin"

	.align 2
	.global DirectSoundData_08372138
DirectSoundData_08372138:
	.incbin "sound/direct_sound_samples/08372138.bin"

	.align 2
	.global DirectSoundData_08375140
DirectSoundData_08375140:
	.incbin "sound/direct_sound_samples/08375140.bin"

	.align 2
	.global DirectSoundData_08376650
DirectSoundData_08376650:
	.incbin "sound/direct_sound_samples/08376650.bin"

	.align 2
	.global DirectSoundData_08378A1C
DirectSoundData_08378A1C:
	.incbin "sound/direct_sound_samples/08378A1C.bin"

	.align 2
	.global DirectSoundData_0837A1B4
DirectSoundData_0837A1B4:
	.incbin "sound/direct_sound_samples/0837A1B4.bin"

	.align 2
	.global DirectSoundData_0837B918
DirectSoundData_0837B918:
	.incbin "sound/direct_sound_samples/0837B918.bin"

	.align 2
	.global DirectSoundData_0837EEC0
DirectSoundData_0837EEC0:
	.incbin "sound/direct_sound_samples/0837EEC0.bin"

	.align 2
	.global DirectSoundData_083804A4
DirectSoundData_083804A4:
	.incbin "sound/direct_sound_samples/083804A4.bin"

	.align 2
	.global DirectSoundData_08382B10
DirectSoundData_08382B10:
	.incbin "sound/direct_sound_samples/08382B10.bin"

	.align 2
	.global DirectSoundData_08385640
DirectSoundData_08385640:
	.incbin "sound/direct_sound_samples/08385640.bin"

	.align 2
	.global DirectSoundData_08385F48
DirectSoundData_08385F48:
	.incbin "sound/direct_sound_samples/08385F48.bin"

	.align 2
	.global DirectSoundData_0838642C
DirectSoundData_0838642C:
	.incbin "sound/direct_sound_samples/0838642C.bin"

	.align 2
	.global DirectSoundData_08386EB4
DirectSoundData_08386EB4:
	.incbin "sound/direct_sound_samples/08386EB4.bin"

	.align 2
	.global DirectSoundData_08388008
DirectSoundData_08388008:
	.incbin "sound/direct_sound_samples/08388008.bin"

	.align 2
	.global DirectSoundData_083885DC
DirectSoundData_083885DC:
	.incbin "sound/direct_sound_samples/083885DC.bin"

	.align 2
	.global DirectSoundData_08388B5C
DirectSoundData_08388B5C:
	.incbin "sound/direct_sound_samples/08388B5C.bin"

	.align 2
	.global DirectSoundData_083895E4
DirectSoundData_083895E4:
	.incbin "sound/direct_sound_samples/083895E4.bin"

	.align 2
	.global DirectSoundData_0838A5A8
DirectSoundData_0838A5A8:
	.incbin "sound/direct_sound_samples/0838A5A8.bin"

	.align 2
	.global DirectSoundData_0838ABC0
DirectSoundData_0838ABC0:
	.incbin "sound/direct_sound_samples/0838ABC0.bin"

	.align 2
	.global DirectSoundData_0838B098
DirectSoundData_0838B098:
	.incbin "sound/direct_sound_samples/0838B098.bin"

	.align 2
	.global DirectSoundData_0838BAF4
DirectSoundData_0838BAF4:
	.incbin "sound/direct_sound_samples/0838BAF4.bin"

	.align 2
	.global DirectSoundData_0838CAB8
DirectSoundData_0838CAB8:
	.incbin "sound/direct_sound_samples/0838CAB8.bin"

	.align 2
	.global DirectSoundData_0838D240
DirectSoundData_0838D240:
	.incbin "sound/direct_sound_samples/0838D240.bin"

	.align 2
	.global DirectSoundData_0838D940
DirectSoundData_0838D940:
	.incbin "sound/direct_sound_samples/0838D940.bin"

	.align 2
	.global DirectSoundData_0838E3A0
DirectSoundData_0838E3A0:
	.incbin "sound/direct_sound_samples/0838E3A0.bin"

	.align 2
	.global DirectSoundData_0838F364
DirectSoundData_0838F364:
	.incbin "sound/direct_sound_samples/0838F364.bin"

	.align 2
	.global DirectSoundData_0838F994
DirectSoundData_0838F994:
	.incbin "sound/direct_sound_samples/0838F994.bin"

	.align 2
	.global DirectSoundData_0838FEE0
DirectSoundData_0838FEE0:
	.incbin "sound/direct_sound_samples/0838FEE0.bin"

	.align 2
	.global DirectSoundData_08390758
DirectSoundData_08390758:
	.incbin "sound/direct_sound_samples/08390758.bin"

	.align 2
	.global DirectSoundData_08391480
DirectSoundData_08391480:
	.incbin "sound/direct_sound_samples/08391480.bin"

	.align 2
	.global DirectSoundData_083918C0
DirectSoundData_083918C0:
	.incbin "sound/direct_sound_samples/083918C0.bin"

	.align 2
	.global DirectSoundData_08391D8C
DirectSoundData_08391D8C:
	.incbin "sound/direct_sound_samples/08391D8C.bin"

	.align 2
	.global DirectSoundData_08392980
DirectSoundData_08392980:
	.incbin "sound/direct_sound_samples/08392980.bin"

	.align 2
	.global DirectSoundData_083932E4
DirectSoundData_083932E4:
	.incbin "sound/direct_sound_samples/083932E4.bin"

	.align 2
	.global DirectSoundData_0839377C
DirectSoundData_0839377C:
	.incbin "sound/direct_sound_samples/0839377C.bin"

	.align 2
	.global DirectSoundData_08393C08
DirectSoundData_08393C08:
	.incbin "sound/direct_sound_samples/08393C08.bin"

	.align 2
	.global DirectSoundData_0839460C
DirectSoundData_0839460C:
	.incbin "sound/direct_sound_samples/0839460C.bin"

	.align 2
	.global DirectSoundData_08395230
DirectSoundData_08395230:
	.incbin "sound/direct_sound_samples/08395230.bin"

	.align 2
	.global DirectSoundData_0839639C
DirectSoundData_0839639C:
	.incbin "sound/direct_sound_samples/0839639C.bin"

	.align 2
	.global DirectSoundData_08397150
DirectSoundData_08397150:
	.incbin "sound/direct_sound_samples/08397150.bin"

	.align 2
	.global DirectSoundData_08398934
DirectSoundData_08398934:
	.incbin "sound/direct_sound_samples/08398934.bin"

	.align 2
	.global DirectSoundData_083997C4
DirectSoundData_083997C4:
	.incbin "sound/direct_sound_samples/083997C4.bin"

	.align 2
	.global DirectSoundData_0839A3BC
DirectSoundData_0839A3BC:
	.incbin "sound/direct_sound_samples/0839A3BC.bin"

	.align 2
	.global DirectSoundData_0839AE78
DirectSoundData_0839AE78:
	.incbin "sound/direct_sound_samples/0839AE78.bin"

	.align 2
	.global DirectSoundData_0839B80C
DirectSoundData_0839B80C:
	.incbin "sound/direct_sound_samples/0839B80C.bin"

	.align 2
	.global DirectSoundData_0839C4D0
DirectSoundData_0839C4D0:
	.incbin "sound/direct_sound_samples/0839C4D0.bin"

	.align 2
	.global DirectSoundData_0839D108
DirectSoundData_0839D108:
	.incbin "sound/direct_sound_samples/0839D108.bin"

	.align 2
	.global DirectSoundData_0839D6EC
DirectSoundData_0839D6EC:
	.incbin "sound/direct_sound_samples/0839D6EC.bin"

	.align 2
	.global DirectSoundData_0839E4D4
DirectSoundData_0839E4D4:
	.incbin "sound/direct_sound_samples/0839E4D4.bin"

	.align 2
	.global DirectSoundData_0839F298
DirectSoundData_0839F298:
	.incbin "sound/direct_sound_samples/0839F298.bin"

	.align 2
	.global DirectSoundData_0839FBCC
DirectSoundData_0839FBCC:
	.incbin "sound/direct_sound_samples/0839FBCC.bin"

	.align 2
	.global DirectSoundData_083A09E4
DirectSoundData_083A09E4:
	.incbin "sound/direct_sound_samples/083A09E4.bin"

	.align 2
	.global DirectSoundData_083A14A0
DirectSoundData_083A14A0:
	.incbin "sound/direct_sound_samples/083A14A0.bin"

	.align 2
	.global DirectSoundData_083A1EF4
DirectSoundData_083A1EF4:
	.incbin "sound/direct_sound_samples/083A1EF4.bin"

	.align 2
	.global DirectSoundData_083A2B88
DirectSoundData_083A2B88:
	.incbin "sound/direct_sound_samples/083A2B88.bin"

	.align 2
	.global DirectSoundData_083A37C0
DirectSoundData_083A37C0:
	.incbin "sound/direct_sound_samples/083A37C0.bin"

	.align 2
	.global DirectSoundData_083A3E80
DirectSoundData_083A3E80:
	.incbin "sound/direct_sound_samples/083A3E80.bin"

	.align 2
	.global DirectSoundData_083A4D58
DirectSoundData_083A4D58:
	.incbin "sound/direct_sound_samples/083A4D58.bin"

	.align 2
	.global DirectSoundData_083A5AF0
DirectSoundData_083A5AF0:
	.incbin "sound/direct_sound_samples/083A5AF0.bin"

	.align 2
	.global DirectSoundData_083A6468
DirectSoundData_083A6468:
	.incbin "sound/direct_sound_samples/083A6468.bin"

	.align 2
	.global DirectSoundData_083A722C
DirectSoundData_083A722C:
	.incbin "sound/direct_sound_samples/083A722C.bin"

	.align 2
	.global DirectSoundData_083A7D44
DirectSoundData_083A7D44:
	.incbin "sound/direct_sound_samples/083A7D44.bin"

	.align 2
	.global DirectSoundData_083A8530
DirectSoundData_083A8530:
	.incbin "sound/direct_sound_samples/083A8530.bin"

	.align 2
	.global DirectSoundData_083A91D4
DirectSoundData_083A91D4:
	.incbin "sound/direct_sound_samples/083A91D4.bin"

	.align 2
	.global DirectSoundData_083A9E20
DirectSoundData_083A9E20:
	.incbin "sound/direct_sound_samples/083A9E20.bin"

	.align 2
	.global DirectSoundData_083AA444
DirectSoundData_083AA444:
	.incbin "sound/direct_sound_samples/083AA444.bin"

	.align 2
	.global DirectSoundData_083AB36C
DirectSoundData_083AB36C:
	.incbin "sound/direct_sound_samples/083AB36C.bin"

	.align 2
	.global DirectSoundData_083AC048
DirectSoundData_083AC048:
	.incbin "sound/direct_sound_samples/083AC048.bin"

	.align 2
	.global DirectSoundData_083ACA08
DirectSoundData_083ACA08:
	.incbin "sound/direct_sound_samples/083ACA08.bin"

	.align 2
	.global DirectSoundData_083AD738
DirectSoundData_083AD738:
	.incbin "sound/direct_sound_samples/083AD738.bin"

	.align 2
	.global DirectSoundData_083AE2B8
DirectSoundData_083AE2B8:
	.incbin "sound/direct_sound_samples/083AE2B8.bin"

	.align 2
	.global DirectSoundData_083AED14
DirectSoundData_083AED14:
	.incbin "sound/direct_sound_samples/083AED14.bin"

	.align 2
	.global DirectSoundData_083AFA24
DirectSoundData_083AFA24:
	.incbin "sound/direct_sound_samples/083AFA24.bin"

	.align 2
	.global DirectSoundData_083B065C
DirectSoundData_083B065C:
	.incbin "sound/direct_sound_samples/083B065C.bin"

	.align 2
	.global DirectSoundData_083B0D54
DirectSoundData_083B0D54:
	.incbin "sound/direct_sound_samples/083B0D54.bin"

	.align 2
	.global DirectSoundData_083B1B9C
DirectSoundData_083B1B9C:
	.incbin "sound/direct_sound_samples/083B1B9C.bin"

	.align 2
	.global DirectSoundData_083B2678
DirectSoundData_083B2678:
	.incbin "sound/direct_sound_samples/083B2678.bin"

	.align 2
	.global DirectSoundData_083B2FFC
DirectSoundData_083B2FFC:
	.incbin "sound/direct_sound_samples/083B2FFC.bin"

	.align 2
	.global DirectSoundData_083B3D24
DirectSoundData_083B3D24:
	.incbin "sound/direct_sound_samples/083B3D24.bin"

	.align 2
	.global DirectSoundData_083B48AC
DirectSoundData_083B48AC:
	.incbin "sound/direct_sound_samples/083B48AC.bin"

	.align 2
	.global DirectSoundData_083B5424
DirectSoundData_083B5424:
	.incbin "sound/direct_sound_samples/083B5424.bin"

	.align 2
	.global DirectSoundData_083B60AC
DirectSoundData_083B60AC:
	.incbin "sound/direct_sound_samples/083B60AC.bin"

	.align 2
	.global DirectSoundData_083B6C08
DirectSoundData_083B6C08:
	.incbin "sound/direct_sound_samples/083B6C08.bin"

	.align 2
	.global DirectSoundData_083B72D0
DirectSoundData_083B72D0:
	.incbin "sound/direct_sound_samples/083B72D0.bin"

	.align 2
	.global DirectSoundData_083B820C
DirectSoundData_083B820C:
	.incbin "sound/direct_sound_samples/083B820C.bin"

	.align 2
	.global DirectSoundData_083B8BC0
DirectSoundData_083B8BC0:
	.incbin "sound/direct_sound_samples/083B8BC0.bin"

	.align 2
	.global DirectSoundData_083B9580
DirectSoundData_083B9580:
	.incbin "sound/direct_sound_samples/083B9580.bin"

	.align 2
	.global DirectSoundData_083BA344
DirectSoundData_083BA344:
	.incbin "sound/direct_sound_samples/083BA344.bin"

	.align 2
	.global DirectSoundData_083BAE44
DirectSoundData_083BAE44:
	.incbin "sound/direct_sound_samples/083BAE44.bin"

	.align 2
	.global DirectSoundData_083BB898
DirectSoundData_083BB898:
	.incbin "sound/direct_sound_samples/083BB898.bin"

	.align 2
	.global DirectSoundData_083BC4B4
DirectSoundData_083BC4B4:
	.incbin "sound/direct_sound_samples/083BC4B4.bin"

	.align 2
	.global DirectSoundData_083BD064
DirectSoundData_083BD064:
	.incbin "sound/direct_sound_samples/083BD064.bin"

	.align 2
	.global DirectSoundData_083BD738
DirectSoundData_083BD738:
	.incbin "sound/direct_sound_samples/083BD738.bin"

	.align 2
	.global DirectSoundData_083BE9A4
DirectSoundData_083BE9A4:
	.incbin "sound/direct_sound_samples/083BE9A4.bin"

	.align 2
	.global DirectSoundData_083BF484
DirectSoundData_083BF484:
	.incbin "sound/direct_sound_samples/083BF484.bin"

	.align 2
	.global DirectSoundData_083C004C
DirectSoundData_083C004C:
	.incbin "sound/direct_sound_samples/083C004C.bin"

	.align 2
	.global DirectSoundData_083C0EEC
DirectSoundData_083C0EEC:
	.incbin "sound/direct_sound_samples/083C0EEC.bin"

	.align 2
	.global DirectSoundData_083C1970
DirectSoundData_083C1970:
	.incbin "sound/direct_sound_samples/083C1970.bin"

	.align 2
	.global DirectSoundData_083C23C4
DirectSoundData_083C23C4:
	.incbin "sound/direct_sound_samples/083C23C4.bin"

	.align 2
	.global DirectSoundData_083C31C8
DirectSoundData_083C31C8:
	.incbin "sound/direct_sound_samples/083C31C8.bin"

	.align 2
	.global DirectSoundData_083C3DF8
DirectSoundData_083C3DF8:
	.incbin "sound/direct_sound_samples/083C3DF8.bin"

	.align 2
	.global DirectSoundData_083C4580
DirectSoundData_083C4580:
	.incbin "sound/direct_sound_samples/083C4580.bin"

	.align 2
	.global DirectSoundData_083C568C
DirectSoundData_083C568C:
	.incbin "sound/direct_sound_samples/083C568C.bin"

	.align 2
	.global DirectSoundData_083C625C
DirectSoundData_083C625C:
	.incbin "sound/direct_sound_samples/083C625C.bin"

	.align 2
	.global DirectSoundData_083C6E54
DirectSoundData_083C6E54:
	.incbin "sound/direct_sound_samples/083C6E54.bin"

	.align 2
	.global DirectSoundData_083C9478
DirectSoundData_083C9478:
	.incbin "sound/direct_sound_samples/083C9478.bin"

	.align 2
	.global DirectSoundData_083CBEB8
DirectSoundData_083CBEB8:
	.incbin "sound/direct_sound_samples/083CBEB8.bin"

	.align 2
	.global DirectSoundData_083D3E90
DirectSoundData_083D3E90:
	.incbin "sound/direct_sound_samples/083D3E90.bin"

	.align 2
	.global DirectSoundData_083D5EF0
DirectSoundData_083D5EF0:
	.incbin "sound/direct_sound_samples/083D5EF0.bin"

	.align 2
	.global DirectSoundData_083D9AC8
DirectSoundData_083D9AC8:
	.incbin "sound/direct_sound_samples/083D9AC8.bin"

	.align 2
	.global DirectSoundData_083DB660
DirectSoundData_083DB660:
	.incbin "sound/direct_sound_samples/083DB660.bin"

	.align 2
	.global DirectSoundData_083DE400
DirectSoundData_083DE400:
	.incbin "sound/direct_sound_samples/083DE400.bin"

	.align 2
	.global DirectSoundData_083E4BE0
DirectSoundData_083E4BE0:
	.incbin "sound/direct_sound_samples/083E4BE0.bin"

	.align 2
	.global DirectSoundData_083E8F14
DirectSoundData_083E8F14:
	.incbin "sound/direct_sound_samples/083E8F14.bin"

	.align 2
	.global DirectSoundData_083EB134
DirectSoundData_083EB134:
	.incbin "sound/direct_sound_samples/083EB134.bin"

	.align 2
	.global DirectSoundData_083EFB0C
DirectSoundData_083EFB0C:
	.incbin "sound/direct_sound_samples/083EFB0C.bin"

	.align 2
	.global DirectSoundData_083F234C
DirectSoundData_083F234C:
	.incbin "sound/direct_sound_samples/083F234C.bin"

	.align 2
	.global DirectSoundData_083F30F0
DirectSoundData_083F30F0:
	.incbin "sound/direct_sound_samples/083F30F0.bin"

	.align 2
	.global DirectSoundData_083F368C
DirectSoundData_083F368C:
	.incbin "sound/direct_sound_samples/083F368C.bin"

	.align 2
	.global DirectSoundData_083F4E00
DirectSoundData_083F4E00:
	.incbin "sound/direct_sound_samples/083F4E00.bin"

	.align 2
	.global DirectSoundData_083F715C
DirectSoundData_083F715C:
	.incbin "sound/direct_sound_samples/083F715C.bin"

	.align 2
	.global DirectSoundData_083F8B38
DirectSoundData_083F8B38:
	.incbin "sound/direct_sound_samples/083F8B38.bin"

	.align 2
	.global DirectSoundData_083FB6F8
DirectSoundData_083FB6F8:
	.incbin "sound/direct_sound_samples/083FB6F8.bin"

	.align 2
	.global DirectSoundData_083FCEBC
DirectSoundData_083FCEBC:
	.incbin "sound/direct_sound_samples/083FCEBC.bin"

	.align 2
	.global DirectSoundData_083FFCF4
DirectSoundData_083FFCF4:
	.incbin "sound/direct_sound_samples/083FFCF4.bin"

	.align 2
	.global DirectSoundData_08401BA0
DirectSoundData_08401BA0:
	.incbin "sound/direct_sound_samples/08401BA0.bin"

	.align 2
	.global DirectSoundData_08406064
DirectSoundData_08406064:
	.incbin "sound/direct_sound_samples/08406064.bin"

	.align 2
	.global DirectSoundData_08408B14
DirectSoundData_08408B14:
	.incbin "sound/direct_sound_samples/08408B14.bin"

	.align 2
	.global DirectSoundData_0840CA94
DirectSoundData_0840CA94:
	.incbin "sound/direct_sound_samples/0840CA94.bin"

	.align 2
	.global DirectSoundData_0840D3D0
DirectSoundData_0840D3D0:
	.incbin "sound/direct_sound_samples/0840D3D0.bin"

	.align 2
	.global DirectSoundData_0840DE48
DirectSoundData_0840DE48:
	.incbin "sound/direct_sound_samples/0840DE48.bin"

	.align 2
	.global DirectSoundData_0840E730
DirectSoundData_0840E730:
	.incbin "sound/direct_sound_samples/0840E730.bin"

	.align 2
	.global DirectSoundData_0840FC68
DirectSoundData_0840FC68:
	.incbin "sound/direct_sound_samples/0840FC68.bin"

	.align 2
	.global DirectSoundData_08410A1C
DirectSoundData_08410A1C:
	.incbin "sound/direct_sound_samples/08410A1C.bin"

	.align 2
	.global DirectSoundData_0841144C
DirectSoundData_0841144C:
	.incbin "sound/direct_sound_samples/0841144C.bin"

	.align 2
	.global DirectSoundData_08411DD8
DirectSoundData_08411DD8:
	.incbin "sound/direct_sound_samples/08411DD8.bin"

	.align 2
	.global DirectSoundData_08412A40
DirectSoundData_08412A40:
	.incbin "sound/direct_sound_samples/08412A40.bin"

	.align 2
	.global DirectSoundData_08413B40
DirectSoundData_08413B40:
	.incbin "sound/direct_sound_samples/08413B40.bin"

	.align 2
	.global DirectSoundData_084157EC
DirectSoundData_084157EC:
	.incbin "sound/direct_sound_samples/084157EC.bin"

	.align 2
	.global DirectSoundData_08416178
DirectSoundData_08416178:
	.incbin "sound/direct_sound_samples/08416178.bin"

	.align 2
	.global DirectSoundData_084168FC
DirectSoundData_084168FC:
	.incbin "sound/direct_sound_samples/084168FC.bin"

	.align 2
	.global DirectSoundData_08417288
DirectSoundData_08417288:
	.incbin "sound/direct_sound_samples/08417288.bin"

	.align 2
	.global DirectSoundData_08417D5C
DirectSoundData_08417D5C:
	.incbin "sound/direct_sound_samples/08417D5C.bin"

	.align 2
	.global DirectSoundData_084186E8
DirectSoundData_084186E8:
	.incbin "sound/direct_sound_samples/084186E8.bin"

	.align 2
	.global DirectSoundData_08419074
DirectSoundData_08419074:
	.incbin "sound/direct_sound_samples/08419074.bin"

	.align 2
	.global DirectSoundData_084193DC
DirectSoundData_084193DC:
	.incbin "sound/direct_sound_samples/084193DC.bin"

	.align 2
	.global DirectSoundData_0841AE28
DirectSoundData_0841AE28:
	.incbin "sound/direct_sound_samples/0841AE28.bin"

	.align 2
	.global DirectSoundData_0841BE08
DirectSoundData_0841BE08:
	.incbin "sound/direct_sound_samples/0841BE08.bin"

	.align 2
	.global DirectSoundData_0841C1DC
DirectSoundData_0841C1DC:
	.incbin "sound/direct_sound_samples/0841C1DC.bin"

	.align 2
	.global DirectSoundData_0841C5E4
DirectSoundData_0841C5E4:
	.incbin "sound/direct_sound_samples/0841C5E4.bin"

	.align 2
	.global DirectSoundData_0841CA28
DirectSoundData_0841CA28:
	.incbin "sound/direct_sound_samples/0841CA28.bin"

	.align 2
	.global DirectSoundData_0841CDB8
DirectSoundData_0841CDB8:
	.incbin "sound/direct_sound_samples/0841CDB8.bin"

	.align 2
	.global DirectSoundData_0841D1A8
DirectSoundData_0841D1A8:
	.incbin "sound/direct_sound_samples/0841D1A8.bin"

	.align 2
	.global DirectSoundData_0841D510
DirectSoundData_0841D510:
	.incbin "sound/direct_sound_samples/0841D510.bin"

	.align 2
	.global DirectSoundData_08420660
DirectSoundData_08420660:
	.incbin "sound/direct_sound_samples/08420660.bin"

	.align 2
	.global DirectSoundData_0842208C
DirectSoundData_0842208C:
	.incbin "sound/direct_sound_samples/0842208C.bin"

	.align 2
	.global DirectSoundData_084230C4
DirectSoundData_084230C4:
	.incbin "sound/direct_sound_samples/084230C4.bin"

	.align 2
	.global DirectSoundData_0842386C
DirectSoundData_0842386C:
	.incbin "sound/direct_sound_samples/0842386C.bin"

	.align 2
	.global DirectSoundData_0842472C
DirectSoundData_0842472C:
	.incbin "sound/direct_sound_samples/0842472C.bin"

	.align 2
	.global DirectSoundData_0842620C
DirectSoundData_0842620C:
	.incbin "sound/direct_sound_samples/0842620C.bin"

	.align 2
	.global DirectSoundData_084286D0
DirectSoundData_084286D0:
	.incbin "sound/direct_sound_samples/084286D0.bin"

	.align 2
	.global DirectSoundData_0842B820
DirectSoundData_0842B820:
	.incbin "sound/direct_sound_samples/0842B820.bin"

	.align 2
	.global DirectSoundData_0842DB04
DirectSoundData_0842DB04:
	.incbin "sound/direct_sound_samples/0842DB04.bin"

	.align 2
	.global DirectSoundData_084348D0
DirectSoundData_084348D0:
	.incbin "sound/direct_sound_samples/084348D0.bin"

	.align 2
	.global DirectSoundData_08438D94
DirectSoundData_08438D94:
	.incbin "sound/direct_sound_samples/08438D94.bin"

	.align 2
	.global DirectSoundData_0843DA48
DirectSoundData_0843DA48:
	.incbin "sound/direct_sound_samples/0843DA48.bin"

	.align 2
	.global DirectSoundData_08440078
DirectSoundData_08440078:
	.incbin "sound/direct_sound_samples/08440078.bin"

	.align 2
	.global DirectSoundData_0844127C
DirectSoundData_0844127C:
	.incbin "sound/direct_sound_samples/0844127C.bin"

	.align 2
	.global DirectSoundData_08443E74
DirectSoundData_08443E74:
	.incbin "sound/direct_sound_samples/08443E74.bin"

	.align 2
	.global DirectSoundData_08448094
DirectSoundData_08448094:
	.incbin "sound/direct_sound_samples/08448094.bin"

	.align 2
	.global DirectSoundData_08449300
DirectSoundData_08449300:
	.incbin "sound/direct_sound_samples/08449300.bin"

	.align 2
	.global DirectSoundData_0844D59C
DirectSoundData_0844D59C:
	.incbin "sound/direct_sound_samples/0844D59C.bin"

	.align 2
	.global DirectSoundData_0844F71C
DirectSoundData_0844F71C:
	.incbin "sound/direct_sound_samples/0844F71C.bin"

	.align 2
	.global DirectSoundData_08451658
DirectSoundData_08451658:
	.incbin "sound/direct_sound_samples/08451658.bin"

	.align 2
	.global DirectSoundData_08455154
DirectSoundData_08455154:
	.incbin "sound/direct_sound_samples/08455154.bin"

	.align 2
	.global DirectSoundData_0845CAA8
DirectSoundData_0845CAA8:
	.incbin "sound/direct_sound_samples/0845CAA8.bin"

	.align 2
	.global DirectSoundData_08460298
DirectSoundData_08460298:
	.incbin "sound/direct_sound_samples/08460298.bin"

	.align 2
	.global DirectSoundData_08462474
DirectSoundData_08462474:
	.incbin "sound/direct_sound_samples/08462474.bin"

	.align 2
	.global DirectSoundData_084643CC
DirectSoundData_084643CC:
	.incbin "sound/direct_sound_samples/084643CC.bin"

	.align 2
	.global DirectSoundData_08473130
DirectSoundData_08473130:
	.incbin "sound/direct_sound_samples/08473130.bin"

	.align 2
	.global DirectSoundData_08476314
DirectSoundData_08476314:
	.incbin "sound/direct_sound_samples/08476314.bin"

	.align 2
	.global DirectSoundData_084825A4
DirectSoundData_084825A4:
	.incbin "sound/direct_sound_samples/084825A4.bin"

	.align 2
	.global DirectSoundData_08485930
DirectSoundData_08485930:
	.incbin "sound/direct_sound_samples/08485930.bin"

	.align 2
	.global DirectSoundData_084882AC
DirectSoundData_084882AC:
	.incbin "sound/direct_sound_samples/084882AC.bin"

	.align 2
	.global DirectSoundData_0848ACBC
DirectSoundData_0848ACBC:
	.incbin "sound/direct_sound_samples/0848ACBC.bin"

	.align 2
	.global DirectSoundData_0848D15C
DirectSoundData_0848D15C:
	.incbin "sound/direct_sound_samples/0848D15C.bin"

	.align 2
	.global DirectSoundData_0848DBF0
DirectSoundData_0848DBF0:
	.incbin "sound/direct_sound_samples/0848DBF0.bin"

	.align 2
	.global DirectSoundData_084902A0
DirectSoundData_084902A0:
	.incbin "sound/direct_sound_samples/084902A0.bin"

	.align 2
	.global DirectSoundData_084942D8
DirectSoundData_084942D8:
	.incbin "sound/direct_sound_samples/084942D8.bin"

	.align 2
	.global DirectSoundData_0849ECF0
DirectSoundData_0849ECF0:
	.incbin "sound/direct_sound_samples/0849ECF0.bin"

	.align 2
	.global DirectSoundData_084A386C
DirectSoundData_084A386C:
	.incbin "sound/direct_sound_samples/084A386C.bin"

	.align 2
	.global DirectSoundData_084A8FAC
DirectSoundData_084A8FAC:
	.incbin "sound/direct_sound_samples/084A8FAC.bin"

	.align 2
	.global DirectSoundData_084ABC48
DirectSoundData_084ABC48:
	.incbin "sound/direct_sound_samples/084ABC48.bin"

	.align 2
	.global DirectSoundData_084AE2E0
DirectSoundData_084AE2E0:
	.incbin "sound/direct_sound_samples/084AE2E0.bin"

	.align 2
	.global DirectSoundData_084B466C
DirectSoundData_084B466C:
	.incbin "sound/direct_sound_samples/084B466C.bin"

	.align 2
	.global DirectSoundData_084B5180
DirectSoundData_084B5180:
	.incbin "sound/direct_sound_samples/084B5180.bin"

	.align 2
	.global DirectSoundData_084B6100
DirectSoundData_084B6100:
	.incbin "sound/direct_sound_samples/084B6100.bin"

	.align 2
	.global DirectSoundData_084B6D04
DirectSoundData_084B6D04:
	.incbin "sound/direct_sound_samples/084B6D04.bin"

	.align 2
	.global DirectSoundData_084B783C
DirectSoundData_084B783C:
	.incbin "sound/direct_sound_samples/084B783C.bin"

	.align 2
	.global DirectSoundData_084B82C4
DirectSoundData_084B82C4:
	.incbin "sound/direct_sound_samples/084B82C4.bin"

	.align 2
	.global DirectSoundData_084B8D34
DirectSoundData_084B8D34:
	.incbin "sound/direct_sound_samples/084B8D34.bin"

	.align 2
	.global DirectSoundData_084B9334
DirectSoundData_084B9334:
	.incbin "sound/direct_sound_samples/084B9334.bin"

	.align 2
	.global DirectSoundData_084BA6C8
DirectSoundData_084BA6C8:
	.incbin "sound/direct_sound_samples/084BA6C8.bin"

	.align 2
	.global DirectSoundData_084BB9A8
DirectSoundData_084BB9A8:
	.incbin "sound/direct_sound_samples/084BB9A8.bin"

	.align 2
	.global DirectSoundData_084BC890
DirectSoundData_084BC890:
	.incbin "sound/direct_sound_samples/084BC890.bin"

	.align 2
	.global DirectSoundData_084BD490
DirectSoundData_084BD490:
	.incbin "sound/direct_sound_samples/084BD490.bin"

	.align 2
	.global DirectSoundData_084BE7C0
DirectSoundData_084BE7C0:
	.incbin "sound/direct_sound_samples/084BE7C0.bin"

	.align 2
	.global DirectSoundData_084BF480
DirectSoundData_084BF480:
	.incbin "sound/direct_sound_samples/084BF480.bin"

	.align 2
	.global DirectSoundData_084C0120
DirectSoundData_084C0120:
	.incbin "sound/direct_sound_samples/084C0120.bin"

	.align 2
	.global DirectSoundData_084C3630
DirectSoundData_084C3630:
	.incbin "sound/direct_sound_samples/084C3630.bin"

	.align 2
	.global DirectSoundData_084C4758
DirectSoundData_084C4758:
	.incbin "sound/direct_sound_samples/084C4758.bin"

	.align 2
	.global DirectSoundData_084C4F6C
DirectSoundData_084C4F6C:
	.incbin "sound/direct_sound_samples/084C4F6C.bin"

	.align 2
	.global DirectSoundData_084C8ED4
DirectSoundData_084C8ED4:
	.incbin "sound/direct_sound_samples/084C8ED4.bin"

	.align 2
	.global DirectSoundData_084CD8AC
DirectSoundData_084CD8AC:
	.incbin "sound/direct_sound_samples/084CD8AC.bin"

	.align 2
	.global DirectSoundData_084CE300
DirectSoundData_084CE300:
	.incbin "sound/direct_sound_samples/084CE300.bin"

	.align 2
	.global DirectSoundData_084D1AD4
DirectSoundData_084D1AD4:
	.incbin "sound/direct_sound_samples/084D1AD4.bin"

	.align 2
	.global DirectSoundData_084D373C
DirectSoundData_084D373C:
	.incbin "sound/direct_sound_samples/084D373C.bin"

	.align 2
	.global DirectSoundData_084D4684
DirectSoundData_084D4684:
	.incbin "sound/direct_sound_samples/084D4684.bin"

	.align 2
	.global DirectSoundData_084D5A44
DirectSoundData_084D5A44:
	.incbin "sound/direct_sound_samples/084D5A44.bin"

	.align 2
	.global DirectSoundData_084D60BC
DirectSoundData_084D60BC:
	.incbin "sound/direct_sound_samples/084D60BC.bin"

	.align 2
	.global DirectSoundData_084D8188
DirectSoundData_084D8188:
	.incbin "sound/direct_sound_samples/084D8188.bin"

	.align 2
	.global DirectSoundData_084D9304
DirectSoundData_084D9304:
	.incbin "sound/direct_sound_samples/084D9304.bin"

	.align 2
	.global DirectSoundData_084DA07C
DirectSoundData_084DA07C:
	.incbin "sound/direct_sound_samples/084DA07C.bin"

	.align 2
	.global DirectSoundData_084DA53C
DirectSoundData_084DA53C:
	.incbin "sound/direct_sound_samples/084DA53C.bin"

	.align 2
	.global DirectSoundData_084DA7EC
DirectSoundData_084DA7EC:
	.incbin "sound/direct_sound_samples/084DA7EC.bin"

	.align 2
	.global DirectSoundData_084DAF40
DirectSoundData_084DAF40:
	.incbin "sound/direct_sound_samples/084DAF40.bin"

	.align 2
	.global DirectSoundData_084DB690
DirectSoundData_084DB690:
	.incbin "sound/direct_sound_samples/084DB690.bin"

	.align 2
	.global DirectSoundData_084DC330
DirectSoundData_084DC330:
	.incbin "sound/direct_sound_samples/084DC330.bin"

	.align 2
	.global DirectSoundData_084DCA24
DirectSoundData_084DCA24:
	.incbin "sound/direct_sound_samples/084DCA24.bin"

	.align 2
	.global DirectSoundData_084DD66C
DirectSoundData_084DD66C:
	.incbin "sound/direct_sound_samples/084DD66C.bin"

	.align 2
	.global DirectSoundData_084DE884
DirectSoundData_084DE884:
	.incbin "sound/direct_sound_samples/084DE884.bin"

	.align 2
	.global DirectSoundData_084DF2E8
DirectSoundData_084DF2E8:
	.incbin "sound/direct_sound_samples/084DF2E8.bin"

	.align 2
	.global DirectSoundData_084E20A0
DirectSoundData_084E20A0:
	.incbin "sound/direct_sound_samples/084E20A0.bin"

	.align 2
	.global DirectSoundData_084E7244
DirectSoundData_084E7244:
	.incbin "sound/direct_sound_samples/084E7244.bin"

	.align 2
	.global DirectSoundData_084F27CC
DirectSoundData_084F27CC:
	.incbin "sound/direct_sound_samples/084F27CC.bin"

	.align 2
	.global DirectSoundData_084F7390
DirectSoundData_084F7390:
	.incbin "sound/direct_sound_samples/084F7390.bin"

	.align 2
	.global DirectSoundData_084F7C7C
DirectSoundData_084F7C7C:
	.incbin "sound/direct_sound_samples/084F7C7C.bin"

	.align 2
	.global DirectSoundData_084F9EE8
DirectSoundData_084F9EE8:
	.incbin "sound/direct_sound_samples/084F9EE8.bin"

	.align 2
	.global DirectSoundData_084FA19C
DirectSoundData_084FA19C:
	.incbin "sound/direct_sound_samples/084FA19C.bin"

	.align 2
	.global DirectSoundData_084FC158
DirectSoundData_084FC158:
	.incbin "sound/direct_sound_samples/084FC158.bin"

	.align 2
	.global DirectSoundData_084FC3B8
DirectSoundData_084FC3B8:
	.incbin "sound/direct_sound_samples/084FC3B8.bin"

	.align 2
	.global DirectSoundData_084FC718
DirectSoundData_084FC718:
	.incbin "sound/direct_sound_samples/084FC718.bin"

	.align 2
	.global DirectSoundData_084FCAA8
DirectSoundData_084FCAA8:
	.incbin "sound/direct_sound_samples/084FCAA8.bin"

	.align 2
	.global DirectSoundData_084FCFB4
DirectSoundData_084FCFB4:
	.incbin "sound/direct_sound_samples/084FCFB4.bin"

	.align 2
	.global DirectSoundData_084FD7B0
DirectSoundData_084FD7B0:
	.incbin "sound/direct_sound_samples/084FD7B0.bin"

	.align 2
	.global DirectSoundData_084FDB48
DirectSoundData_084FDB48:
	.incbin "sound/direct_sound_samples/084FDB48.bin"

	.align 2
	.global DirectSoundData_084FE008
DirectSoundData_084FE008:
	.incbin "sound/direct_sound_samples/084FE008.bin"

	.align 2
	.global DirectSoundData_084FE1F0
DirectSoundData_084FE1F0:
	.incbin "sound/direct_sound_samples/084FE1F0.bin"

	.align 2
	.global DirectSoundData_084FEC3C
DirectSoundData_084FEC3C:
	.incbin "sound/direct_sound_samples/084FEC3C.bin"

	.align 2
	.global DirectSoundData_084FEE4C
DirectSoundData_084FEE4C:
	.incbin "sound/direct_sound_samples/084FEE4C.bin"

	.align 2
	.global DirectSoundData_084FF020
DirectSoundData_084FF020:
	.incbin "sound/direct_sound_samples/084FF020.bin"

	.align 2
	.global DirectSoundData_084FF26C
DirectSoundData_084FF26C:
	.incbin "sound/direct_sound_samples/084FF26C.bin"

	.align 2
	.global DirectSoundData_084FF5C4
DirectSoundData_084FF5C4:
	.incbin "sound/direct_sound_samples/084FF5C4.bin"

	.align 2
	.global DirectSoundData_085006D0
DirectSoundData_085006D0:
	.incbin "sound/direct_sound_samples/085006D0.bin"

	.align 2
	.global DirectSoundData_085016D8
DirectSoundData_085016D8:
	.incbin "sound/direct_sound_samples/085016D8.bin"

	.align 2
	.global DirectSoundData_08502CB4
DirectSoundData_08502CB4:
	.incbin "sound/direct_sound_samples/08502CB4.bin"

	.align 2
	.global DirectSoundData_08503E8C
DirectSoundData_08503E8C:
	.incbin "sound/direct_sound_samples/08503E8C.bin"

	.align 2
	.global DirectSoundData_085045A8
DirectSoundData_085045A8:
	.incbin "sound/direct_sound_samples/085045A8.bin"

	.align 2
	.global DirectSoundData_08504F40
DirectSoundData_08504F40:
	.incbin "sound/direct_sound_samples/08504F40.bin"

	.align 2
	.global DirectSoundData_08505B2C
DirectSoundData_08505B2C:
	.incbin "sound/direct_sound_samples/08505B2C.bin"

	.align 2
	.global DirectSoundData_08506018
DirectSoundData_08506018:
	.incbin "sound/direct_sound_samples/08506018.bin"

	.align 2
	.global DirectSoundData_08506B50
DirectSoundData_08506B50:
	.incbin "sound/direct_sound_samples/08506B50.bin"

	.align 2
	.global DirectSoundData_08507D60
DirectSoundData_08507D60:
	.incbin "sound/direct_sound_samples/08507D60.bin"

	.align 2
	.global DirectSoundData_08508870
DirectSoundData_08508870:
	.incbin "sound/direct_sound_samples/08508870.bin"

	.align 2
	.global DirectSoundData_0850A7D0
DirectSoundData_0850A7D0:
	.incbin "sound/direct_sound_samples/0850A7D0.bin"

	.align 2
	.global DirectSoundData_0850C548
DirectSoundData_0850C548:
	.incbin "sound/direct_sound_samples/0850C548.bin"

	.align 2
	.global DirectSoundData_0850E4A0
DirectSoundData_0850E4A0:
	.incbin "sound/direct_sound_samples/0850E4A0.bin"

	.align 2
	.global DirectSoundData_0850E8E8
DirectSoundData_0850E8E8:
	.incbin "sound/direct_sound_samples/0850E8E8.bin"

	.align 2
	.global DirectSoundData_0850F1CC
DirectSoundData_0850F1CC:
	.incbin "sound/direct_sound_samples/0850F1CC.bin"

	.align 2
	.global DirectSoundData_08512AB8
DirectSoundData_08512AB8:
	.incbin "sound/direct_sound_samples/08512AB8.bin"

	.align 2
	.global DirectSoundData_08516680
DirectSoundData_08516680:
	.incbin "sound/direct_sound_samples/08516680.bin"

	.align 2
	.global DirectSoundData_08517CC8
DirectSoundData_08517CC8:
	.incbin "sound/direct_sound_samples/08517CC8.bin"

	.align 2
	.global DirectSoundData_0851A674
DirectSoundData_0851A674:
	.incbin "sound/direct_sound_samples/0851A674.bin"

	.align 2
	.global DirectSoundData_0851CDA4
DirectSoundData_0851CDA4:
	.incbin "sound/direct_sound_samples/0851CDA4.bin"

	.align 2
	.global DirectSoundData_0851E398
DirectSoundData_0851E398:
	.incbin "sound/direct_sound_samples/0851E398.bin"

	.align 2
	.global DirectSoundData_0851EC74
DirectSoundData_0851EC74:
	.incbin "sound/direct_sound_samples/0851EC74.bin"

	.align 2
	.global DirectSoundData_0851FF4C
DirectSoundData_0851FF4C:
	.incbin "sound/direct_sound_samples/0851FF4C.bin"

	.align 2
	.global DirectSoundData_08524984
DirectSoundData_08524984:
	.incbin "sound/direct_sound_samples/08524984.bin"

	.align 2
	.global DirectSoundData_08524DBC
DirectSoundData_08524DBC:
	.incbin "sound/direct_sound_samples/08524DBC.bin"

	.align 2
	.global DirectSoundData_08525FB8
DirectSoundData_08525FB8:
	.incbin "sound/direct_sound_samples/08525FB8.bin"

	.align 2
	.global DirectSoundData_0852674C
DirectSoundData_0852674C:
	.incbin "sound/direct_sound_samples/0852674C.bin"

	.align 2
	.global DirectSoundData_08528258
DirectSoundData_08528258:
	.incbin "sound/direct_sound_samples/08528258.bin"

	.align 2
	.global DirectSoundData_085298AC
DirectSoundData_085298AC:
	.incbin "sound/direct_sound_samples/085298AC.bin"

	.align 2
	.global DirectSoundData_0852D908
DirectSoundData_0852D908:
	.incbin "sound/direct_sound_samples/0852D908.bin"

	.align 2
	.global DirectSoundData_08530CDC
DirectSoundData_08530CDC:
	.incbin "sound/direct_sound_samples/08530CDC.bin"

	.align 2
	.global DirectSoundData_0853318C
DirectSoundData_0853318C:
	.incbin "sound/direct_sound_samples/0853318C.bin"

	.align 2
	.global DirectSoundData_08535F64
DirectSoundData_08535F64:
	.incbin "sound/direct_sound_samples/08535F64.bin"

	.align 2
	.global DirectSoundData_0853A088
DirectSoundData_0853A088:
	.incbin "sound/direct_sound_samples/0853A088.bin"

	.align 2
	.global DirectSoundData_0853A634
DirectSoundData_0853A634:
	.incbin "sound/direct_sound_samples/0853A634.bin"

	.align 2
	.global DirectSoundData_0853FF58
DirectSoundData_0853FF58:
	.incbin "sound/direct_sound_samples/0853FF58.bin"

	.align 2
	.global DirectSoundData_08540AC8
DirectSoundData_08540AC8:
	.incbin "sound/direct_sound_samples/08540AC8.bin"

	.align 2
	.global DirectSoundData_085411C8
DirectSoundData_085411C8:
	.incbin "sound/direct_sound_samples/085411C8.bin"

	.align 2
	.global DirectSoundData_08543C90
DirectSoundData_08543C90:
	.incbin "sound/direct_sound_samples/08543C90.bin"

	.align 2
