	.align 2
	.global DirectSoundWaveData_082263B4
DirectSoundWaveData_082263B4:
	.incbin "sound/direct_sound_samples/082263B4.pcm"

	.align 2
	.global DirectSoundWaveData_08227988
DirectSoundWaveData_08227988:
	.incbin "sound/direct_sound_samples/08227988.pcm"

	.align 2
	.global DirectSoundWaveData_0822807C
DirectSoundWaveData_0822807C:
	.incbin "sound/direct_sound_samples/0822807C.pcm"

	.align 2
	.global DirectSoundWaveData_08228C7C
DirectSoundWaveData_08228C7C:
	.incbin "sound/direct_sound_samples/08228C7C.pcm"

	.align 2
	.global DirectSoundWaveData_0822B4DC
DirectSoundWaveData_0822B4DC:
	.incbin "sound/direct_sound_samples/0822B4DC.pcm"

	.align 2
	.global DirectSoundWaveData_08233650
DirectSoundWaveData_08233650:
	.incbin "sound/direct_sound_samples/08233650.pcm"

	.align 2
	.global DirectSoundWaveData_082367A8
DirectSoundWaveData_082367A8:
	.incbin "sound/direct_sound_samples/082367A8.pcm"

	.align 2
	.global DirectSoundWaveData_0823B5FC
DirectSoundWaveData_0823B5FC:
	.incbin "sound/direct_sound_samples/0823B5FC.pcm"

	.align 2
	.global DirectSoundWaveData_0823F698
DirectSoundWaveData_0823F698:
	.incbin "sound/direct_sound_samples/0823F698.pcm"

	.align 2
	.global DirectSoundWaveData_08243A54
DirectSoundWaveData_08243A54:
	.incbin "sound/direct_sound_samples/08243A54.pcm"

	.align 2
	.global DirectSoundWaveData_08247AE8
DirectSoundWaveData_08247AE8:
	.incbin "sound/direct_sound_samples/08247AE8.pcm"

	.align 2
	.global DirectSoundWaveData_0824BBAC
DirectSoundWaveData_0824BBAC:
	.incbin "sound/direct_sound_samples/0824BBAC.pcm"

	.align 2
	.global DirectSoundWaveData_0825305C
DirectSoundWaveData_0825305C:
	.incbin "sound/direct_sound_samples/0825305C.pcm"

	.align 2
	.global DirectSoundWaveData_082595BC
DirectSoundWaveData_082595BC:
	.incbin "sound/direct_sound_samples/082595BC.pcm"

	.align 2
	.global DirectSoundWaveData_08261150
DirectSoundWaveData_08261150:
	.incbin "sound/direct_sound_samples/08261150.pcm"

	.align 2
	.global DirectSoundWaveData_08265DDC
DirectSoundWaveData_08265DDC:
	.incbin "sound/direct_sound_samples/08265DDC.pcm"

	.align 2
	.global DirectSoundWaveData_0826CFD0
DirectSoundWaveData_0826CFD0:
	.incbin "sound/direct_sound_samples/0826CFD0.pcm"

	.align 2
	.global DirectSoundWaveData_08274F48
DirectSoundWaveData_08274F48:
	.incbin "sound/direct_sound_samples/08274F48.pcm"

	.align 2
	.global DirectSoundWaveData_0827BBD0
DirectSoundWaveData_0827BBD0:
	.incbin "sound/direct_sound_samples/0827BBD0.pcm"

	.align 2
	.global DirectSoundWaveData_0827E28C
DirectSoundWaveData_0827E28C:
	.incbin "sound/direct_sound_samples/0827E28C.pcm"

	.align 2
	.global DirectSoundWaveData_0827E640
DirectSoundWaveData_0827E640:
	.incbin "sound/direct_sound_samples/0827E640.pcm"

	.align 2
	.global DirectSoundWaveData_08280AF0
DirectSoundWaveData_08280AF0:
	.incbin "sound/direct_sound_samples/08280AF0.pcm"

	.align 2
	.global DirectSoundWaveData_08281974
DirectSoundWaveData_08281974:
	.incbin "sound/direct_sound_samples/08281974.pcm"

	.align 2
	.global DirectSoundWaveData_08281DD0
DirectSoundWaveData_08281DD0:
	.incbin "sound/direct_sound_samples/08281DD0.pcm"

	.align 2
	.global DirectSoundWaveData_08287CC4
DirectSoundWaveData_08287CC4:
	.incbin "sound/direct_sound_samples/08287CC4.pcm"

	.align 2
	.global DirectSoundWaveData_08288F7C
DirectSoundWaveData_08288F7C:
	.incbin "sound/direct_sound_samples/08288F7C.pcm"

	.align 2
	.global DirectSoundWaveData_08289978
DirectSoundWaveData_08289978:
	.incbin "sound/direct_sound_samples/08289978.pcm"

	.align 2
	.global DirectSoundWaveData_0828B404
DirectSoundWaveData_0828B404:
	.incbin "sound/direct_sound_samples/0828B404.pcm"

	.align 2
	.global DirectSoundWaveData_0828CD70
DirectSoundWaveData_0828CD70:
	.incbin "sound/direct_sound_samples/0828CD70.pcm"

	.align 2
	.global DirectSoundWaveData_0828DDD0
DirectSoundWaveData_0828DDD0:
	.incbin "sound/direct_sound_samples/0828DDD0.pcm"

	.align 2
	.global DirectSoundWaveData_0828F524
DirectSoundWaveData_0828F524:
	.incbin "sound/direct_sound_samples/0828F524.pcm"

	.align 2
	.global DirectSoundWaveData_082903C8
DirectSoundWaveData_082903C8:
	.incbin "sound/direct_sound_samples/082903C8.pcm"

	.align 2
	.global DirectSoundWaveData_08293544
DirectSoundWaveData_08293544:
	.incbin "sound/direct_sound_samples/08293544.pcm"

	.align 2
	.global DirectSoundWaveData_082962B0
DirectSoundWaveData_082962B0:
	.incbin "sound/direct_sound_samples/082962B0.pcm"

	.align 2
	.global DirectSoundWaveData_08296E54
DirectSoundWaveData_08296E54:
	.incbin "sound/direct_sound_samples/08296E54.pcm"

	.align 2
	.global DirectSoundWaveData_0829918C
DirectSoundWaveData_0829918C:
	.incbin "sound/direct_sound_samples/0829918C.pcm"

	.align 2
	.global DirectSoundWaveData_0829A1EC
DirectSoundWaveData_0829A1EC:
	.incbin "sound/direct_sound_samples/0829A1EC.pcm"

	.align 2
	.global DirectSoundWaveData_0829ED58
DirectSoundWaveData_0829ED58:
	.incbin "sound/direct_sound_samples/0829ED58.pcm"

	.align 2
	.global DirectSoundWaveData_082A0690
DirectSoundWaveData_082A0690:
	.incbin "sound/direct_sound_samples/082A0690.pcm"

	.align 2
	.global DirectSoundWaveData_082A1728
DirectSoundWaveData_082A1728:
	.incbin "sound/direct_sound_samples/082A1728.pcm"

	.align 2
	.global DirectSoundWaveData_082A7AA8
DirectSoundWaveData_082A7AA8:
	.incbin "sound/direct_sound_samples/082A7AA8.pcm"

	.align 2
	.global DirectSoundWaveData_082A8068
DirectSoundWaveData_082A8068:
	.incbin "sound/direct_sound_samples/082A8068.pcm"

	.align 2
	.global DirectSoundWaveData_082AC224
DirectSoundWaveData_082AC224:
	.incbin "sound/direct_sound_samples/082AC224.pcm"

	.align 2
	.global DirectSoundWaveData_082AC868
DirectSoundWaveData_082AC868:
	.incbin "sound/direct_sound_samples/082AC868.pcm"

	.align 2
	.global DirectSoundWaveData_082ADD3C
DirectSoundWaveData_082ADD3C:
	.incbin "sound/direct_sound_samples/082ADD3C.pcm"

	.align 2
	.global DirectSoundWaveData_082AE988
DirectSoundWaveData_082AE988:
	.incbin "sound/direct_sound_samples/082AE988.pcm"

	.align 2
	.global DirectSoundWaveData_082AF0B0
DirectSoundWaveData_082AF0B0:
	.incbin "sound/direct_sound_samples/082AF0B0.pcm"

	.align 2
	.global DirectSoundWaveData_082B235C
DirectSoundWaveData_082B235C:
	.incbin "sound/direct_sound_samples/082B235C.pcm"

	.align 2
	.global DirectSoundWaveData_082B3F54
DirectSoundWaveData_082B3F54:
	.incbin "sound/direct_sound_samples/082B3F54.pcm"

	.align 2
	.global DirectSoundWaveData_082BA464
DirectSoundWaveData_082BA464:
	.incbin "sound/direct_sound_samples/082BA464.pcm"

	.align 2
	.global DirectSoundWaveData_082BB7F4
DirectSoundWaveData_082BB7F4:
	.incbin "sound/direct_sound_samples/082BB7F4.pcm"

	.align 2
	.global DirectSoundWaveData_082C0D0C
DirectSoundWaveData_082C0D0C:
	.incbin "sound/direct_sound_samples/082C0D0C.pcm"

	.align 2
	.global DirectSoundWaveData_082C24A8
DirectSoundWaveData_082C24A8:
	.incbin "sound/direct_sound_samples/082C24A8.pcm"

	.align 2
	.global DirectSoundWaveData_082C5874
DirectSoundWaveData_082C5874:
	.incbin "sound/direct_sound_samples/082C5874.pcm"

	.align 2
	.global DirectSoundWaveData_082C6A4C
DirectSoundWaveData_082C6A4C:
	.incbin "sound/direct_sound_samples/082C6A4C.pcm"

	.align 2
	.global DirectSoundWaveData_082C6DB8
DirectSoundWaveData_082C6DB8:
	.incbin "sound/direct_sound_samples/082C6DB8.pcm"

	.align 2
	.global DirectSoundWaveData_082CAC80
DirectSoundWaveData_082CAC80:
	.incbin "sound/direct_sound_samples/082CAC80.pcm"

	.align 2
	.global DirectSoundWaveData_082CB2F8
DirectSoundWaveData_082CB2F8:
	.incbin "sound/direct_sound_samples/082CB2F8.pcm"

	.align 2
	.global DirectSoundWaveData_082CBE8C
DirectSoundWaveData_082CBE8C:
	.incbin "sound/direct_sound_samples/082CBE8C.pcm"

	.align 2
	.global DirectSoundWaveData_082CD7F4
DirectSoundWaveData_082CD7F4:
	.incbin "sound/direct_sound_samples/082CD7F4.pcm"

	.align 2
	.global DirectSoundWaveData_082CF3B0
DirectSoundWaveData_082CF3B0:
	.incbin "sound/direct_sound_samples/082CF3B0.pcm"

	.align 2
	.global DirectSoundWaveData_082D0018
DirectSoundWaveData_082D0018:
	.incbin "sound/direct_sound_samples/082D0018.pcm"

	.align 2
	.global DirectSoundWaveData_082D0414
DirectSoundWaveData_082D0414:
	.incbin "sound/direct_sound_samples/082D0414.pcm"

	.align 2
	.global DirectSoundWaveData_082D0964
DirectSoundWaveData_082D0964:
	.incbin "sound/direct_sound_samples/082D0964.pcm"

	.align 2
	.global DirectSoundWaveData_082D0C08
DirectSoundWaveData_082D0C08:
	.incbin "sound/direct_sound_samples/082D0C08.pcm"

	.align 2
	.global DirectSoundWaveData_082D1238
DirectSoundWaveData_082D1238:
	.incbin "sound/direct_sound_samples/082D1238.pcm"

	.align 2
	.global DirectSoundWaveData_082D1818
DirectSoundWaveData_082D1818:
	.incbin "sound/direct_sound_samples/082D1818.pcm"

	.align 2
	.global DirectSoundWaveData_082D2050
DirectSoundWaveData_082D2050:
	.incbin "sound/direct_sound_samples/082D2050.pcm"

	.align 2
	.global DirectSoundWaveData_082D293C
DirectSoundWaveData_082D293C:
	.incbin "sound/direct_sound_samples/082D293C.pcm"

	.align 2
	.global DirectSoundWaveData_082D2EA4
DirectSoundWaveData_082D2EA4:
	.incbin "sound/direct_sound_samples/082D2EA4.pcm"

	.align 2
	.global DirectSoundWaveData_082D3020
DirectSoundWaveData_082D3020:
	.incbin "sound/direct_sound_samples/082D3020.pcm"

	.align 2
	.global DirectSoundWaveData_082D4BE4
DirectSoundWaveData_082D4BE4:
	.incbin "sound/direct_sound_samples/082D4BE4.pcm"

	.align 2
	.global DirectSoundWaveData_082D6BA0
DirectSoundWaveData_082D6BA0:
	.incbin "sound/direct_sound_samples/082D6BA0.pcm"

	.align 2
	.global DirectSoundWaveData_082D712C
DirectSoundWaveData_082D712C:
	.incbin "sound/direct_sound_samples/082D712C.pcm"

	.align 2
	.global DirectSoundWaveData_082D80E0
DirectSoundWaveData_082D80E0:
	.incbin "sound/direct_sound_samples/082D80E0.pcm"

	.align 2
	.global DirectSoundWaveData_082DB668
DirectSoundWaveData_082DB668:
	.incbin "sound/direct_sound_samples/082DB668.pcm"

	.align 2
	.global DirectSoundWaveData_082DE9D8
DirectSoundWaveData_082DE9D8:
	.incbin "sound/direct_sound_samples/082DE9D8.pcm"

	.align 2
	.global DirectSoundWaveData_082E2F6C
DirectSoundWaveData_082E2F6C:
	.incbin "sound/direct_sound_samples/082E2F6C.pcm"

	.align 2
	.global DirectSoundWaveData_082E7580
DirectSoundWaveData_082E7580:
	.incbin "sound/direct_sound_samples/082E7580.pcm"

	.align 2
	.global DirectSoundWaveData_082EA140
DirectSoundWaveData_082EA140:
	.incbin "sound/direct_sound_samples/082EA140.pcm"

	.align 2
	.global DirectSoundWaveData_082EBA88
DirectSoundWaveData_082EBA88:
	.incbin "sound/direct_sound_samples/082EBA88.pcm"

	.align 2
	.global DirectSoundWaveData_082ED1FC
DirectSoundWaveData_082ED1FC:
	.incbin "sound/direct_sound_samples/082ED1FC.pcm"

	.align 2
	.global DirectSoundWaveData_082EE958
DirectSoundWaveData_082EE958:
	.incbin "sound/direct_sound_samples/082EE958.pcm"

	.align 2
	.global DirectSoundWaveData_082F0884
DirectSoundWaveData_082F0884:
	.incbin "sound/direct_sound_samples/082F0884.pcm"

	.align 2
	.global DirectSoundWaveData_082F21F8
DirectSoundWaveData_082F21F8:
	.incbin "sound/direct_sound_samples/082F21F8.pcm"

	.align 2
	.global DirectSoundWaveData_082F2E14
DirectSoundWaveData_082F2E14:
	.incbin "sound/direct_sound_samples/082F2E14.pcm"

	.align 2
	.global DirectSoundWaveData_082F4654
DirectSoundWaveData_082F4654:
	.incbin "sound/direct_sound_samples/082F4654.pcm"

	.align 2
	.global DirectSoundWaveData_082F725C
DirectSoundWaveData_082F725C:
	.incbin "sound/direct_sound_samples/082F725C.pcm"

	.align 2
	.global DirectSoundWaveData_082F89B8
DirectSoundWaveData_082F89B8:
	.incbin "sound/direct_sound_samples/082F89B8.pcm"

	.align 2
	.global DirectSoundWaveData_082F9520
DirectSoundWaveData_082F9520:
	.incbin "sound/direct_sound_samples/082F9520.pcm"

	.align 2
	.global DirectSoundWaveData_082FBF50
DirectSoundWaveData_082FBF50:
	.incbin "sound/direct_sound_samples/082FBF50.pcm"

	.align 2
	.global DirectSoundWaveData_082FE634
DirectSoundWaveData_082FE634:
	.incbin "sound/direct_sound_samples/082FE634.pcm"

	.align 2
	.global DirectSoundWaveData_08300664
DirectSoundWaveData_08300664:
	.incbin "sound/direct_sound_samples/08300664.pcm"

	.align 2
	.global DirectSoundWaveData_08302860
DirectSoundWaveData_08302860:
	.incbin "sound/direct_sound_samples/08302860.pcm"

	.align 2
	.global DirectSoundWaveData_083099E8
DirectSoundWaveData_083099E8:
	.incbin "sound/direct_sound_samples/083099E8.pcm"

	.align 2
	.global DirectSoundWaveData_0830A05C
DirectSoundWaveData_0830A05C:
	.incbin "sound/direct_sound_samples/0830A05C.pcm"

	.align 2
	.global DirectSoundWaveData_0830A720
DirectSoundWaveData_0830A720:
	.incbin "sound/direct_sound_samples/0830A720.pcm"

	.align 2
	.global DirectSoundWaveData_0830DCA8
DirectSoundWaveData_0830DCA8:
	.incbin "sound/direct_sound_samples/0830DCA8.pcm"

	.align 2
	.global DirectSoundWaveData_0830E770
DirectSoundWaveData_0830E770:
	.incbin "sound/direct_sound_samples/0830E770.pcm"

	.align 2
	.global DirectSoundWaveData_0830F1BC
DirectSoundWaveData_0830F1BC:
	.incbin "sound/direct_sound_samples/0830F1BC.pcm"

	.align 2
	.global DirectSoundWaveData_0830FA60
DirectSoundWaveData_0830FA60:
	.incbin "sound/direct_sound_samples/0830FA60.pcm"

	.align 2
	.global DirectSoundWaveData_08310124
DirectSoundWaveData_08310124:
	.incbin "sound/direct_sound_samples/08310124.pcm"

	.align 2
	.global DirectSoundWaveData_08310DDC
DirectSoundWaveData_08310DDC:
	.incbin "sound/direct_sound_samples/08310DDC.pcm"

	.align 2
	.global DirectSoundWaveData_083116C4
DirectSoundWaveData_083116C4:
	.incbin "sound/direct_sound_samples/083116C4.pcm"

	.align 2
	.global DirectSoundWaveData_08311AC8
DirectSoundWaveData_08311AC8:
	.incbin "sound/direct_sound_samples/08311AC8.pcm"

	.align 2
	.global DirectSoundWaveData_0831229C
DirectSoundWaveData_0831229C:
	.incbin "sound/direct_sound_samples/0831229C.pcm"

	.align 2
	.global DirectSoundWaveData_08312AE0
DirectSoundWaveData_08312AE0:
	.incbin "sound/direct_sound_samples/08312AE0.pcm"

	.align 2
	.global DirectSoundWaveData_083133CC
DirectSoundWaveData_083133CC:
	.incbin "sound/direct_sound_samples/083133CC.pcm"

	.align 2
	.global DirectSoundWaveData_08316404
DirectSoundWaveData_08316404:
	.incbin "sound/direct_sound_samples/08316404.pcm"

	.align 2
	.global DirectSoundWaveData_08318D10
DirectSoundWaveData_08318D10:
	.incbin "sound/direct_sound_samples/08318D10.pcm"

	.align 2
	.global DirectSoundWaveData_0831A290
DirectSoundWaveData_0831A290:
	.incbin "sound/direct_sound_samples/0831A290.pcm"

	.align 2
	.global DirectSoundWaveData_0831AADC
DirectSoundWaveData_0831AADC:
	.incbin "sound/direct_sound_samples/0831AADC.pcm"

	.align 2
	.global DirectSoundWaveData_0831B314
DirectSoundWaveData_0831B314:
	.incbin "sound/direct_sound_samples/0831B314.pcm"

	.align 2
	.global DirectSoundWaveData_0831C44C
DirectSoundWaveData_0831C44C:
	.incbin "sound/direct_sound_samples/0831C44C.pcm"

	.align 2
	.global DirectSoundWaveData_0831E954
DirectSoundWaveData_0831E954:
	.incbin "sound/direct_sound_samples/0831E954.pcm"

	.align 2
	.global DirectSoundWaveData_08320768
DirectSoundWaveData_08320768:
	.incbin "sound/direct_sound_samples/08320768.pcm"

	.align 2
	.global DirectSoundWaveData_08321C10
DirectSoundWaveData_08321C10:
	.incbin "sound/direct_sound_samples/08321C10.pcm"

	.align 2
	.global DirectSoundWaveData_08325FE8
DirectSoundWaveData_08325FE8:
	.incbin "sound/direct_sound_samples/08325FE8.pcm"

	.align 2
	.global DirectSoundWaveData_0832888C
DirectSoundWaveData_0832888C:
	.incbin "sound/direct_sound_samples/0832888C.pcm"

	.align 2
	.global DirectSoundWaveData_0832E5F8
DirectSoundWaveData_0832E5F8:
	.incbin "sound/direct_sound_samples/0832E5F8.pcm"

	.align 2
	.global DirectSoundWaveData_08330AFC
DirectSoundWaveData_08330AFC:
	.incbin "sound/direct_sound_samples/08330AFC.pcm"

	.align 2
	.global DirectSoundWaveData_08331584
DirectSoundWaveData_08331584:
	.incbin "sound/direct_sound_samples/08331584.pcm"

	.align 2
	.global DirectSoundWaveData_08331EAC
DirectSoundWaveData_08331EAC:
	.incbin "sound/direct_sound_samples/08331EAC.pcm"

	.align 2
	.global DirectSoundWaveData_083328AC
DirectSoundWaveData_083328AC:
	.incbin "sound/direct_sound_samples/083328AC.pcm"

	.align 2
	.global DirectSoundWaveData_08333A94
DirectSoundWaveData_08333A94:
	.incbin "sound/direct_sound_samples/08333A94.pcm"

	.align 2
	.global DirectSoundWaveData_083355B8
DirectSoundWaveData_083355B8:
	.incbin "sound/direct_sound_samples/083355B8.pcm"

	.align 2
	.global DirectSoundWaveData_08336F24
DirectSoundWaveData_08336F24:
	.incbin "sound/direct_sound_samples/08336F24.pcm"

	.align 2
	.global DirectSoundWaveData_08338014
DirectSoundWaveData_08338014:
	.incbin "sound/direct_sound_samples/08338014.pcm"

	.align 2
	.global DirectSoundWaveData_083395B8
DirectSoundWaveData_083395B8:
	.incbin "sound/direct_sound_samples/083395B8.pcm"

	.align 2
	.global DirectSoundWaveData_0833C914
DirectSoundWaveData_0833C914:
	.incbin "sound/direct_sound_samples/0833C914.pcm"

	.align 2
	.global DirectSoundWaveData_0833E0E8
DirectSoundWaveData_0833E0E8:
	.incbin "sound/direct_sound_samples/0833E0E8.pcm"

	.align 2
	.global DirectSoundWaveData_0834146C
DirectSoundWaveData_0834146C:
	.incbin "sound/direct_sound_samples/0834146C.pcm"

	.align 2
	.global DirectSoundWaveData_0834533C
DirectSoundWaveData_0834533C:
	.incbin "sound/direct_sound_samples/0834533C.pcm"

	.align 2
	.global DirectSoundWaveData_08347BC4
DirectSoundWaveData_08347BC4:
	.incbin "sound/direct_sound_samples/08347BC4.pcm"

	.align 2
	.global DirectSoundWaveData_0834CA04
DirectSoundWaveData_0834CA04:
	.incbin "sound/direct_sound_samples/0834CA04.pcm"

	.align 2
	.global DirectSoundWaveData_0835186C
DirectSoundWaveData_0835186C:
	.incbin "sound/direct_sound_samples/0835186C.pcm"

	.align 2
	.global DirectSoundWaveData_0835548C
DirectSoundWaveData_0835548C:
	.incbin "sound/direct_sound_samples/0835548C.pcm"

	.align 2
	.global DirectSoundWaveData_083590A8
DirectSoundWaveData_083590A8:
	.incbin "sound/direct_sound_samples/083590A8.pcm"

	.align 2
	.global DirectSoundWaveData_0835CA6C
DirectSoundWaveData_0835CA6C:
	.incbin "sound/direct_sound_samples/0835CA6C.pcm"

	.align 2
	.global DirectSoundWaveData_08361CD0
DirectSoundWaveData_08361CD0:
	.incbin "sound/direct_sound_samples/08361CD0.pcm"

	.align 2
	.global DirectSoundWaveData_08366110
DirectSoundWaveData_08366110:
	.incbin "sound/direct_sound_samples/08366110.pcm"

	.align 2
	.global DirectSoundWaveData_08367F14
DirectSoundWaveData_08367F14:
	.incbin "sound/direct_sound_samples/08367F14.pcm"

	.align 2
	.global DirectSoundWaveData_08368534
DirectSoundWaveData_08368534:
	.incbin "sound/direct_sound_samples/08368534.pcm"

	.align 2
	.global DirectSoundWaveData_0836B504
DirectSoundWaveData_0836B504:
	.incbin "sound/direct_sound_samples/0836B504.pcm"

	.align 2
	.global DirectSoundWaveData_0836CD24
DirectSoundWaveData_0836CD24:
	.incbin "sound/direct_sound_samples/0836CD24.pcm"

	.align 2
	.global DirectSoundWaveData_0836EE64
DirectSoundWaveData_0836EE64:
	.incbin "sound/direct_sound_samples/0836EE64.pcm"

	.align 2
	.global DirectSoundWaveData_08372138
DirectSoundWaveData_08372138:
	.incbin "sound/direct_sound_samples/08372138.pcm"

	.align 2
	.global DirectSoundWaveData_08375140
DirectSoundWaveData_08375140:
	.incbin "sound/direct_sound_samples/08375140.pcm"

	.align 2
	.global DirectSoundWaveData_08376650
DirectSoundWaveData_08376650:
	.incbin "sound/direct_sound_samples/08376650.pcm"

	.align 2
	.global DirectSoundWaveData_08378A1C
DirectSoundWaveData_08378A1C:
	.incbin "sound/direct_sound_samples/08378A1C.pcm"

	.align 2
	.global DirectSoundWaveData_0837A1B4
DirectSoundWaveData_0837A1B4:
	.incbin "sound/direct_sound_samples/0837A1B4.pcm"

	.align 2
	.global DirectSoundWaveData_0837B918
DirectSoundWaveData_0837B918:
	.incbin "sound/direct_sound_samples/0837B918.pcm"

	.align 2
	.global DirectSoundWaveData_0837EEC0
DirectSoundWaveData_0837EEC0:
	.incbin "sound/direct_sound_samples/0837EEC0.pcm"

	.align 2
	.global DirectSoundWaveData_083804A4
DirectSoundWaveData_083804A4:
	.incbin "sound/direct_sound_samples/083804A4.pcm"

	.align 2
	.global DirectSoundWaveData_08382B10
DirectSoundWaveData_08382B10:
	.incbin "sound/direct_sound_samples/08382B10.pcm"

	.align 2
	.global DirectSoundWaveData_08385640
DirectSoundWaveData_08385640:
	.incbin "sound/direct_sound_samples/08385640.pcm"

	.align 2
	.global DirectSoundWaveData_08385F48
DirectSoundWaveData_08385F48:
	.incbin "sound/direct_sound_samples/08385F48.pcm"

	.align 2
	.global DirectSoundWaveData_0838642C
DirectSoundWaveData_0838642C:
	.incbin "sound/direct_sound_samples/0838642C.pcm"

	.align 2
	.global DirectSoundWaveData_08386EB4
DirectSoundWaveData_08386EB4:
	.incbin "sound/direct_sound_samples/08386EB4.pcm"

	.align 2
	.global DirectSoundWaveData_08388008
DirectSoundWaveData_08388008:
	.incbin "sound/direct_sound_samples/08388008.pcm"

	.align 2
	.global DirectSoundWaveData_083885DC
DirectSoundWaveData_083885DC:
	.incbin "sound/direct_sound_samples/083885DC.pcm"

	.align 2
	.global DirectSoundWaveData_08388B5C
DirectSoundWaveData_08388B5C:
	.incbin "sound/direct_sound_samples/08388B5C.pcm"

	.align 2
	.global DirectSoundWaveData_083895E4
DirectSoundWaveData_083895E4:
	.incbin "sound/direct_sound_samples/083895E4.pcm"

	.align 2
	.global DirectSoundWaveData_0838A5A8
DirectSoundWaveData_0838A5A8:
	.incbin "sound/direct_sound_samples/0838A5A8.pcm"

	.align 2
	.global DirectSoundWaveData_0838ABC0
DirectSoundWaveData_0838ABC0:
	.incbin "sound/direct_sound_samples/0838ABC0.pcm"

	.align 2
	.global DirectSoundWaveData_0838B098
DirectSoundWaveData_0838B098:
	.incbin "sound/direct_sound_samples/0838B098.pcm"

	.align 2
	.global DirectSoundWaveData_0838BAF4
DirectSoundWaveData_0838BAF4:
	.incbin "sound/direct_sound_samples/0838BAF4.pcm"

	.align 2
	.global DirectSoundWaveData_0838CAB8
DirectSoundWaveData_0838CAB8:
	.incbin "sound/direct_sound_samples/0838CAB8.pcm"

	.align 2
	.global DirectSoundWaveData_0838D240
DirectSoundWaveData_0838D240:
	.incbin "sound/direct_sound_samples/0838D240.pcm"

	.align 2
	.global DirectSoundWaveData_0838D940
DirectSoundWaveData_0838D940:
	.incbin "sound/direct_sound_samples/0838D940.pcm"

	.align 2
	.global DirectSoundWaveData_0838E3A0
DirectSoundWaveData_0838E3A0:
	.incbin "sound/direct_sound_samples/0838E3A0.pcm"

	.align 2
	.global DirectSoundWaveData_0838F364
DirectSoundWaveData_0838F364:
	.incbin "sound/direct_sound_samples/0838F364.pcm"

	.align 2
	.global DirectSoundWaveData_0838F994
DirectSoundWaveData_0838F994:
	.incbin "sound/direct_sound_samples/0838F994.pcm"

	.align 2
	.global DirectSoundWaveData_0838FEE0
DirectSoundWaveData_0838FEE0:
	.incbin "sound/direct_sound_samples/0838FEE0.pcm"

	.align 2
	.global DirectSoundWaveData_08390758
DirectSoundWaveData_08390758:
	.incbin "sound/direct_sound_samples/08390758.pcm"

	.align 2
	.global DirectSoundWaveData_08391480
DirectSoundWaveData_08391480:
	.incbin "sound/direct_sound_samples/08391480.pcm"

	.align 2
	.global DirectSoundWaveData_083918C0
DirectSoundWaveData_083918C0:
	.incbin "sound/direct_sound_samples/083918C0.pcm"

	.align 2
	.global DirectSoundWaveData_08391D8C
DirectSoundWaveData_08391D8C:
	.incbin "sound/direct_sound_samples/08391D8C.pcm"

	.align 2
	.global DirectSoundWaveData_08392980
DirectSoundWaveData_08392980:
	.incbin "sound/direct_sound_samples/08392980.pcm"

	.align 2
	.global DirectSoundWaveData_083932E4
DirectSoundWaveData_083932E4:
	.incbin "sound/direct_sound_samples/083932E4.pcm"

	.align 2
	.global DirectSoundWaveData_0839377C
DirectSoundWaveData_0839377C:
	.incbin "sound/direct_sound_samples/0839377C.pcm"

	.align 2
	.global DirectSoundWaveData_08393C08
DirectSoundWaveData_08393C08:
	.incbin "sound/direct_sound_samples/08393C08.pcm"

	.align 2
	.global DirectSoundWaveData_0839460C
DirectSoundWaveData_0839460C:
	.incbin "sound/direct_sound_samples/0839460C.pcm"

	.align 2
	.global DirectSoundWaveData_08395230
DirectSoundWaveData_08395230:
	.incbin "sound/direct_sound_samples/08395230.pcm"

	.align 2
	.global DirectSoundWaveData_0839639C
DirectSoundWaveData_0839639C:
	.incbin "sound/direct_sound_samples/0839639C.pcm"

	.align 2
	.global DirectSoundWaveData_08397150
DirectSoundWaveData_08397150:
	.incbin "sound/direct_sound_samples/08397150.pcm"

	.align 2
	.global DirectSoundWaveData_08398934
DirectSoundWaveData_08398934:
	.incbin "sound/direct_sound_samples/08398934.pcm"

	.align 2
	.global DirectSoundWaveData_083997C4
DirectSoundWaveData_083997C4:
	.incbin "sound/direct_sound_samples/083997C4.pcm"

	.align 2
	.global DirectSoundWaveData_0839A3BC
DirectSoundWaveData_0839A3BC:
	.incbin "sound/direct_sound_samples/0839A3BC.pcm"

	.align 2
	.global DirectSoundWaveData_0839AE78
DirectSoundWaveData_0839AE78:
	.incbin "sound/direct_sound_samples/0839AE78.pcm"

	.align 2
	.global DirectSoundWaveData_0839B80C
DirectSoundWaveData_0839B80C:
	.incbin "sound/direct_sound_samples/0839B80C.pcm"

	.align 2
	.global DirectSoundWaveData_0839C4D0
DirectSoundWaveData_0839C4D0:
	.incbin "sound/direct_sound_samples/0839C4D0.pcm"

	.align 2
	.global DirectSoundWaveData_0839D108
DirectSoundWaveData_0839D108:
	.incbin "sound/direct_sound_samples/0839D108.pcm"

	.align 2
	.global DirectSoundWaveData_0839D6EC
DirectSoundWaveData_0839D6EC:
	.incbin "sound/direct_sound_samples/0839D6EC.pcm"

	.align 2
	.global DirectSoundWaveData_0839E4D4
DirectSoundWaveData_0839E4D4:
	.incbin "sound/direct_sound_samples/0839E4D4.pcm"

	.align 2
	.global DirectSoundWaveData_0839F298
DirectSoundWaveData_0839F298:
	.incbin "sound/direct_sound_samples/0839F298.pcm"

	.align 2
	.global DirectSoundWaveData_0839FBCC
DirectSoundWaveData_0839FBCC:
	.incbin "sound/direct_sound_samples/0839FBCC.pcm"

	.align 2
	.global DirectSoundWaveData_083A09E4
DirectSoundWaveData_083A09E4:
	.incbin "sound/direct_sound_samples/083A09E4.pcm"

	.align 2
	.global DirectSoundWaveData_083A14A0
DirectSoundWaveData_083A14A0:
	.incbin "sound/direct_sound_samples/083A14A0.pcm"

	.align 2
	.global DirectSoundWaveData_083A1EF4
DirectSoundWaveData_083A1EF4:
	.incbin "sound/direct_sound_samples/083A1EF4.pcm"

	.align 2
	.global DirectSoundWaveData_083A2B88
DirectSoundWaveData_083A2B88:
	.incbin "sound/direct_sound_samples/083A2B88.pcm"

	.align 2
	.global DirectSoundWaveData_083A37C0
DirectSoundWaveData_083A37C0:
	.incbin "sound/direct_sound_samples/083A37C0.pcm"

	.align 2
	.global DirectSoundWaveData_083A3E80
DirectSoundWaveData_083A3E80:
	.incbin "sound/direct_sound_samples/083A3E80.pcm"

	.align 2
	.global DirectSoundWaveData_083A4D58
DirectSoundWaveData_083A4D58:
	.incbin "sound/direct_sound_samples/083A4D58.pcm"

	.align 2
	.global DirectSoundWaveData_083A5AF0
DirectSoundWaveData_083A5AF0:
	.incbin "sound/direct_sound_samples/083A5AF0.pcm"

	.align 2
	.global DirectSoundWaveData_083A6468
DirectSoundWaveData_083A6468:
	.incbin "sound/direct_sound_samples/083A6468.pcm"

	.align 2
	.global DirectSoundWaveData_083A722C
DirectSoundWaveData_083A722C:
	.incbin "sound/direct_sound_samples/083A722C.pcm"

	.align 2
	.global DirectSoundWaveData_083A7D44
DirectSoundWaveData_083A7D44:
	.incbin "sound/direct_sound_samples/083A7D44.pcm"

	.align 2
	.global DirectSoundWaveData_083A8530
DirectSoundWaveData_083A8530:
	.incbin "sound/direct_sound_samples/083A8530.pcm"

	.align 2
	.global DirectSoundWaveData_083A91D4
DirectSoundWaveData_083A91D4:
	.incbin "sound/direct_sound_samples/083A91D4.pcm"

	.align 2
	.global DirectSoundWaveData_083A9E20
DirectSoundWaveData_083A9E20:
	.incbin "sound/direct_sound_samples/083A9E20.pcm"

	.align 2
	.global DirectSoundWaveData_083AA444
DirectSoundWaveData_083AA444:
	.incbin "sound/direct_sound_samples/083AA444.pcm"

	.align 2
	.global DirectSoundWaveData_083AB36C
DirectSoundWaveData_083AB36C:
	.incbin "sound/direct_sound_samples/083AB36C.pcm"

	.align 2
	.global DirectSoundWaveData_083AC048
DirectSoundWaveData_083AC048:
	.incbin "sound/direct_sound_samples/083AC048.pcm"

	.align 2
	.global DirectSoundWaveData_083ACA08
DirectSoundWaveData_083ACA08:
	.incbin "sound/direct_sound_samples/083ACA08.pcm"

	.align 2
	.global DirectSoundWaveData_083AD738
DirectSoundWaveData_083AD738:
	.incbin "sound/direct_sound_samples/083AD738.pcm"

	.align 2
	.global DirectSoundWaveData_083AE2B8
DirectSoundWaveData_083AE2B8:
	.incbin "sound/direct_sound_samples/083AE2B8.pcm"

	.align 2
	.global DirectSoundWaveData_083AED14
DirectSoundWaveData_083AED14:
	.incbin "sound/direct_sound_samples/083AED14.pcm"

	.align 2
	.global DirectSoundWaveData_083AFA24
DirectSoundWaveData_083AFA24:
	.incbin "sound/direct_sound_samples/083AFA24.pcm"

	.align 2
	.global DirectSoundWaveData_083B065C
DirectSoundWaveData_083B065C:
	.incbin "sound/direct_sound_samples/083B065C.pcm"

	.align 2
	.global DirectSoundWaveData_083B0D54
DirectSoundWaveData_083B0D54:
	.incbin "sound/direct_sound_samples/083B0D54.pcm"

	.align 2
	.global DirectSoundWaveData_083B1B9C
DirectSoundWaveData_083B1B9C:
	.incbin "sound/direct_sound_samples/083B1B9C.pcm"

	.align 2
	.global DirectSoundWaveData_083B2678
DirectSoundWaveData_083B2678:
	.incbin "sound/direct_sound_samples/083B2678.pcm"

	.align 2
	.global DirectSoundWaveData_083B2FFC
DirectSoundWaveData_083B2FFC:
	.incbin "sound/direct_sound_samples/083B2FFC.pcm"

	.align 2
	.global DirectSoundWaveData_083B3D24
DirectSoundWaveData_083B3D24:
	.incbin "sound/direct_sound_samples/083B3D24.pcm"

	.align 2
	.global DirectSoundWaveData_083B48AC
DirectSoundWaveData_083B48AC:
	.incbin "sound/direct_sound_samples/083B48AC.pcm"

	.align 2
	.global DirectSoundWaveData_083B5424
DirectSoundWaveData_083B5424:
	.incbin "sound/direct_sound_samples/083B5424.pcm"

	.align 2
	.global DirectSoundWaveData_083B60AC
DirectSoundWaveData_083B60AC:
	.incbin "sound/direct_sound_samples/083B60AC.pcm"

	.align 2
	.global DirectSoundWaveData_083B6C08
DirectSoundWaveData_083B6C08:
	.incbin "sound/direct_sound_samples/083B6C08.pcm"

	.align 2
	.global DirectSoundWaveData_083B72D0
DirectSoundWaveData_083B72D0:
	.incbin "sound/direct_sound_samples/083B72D0.pcm"

	.align 2
	.global DirectSoundWaveData_083B820C
DirectSoundWaveData_083B820C:
	.incbin "sound/direct_sound_samples/083B820C.pcm"

	.align 2
	.global DirectSoundWaveData_083B8BC0
DirectSoundWaveData_083B8BC0:
	.incbin "sound/direct_sound_samples/083B8BC0.pcm"

	.align 2
	.global DirectSoundWaveData_083B9580
DirectSoundWaveData_083B9580:
	.incbin "sound/direct_sound_samples/083B9580.pcm"

	.align 2
	.global DirectSoundWaveData_083BA344
DirectSoundWaveData_083BA344:
	.incbin "sound/direct_sound_samples/083BA344.pcm"

	.align 2
	.global DirectSoundWaveData_083BAE44
DirectSoundWaveData_083BAE44:
	.incbin "sound/direct_sound_samples/083BAE44.pcm"

	.align 2
	.global DirectSoundWaveData_083BB898
DirectSoundWaveData_083BB898:
	.incbin "sound/direct_sound_samples/083BB898.pcm"

	.align 2
	.global DirectSoundWaveData_083BC4B4
DirectSoundWaveData_083BC4B4:
	.incbin "sound/direct_sound_samples/083BC4B4.pcm"

	.align 2
	.global DirectSoundWaveData_083BD064
DirectSoundWaveData_083BD064:
	.incbin "sound/direct_sound_samples/083BD064.pcm"

	.align 2
	.global DirectSoundWaveData_083BD738
DirectSoundWaveData_083BD738:
	.incbin "sound/direct_sound_samples/083BD738.pcm"

	.align 2
	.global DirectSoundWaveData_083BE9A4
DirectSoundWaveData_083BE9A4:
	.incbin "sound/direct_sound_samples/083BE9A4.pcm"

	.align 2
	.global DirectSoundWaveData_083BF484
DirectSoundWaveData_083BF484:
	.incbin "sound/direct_sound_samples/083BF484.pcm"

	.align 2
	.global DirectSoundWaveData_083C004C
DirectSoundWaveData_083C004C:
	.incbin "sound/direct_sound_samples/083C004C.pcm"

	.align 2
	.global DirectSoundWaveData_083C0EEC
DirectSoundWaveData_083C0EEC:
	.incbin "sound/direct_sound_samples/083C0EEC.pcm"

	.align 2
	.global DirectSoundWaveData_083C1970
DirectSoundWaveData_083C1970:
	.incbin "sound/direct_sound_samples/083C1970.pcm"

	.align 2
	.global DirectSoundWaveData_083C23C4
DirectSoundWaveData_083C23C4:
	.incbin "sound/direct_sound_samples/083C23C4.pcm"

	.align 2
	.global DirectSoundWaveData_083C31C8
DirectSoundWaveData_083C31C8:
	.incbin "sound/direct_sound_samples/083C31C8.pcm"

	.align 2
	.global DirectSoundWaveData_083C3DF8
DirectSoundWaveData_083C3DF8:
	.incbin "sound/direct_sound_samples/083C3DF8.pcm"

	.align 2
	.global DirectSoundWaveData_083C4580
DirectSoundWaveData_083C4580:
	.incbin "sound/direct_sound_samples/083C4580.pcm"

	.align 2
	.global DirectSoundWaveData_083C568C
DirectSoundWaveData_083C568C:
	.incbin "sound/direct_sound_samples/083C568C.pcm"

	.align 2
	.global DirectSoundWaveData_083C625C
DirectSoundWaveData_083C625C:
	.incbin "sound/direct_sound_samples/083C625C.pcm"

	.align 2
	.global DirectSoundWaveData_083C6E54
DirectSoundWaveData_083C6E54:
	.incbin "sound/direct_sound_samples/083C6E54.pcm"

	.align 2
	.global DirectSoundWaveData_083C9478
DirectSoundWaveData_083C9478:
	.incbin "sound/direct_sound_samples/083C9478.pcm"

	.align 2
	.global DirectSoundWaveData_083CBEB8
DirectSoundWaveData_083CBEB8:
	.incbin "sound/direct_sound_samples/083CBEB8.pcm"

	.align 2
	.global DirectSoundWaveData_083D3E90
DirectSoundWaveData_083D3E90:
	.incbin "sound/direct_sound_samples/083D3E90.pcm"

	.align 2
	.global DirectSoundWaveData_083D5EF0
DirectSoundWaveData_083D5EF0:
	.incbin "sound/direct_sound_samples/083D5EF0.pcm"

	.align 2
	.global DirectSoundWaveData_083D9AC8
DirectSoundWaveData_083D9AC8:
	.incbin "sound/direct_sound_samples/083D9AC8.pcm"

	.align 2
	.global DirectSoundWaveData_083DB660
DirectSoundWaveData_083DB660:
	.incbin "sound/direct_sound_samples/083DB660.pcm"

	.align 2
	.global DirectSoundWaveData_083DE400
DirectSoundWaveData_083DE400:
	.incbin "sound/direct_sound_samples/083DE400.pcm"

	.align 2
	.global DirectSoundWaveData_083E4BE0
DirectSoundWaveData_083E4BE0:
	.incbin "sound/direct_sound_samples/083E4BE0.pcm"

	.align 2
	.global DirectSoundWaveData_083E8F14
DirectSoundWaveData_083E8F14:
	.incbin "sound/direct_sound_samples/083E8F14.pcm"

	.align 2
	.global DirectSoundWaveData_083EB134
DirectSoundWaveData_083EB134:
	.incbin "sound/direct_sound_samples/083EB134.pcm"

	.align 2
	.global DirectSoundWaveData_083EFB0C
DirectSoundWaveData_083EFB0C:
	.incbin "sound/direct_sound_samples/083EFB0C.pcm"

	.align 2
	.global DirectSoundWaveData_083F234C
DirectSoundWaveData_083F234C:
	.incbin "sound/direct_sound_samples/083F234C.pcm"

	.align 2
	.global DirectSoundWaveData_083F30F0
DirectSoundWaveData_083F30F0:
	.incbin "sound/direct_sound_samples/083F30F0.pcm"

	.align 2
	.global DirectSoundWaveData_083F368C
DirectSoundWaveData_083F368C:
	.incbin "sound/direct_sound_samples/083F368C.pcm"

	.align 2
	.global DirectSoundWaveData_083F4E00
DirectSoundWaveData_083F4E00:
	.incbin "sound/direct_sound_samples/083F4E00.pcm"

	.align 2
	.global DirectSoundWaveData_083F715C
DirectSoundWaveData_083F715C:
	.incbin "sound/direct_sound_samples/083F715C.pcm"

	.align 2
	.global DirectSoundWaveData_083F8B38
DirectSoundWaveData_083F8B38:
	.incbin "sound/direct_sound_samples/083F8B38.pcm"

	.align 2
	.global DirectSoundWaveData_083FB6F8
DirectSoundWaveData_083FB6F8:
	.incbin "sound/direct_sound_samples/083FB6F8.pcm"

	.align 2
	.global DirectSoundWaveData_083FCEBC
DirectSoundWaveData_083FCEBC:
	.incbin "sound/direct_sound_samples/083FCEBC.pcm"

	.align 2
	.global DirectSoundWaveData_083FFCF4
DirectSoundWaveData_083FFCF4:
	.incbin "sound/direct_sound_samples/083FFCF4.pcm"

	.align 2
	.global DirectSoundWaveData_08401BA0
DirectSoundWaveData_08401BA0:
	.incbin "sound/direct_sound_samples/08401BA0.pcm"

	.align 2
	.global DirectSoundWaveData_08406064
DirectSoundWaveData_08406064:
	.incbin "sound/direct_sound_samples/08406064.pcm"

	.align 2
	.global DirectSoundWaveData_08408B14
DirectSoundWaveData_08408B14:
	.incbin "sound/direct_sound_samples/08408B14.pcm"

	.align 2
	.global DirectSoundWaveData_0840CA94
DirectSoundWaveData_0840CA94:
	.incbin "sound/direct_sound_samples/0840CA94.pcm"

	.align 2
	.global DirectSoundWaveData_0840D3D0
DirectSoundWaveData_0840D3D0:
	.incbin "sound/direct_sound_samples/0840D3D0.pcm"

	.align 2
	.global DirectSoundWaveData_0840DE48
DirectSoundWaveData_0840DE48:
	.incbin "sound/direct_sound_samples/0840DE48.pcm"

	.align 2
	.global DirectSoundWaveData_0840E730
DirectSoundWaveData_0840E730:
	.incbin "sound/direct_sound_samples/0840E730.pcm"

	.align 2
	.global DirectSoundWaveData_0840FC68
DirectSoundWaveData_0840FC68:
	.incbin "sound/direct_sound_samples/0840FC68.pcm"

	.align 2
	.global DirectSoundWaveData_08410A1C
DirectSoundWaveData_08410A1C:
	.incbin "sound/direct_sound_samples/08410A1C.pcm"

	.align 2
	.global DirectSoundWaveData_0841144C
DirectSoundWaveData_0841144C:
	.incbin "sound/direct_sound_samples/0841144C.pcm"

	.align 2
	.global DirectSoundWaveData_08411DD8
DirectSoundWaveData_08411DD8:
	.incbin "sound/direct_sound_samples/08411DD8.pcm"

	.align 2
	.global DirectSoundWaveData_08412A40
DirectSoundWaveData_08412A40:
	.incbin "sound/direct_sound_samples/08412A40.pcm"

	.align 2
	.global DirectSoundWaveData_08413B40
DirectSoundWaveData_08413B40:
	.incbin "sound/direct_sound_samples/08413B40.pcm"

	.align 2
	.global DirectSoundWaveData_084157EC
DirectSoundWaveData_084157EC:
	.incbin "sound/direct_sound_samples/084157EC.pcm"

	.align 2
	.global DirectSoundWaveData_08416178
DirectSoundWaveData_08416178:
	.incbin "sound/direct_sound_samples/08416178.pcm"

	.align 2
	.global DirectSoundWaveData_084168FC
DirectSoundWaveData_084168FC:
	.incbin "sound/direct_sound_samples/084168FC.pcm"

	.align 2
	.global DirectSoundWaveData_08417288
DirectSoundWaveData_08417288:
	.incbin "sound/direct_sound_samples/08417288.pcm"

	.align 2
	.global DirectSoundWaveData_08417D5C
DirectSoundWaveData_08417D5C:
	.incbin "sound/direct_sound_samples/08417D5C.pcm"

	.align 2
	.global DirectSoundWaveData_084186E8
DirectSoundWaveData_084186E8:
	.incbin "sound/direct_sound_samples/084186E8.pcm"

	.align 2
	.global DirectSoundWaveData_08419074
DirectSoundWaveData_08419074:
	.incbin "sound/direct_sound_samples/08419074.pcm"

	.align 2
	.global DirectSoundWaveData_084193DC
DirectSoundWaveData_084193DC:
	.incbin "sound/direct_sound_samples/084193DC.pcm"

	.align 2
	.global DirectSoundWaveData_0841AE28
DirectSoundWaveData_0841AE28:
	.incbin "sound/direct_sound_samples/0841AE28.pcm"

	.align 2
	.global DirectSoundWaveData_0841BE08
DirectSoundWaveData_0841BE08:
	.incbin "sound/direct_sound_samples/0841BE08.pcm"

	.align 2
	.global DirectSoundWaveData_0841C1DC
DirectSoundWaveData_0841C1DC:
	.incbin "sound/direct_sound_samples/0841C1DC.pcm"

	.align 2
	.global DirectSoundWaveData_0841C5E4
DirectSoundWaveData_0841C5E4:
	.incbin "sound/direct_sound_samples/0841C5E4.pcm"

	.align 2
	.global DirectSoundWaveData_0841CA28
DirectSoundWaveData_0841CA28:
	.incbin "sound/direct_sound_samples/0841CA28.pcm"

	.align 2
	.global DirectSoundWaveData_0841CDB8
DirectSoundWaveData_0841CDB8:
	.incbin "sound/direct_sound_samples/0841CDB8.pcm"

	.align 2
	.global DirectSoundWaveData_0841D1A8
DirectSoundWaveData_0841D1A8:
	.incbin "sound/direct_sound_samples/0841D1A8.pcm"

	.align 2
	.global DirectSoundWaveData_0841D510
DirectSoundWaveData_0841D510:
	.incbin "sound/direct_sound_samples/0841D510.pcm"

	.align 2
	.global DirectSoundWaveData_08420660
DirectSoundWaveData_08420660:
	.incbin "sound/direct_sound_samples/08420660.pcm"

	.align 2
	.global DirectSoundWaveData_0842208C
DirectSoundWaveData_0842208C:
	.incbin "sound/direct_sound_samples/0842208C.pcm"

	.align 2
	.global DirectSoundWaveData_084230C4
DirectSoundWaveData_084230C4:
	.incbin "sound/direct_sound_samples/084230C4.pcm"

	.align 2
	.global DirectSoundWaveData_0842386C
DirectSoundWaveData_0842386C:
	.incbin "sound/direct_sound_samples/0842386C.pcm"

	.align 2
	.global DirectSoundWaveData_0842472C
DirectSoundWaveData_0842472C:
	.incbin "sound/direct_sound_samples/0842472C.pcm"

	.align 2
	.global DirectSoundWaveData_0842620C
DirectSoundWaveData_0842620C:
	.incbin "sound/direct_sound_samples/0842620C.pcm"

	.align 2
	.global DirectSoundWaveData_084286D0
DirectSoundWaveData_084286D0:
	.incbin "sound/direct_sound_samples/084286D0.pcm"

	.align 2
	.global DirectSoundWaveData_0842B820
DirectSoundWaveData_0842B820:
	.incbin "sound/direct_sound_samples/0842B820.pcm"

	.align 2
	.global DirectSoundWaveData_0842DB04
DirectSoundWaveData_0842DB04:
	.incbin "sound/direct_sound_samples/0842DB04.pcm"

	.align 2
	.global DirectSoundWaveData_084348D0
DirectSoundWaveData_084348D0:
	.incbin "sound/direct_sound_samples/084348D0.pcm"

	.align 2
	.global DirectSoundWaveData_08438D94
DirectSoundWaveData_08438D94:
	.incbin "sound/direct_sound_samples/08438D94.pcm"

	.align 2
	.global DirectSoundWaveData_0843DA48
DirectSoundWaveData_0843DA48:
	.incbin "sound/direct_sound_samples/0843DA48.pcm"

	.align 2
	.global DirectSoundWaveData_08440078
DirectSoundWaveData_08440078:
	.incbin "sound/direct_sound_samples/08440078.pcm"

	.align 2
	.global DirectSoundWaveData_0844127C
DirectSoundWaveData_0844127C:
	.incbin "sound/direct_sound_samples/0844127C.pcm"

	.align 2
	.global DirectSoundWaveData_08443E74
DirectSoundWaveData_08443E74:
	.incbin "sound/direct_sound_samples/08443E74.pcm"

	.align 2
	.global DirectSoundWaveData_08448094
DirectSoundWaveData_08448094:
	.incbin "sound/direct_sound_samples/08448094.pcm"

	.align 2
	.global DirectSoundWaveData_08449300
DirectSoundWaveData_08449300:
	.incbin "sound/direct_sound_samples/08449300.pcm"

	.align 2
	.global DirectSoundWaveData_0844D59C
DirectSoundWaveData_0844D59C:
	.incbin "sound/direct_sound_samples/0844D59C.pcm"

	.align 2
	.global DirectSoundWaveData_0844F71C
DirectSoundWaveData_0844F71C:
	.incbin "sound/direct_sound_samples/0844F71C.pcm"

	.align 2
	.global DirectSoundWaveData_08451658
DirectSoundWaveData_08451658:
	.incbin "sound/direct_sound_samples/08451658.pcm"

	.align 2
	.global DirectSoundWaveData_08455154
DirectSoundWaveData_08455154:
	.incbin "sound/direct_sound_samples/08455154.pcm"

	.align 2
	.global DirectSoundWaveData_0845CAA8
DirectSoundWaveData_0845CAA8:
	.incbin "sound/direct_sound_samples/0845CAA8.pcm"

	.align 2
	.global DirectSoundWaveData_08460298
DirectSoundWaveData_08460298:
	.incbin "sound/direct_sound_samples/08460298.pcm"

	.align 2
	.global DirectSoundWaveData_08462474
DirectSoundWaveData_08462474:
	.incbin "sound/direct_sound_samples/08462474.pcm"

	.align 2
	.global DirectSoundWaveData_084643CC
DirectSoundWaveData_084643CC:
	.incbin "sound/direct_sound_samples/084643CC.pcm"

	.align 2
	.global DirectSoundWaveData_08473130
DirectSoundWaveData_08473130:
	.incbin "sound/direct_sound_samples/08473130.pcm"

	.align 2
	.global DirectSoundWaveData_08476314
DirectSoundWaveData_08476314:
	.incbin "sound/direct_sound_samples/08476314.pcm"

	.align 2
	.global DirectSoundWaveData_084825A4
DirectSoundWaveData_084825A4:
	.incbin "sound/direct_sound_samples/084825A4.pcm"

	.align 2
	.global DirectSoundWaveData_08485930
DirectSoundWaveData_08485930:
	.incbin "sound/direct_sound_samples/08485930.pcm"

	.align 2
	.global DirectSoundWaveData_084882AC
DirectSoundWaveData_084882AC:
	.incbin "sound/direct_sound_samples/084882AC.pcm"

	.align 2
	.global DirectSoundWaveData_0848ACBC
DirectSoundWaveData_0848ACBC:
	.incbin "sound/direct_sound_samples/0848ACBC.pcm"

	.align 2
	.global DirectSoundWaveData_0848D15C
DirectSoundWaveData_0848D15C:
	.incbin "sound/direct_sound_samples/0848D15C.pcm"

	.align 2
	.global DirectSoundWaveData_0848DBF0
DirectSoundWaveData_0848DBF0:
	.incbin "sound/direct_sound_samples/0848DBF0.pcm"

	.align 2
	.global DirectSoundWaveData_084902A0
DirectSoundWaveData_084902A0:
	.incbin "sound/direct_sound_samples/084902A0.pcm"

	.align 2
	.global DirectSoundWaveData_084942D8
DirectSoundWaveData_084942D8:
	.incbin "sound/direct_sound_samples/084942D8.pcm"

	.align 2
	.global DirectSoundWaveData_0849ECF0
DirectSoundWaveData_0849ECF0:
	.incbin "sound/direct_sound_samples/0849ECF0.pcm"

	.align 2
	.global DirectSoundWaveData_084A386C
DirectSoundWaveData_084A386C:
	.incbin "sound/direct_sound_samples/084A386C.pcm"

	.align 2
	.global DirectSoundWaveData_084A8FAC
DirectSoundWaveData_084A8FAC:
	.incbin "sound/direct_sound_samples/084A8FAC.pcm"

	.align 2
	.global DirectSoundWaveData_084ABC48
DirectSoundWaveData_084ABC48:
	.incbin "sound/direct_sound_samples/084ABC48.pcm"

	.align 2
	.global DirectSoundWaveData_084AE2E0
DirectSoundWaveData_084AE2E0:
	.incbin "sound/direct_sound_samples/084AE2E0.pcm"

	.align 2
	.global DirectSoundWaveData_084B466C
DirectSoundWaveData_084B466C:
	.incbin "sound/direct_sound_samples/084B466C.pcm"

	.align 2
	.global DirectSoundWaveData_084B5180
DirectSoundWaveData_084B5180:
	.incbin "sound/direct_sound_samples/084B5180.pcm"

	.align 2
	.global DirectSoundWaveData_084B6100
DirectSoundWaveData_084B6100:
	.incbin "sound/direct_sound_samples/084B6100.pcm"

	.align 2
	.global DirectSoundWaveData_084B6D04
DirectSoundWaveData_084B6D04:
	.incbin "sound/direct_sound_samples/084B6D04.pcm"

	.align 2
	.global DirectSoundWaveData_084B783C
DirectSoundWaveData_084B783C:
	.incbin "sound/direct_sound_samples/084B783C.pcm"

	.align 2
	.global DirectSoundWaveData_084B82C4
DirectSoundWaveData_084B82C4:
	.incbin "sound/direct_sound_samples/084B82C4.pcm"

	.align 2
	.global DirectSoundWaveData_084B8D34
DirectSoundWaveData_084B8D34:
	.incbin "sound/direct_sound_samples/084B8D34.pcm"

	.align 2
	.global DirectSoundWaveData_084B9334
DirectSoundWaveData_084B9334:
	.incbin "sound/direct_sound_samples/084B9334.pcm"

	.align 2
	.global DirectSoundWaveData_084BA6C8
DirectSoundWaveData_084BA6C8:
	.incbin "sound/direct_sound_samples/084BA6C8.pcm"

	.align 2
	.global DirectSoundWaveData_084BB9A8
DirectSoundWaveData_084BB9A8:
	.incbin "sound/direct_sound_samples/084BB9A8.pcm"

	.align 2
	.global DirectSoundWaveData_084BC890
DirectSoundWaveData_084BC890:
	.incbin "sound/direct_sound_samples/084BC890.pcm"

	.align 2
	.global DirectSoundWaveData_084BD490
DirectSoundWaveData_084BD490:
	.incbin "sound/direct_sound_samples/084BD490.pcm"

	.align 2
	.global DirectSoundWaveData_084BE7C0
DirectSoundWaveData_084BE7C0:
	.incbin "sound/direct_sound_samples/084BE7C0.pcm"

	.align 2
	.global DirectSoundWaveData_084BF480
DirectSoundWaveData_084BF480:
	.incbin "sound/direct_sound_samples/084BF480.pcm"

	.align 2
	.global DirectSoundWaveData_084C0120
DirectSoundWaveData_084C0120:
	.incbin "sound/direct_sound_samples/084C0120.pcm"

	.align 2
	.global DirectSoundWaveData_084C3630
DirectSoundWaveData_084C3630:
	.incbin "sound/direct_sound_samples/084C3630.pcm"

	.align 2
	.global DirectSoundWaveData_084C4758
DirectSoundWaveData_084C4758:
	.incbin "sound/direct_sound_samples/084C4758.pcm"

	.align 2
	.global DirectSoundWaveData_084C4F6C
DirectSoundWaveData_084C4F6C:
	.incbin "sound/direct_sound_samples/084C4F6C.pcm"

	.align 2
	.global DirectSoundWaveData_084C8ED4
DirectSoundWaveData_084C8ED4:
	.incbin "sound/direct_sound_samples/084C8ED4.pcm"

	.align 2
	.global DirectSoundWaveData_084CD8AC
DirectSoundWaveData_084CD8AC:
	.incbin "sound/direct_sound_samples/084CD8AC.pcm"

	.align 2
	.global DirectSoundWaveData_084CE300
DirectSoundWaveData_084CE300:
	.incbin "sound/direct_sound_samples/084CE300.pcm"

	.align 2
	.global DirectSoundWaveData_084D1AD4
DirectSoundWaveData_084D1AD4:
	.incbin "sound/direct_sound_samples/084D1AD4.pcm"

	.align 2
	.global DirectSoundWaveData_084D373C
DirectSoundWaveData_084D373C:
	.incbin "sound/direct_sound_samples/084D373C.pcm"

	.align 2
	.global DirectSoundWaveData_084D4684
DirectSoundWaveData_084D4684:
	.incbin "sound/direct_sound_samples/084D4684.pcm"

	.align 2
	.global DirectSoundWaveData_084D5A44
DirectSoundWaveData_084D5A44:
	.incbin "sound/direct_sound_samples/084D5A44.pcm"

	.align 2
	.global DirectSoundWaveData_084D60BC
DirectSoundWaveData_084D60BC:
	.incbin "sound/direct_sound_samples/084D60BC.pcm"

	.align 2
	.global DirectSoundWaveData_084D8188
DirectSoundWaveData_084D8188:
	.incbin "sound/direct_sound_samples/084D8188.pcm"

	.align 2
	.global DirectSoundWaveData_084D9304
DirectSoundWaveData_084D9304:
	.incbin "sound/direct_sound_samples/084D9304.pcm"

	.align 2
	.global DirectSoundWaveData_084DA07C
DirectSoundWaveData_084DA07C:
	.incbin "sound/direct_sound_samples/084DA07C.pcm"

	.align 2
	.global DirectSoundWaveData_084DA53C
DirectSoundWaveData_084DA53C:
	.incbin "sound/direct_sound_samples/084DA53C.pcm"

	.align 2
	.global DirectSoundWaveData_084DA7EC
DirectSoundWaveData_084DA7EC:
	.incbin "sound/direct_sound_samples/084DA7EC.pcm"

	.align 2
	.global DirectSoundWaveData_084DAF40
DirectSoundWaveData_084DAF40:
	.incbin "sound/direct_sound_samples/084DAF40.pcm"

	.align 2
	.global DirectSoundWaveData_084DB690
DirectSoundWaveData_084DB690:
	.incbin "sound/direct_sound_samples/084DB690.pcm"

	.align 2
	.global DirectSoundWaveData_084DC330
DirectSoundWaveData_084DC330:
	.incbin "sound/direct_sound_samples/084DC330.pcm"

	.align 2
	.global DirectSoundWaveData_084DCA24
DirectSoundWaveData_084DCA24:
	.incbin "sound/direct_sound_samples/084DCA24.pcm"

	.align 2
	.global DirectSoundWaveData_084DD66C
DirectSoundWaveData_084DD66C:
	.incbin "sound/direct_sound_samples/084DD66C.pcm"

	.align 2
	.global DirectSoundWaveData_084DE884
DirectSoundWaveData_084DE884:
	.incbin "sound/direct_sound_samples/084DE884.pcm"

	.align 2
	.global DirectSoundWaveData_084DF2E8
DirectSoundWaveData_084DF2E8:
	.incbin "sound/direct_sound_samples/084DF2E8.pcm"

	.align 2
	.global DirectSoundWaveData_084E20A0
DirectSoundWaveData_084E20A0:
	.incbin "sound/direct_sound_samples/084E20A0.pcm"

	.align 2
	.global DirectSoundWaveData_084E7244
DirectSoundWaveData_084E7244:
	.incbin "sound/direct_sound_samples/084E7244.pcm"

	.align 2
	.global DirectSoundWaveData_084F27CC
DirectSoundWaveData_084F27CC:
	.incbin "sound/direct_sound_samples/084F27CC.pcm"

	.align 2
	.global DirectSoundWaveData_084F7390
DirectSoundWaveData_084F7390:
	.incbin "sound/direct_sound_samples/084F7390.pcm"

	.align 2
	.global DirectSoundWaveData_084F7C7C
DirectSoundWaveData_084F7C7C:
	.incbin "sound/direct_sound_samples/084F7C7C.pcm"

	.align 2
	.global DirectSoundWaveData_084F9EE8
DirectSoundWaveData_084F9EE8:
	.incbin "sound/direct_sound_samples/084F9EE8.pcm"

	.align 2
	.global DirectSoundWaveData_084FA19C
DirectSoundWaveData_084FA19C:
	.incbin "sound/direct_sound_samples/084FA19C.pcm"

	.align 2
	.global DirectSoundWaveData_084FC158
DirectSoundWaveData_084FC158:
	.incbin "sound/direct_sound_samples/084FC158.pcm"

	.align 2
	.global DirectSoundWaveData_084FC3B8
DirectSoundWaveData_084FC3B8:
	.incbin "sound/direct_sound_samples/084FC3B8.pcm"

	.align 2
	.global DirectSoundWaveData_084FC718
DirectSoundWaveData_084FC718:
	.incbin "sound/direct_sound_samples/084FC718.pcm"

	.align 2
	.global DirectSoundWaveData_084FCAA8
DirectSoundWaveData_084FCAA8:
	.incbin "sound/direct_sound_samples/084FCAA8.pcm"

	.align 2
	.global DirectSoundWaveData_084FCFB4
DirectSoundWaveData_084FCFB4:
	.incbin "sound/direct_sound_samples/084FCFB4.pcm"

	.align 2
	.global DirectSoundWaveData_084FD7B0
DirectSoundWaveData_084FD7B0:
	.incbin "sound/direct_sound_samples/084FD7B0.pcm"

	.align 2
	.global DirectSoundWaveData_084FDB48
DirectSoundWaveData_084FDB48:
	.incbin "sound/direct_sound_samples/084FDB48.pcm"

	.align 2
	.global DirectSoundWaveData_084FE008
DirectSoundWaveData_084FE008:
	.incbin "sound/direct_sound_samples/084FE008.pcm"

	.align 2
	.global DirectSoundWaveData_084FE1F0
DirectSoundWaveData_084FE1F0:
	.incbin "sound/direct_sound_samples/084FE1F0.pcm"

	.align 2
	.global DirectSoundWaveData_084FEC3C
DirectSoundWaveData_084FEC3C:
	.incbin "sound/direct_sound_samples/084FEC3C.pcm"

	.align 2
	.global DirectSoundWaveData_084FEE4C
DirectSoundWaveData_084FEE4C:
	.incbin "sound/direct_sound_samples/084FEE4C.pcm"

	.align 2
	.global DirectSoundWaveData_084FF020
DirectSoundWaveData_084FF020:
	.incbin "sound/direct_sound_samples/084FF020.pcm"

	.align 2
	.global DirectSoundWaveData_084FF26C
DirectSoundWaveData_084FF26C:
	.incbin "sound/direct_sound_samples/084FF26C.pcm"

	.align 2
	.global DirectSoundWaveData_084FF5C4
DirectSoundWaveData_084FF5C4:
	.incbin "sound/direct_sound_samples/084FF5C4.pcm"

	.align 2
	.global DirectSoundWaveData_085006D0
DirectSoundWaveData_085006D0:
	.incbin "sound/direct_sound_samples/085006D0.pcm"

	.align 2
	.global DirectSoundWaveData_085016D8
DirectSoundWaveData_085016D8:
	.incbin "sound/direct_sound_samples/085016D8.pcm"

	.align 2
	.global DirectSoundWaveData_08502CB4
DirectSoundWaveData_08502CB4:
	.incbin "sound/direct_sound_samples/08502CB4.pcm"

	.align 2
	.global DirectSoundWaveData_08503E8C
DirectSoundWaveData_08503E8C:
	.incbin "sound/direct_sound_samples/08503E8C.pcm"

	.align 2
	.global DirectSoundWaveData_085045A8
DirectSoundWaveData_085045A8:
	.incbin "sound/direct_sound_samples/085045A8.pcm"

	.align 2
	.global DirectSoundWaveData_08504F40
DirectSoundWaveData_08504F40:
	.incbin "sound/direct_sound_samples/08504F40.pcm"

	.align 2
	.global DirectSoundWaveData_08505B2C
DirectSoundWaveData_08505B2C:
	.incbin "sound/direct_sound_samples/08505B2C.pcm"

	.align 2
	.global DirectSoundWaveData_08506018
DirectSoundWaveData_08506018:
	.incbin "sound/direct_sound_samples/08506018.pcm"

	.align 2
	.global DirectSoundWaveData_08506B50
DirectSoundWaveData_08506B50:
	.incbin "sound/direct_sound_samples/08506B50.pcm"

	.align 2
	.global DirectSoundWaveData_08507D60
DirectSoundWaveData_08507D60:
	.incbin "sound/direct_sound_samples/08507D60.pcm"

	.align 2
	.global DirectSoundWaveData_08508870
DirectSoundWaveData_08508870:
	.incbin "sound/direct_sound_samples/08508870.pcm"

	.align 2
	.global DirectSoundWaveData_0850A7D0
DirectSoundWaveData_0850A7D0:
	.incbin "sound/direct_sound_samples/0850A7D0.pcm"

	.align 2
	.global DirectSoundWaveData_0850C548
DirectSoundWaveData_0850C548:
	.incbin "sound/direct_sound_samples/0850C548.pcm"

	.align 2
	.global DirectSoundWaveData_0850E4A0
DirectSoundWaveData_0850E4A0:
	.incbin "sound/direct_sound_samples/0850E4A0.pcm"

	.align 2
	.global DirectSoundWaveData_0850E8E8
DirectSoundWaveData_0850E8E8:
	.incbin "sound/direct_sound_samples/0850E8E8.pcm"

	.align 2
	.global DirectSoundWaveData_0850F1CC
DirectSoundWaveData_0850F1CC:
	.incbin "sound/direct_sound_samples/0850F1CC.pcm"

	.align 2
	.global DirectSoundWaveData_08512AB8
DirectSoundWaveData_08512AB8:
	.incbin "sound/direct_sound_samples/08512AB8.pcm"

	.align 2
	.global DirectSoundWaveData_08516680
DirectSoundWaveData_08516680:
	.incbin "sound/direct_sound_samples/08516680.pcm"

	.align 2
	.global DirectSoundWaveData_08517CC8
DirectSoundWaveData_08517CC8:
	.incbin "sound/direct_sound_samples/08517CC8.pcm"

	.align 2
	.global DirectSoundWaveData_0851A674
DirectSoundWaveData_0851A674:
	.incbin "sound/direct_sound_samples/0851A674.pcm"

	.align 2
	.global DirectSoundWaveData_0851CDA4
DirectSoundWaveData_0851CDA4:
	.incbin "sound/direct_sound_samples/0851CDA4.pcm"

	.align 2
	.global DirectSoundWaveData_0851E398
DirectSoundWaveData_0851E398:
	.incbin "sound/direct_sound_samples/0851E398.pcm"

	.align 2
	.global DirectSoundWaveData_0851EC74
DirectSoundWaveData_0851EC74:
	.incbin "sound/direct_sound_samples/0851EC74.pcm"

	.align 2
	.global DirectSoundWaveData_0851FF4C
DirectSoundWaveData_0851FF4C:
	.incbin "sound/direct_sound_samples/0851FF4C.pcm"

	.align 2
	.global DirectSoundWaveData_08524984
DirectSoundWaveData_08524984:
	.incbin "sound/direct_sound_samples/08524984.pcm"

	.align 2
	.global DirectSoundWaveData_08524DBC
DirectSoundWaveData_08524DBC:
	.incbin "sound/direct_sound_samples/08524DBC.pcm"

	.align 2
	.global DirectSoundWaveData_08525FB8
DirectSoundWaveData_08525FB8:
	.incbin "sound/direct_sound_samples/08525FB8.pcm"

	.align 2
	.global DirectSoundWaveData_0852674C
DirectSoundWaveData_0852674C:
	.incbin "sound/direct_sound_samples/0852674C.pcm"

	.align 2
	.global DirectSoundWaveData_08528258
DirectSoundWaveData_08528258:
	.incbin "sound/direct_sound_samples/08528258.pcm"

	.align 2
	.global DirectSoundWaveData_085298AC
DirectSoundWaveData_085298AC:
	.incbin "sound/direct_sound_samples/085298AC.pcm"

	.align 2
	.global DirectSoundWaveData_0852D908
DirectSoundWaveData_0852D908:
	.incbin "sound/direct_sound_samples/0852D908.pcm"

	.align 2
	.global DirectSoundWaveData_08530CDC
DirectSoundWaveData_08530CDC:
	.incbin "sound/direct_sound_samples/08530CDC.pcm"

	.align 2
	.global DirectSoundWaveData_0853318C
DirectSoundWaveData_0853318C:
	.incbin "sound/direct_sound_samples/0853318C.pcm"

	.align 2
	.global DirectSoundWaveData_08535F64
DirectSoundWaveData_08535F64:
	.incbin "sound/direct_sound_samples/08535F64.pcm"

	.align 2
	.global DirectSoundWaveData_0853A088
DirectSoundWaveData_0853A088:
	.incbin "sound/direct_sound_samples/0853A088.pcm"

	.align 2
	.global DirectSoundWaveData_0853A634
DirectSoundWaveData_0853A634:
	.incbin "sound/direct_sound_samples/0853A634.pcm"

	.align 2
	.global DirectSoundWaveData_0853FF58
DirectSoundWaveData_0853FF58:
	.incbin "sound/direct_sound_samples/0853FF58.pcm"

	.align 2
	.global DirectSoundWaveData_08540AC8
DirectSoundWaveData_08540AC8:
	.incbin "sound/direct_sound_samples/08540AC8.pcm"

	.align 2
	.global DirectSoundWaveData_085411C8
DirectSoundWaveData_085411C8:
	.incbin "sound/direct_sound_samples/085411C8.pcm"

	.align 2
	.global DirectSoundWaveData_08543C90
DirectSoundWaveData_08543C90:
	.incbin "sound/direct_sound_samples/08543C90.pcm"

	.align 2
