    .global ProgrammableWaveData_8224354
ProgrammableWaveData_8224354: @ 8224354
    .incbin "sound/programmable_wave_samples/8224354.pcm"

    .global ProgrammableWaveData_8224364
ProgrammableWaveData_8224364: @ 8224364
    .incbin "sound/programmable_wave_samples/8224364.pcm"

    .global ProgrammableWaveData_8224374
ProgrammableWaveData_8224374: @ 8224374
    .incbin "sound/programmable_wave_samples/8224374.pcm"

    .global ProgrammableWaveData_8224384
ProgrammableWaveData_8224384: @ 8224384
    .incbin "sound/programmable_wave_samples/8224384.pcm"

    .global ProgrammableWaveData_8224394
ProgrammableWaveData_8224394: @ 8224394
    .incbin "sound/programmable_wave_samples/8224394.pcm"

    .global ProgrammableWaveData_82243A4
ProgrammableWaveData_82243A4: @ 82243A4
    .incbin "sound/programmable_wave_samples/82243A4.pcm"

    .global ProgrammableWaveData_82243B4
ProgrammableWaveData_82243B4: @ 82243B4
    .incbin "sound/programmable_wave_samples/82243B4.pcm"

    .global ProgrammableWaveData_82243C4
ProgrammableWaveData_82243C4: @ 82243C4
    .incbin "sound/programmable_wave_samples/82243C4.pcm"

    .global ProgrammableWaveData_82243D4
ProgrammableWaveData_82243D4: @ 82243D4
    .incbin "sound/programmable_wave_samples/82243D4.pcm"

    .global ProgrammableWaveData_82243E4
ProgrammableWaveData_82243E4: @ 82243E4
    .incbin "sound/programmable_wave_samples/82243E4.pcm"

    .global ProgrammableWaveData_82243F4
ProgrammableWaveData_82243F4: @ 82243F4
    .incbin "sound/programmable_wave_samples/82243F4.pcm"
