#ifndef GUARD_CONSTANTS_NODES_H
#define GUARD_CONSTANTS_NODES_H

enum
{
    NODE_BORDER_MULAN       = 0x00,
    NODE_CASTLE_FRELIA      = 0x01,
    NODE_IDE                = 0x02,
    NODE_BORGO_RIDGE        = 0x03,
    NODE_ZAHA_WOODS         = 0x04,
    NODE_SERAFEW            = 0x05,
    NODE_ADLAS_PLAINS       = 0x06,
    NODE_RENVALL_07         = 0x07,
    NODE_RENVALL_08         = 0x08,
    NODE_PORT_KIRIS         = 0x09,
    NODE_TERAZ_PLATEAU      = 0x0A,
    NODE_CAER_PELYN         = 0x0B,
    NODE_HAMILL_CANYON      = 0x0C,
    NODE_JEHANNA_HALL_0D    = 0x0D,
    NODE_FORT_RIGWALD       = 0x0E,
    NODE_BETHROEN           = 0x0F,
    NODE_TAIZEL             = 0x10,
    NODE_ZAALBUL_MARSH      = 0x11,
    NODE_GRADO_KEEP         = 0x12,
    NODE_JEHANNA_HALL_13    = 0x13,
    NODE_RENAIS_CASTLE      = 0x14,
    NODE_NARUBE_RIVER       = 0x15,
    NODE_NELERAS_PEAK       = 0x16,
    NODE_RAUSTEN_COURT      = 0x17,
    NODE_DARKLING_WOODS     = 0x18,
    NODE_BLACK_TEMPLE       = 0x19,
    NODE_TOWER_OF_VALNI     = 0x1A,
    NODE_LAGDOU_RUINS       = 0x1B,
    NODE_MELKAEN_COAST      = 0x1C,

    NODE_MAX                = 0x1D,
};

enum wm_node_idx {
    WM_NODE_BorderMulan = 0x00,
    WM_NODE_CastleFrelia = 1,
    WM_NODE_Ide = 2,
    WM_NODE_BorgoRidge = 3,
    WM_NODE_ZahaWoods = 4,
    WM_NODE_Serafew = 5,
    WM_NODE_AdlasPlains = 6,
    WM_NODE_Renvall1 = 7,
    WM_NODE_Renvall2 = 8,
    WM_NODE_PortKiris = 9,
    WM_NODE_TerazPlateau = 10,
    WM_NODE_CaerPelyn = 11,
    WM_NODE_HamillCanyon = 12,
    WM_NODE_JehannaHall = 13,
    WM_NODE_FortRigwald = 14,
    WM_NODE_Bethroen = 15,
    WM_NODE_Taizel = 16,
    WM_NODE_ZaalbulMarsh = 17,
    WM_NODE_GradoKeep = 18,
    WM_NODE_JehannaHall2 = 19,
    WM_NODE_RenaisCastle = 20,
    WM_NODE_NarubeRiver = 21,
    WM_NODE_NelerasPeak = 22,
    WM_NODE_RaustenCourt = 23,
    WM_NODE_DarklingWoods = 24,
    WM_NODE_BlackTemple = 25,
    WM_NODE_TowerOfValni = 26,
    WM_NODE_LagdouRuins = 27,
    WM_NODE_MelkaenCoast = 28,
};

/* Overwride in eventscr */
enum wm_path_idx {
    WM_PATH_00 = 0x00,
    WM_PATH_01 = 0x01,
    WM_PATH_02 = 0x02,
    WM_PATH_03 = 0x03,
    WM_PATH_04 = 0x04,
    WM_PATH_05 = 0x05,
    WM_PATH_06 = 0x06,
    WM_PATH_07 = 0x07,
    WM_PATH_08 = 0x08,
    WM_PATH_09 = 0x09,
    WM_PATH_0A = 0x0A,
    WM_PATH_0B = 0x0B,
    WM_PATH_0C = 0x0C,
    WM_PATH_0D = 0x0D,
    WM_PATH_0E = 0x0E,
    WM_PATH_0F = 0x0F,
    WM_PATH_10 = 0x10,
    WM_PATH_11 = 0x11,
    WM_PATH_12 = 0x12,
    WM_PATH_13 = 0x13,
    WM_PATH_14 = 0x14,
    WM_PATH_15 = 0x15,
    WM_PATH_16 = 0x16,
    WM_PATH_17 = 0x17,
    WM_PATH_18 = 0x18,
    WM_PATH_19 = 0x19,
    WM_PATH_1A = 0x1A,
    WM_PATH_1B = 0x1B,
    WM_PATH_1C = 0x1C,
    WM_PATH_1D = 0x1D,
    WM_PATH_1E = 0x1E,
    WM_PATH_1F = 0x1F,

    WM_PATH_MAX = 0x20,
};

enum wm_hightlighted_nation_idx {
    WM_NATION_Frelia = 0,
    WM_NATION_Grado = 1,
    WM_NATION_Jehanna = 2,
    WM_NATION_Carcino = 3,
    WM_NATION_ZahaWoods = 4,
    WM_NATION_Rausten = 5,
    WM_NATION_Pokhara = 6,
    WM_NATION_Renais = 7,

    WM_NATION_MAX = 8,
};

enum wm_mu_idx {
    WM_MU_0 = 0,
    WM_MU_1 = 1,
    WM_MU_2 = 2,
    WM_MU_3 = 3,
    WM_MU_4 = 4,
    WM_MU_5 = 5,
    WM_MU_6 = 6,

    WM_MU_MAX = 7,
    WM_MU_ANY = -1,
};

#endif // GUARD_CONSTANTS_NODES_H
