#include "gbafe.h"

CONST_DATA EventListScr EventScr_Ch11a_BeginningScene[] = {
    MUSC(SONG_4D)
    LOAD2(0x1, UnitDef_Ch11AAlly_0)
    ENUN
    CUMO_CHAR(CHARACTER_EWAN)
    STAL(60)
    CURE
    SetBackground(BG_PLAIN_2_FOG)
    TEXTSHOW(0xa46)
    TEXTEND
    MUSCMID(SONG_SILENT)
    TEXTCONT
    TEXTEND
    MUSC(SONG_TENSION)
    TEXTCONT
    TEXTEND
    REMA
    CALL(EventScr_TextShowWithFadeIn)
    CHECK_ALIVE(CHARACTER_TETHYS)
    BEQ(0x0, EVT_SLOT_C, EVT_SLOT_0)
    CUMO_CHAR(CHARACTER_TETHYS)
    STAL(60)
    CURE
    Text_BG(BG_PLAIN_2_FOG, 0xa47)
    GOTO(0x1)
LABEL(0x0)
    MOVE_1STEP(0x0, CHARACTER_INNES, FACING_RIGHT)
    ENUN
    CUMO_CHAR(CHARACTER_INNES)
    STAL(60)
    CURE
    Text_BG(BG_PLAIN_2_FOG, 0xa48)
LABEL(0x1)
    SVAL(EVT_SLOT_D, 0x0)
    SVAL(EVT_SLOT_1, 0x86)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x85)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x5)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    MOVE_DEFINED(CHARACTER_EWAN)
    ENUN
    DISA(CHARACTER_EWAN)
    FADI(16)
    CLEA
    CAMERA2(12, 13)
    FADU(16)
    LOAD1(0x1, UnitDef_Ch11ANPC)
    ENUN
    CUMO_CHAR(CHARACTER_LARACHEL)
    STAL(60)
    CURE
    SetBackground(BG_INTERIOR_BROWN)
    TEXTSHOW(0xa49)
    TEXTEND
    REMA
    FADI(16)
    LOAD1(0x1, UnitDef_Ch11AEnemy_0)
    ENUN
    CALL(EventScr_CommonPrep)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11a_EndingScene[] = {
    MUSC(SONG_VICTORY)
    SetBackground(BG_INTERIOR_BROWN)
    CHECK_ALIVE(CHARACTER_LARACHEL)
    BEQ(0x0, EVT_SLOT_C, EVT_SLOT_0)
    TEXTSHOW(0xa4a)
    TEXTEND
    GOTO(0x1)
LABEL(0x0)
    TEXTSHOW(0xa4b)
    TEXTEND
LABEL(0x1)
    FADI(4)
    REMA
    FADU(4)
    TEXTSHOW(0xa4c)
    TEXTEND
    CHECK_ALIVE(CHARACTER_DOZLA)
    BEQ(0x2, EVT_SLOT_C, EVT_SLOT_0)
    EvtTextShow2(0xa4d) // ENOSUPP in EAstdlib
    TEXTEND
LABEL(0x2)
    REMA
    MUSCMID(SONG_SILENT)
    FADI(16)
    SVAL(EVT_SLOT_2, CHARACTER_LARACHEL)
    CALL(EventScr_LoadUniqueAlly)
    SVAL(EVT_SLOT_2, CHARACTER_DOZLA)
    CALL(EventScr_LoadUniqueAlly)
    CLEA
    CLEE
    CLEN
    SVAL(EVT_SLOT_B, 0xa0000)
    LOMA(CHAPTER_41)
    VCWF(0)
    MUSC(SONG_4A)
    FADU(16)
    LOAD2(0x1, UnitDef_Ch11AAlly_1)
    ENUN
    DISA(CHARACTER_EWAN)
    STAL(30)
    CUMO_AT(2, 6)
    STAL(60)
    CURE
    SetBackground(BG_CAER_PELYN)
    MUSI
    TEXTSHOW(0xa4e)
    TEXTEND
    REMA
    EvtBgmFadeIn(SONG_SILENT, 8) // ENOSUPP in EAstdlib
    FADI(2)
    CLEAN
    EvtSetLoadUnitNoREDA // ENOSUPP in EAstdlib
    LOAD2(0x1, UnitDef_Ch11AMixed)
    ENUN
    DISA(CHARACTER_GLEN)
    DISA(0x80)
    DISA(0x81)
    FADU(2)
    LOAD2(0x1, UnitDef_Ch11AMixed)
    ENUN
    CUMO_CHAR(CHARACTER_GLEN)
    STAL(60)
    CURE
    MUSC(SONG_SOLVE_THE_RIDDLE)
    SetBackground(BG_PLAIN_2)
    TEXTSHOW(0xa4f)
    TEXTEND
    MUSC(SONG_INDIGNATION)
    TEXTCONT
    TEXTEND
    REMA
    CALL(EventScr_TextShowWithFadeIn)
    MOVE(0x0, CHARACTER_SALEH, 13, 0)
    ENUN
    MOVE(0x10, CHARACTER_INNES, 13, 0)
    MOVE(0x10, CHARACTER_LARACHEL, 13, 0)
    MOVE(0x10, CHARACTER_SETH, 13, 0)
    MOVE(0x10, CHARACTER_EIRIKA, 13, 0)
    ENUN
    MOVE(0x10, CHARACTER_GLEN, 8, 5)
    MOVE(0x10, 0x80, 7, 4)
    MOVE(0x10, 0x81, 9, 4)
    LOAD1(0x1, UnitDef_Ch11AEnemy_5)
    ENUN
    ENUN
    CUMO_CHAR(CHARACTER_VALTER)
    STAL(60)
    CURE
    MUSC(SONG_SOLVE_THE_RIDDLE)
    SetBackground(BG_PLAIN_2)
    TEXTSHOW(0xa50)
    TEXTEND
    MUSC(SONG_RAID)
    TEXTCONT
    TEXTEND
    REMA
    CALL(EventScr_TextShowWithFadeIn)
    MOVE_1STEP(0x0, CHARACTER_VALTER, FACING_UP)
    ENUN

    StartBattle
    NormalDamage(ATTACKER, 0)
    MissedAttack(DEFENDER, 0)
    CriticalHit(ATTACKER, 100)
    EndAttack
    FIGHT(CHARACTER_GLEN, CHARACTER_VALTER, 0, 0)

    KILL(CHARACTER_GLEN)
    DISA_IF(CHARACTER_GLEN)

    CUMO_CHAR(CHARACTER_VALTER)
    STAL(60)
    CURE
    TEXTSTART
    TEXTSHOW(0xa52)
    TEXTEND
    REMA
    SVAL(EVT_SLOT_D, 0x0)
    SVAL(EVT_SLOT_1, 0x20087)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x20083)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x20003)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    MOVE_DEFINED(0x80)
    SVAL(EVT_SLOT_D, 0x0)
    SVAL(EVT_SLOT_1, 0x20101)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x20001)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    MOVE_DEFINED(0x81)
    STAL2(15)
    SVAL(EVT_SLOT_D, 0x0)
    SVAL(EVT_SLOT_1, 0x20086)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x20083)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x20003)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    MOVE_DEFINED(CHARACTER_BANDIT_CH5)
    SVAL(EVT_SLOT_D, 0x0)
    SVAL(EVT_SLOT_1, 0x20101)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x20001)
    SENQUEUE1
    SVAL(EVT_SLOT_1, 0x0)
    SENQUEUE1
    MOVE_DEFINED(0x67)
    ENUN
    CUMO_CHAR(CHARACTER_VALTER)
    STAL(60)
    CURE
    TEXTSTART
    TEXTSHOW(0xa53)
    TEXTEND
    REMA
    ENUT(115)
    MNC2(0xc)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11A_0[] = {
    MUSS(0x30)
    STAL(33)
    TEXTSTART
    TEXTSHOW(0xa54)
    TEXTEND
    REMA
    MURE(0x2)
    CUSA(CHARACTER_LARACHEL)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11A_1[] = {
    MUSS(0x30)
    STAL(33)
    TEXTSTART
    TEXTSHOW(0xa55)
    TEXTEND
    REMA
    MURE(0x2)
    CUSA(CHARACTER_DOZLA)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11A_2[] = {
    SVAL(EVT_SLOT_2, UnitDef_Ch11AEnemy_1)
    CALL(EventScr_LoadReinforce)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11A_3[] = {
    SVAL(EVT_SLOT_2, 0x0)
    CALL(EventScr_UnTriggerIfNotFaction)
    SVAL(EVT_SLOT_1, 0x10000)
    CHAI(0xb4)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11A_4[] = {
    SVAL(EVT_SLOT_2, 0x0)
    CALL(EventScr_UnTriggerIfNotFaction)
    SVAL(EVT_SLOT_1, 0x10500)
    CHAI(0xaf)
    SVAL(EVT_SLOT_1, 0x10000)
    CHAI(0xbc)
    SVAL(EVT_SLOT_1, 0x11200)
    CHAI(0xb8)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11A_5[] = {
    SVAL(EVT_SLOT_2, 0x0)
    CALL(EventScr_UnTriggerIfNotFaction)
    SVAL(EVT_SLOT_1, 0x10000)
    CHAI(0xae)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11A_6[] = {
    SVAL(EVT_SLOT_2, UnitDef_Ch11AEnemy_2)
    CALL(EventScr_LoadReinforceHardMode)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11A_7[] = {
    SVAL(EVT_SLOT_2, UnitDef_Ch11AEnemy_3)
    CALL(EventScr_LoadReinforceHardMode)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch11A_8[] = {
    SVAL(EVT_SLOT_2, UnitDef_Ch11AEnemy_4)
    CALL(EventScr_LoadReinforceHardMode)
    EVBIT_T(7)
    ENDA
};
