#include "gbafe.h"

CONST_DATA EventListScr EventScr_Ch13a_BeginningScene[] = {
    SVAL(EVT_SLOT_2, 0x0)
    CALL(EventScr_9EEA58)
    SetBackground(BG_GRADO_CHAMBER)
    TEXTSHOW(0xa68)
    TEXTEND
    REMA
    FADI(16)
    SVAL(EVT_SLOT_B, 0x0)
    LOMA(CHAPTER_3F)
    FADU(16)
    LOAD1(0x1, UnitDef_Ch13AEnemy_15)
    ENUN
    CLEE
    CUMO_AT(10, 4)
    STAL(60)
    CURE
    SetBackground(BG_GRADO_CHAMBER)
    TEXTSHOW(0xa69)
    TEXTEND
    REMA
    FADI(16)
    SVAL(EVT_SLOT_B, 0x0)
    LOMA(CHAPTER_49)
    EvtSetLoadUnitNoREDA // ENOSUPP in EAstdlib
    LOAD2(0x1, UnitDef_Ch13AMixed)
    ENUN
    DISA(CHARACTER_MESSENGER)
    FADU(16)
    LOAD2(0x1, UnitDef_Ch13AMixed)
    ENUN
    CUMO_CHAR(CHARACTER_MESSENGER)
    STAL(60)
    CURE
    SetBackground(BG_PLAIN_2)
    MUSC(SONG_TENSION)
    TEXTSHOW(0xa6a)
    TEXTEND
    REMA
    FADI(4)
    CLEA
    CLEE
    CLEN
    SetBackground(BG_PLAIN_2)
    TEXTSHOW(0xa6b)
    TEXTEND
    REMA
    FADI(16)
    SVAL(EVT_SLOT_B, 0x90012)
    LOMA(CHAPTER_E_13)
    LOAD1(0x1, UnitDef_Ch13AEnemy_1)
    ENUN
    SVAL(EVT_SLOT_2, UnitDef_Ch13AEnemy_2)
    SVAL(EVT_SLOT_3, 0x1)
    CALL(EventScr_LoadUnitForTutorial)
    CHECK_EVENTID(134)
    BNE(0x0, EVT_SLOT_C, EVT_SLOT_0)
    CHECK_EXISTS(CHARACTER_AMELIA)
    BNE(0x0, EVT_SLOT_C, EVT_SLOT_0)
    LOAD1(0x1, UnitDef_Ch13AEnemy_10)
    ENUN
    GOTO(0x1)
LABEL(0x0)
    ENUT(7)
LABEL(0x1)
    FADU(16)
    CUMO_AT(23, 11)
    STAL(60)
    CURE
    MUSS(0x2e)
    STAL(33)
    Text_BG(BG_INTERIOR_BLACK, 0xa6c)
    LOAD1(0x1, UnitDef_Ch13AEnemy_11)
    ENUN
    LOAD1(0x1, UnitDef_Ch13AEnemy_0)
    ENUN
    DISA(CHARACTER_CAELLACH)
    CAMERA2(13, 9)
    LOAD2(0x1, UnitDef_Ch13AAlly_0)
    ENUN
    SVAL(EVT_SLOT_1, 0x0)
    SET_STATE(CHARACTER_EIRIKA)
    SVAL(EVT_SLOT_1, 0x0)
    SET_STATE(CHARACTER_LARACHEL)
    SVAL(EVT_SLOT_1, 0x0)
    SET_STATE(CHARACTER_INNES)
    SVAL(EVT_SLOT_1, 0x0)
    SET_STATE(CHARACTER_SETH)
    LOAD3(0x0, UnitDef_Ch13AAlly_1)
    ENUN
    SVAL(EVT_SLOT_1, 0xffffffff)
    SET_STATE(CHARACTER_EIRIKA)
    SVAL(EVT_SLOT_1, 0xffffffff)
    SET_STATE(CHARACTER_LARACHEL)
    SVAL(EVT_SLOT_1, 0xffffffff)
    SET_STATE(CHARACTER_INNES)
    SVAL(EVT_SLOT_1, 0xffffffff)
    SET_STATE(CHARACTER_SETH)
    CUMO_CHAR(CHARACTER_EIRIKA)
    STAL(60)
    CURE
    SetBackground(BG_GRASS_PLAINS_2)
    MURE(0x2)
    TEXTSHOW(0xa6d)
    TEXTEND
    REMA
    CALL(EventScr_CommonPrep)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch13a_EndingScene[] = {
    CHECK_EVENTID(2)
    BNE(0x0, EVT_SLOT_C, EVT_SLOT_0)
    CAMERA_CAHR(CHARACTER_AIAS)
    CUMO_CHAR(CHARACTER_AIAS)
    STAL(60)
    CURE
    SetBackground(BG_GRASS_PLAINS_2)
    TEXTSHOW(0xa75)
    TEXTEND
    GOTO(0x1)
LABEL(0x0)
    SetBackground(BG_GRASS_PLAINS_2)
    TEXTSHOW(0xa76)
    TEXTEND
LABEL(0x1)
    REMA
    FADI(16)
    CLEE
    CLEAN
    CAMERA(23, 0)
    FADU(16)
    LOAD1(0x1, UnitDef_Ch13ANPC)
    ENUN
    CUMO_CHAR(CHARACTER_MANSEL)
    STAL(60)
    CURE
    MUSC(SONG_BINDING_VOW)
    TEXTSTART
    TEXTSHOW(0xa77)
    TEXTEND
    REMA
    CAMERA_CAHR(CHARACTER_EIRIKA)
    CUMO_CHAR(CHARACTER_EIRIKA)
    STAL(60)
    CURE
    SetBackground(BG_GRASS_PLAINS_2)
    TEXTSHOW(0xa78)
    TEXTEND
    REMA
    FADI(16)
    SetBackground(BG_GRASS_PLAINS_2)
    MUSS(0x31)
    STAL(33)
    CHECK_ALIVE(CHARACTER_DOZLA)
    BEQ(0xa, EVT_SLOT_C, EVT_SLOT_0)
    TEXTSHOW(0xa79)
    TEXTEND
    REMA
    CALL(EventScr_RemoveBGIfNeeded)
    SVAL(EVT_SLOT_3, 0x1388)
    GIVEITEMTOMAIN(CHAR_EVT_PLAYER_LEADER)
    TEXTSHOW(0xa7a)
    TEXTEND
    MUSCMID(SONG_SILENT)
    TEXTCONT
    TEXTEND
    MUSC(SONG_RAID)
    TEXTCONT
    TEXTEND
    GOTO(0xb)
LABEL(0xa)
    TEXTSHOW(0xa7b)
    TEXTEND
    REMA
    CALL(EventScr_RemoveBGIfNeeded)
    SVAL(EVT_SLOT_3, 0x1388)
    GIVEITEMTOMAIN(CHAR_EVT_PLAYER_LEADER)
    TEXTSHOW(0xa7c)
    TEXTEND
    MUSCMID(SONG_SILENT)
    TEXTCONT
    TEXTEND
    MUSC(SONG_RAID)
    TEXTCONT
    TEXTEND
LABEL(0xb)
    REMA
    FADI(4)
    CLEA
    CLEE
    CLEN
    CHECK_EVENTID(2)
    BNE(0x63, EVT_SLOT_C, EVT_SLOT_0)
    SVAL(EVT_SLOT_B, 0x0)
    LOMA(CHAPTER_E_15)
    LOAD1(0x1, UnitDef_Ch13AEnemy_16)
    ENUN
    FADU(4)
    LOAD1(0x1, UnitDef_Ch13AEnemy_17)
    ENUN
    SVAL(EVT_SLOT_1, 0x5)
    SET_HP(CHARACTER_AIAS)
    CUMO_CHAR(CHARACTER_CAELLACH)
    STAL(60)
    CURE
    SetBackground(BG_DESERT)
    MUSC(SONG_SOLVE_THE_RIDDLE)
    TEXTSHOW(0xa7d)
    TEXTEND
    REMA
    CALL(EventScr_TextShowWithFadeIn)

    StartBattle
    CriticalHit(DEFENDER, 0)
    FIGHT_MAP(CHARACTER_CAELLACH, CHARACTER_AIAS, 0, 0)

    FADI(4)
LABEL(0x63)
    ENUT(117)
    MNCH(0xe)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch13A_0[] = {
    MUSS(0x30)
    STAL(33)
    TEXTSTART
    TEXTSHOW(0xa28)
    TEXTEND
    REMA
    MURE(0x2)
    CUSA(CHARACTER_AMELIA)
LABEL(0x0)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch13A_1[] = {
    MUSS(0x30)
    STAL(33)
    TEXTSTART
    TEXTSHOW(0xa27)
    TEXTEND
    REMA
    MURE(0x2)
    CUSA(CHARACTER_AMELIA)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch13A_2[] = {
    MUSS(0x30)
    STAL(33)
    TEXTSTART
    TEXTSHOW(0xa80)
    TEXTEND
    REMA
    MURE(0x2)
    CUSA(CHARACTER_CORMAG)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch13A_3[] = {
    MUSC(SONG_ASSAULT)
    SVAL(EVT_SLOT_2, UnitDef_Ch13AEnemy_3)
    CALL(EventScr_LoadReinforce)
    SVAL(EVT_SLOT_2, UnitDef_Ch13AEnemy_4)
    CALL(EventScr_LoadReinforceHardMode)
    CUMO_CHAR(CHARACTER_PABLO)
    STAL(60)
    CURE
    TEXTSTART
    TEXTSHOW(0xa6e)
    TEXTEND
    REMA
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch13A_4[] = {
    CHECK_TURNS
    SVAL(EVT_SLOT_1, 0x1)
    SAND(EVT_SLOT_C, EVT_SLOT_C, EVT_SLOT_1)
    BEQ(0x0, EVT_SLOT_C, EVT_SLOT_0)
    SVAL(EVT_SLOT_2, UnitDef_Ch13AEnemy_5)
    CALL(EventScr_LoadReinforce)
    SVAL(EVT_SLOT_2, UnitDef_Ch13AEnemy_6)
    CALL(EventScr_LoadReinforce)
LABEL(0x0)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch13A_5[] = {
    SVAL(EVT_SLOT_2, UnitDef_Ch13AEnemy_7)
    CALL(EventScr_LoadReinforce)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch13A_6[] = {
    SVAL(EVT_SLOT_2, UnitDef_Ch13AEnemy_8)
    CALL(EventScr_LoadReinforce)
    EVBIT_T(7)
    ENDA
};

CONST_DATA EventListScr EventScr_Ch13A_7[] = {
    MUSC(SONG_ASSAULT)
    SVAL(EVT_SLOT_2, UnitDef_Ch13AEnemy_9)
    CALL(EventScr_LoadReinforce)
    CUMO_CHAR(CHARACTER_CORMAG)
    STAL(60)
    CURE
    TEXTSTART
    TEXTSHOW(0xa6f)
    TEXTEND
    REMA
    EVBIT_T(7)
    ENDA
};
