#pragma once

#include "global.h"
#include "event.h"
#include "eventinfo.h"
#include "eventcall.h"
#include "EAstdlib.h"
#include "constants/characters.h"
#include "constants/backgrounds.h"
#include "constants/songs.h"
#include "constants/chapters.h"

CONST_DATA EventListScr EventScr_Ch9a_BeginningScene[] = {
	MUSC(SONG_SOLVE_THE_RIDDLE)
	SVAL(EVT_SLOT_2, 0xa16)
	SVAL(EVT_SLOT_3, 0xa17)
	SVAL(EVT_SLOT_4, 0xa18)
	CALL(EventScr_Ch8_11)
	MUSCMID(SONG_SILENT)
	SVAL(EVT_SLOT_B, 0x0)
	LOMA(CHAPTER_45)
	CHECK_EXISTS(CHARACTER_TANA)
	BEQ(0x0, EVT_SLOT_C, EVT_SLOT_0)
	SVAL(EVT_SLOT_1, 0x0)
	SET_STATE(CHARACTER_TANA)
LABEL(0x0)
	SVAL(EVT_SLOT_1, 0x1)
	SET_STATE(CHARACTER_EIRIKA)
	LOAD3(0x0, UnitDef_Ch9AAlly_2)
	ENUN
	FADU(16)
	LOAD2(0x1, UnitDef_Ch9AAlly_3)
	ENUN
	MOVE_1STEP(0x0, CHARACTER_EIRIKA, FACING_LEFT)
	ENUN
	CUMO_CHAR(CHARACTER_TANA)
	STAL(60)
	CURE
	MUSC(SONG_ADVANCE)
	SetBackground(BG_GRASS_PLAINS)
	TEXTSHOW(0xa19)
	TEXTEND
	REMA
	FADI(16)
	CLEA
	CLEE
	CLEN
	SVAL(EVT_SLOT_B, 0x40012)
	LOMA(CHAPTER_E_9)
	FADU(16)
	LOAD2(0x1, UnitDef_Ch9AAlly_0)
	ENUN
	CUMO_CHAR(CHARACTER_SETH)
	STAL(60)
	CURE
	SetBackground(BG_PORT)
	TEXTSHOW(0xa1a)
	TEXTEND
	MUSI
	TEXTCONT
	TEXTEND
	REMA
	FADI(16)
	CLEAN
	FADU(16)
	LOAD2(0x1, UnitDef_Ch9AMixed_0)
	ENUN
	CUMO_CHAR(CHARACTER_LARACHEL)
	STAL(60)
	CURE
	MUSS(0x2a)
	STAL(33)
	SetBackground(BG_PORT)
	TEXTSHOW(0xa1b)
	TEXTEND
	MURE(0x4)
	TEXTCONT
	TEXTEND
	REMA
	FADI(16)
	CLEAN
	FADU(16)
	MOVE(0x0, CHARACTER_LARACHEL, 9, 2)
	STAL2(16)
	SVAL(EVT_SLOT_D, 0x0)
	SVAL(EVT_SLOT_1, 0x91)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x89)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	MOVE_DEFINED(CHARACTER_DOZLA)
	SVAL(EVT_SLOT_D, 0x0)
	SVAL(EVT_SLOT_1, 0x93)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x89)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	MOVE_DEFINED(CHARACTER_RENNAC)
	ENUN
	CLEN
	MOVE_1STEP(0x10, CHARACTER_EIRIKA, FACING_LEFT)
	ENUN
	CUMO_CHAR(CHARACTER_EIRIKA)
	STAL(60)
	CURE
	TEXTSTART
	TEXTSHOW(0xa1c)
	TEXTEND
	REMA
	MUSCMID(SONG_SILENT)
	CAMERA2(14, 4)
	LOAD1(0x1, UnitDef_Ch9AEnemy_10)
	ENUN
	MOVE_1STEP(0x0, CHARACTER_SETH, FACING_LEFT)
	ENUN
	CUMO_CHAR(CHARACTER_FADO)
	STAL(60)
	CURE
	MUSC(SONG_RAID)
	Text_BG(BG_PORT, 0xa1d)
	LOAD1(0x1, UnitDef_Ch9AEnemy_0)
	ENUN
	SVAL(EVT_SLOT_2, UnitDef_Ch9AEnemy_1)
	SVAL(EVT_SLOT_3, 0x1)
	CALL(EventScr_LoadUnitForTutorial)
	FADI(16)
	DISA(CHARACTER_FADO)
	CLEA
	LOAD1(0x0, UnitDef_Event_Ch9aAlly)
	ENUN
	SVAL(EVT_SLOT_1, 0x1)
	SET_STATE(CHARACTER_TANA)
	CALL(EventScr_CommonPrep)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch8_11[] = {
	SADD(EVT_SLOT_7, EVT_SLOT_2, EVT_SLOT_0)
	SADD(EVT_SLOT_8, EVT_SLOT_3, EVT_SLOT_0)
	SADD(EVT_SLOT_9, EVT_SLOT_4, EVT_SLOT_0)
	SVAL(EVT_SLOT_2, 0x2000f)
	CALL(EventScr_9EEA58)
	TILECHANGE(0x0)
	LOAD1(0x1, UnitDef_Ch9AEnemy_11)
	ENUN
	FADU(16)
	CUMO_CHAR(CHARACTER_VIGARDE)
	STAL(60)
	CURE
	SADD(EVT_SLOT_2, EVT_SLOT_7, EVT_SLOT_0)
	TEXTSTART
	TEXTSHOW(0xffff)
	TEXTEND
	REMA
	MOVE(0x10, CHARACTER_GLEN, 13, 10)
	MOVE(0x10, CHARACTER_VALTER, 15, 10)
	MOVE(0x10, CHARACTER_CAELLACH, 13, 5)
	SVAL(EVT_SLOT_D, 0x0)
	SVAL(EVT_SLOT_1, 0x10151)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x1014f)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	MOVE_DEFINED(CHARACTER_RIEV)
	ENUN
	DISA(CHARACTER_GLEN)
	DISA(CHARACTER_VALTER)
	CUMO_CHAR(CHARACTER_VIGARDE)
	STAL(60)
	CURE
	SADD(EVT_SLOT_2, EVT_SLOT_8, EVT_SLOT_0)
	TEXTSTART
	TEXTSHOW(0xffff)
	TEXTEND
	REMA
	MOVE(0x10, CHARACTER_CAELLACH, 13, 10)
	MOVE(0x10, CHARACTER_RIEV, 15, 10)
	MOVE(0x10, CHARACTER_SELENA, 15, 5)
	SVAL(EVT_SLOT_D, 0x0)
	SVAL(EVT_SLOT_1, 0x1014b)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x1014d)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	MOVE_DEFINED(CHARACTER_DUESSEL)
	ENUN
	DISA(CHARACTER_CAELLACH)
	DISA(CHARACTER_RIEV)
	CUMO_CHAR(CHARACTER_VIGARDE)
	STAL(60)
	CURE
	SADD(EVT_SLOT_2, EVT_SLOT_9, EVT_SLOT_0)
	TEXTSTART
	TEXTSHOW(0xffff)
	TEXTEND
	REMA
	MOVE(0x10, CHARACTER_DUESSEL, 13, 10)
	MOVE(0x10, CHARACTER_SELENA, 15, 10)
	STAL2(15)
	FADI(16)
	ENUN
	CLEA
	CLEE
	CLEN
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9a_EndingScene[] = {
	MUSC(SONG_INTO_THE_SHADOW_OF_VICTORY)
	SetBackground(BG_PORT)
	TEXTSHOW(0xa22)
	TEXTEND
	REMA
	FADI(16)
	CLEA
	CLEE
	CLEN
	CLEAN
	CAMERA2(20, 7)
	EvtSetLoadUnitNoREDA // ENOSUPP in EAstdlib
	LOAD2(0x1, UnitDef_Ch9AMixed_1)
	ENUN
	FADU(16)
	LOAD2(0x1, UnitDef_Ch9AMixed_1)
	ENUN
	MOVE_1STEP(0x0, 0xa7, FACING_DOWN)
	ENUN
	CUMO_CHAR(CHARACTER_SETH)
	STAL(60)
	CURE
	Text_BG(BG_PORT, 0xa23)
	MUSCMID(SONG_SILENT)
	MOVE_1STEP(0x10, CHARACTER_SETH, FACING_UP)
	ENUN
	SVAL(EVT_SLOT_D, 0x0)
	SVAL(EVT_SLOT_1, 0x301d4)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x30014)
	SENQUEUE1
	SVAL(EVT_SLOT_1, 0x0)
	SENQUEUE1
	MOVE_DEFINED(0xa7)
	ENUN
	CUMO_CHAR(CHARACTER_SETH)
	STAL(60)
	CURE
	MUSC(SONG_INDIGNATION)
	Text_BG(BG_PORT, 0xa24)
	LOAD2(0x1, UnitDef_Ch9AAlly_1)
	ENUN
	CUMO_CHAR(CHARACTER_MESSENGER)
	STAL(60)
	CURE
	SetBackground(BG_PORT)
	MUSC(SONG_RAID)
	TEXTSHOW(0xa25)
	TEXTEND
	REMA
	CHECK_EVENTID(8)
	BEQ(0x0, EVT_SLOT_C, EVT_SLOT_0)
	CHECK_EVENTID(9)
	BEQ(0x0, EVT_SLOT_C, EVT_SLOT_0)
	SetBackground(BG_PORT)
	TEXTSHOW(0xa26)
	TEXTEND
	REMA
	CALL(EventScr_RemoveBGIfNeeded)
	SVAL(EVT_SLOT_3, 0x5b)
	GIVEITEMTO(CHAR_EVT_PLAYER_LEADER)
LABEL(0x0)
	ENUT(113)
	MNCH(0xb)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_0[] = {
	MUSS(0x30)
	STAL(33)
	TEXTSTART
	TEXTSHOW(0xa28)
	TEXTEND
	REMA
	MURE(0x2)
	CUSA(CHARACTER_AMELIA)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_1[] = {
	MUSS(0x30)
	STAL(33)
	TEXTSTART
	TEXTSHOW(0xa27)
	TEXTEND
	REMA
	MURE(0x2)
	CUSA(CHARACTER_AMELIA)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_2[] = {
	MUSS(0x2a)
	STAL(33)
	Text_BG(BG_HOUSE, 0xa29)
	MURE(0x2)
	CALL(EventScr_RemoveBGIfNeeded)
	SVAL(EVT_SLOT_3, 0x60)
	GIVEITEMTO(CHAR_EVT_ACTIVE_UNIT)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_3[] = {
	MUSI
	Text_BG(BG_HOUSE, 0xa2a)
	MUNO
	CALL(EventScr_RemoveBGIfNeeded)
	SVAL(EVT_SLOT_3, 0x9)
	GIVEITEMTO(CHAR_EVT_ACTIVE_UNIT)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_4[] = {
	CHECK_ALIVE(CHARACTER_AMELIA)
	BEQ(0x0, EVT_SLOT_C, EVT_SLOT_0)
	CHECK_ALLEGIANCE(CHARACTER_AMELIA)
	SVAL(EVT_SLOT_1, 0x0)
	BEQ(0x0, EVT_SLOT_C, EVT_SLOT_1)
	CAMERA_CAHR(CHARACTER_AMELIA)
	CUMO_CHAR(CHARACTER_AMELIA)
	STAL(60)
	CURE
	MUSS(0x14)
	STAL(33)
	TEXTSTART
	TEXTSHOW(0xa1f)
	TEXTEND
	REMA
	MOVE(0x18, CHARACTER_AMELIA, 2, 23)
	MOVE(0x18, CHARACTER_SOLDIER_83, 2, 23)
	MOVE(0x18, 0x84, 2, 23)
	MOVE(0x18, 0x85, 2, 23)
	ENUN
	DISA(CHARACTER_AMELIA)
	DISA(CHARACTER_SOLDIER_83)
	DISA(0x84)
	DISA(0x85)
	CHECK_ENEMIES
	BNE(0x0, EVT_SLOT_C, EVT_SLOT_0)
	CALL(EventScr_Ch9a_EndingScene)
	ENDB
};

CONST_DATA EventListScr EventScr_Ch9A_5[] = {
LABEL(0x0)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_6[] = {
	SVAL(EVT_SLOT_2, UnitDef_Ch9AEnemy_2)
	CALL(EventScr_LoadReinforce)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_7[] = {
	SVAL(EVT_SLOT_2, UnitDef_Ch9AEnemy_3)
	CALL(EventScr_LoadReinforce)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_8[] = {
	SVAL(EVT_SLOT_2, UnitDef_Ch9AEnemy_4)
	CALL(EventScr_LoadReinforce)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_9[] = {
	SVAL(EVT_SLOT_2, UnitDef_Ch9AEnemy_5)
	CALL(EventScr_LoadReinforce)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_10[] = {
	SVAL(EVT_SLOT_2, UnitDef_Ch9AEnemy_6)
	CALL(EventScr_LoadReinforce)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_11[] = {
	SVAL(EVT_SLOT_2, UnitDef_Ch9AEnemy_7)
	CALL(EventScr_LoadReinforce)
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_12[] = {
	SVAL(EVT_SLOT_2, UnitDef_Ch9AEnemy_8)
	CALL(EventScr_LoadReinforce)
	CUMO_CHAR(CHARACTER_AMELIA)
	STAL(60)
	CURE
	MUSS(0x14)
	STAL(33)
	TEXTSTART
	TEXTSHOW(0xa1e)
	TEXTEND
	REMA
	EVBIT_T(7)
	ENDA
};

CONST_DATA EventListScr EventScr_Ch9A_13[] = {
	SVAL(EVT_SLOT_2, UnitDef_Ch9AEnemy_9)
	CALL(EventScr_LoadReinforceHardMode)
	EVBIT_T(7)
	ENDA
};
