#include "gbafe.h"

CONST_DATA EventListScr EventScr_CastleFelia_BeginningScene[] = {
    CHECK_EVENTID(136)
    BEQ(0x801c, EVT_SLOT_C, EVT_SLOT_0)
    CALL(EventScr_SplitMenu)
LABEL(0x801c)
    MUSC(SONG_VICTORY)
    SetBackground(BG_THRONE_NORMAL)
    CHECK_ALIVE(CHARACTER_GILLIAM)
    BEQ(0x0, EVT_SLOT_C, EVT_SLOT_0)
    TEXTSHOW(0xbff)
    TEXTEND
    MUSCMID(SONG_SILENT)
    TEXTCONT
    TEXTEND
    MUSC(SONG_INTO_THE_SHADOW_OF_VICTORY)
    TEXTCONT
    TEXTEND
    GOTO(0x1)
LABEL(0x0)
    TEXTSHOW(0xc00)
    TEXTEND
    MUSCMID(SONG_SILENT)
    TEXTCONT
    TEXTEND
    MUSC(SONG_INTO_THE_SHADOW_OF_VICTORY)
    TEXTCONT
    TEXTEND
LABEL(0x1)
    REMA
    CALL(EventScr_RemoveBGIfNeeded)
    SVAL(EVT_SLOT_3, 5000)
    GIVE_MONEY(CHAR_EVT_PLAYER_LEADER)
    FADI(4)
    REMOVEPORTRAITS
    BACG(BG_CASTLE_BRIGHT)
    MUSC(SONG_INTO_THE_SHADOW_OF_VICTORY)
    FADU(4)
    TEXTSHOW(0xc01)
    TEXTEND
    REMA
    FADI(16)
    LOAD1(0x1, UnitDef_088B43D0)
    ENUN
    ENUT(138)
    MNCH(0x2)
    ENDA
};

CONST_DATA EventListScr EventScr_CastleFelia_EndingScene[] = {
    ENDA
};
