#pragma once

#include "global.h"
#include "event.h"
#include "eventinfo.h"
#include "eventcall.h"
#include "eventscript.h"
#include "EAstdlib.h"
#include "worldmap.h"
#include "constants/worldmap.h"
#include "constants/characters.h"
#include "constants/classes.h"

CONST_DATA EventScr EventScrWM_08A3A70C[] = {
    EvtTextStartType5 // ENOSUPP in EAstdlib
    SVAL(EVT_SLOT_B, 0x54000c)
    TEXTSHOW(0x8e5)
    TEXTEND
    REMA
    ENUT(229)
    ENUT(235)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch9a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_CastleFrelia)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(26)
    WM_MOVECAM(-1, -1, 32, 0, 90, 0)
    WM_WAITFORCAM
    STAL(6)
    STAL(20)
    WM_LOADLOCATION3(WM_NODE_TowerOfValni)
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_09)
    STAL(70)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_08)
    STAL(70)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 46, 0) // ENOSUPP in EAstdlib
    STAL(60)
    WM_WAITFORCAM
    MUSC(0x5)
    CALL(EventScrWM_08A3A70C)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch9a_ChapterIntro[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 64, 0, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWDRAWNMAP(0, -8, 0x3)
    STAL(120)
    WM_HIGHLIGHT(WM_NATION_Rausten)
    STAL(30)
    WM_TEXT(0x08E6, 0)
    TEXTEND
    WM_HIGHLIGHTCLEAR1(WM_NATION_Rausten)
    WM_HIGHLIGHTCLEAR2(WM_NATION_Rausten)
    WmEvtRemoveBigMap // WM_WAITFORFXCLEAR1
    WmEvtWaitBigMapRemove // WM_WAITFORFXCLEAR2
    WM_MOVESPRITETO(WM_MU_0, 0x0002, WM_NODE_BorderMulan, WM_NODE_PortKiris, -4, 0)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_MAKELORDDISAPPEAR(WM_MU_0)
    WM_SHOWDRAWNMAP(0, -8, 0x3)
    STAL(120)
    WM_HIGHLIGHT(WM_NATION_Carcino)
    STAL(30)
    TEXTCONT
    TEXTEND
    WM_HIGHLIGHTCLEAR1(WM_NATION_Carcino)
    WM_HIGHLIGHTCLEAR2(WM_NATION_Carcino)
    WM_SHOWPORTRAIT(0, 0x0054, 0x02BC, 0)
    STAL(6)
    STAL(46)
    TEXTCONT
    TEXTEND
    WM_SHOWPORTRAIT(1, 0x0052, 0x0534, 0)
    STAL(6)
    STAL(46)
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x01BC, 0)
    STAL(46)
    WM_CLEARPORTRAIT(1, 0x0634, 0)
    STAL(46)
    WmEvtRemoveBigMap // WM_WAITFORFXCLEAR1
    WmEvtWaitBigMapRemove // WM_WAITFORFXCLEAR2
    WM_MOVECAM(-1, -1, 98, 28, 70, 10)
    STAL(30)
    WM_SHOWPORTRAIT(0, 0x000F, 0x02BC, 0)
    STAL(6)
    STAL(46)
    PUTSPRITE(WM_MU_2, CLASS_SNIPER, WM_FACTION_BLUE, WM_NODE_PortKiris)
    WM_MOVESPRITETO(WM_MU_2, 0x0003, WM_NODE_PortKiris, WM_NODE_TerazPlateau, 180, 0)
    WM_WAITFORCAM
    TEXTCONT
    TEXTEND
    WM_WAITFORCAM
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_CLEARPORTRAIT(0, 0x01BC, 0)
    STAL(46)
    WM_REMSPRITE(WM_MU_2)
    STAL(90)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch10a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_PortKiris)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_0A)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3A9EC[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 86, 20, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWDRAWNMAP(0, -8, 0x3)
    STAL(120)
    WM_HIGHLIGHT(WM_NATION_Carcino)
    STAL(30)
    WM_TEXT(0x08E7, 0)
    TEXTEND
    WM_HIGHLIGHTCLEAR1(WM_NATION_Carcino)
    WM_HIGHLIGHTCLEAR2(WM_NATION_Carcino)
    WmEvtRemoveBigMap // WM_WAITFORFXCLEAR1
    WmEvtWaitBigMapRemove // WM_WAITFORFXCLEAR2
    WM_SHOWPORTRAIT(0, 0x000F, 0x0534, 0)
    STAL(6)
    STAL(46)
    PUTSPRITE(WM_MU_2, CLASS_SNIPER, WM_FACTION_BLUE, WM_NODE_TerazPlateau)
    WM_FADEINSPRITE(WM_MU_2, 60)
    WM_WAITFORSPRITELOAD
    TEXTCONT
    TEXTEND
    PUTSPRITE(WM_MU_3, CLASS_MERCENARY, WM_FACTION_RED, WM_NODE_BorderMulan)
    PUTSPRITE(WM_MU_4, CLASS_MERCENARY, WM_FACTION_RED, WM_NODE_BorderMulan)
    WM_PUTSPRITE(WM_MU_3, 0xd8, 0x58)
    WM_PUTSPRITE(WM_MU_4, 0xd8, 0x78)
    WM_FADEINSPRITE(WM_MU_3, 60)
    WM_FADEINSPRITE(WM_MU_4, 60)
    WM_WAITFORSPRITELOAD
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    WM_FADEOUTSPRITE(WM_MU_2, 60)
    WM_WAITFORSPRITELOAD
    STAL(16)
    WM_FADEOUTSPRITE(WM_MU_3, 60)
    WM_FADEOUTSPRITE(WM_MU_4, 60)
    WM_WAITFORSPRITELOAD
    WM_REMSPRITE(WM_MU_2)
    WM_REMSPRITE(WM_MU_3)
    WM_REMSPRITE(WM_MU_4)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_PortKiris, WM_NODE_TerazPlateau, -4, 0)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    STAL(40)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch12a_Beginning[] = {
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3AB68[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch13a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_CaerPelyn)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_0C)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3ABC8[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 168, 62, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWDRAWNMAP(0, 30, 0x3)
    STAL(120)
    WM_HIGHLIGHT(WM_NATION_Jehanna)
    STAL(30)
    WM_TEXT(0x08E9, 0)
    TEXTEND
    WM_HIGHLIGHTCLEAR1(WM_NATION_Jehanna)
    WM_HIGHLIGHTCLEAR2(WM_NATION_Jehanna)
    WmEvtRemoveBigMap // WM_WAITFORFXCLEAR1
    WmEvtWaitBigMapRemove // WM_WAITFORFXCLEAR2
    WM_SHOWPORTRAIT(0, 0x0056, 0x02BC, 0)
    STAL(6)
    STAL(46)
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_SHOWPORTRAIT(0, 0x0002, 0x0534, 0)
    STAL(6)
    STAL(46)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_CaerPelyn, WM_NODE_HamillCanyon, -4, 0)
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    STAL(30)
    WM_WAITFORSPRITES(WM_MU_ANY)
    STAL(20)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch14a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_HamillCanyon)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(30)
    WM_MOVECAM(-1, -1, -1, 86, 45, 0)
    WM_WAITFORCAM
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_0D)
    STAL(70)
    STAL(26)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 26, 0) // ENOSUPP in EAstdlib
    WM_WAITFORCAM
    STAL(26)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3AD40[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 196, 108, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0022, 0x02BC, 0)
    STAL(6)
    STAL(46)
    WM_TEXT(0x08EA, 0)
    TEXTEND
    WM_SHOWPORTRAIT(1, 0x0002, 0x0534, 0)
    STAL(6)
    STAL(46)
    TEXTCONT
    TEXTEND
    PUTSPRITE(WM_MU_2, CLASS_HERO, WM_FACTION_RED, WM_NODE_JehannaHall)
    WM_FADEINSPRITE(WM_MU_2, 60)
    WM_WAITFORSPRITELOAD
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_FADEOUTSPRITE(WM_MU_2, 60)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_HamillCanyon, WM_NODE_JehannaHall, -4, 0)
    TEXTCONT
    TEXTEND
    WM_SHOWPORTRAIT(0, 0x0056, 0x02BC, 0)
    STAL(6)
    STAL(46)
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_WAITFORSPRITELOAD
    WM_REMSPRITE(WM_MU_2)
    TEXTCONT
    TEXTEND
    WM_FADEOUTSPRITE(WM_MU_0, 60)
    WM_CLEARPORTRAIT(1, 0x0200, 0)
    STAL(20)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_WAITFORSPRITELOAD
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch9b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_CastleFrelia)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_MAKELORDVISIBLE(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(26)
    WM_MOVECAM(-1, -1, 32, 0, 90, 0)
    WM_WAITFORCAM
    STAL(6)
    STAL(20)
    WM_LOADLOCATION3(WM_NODE_TowerOfValni)
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_09)
    STAL(70)
    WM_MOVECAM(-1, -1, 0, 32, 45, 0)
    WM_WAITFORCAM
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_0E)
    STAL(70)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 46, 0) // ENOSUPP in EAstdlib
    STAL(60)
    WM_WAITFORCAM
    MUSC(0x6)
    CALL(EventScrWM_08A3A70C)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3AF30[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 0, 32, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0014, 0x02BC, 0)
    STAL(6)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_CastleFrelia, WM_NODE_FortRigwald, -4, 0)
    STAL(30)
    WM_MOVECAM(-1, -1, 0, 64, 80, 0)
    WM_WAITFORCAM
    STAL(30)
    WmEvtPasueMove(WM_MU_0) // ENOSUPP in EAstdlib
    WM_TEXT(0x08F1, 0)
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_SHOWPORTRAIT(0, 0x003D, 0x0534, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_SHOWPORTRAIT(1, 0x000F, 0x02BC, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    STAL(20)
    WM_CLEARPORTRAIT(1, 0x0100, 0)
    STAL(46)
    TEXTCONT
    TEXTEND
    WM_SHOWPORTRAIT(0, 0x0014, 0x02BC, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITELOAD
    PUTSPRITE(WM_MU_2, CLASS_WARRIOR, WM_FACTION_RED, WM_NODE_FortRigwald)
    WM_FADEINSPRITE(WM_MU_2, 60)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITELOAD
    WM_FADEOUTSPRITE(WM_MU_2, 60)
    WmEvtResumeMove(WM_MU_0) // ENOSUPP in EAstdlib
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_WAITFORSPRITELOAD
    WM_REMSPRITE(WM_MU_2)
    STAL(20)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch10b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_FortRigwald)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_SETCAM(0, 112)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_0F)
    STAL(70)
    STAL(26)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 26, 0) // ENOSUPP in EAstdlib
    WM_WAITFORCAM
    STAL(26)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B10C[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 0, 122, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0025, 0x02BC, 0)
    STAL(6)
    WM_TEXT(0x08F2, 0)
    TEXTEND
    STAL(46)
    WM_SHOWPORTRAIT(1, 0x0014, 0x0534, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(1, 0x0200, 0)
    STAL(46)
    WM_MOVESPRITETO(WM_MU_0, 0x0002, WM_NODE_FortRigwald, WM_NODE_Bethroen, -4, 0)
    WM_MOVECAM(-1, -1, 0, 152, 80, 60)
    TEXTCONT
    TEXTEND
    WM_WAITFORCAM
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch12b_Beginning[] = {
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B1F0[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch13b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_Taizel)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_11)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B250[] = {
    STAL(6)
    CALL(EventScr_WM_FadeCommon)
    WM_MOVECAM(-1, -1, 60, 188, 80, 0)
    WM_WAITFORCAM
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0026, 0x02BC, 0)
    STAL(6)
    WM_TEXT(0x08F4, 0)
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_MOVESPRITETO(WM_MU_0, 0x0002, WM_NODE_Taizel, WM_NODE_ZaalbulMarsh, -4, 0)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    STAL(20)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch14b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_ZaalbulMarsh)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_12)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B338[] = {
    STAL(6)
    CALL(EventScr_WM_FadeCommon)
    WM_MOVECAM(-1, -1, 106, 200, 80, 0)
    WM_WAITFORCAM
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0026, 0x0534, 0)
    STAL(6)
    WM_TEXT(0x08F5, 0)
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    STAL(46)
    WM_SHOWPORTRAIT(0, 0x003F, 0x02BC, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_SHOWPORTRAIT(1, 0x0014, 0x0534, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_ZaalbulMarsh, WM_NODE_GradoKeep, -4, 0)
    STAL(100)
    WmEvtPasueMove(WM_MU_0) // ENOSUPP in EAstdlib
    TEXTCONT
    TEXTEND
    PUTSPRITE(WM_MU_2, CLASS_GENERAL, WM_FACTION_RED, WM_NODE_GradoKeep)
    WM_FADEINSPRITE(WM_MU_2, 60)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITELOAD
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    WM_FADEOUTSPRITE(WM_MU_2, 60)
    WmEvtResumeMove(WM_MU_0) // ENOSUPP in EAstdlib
    STAL(46)
    WM_WAITFORSPRITELOAD
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_REMSPRITE(WM_MU_2)
    STAL(20)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_MelkaenCoast_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B460[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_ValniTower1_Beginning[] = {
    FADU(64)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B46C[] = {
    MUSCFAST(0x7fff)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_ValniTower2_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B47C[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_ValniTower3_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B484[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_ValniTower4_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B48C[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_ValniTower5_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B494[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_ValniTower6_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B49C[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_ValniTower7_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4A4[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_ValniTower8_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4AC[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4B0[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4B4[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4B8[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4BC[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins1_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4C4[] = {
    MUSCFAST(0x7fff)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins2_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4D4[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins3_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4DC[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins4_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4E4[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins5_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4EC[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins6_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4F4[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins7_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B4FC[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins8_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B504[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins9_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B50C[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_LagdouRuins10_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B514[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B518[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B51C[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B520[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B524[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch15a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_JehannaHall2)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_REMOVELOCATION(WM_NODE_JehannaHall)
    WM_REMOVEPATH(WM_PATH_0D)
    WM_LOADLOCATION2(WM_NODE_JehannaHall2)
    WM_SETDESTINATION(WM_NODE_JehannaHall2)
    WM_DRAWPATH2(WM_PATH_16)
    WmEvtSetUnitOnNode(WM_MU_0, WM_NODE_JehannaHall2) // ENOSUPP in EAstdlib
    SKIPWN
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B58C[] = {
    EVBIT_MODIFY(0x1)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch16a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_JehannaHall2)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_LOADLOCATION2(WM_NODE_FortRigwald)
    WM_LOADLOCATION2(WM_NODE_Bethroen)
    WM_LOADLOCATION2(WM_NODE_Taizel)
    WM_LOADLOCATION2(WM_NODE_ZaalbulMarsh)
    WM_LOADLOCATION2(WM_NODE_GradoKeep)
    WM_DRAWPATH2(WM_PATH_0E)
    WM_DRAWPATH2(WM_PATH_0F)
    WM_DRAWPATH2(WM_PATH_10)
    WM_DRAWPATH2(WM_PATH_11)
    WM_DRAWPATH2(WM_PATH_12)
    WM_DRAWPATH2(WM_PATH_13)
    WM_DRAWPATH2(WM_PATH_14)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    WM_MOVECAM(-1, -1, 145, 89, 45, 0)
    WM_WAITFORCAM
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_15)
    STAL(70)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 30, 0) // ENOSUPP in EAstdlib
    STAL(60)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B678[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 122, 108, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_TEXT(0x08EC, 0)
    TEXTEND
    WM_SHOWPORTRAIT(0, 0x0044, 0x0534, 0)
    STAL(6)
    PUTSPRITE(WM_MU_2, CLASS_PALADIN, WM_FACTION_RED, WM_NODE_RenaisCastle)
    WM_FADEINSPRITE(WM_MU_2, 60)
    STAL(46)
    WM_WAITFORSPRITELOAD
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    WM_FADEOUTSPRITE(WM_MU_2, 60)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_JehannaHall2, WM_NODE_RenaisCastle, -4, 0)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_WAITFORSPRITELOAD
    WM_WAITFORSPRITES(WM_MU_ANY)
    STAL(20)
    WM_REMSPRITE(WM_MU_2)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch17a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_RenaisCastle)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(26)
    WM_MOVECAM(-1, -1, 108, 48, 26, 0)
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    DRAWPATH3(WM_PATH_17)
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_17)
    STAL(70)
    STAL(26)
    WM_MOVECAMTO(-1, -1, WM_NODE_JehannaHall2, 40, 0)
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_18)
    STAL(70)
    STAL(26)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 26, 0) // ENOSUPP in EAstdlib
    WM_WAITFORCAM
    STAL(26)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B808[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 216, 128, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0002, 0x02BC, 0)
    STAL(6)
    STAL(20)
    WM_SHOWPORTRAIT(1, 0x0014, 0x0534, 0)
    STAL(6)
    STAL(30)
    WM_TEXT(0x08ED, 0)
    TEXTEND
    STAL(46)
    WM_MOVESPRITETO(WM_MU_0, 0x0002, WM_NODE_JehannaHall2, WM_NODE_NarubeRiver, -6, 0)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(20)
    WM_CLEARPORTRAIT(1, 0x0200, 0)
    STAL(46)
    TEXTCONT
    TEXTEND
    PUTSPRITE(WM_MU_2, CLASS_NECROMANCER, WM_FACTION_RED, WM_NODE_NarubeRiver)
    TEXTCONT
    TEXTEND
    WM_FADEINSPRITE(WM_MU_2, 60)
    WM_WAITFORSPRITELOAD
    WM_REMOVETEXT
    STAL(2)
    STAL(60)
    FADI(16)
    WM_REMSPRITE(WM_MU_2)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch18a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_NarubeRiver)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_19)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3B944[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 240, 86, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_TEXT(0x08EE, 0)
    TEXTEND
    WM_SHOWPORTRAIT(0, 0x0002, 0x0534, 0)
    STAL(6)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_NarubeRiver, WM_NODE_NelerasPeak, -4, 0)
    WM_MOVECAM(-1, -1, 240, 54, 110, 75)
    TEXTCONT
    TEXTEND
    WM_WAITFORCAM
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    STAL(46)
    PUTSPRITE(WM_MU_2, CLASS_GORGONEGG, WM_FACTION_RED, WM_NODE_NelerasPeak)
    PUTSPRITE(WM_MU_3, CLASS_GORGONEGG, WM_FACTION_RED, WM_NODE_NelerasPeak)
    PUTSPRITE(WM_MU_4, CLASS_GORGONEGG, WM_FACTION_RED, WM_NODE_NelerasPeak)
    WM_PUTSPRITE(WM_MU_2, 0x168, 0x68)
    WM_PUTSPRITE(WM_MU_3, 0x158, 0x80)
    WM_PUTSPRITE(WM_MU_4, 0x178, 0x80)
    WM_FADEINSPRITE(WM_MU_2, 60)
    WM_FADEINSPRITE(WM_MU_3, 60)
    WM_FADEINSPRITE(WM_MU_4, 60)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITELOAD
    STAL(20)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    WM_REMSPRITE(WM_MU_2)
    WM_REMSPRITE(WM_MU_3)
    WM_REMSPRITE(WM_MU_4)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch19a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_NelerasPeak)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_1A)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3BAC0[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 240, 32, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0002, 0x02BC, 0)
    STAL(6)
    WM_TEXT(0x08EF, 0)
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_SHOWPORTRAIT(0, 0x0022, 0x0534, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_NelerasPeak, WM_NODE_RaustenCourt, -4, 0)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    STAL(46)
    STAL(20)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch20a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_RaustenCourt)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(26)
    WM_MOVECAM(-1, -1, 240, 48, 26, 0)
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    WM_LOADLOCATION3(WM_NODE_LagdouRuins)
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_1C)
    STAL(70)
    STAL(26)
    WM_MOVECAM(-1, -1, 240, 0, 26, 0)
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    WM_LOADLOCATION3(WM_NODE_MelkaenCoast)
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_1D)
    STAL(70)
    STAL(26)
    WM_MOVECAM(-1, -1, 162, 0, 26, 0)
    WM_WAITFORCAM
    STAL(26)
    WM_DRAWPATH(WM_PATH_1E)
    STAL(60)
    STAL(26)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 26, 0) // ENOSUPP in EAstdlib
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_1B)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3BC8C[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 240, 18, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_TEXT(0x08F0, 0)
    TEXTEND
    WM_SHOWPORTRAIT(0, 0x0002, 0x0534, 0)
    STAL(6)
    STAL(46)
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_RaustenCourt, WM_NODE_BlackTemple, -7, 0)
    STAL(20)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_FADEOUTSPRITE(WM_MU_0, 60)
    WM_WAITFORSPRITELOAD
    STAL(45)
    PUTSPRITE(WM_MU_2, CLASS_MANAKETE_2, WM_FACTION_RED, WM_NODE_BlackTemple)
    WM_FADEINSPRITE(WM_MU_2, 60)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITELOAD
    STAL(40)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    WM_REMSPRITE(WM_MU_2)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch21a_Beginning[] = {
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3BD70[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch15b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_GradoKeep)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(26)
    WM_MOVECAM(-1, -1, 126, 160, 26, 0)
    WM_WAITFORCAM
    STAL(26)
    WM_DRAWPATH(WM_PATH_14)
    STAL(70)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_13)
    STAL(70)
    STAL(26)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 26, 0) // ENOSUPP in EAstdlib
    WM_WAITFORCAM
    STAL(26)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3BE14[] = {
    STAL(6)
    CALL(EventScr_WM_FadeCommon)
    WM_MOVECAM(-1, -1, 150, 200, 80, 0)
    WM_WAITFORCAM
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0002, 0x02BC, 0)
    STAL(6)
    WM_TEXT(0x08F6, 0)
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_SHOWPORTRAIT(0, 0x0043, 0x0534, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_SHOWPORTRAIT(1, 0x0002, 0x02BC, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    STAL(20)
    WM_CLEARPORTRAIT(1, 0x0100, 0)
    STAL(46)
    WM_SHOWPORTRAIT(0, 0x0014, 0x0534, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_GradoKeep, WM_NODE_JehannaHall2, -4, 0)
    WM_MOVECAM(-1, -1, 192, 146, 80, 90)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_WAITFORCAM
    WM_WAITFORSPRITES(WM_MU_ANY)
    STAL(20)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch16b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_JehannaHall2)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_LOADLOCATION2(WM_NODE_PortKiris)
    WM_LOADLOCATION2(WM_NODE_TerazPlateau)
    WM_LOADLOCATION2(WM_NODE_CaerPelyn)
    WM_LOADLOCATION2(WM_NODE_HamillCanyon)
    WM_DRAWPATH2(WM_PATH_08)
    WM_DRAWPATH2(WM_PATH_0A)
    WM_DRAWPATH2(WM_PATH_0B)
    WM_DRAWPATH2(WM_PATH_0C)
    WM_DRAWPATH2(WM_PATH_16)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    WM_MOVECAM(-1, -1, 145, 89, 45, 0)
    WM_WAITFORCAM
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_15)
    STAL(70)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 30, 0) // ENOSUPP in EAstdlib
    STAL(60)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3BFF4[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 122, 108, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_TEXT(0x08F7, 0)
    TEXTEND
    WM_SHOWPORTRAIT(0, 0x0044, 0x0534, 0)
    STAL(6)
    PUTSPRITE(WM_MU_2, CLASS_PALADIN, WM_FACTION_RED, WM_NODE_RenaisCastle)
    WM_FADEINSPRITE(WM_MU_2, 60)
    STAL(46)
    WM_WAITFORSPRITELOAD
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    WM_FADEOUTSPRITE(WM_MU_2, 60)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_JehannaHall2, WM_NODE_RenaisCastle, -4, 0)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_WAITFORSPRITELOAD
    WM_WAITFORSPRITES(WM_MU_ANY)
    STAL(20)
    WM_REMSPRITE(WM_MU_2)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch17b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_RenaisCastle)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(26)
    WM_MOVECAM(-1, -1, 80, 56, 26, 0)
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    DRAWPATH3(WM_PATH_17)
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_17)
    STAL(70)
    STAL(26)
    WM_MOVECAMTO(-1, -1, WM_NODE_JehannaHall2, 40, 0)
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_18)
    STAL(70)
    STAL(26)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 26, 0) // ENOSUPP in EAstdlib
    WM_WAITFORCAM
    STAL(26)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C184[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 216, 128, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0014, 0x02BC, 0)
    STAL(6)
    STAL(20)
    WM_SHOWPORTRAIT(1, 0x0002, 0x0534, 0)
    STAL(6)
    WM_TEXT(0x08F8, 0)
    TEXTEND
    STAL(46)
    WM_MOVESPRITETO(WM_MU_0, 0x0002, WM_NODE_JehannaHall2, WM_NODE_NarubeRiver, -6, 0)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(20)
    WM_CLEARPORTRAIT(1, 0x0200, 0)
    STAL(46)
    TEXTCONT
    TEXTEND
    PUTSPRITE(WM_MU_2, CLASS_NECROMANCER, WM_FACTION_RED, WM_NODE_NarubeRiver)
    TEXTCONT
    TEXTEND
    WM_FADEINSPRITE(WM_MU_2, 60)
    WM_WAITFORSPRITELOAD
    WM_REMOVETEXT
    STAL(2)
    STAL(60)
    FADI(16)
    WM_REMSPRITE(WM_MU_2)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch18b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_NarubeRiver)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_19)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C2BC[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 240, 86, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_TEXT(0x08F9, 0)
    TEXTEND
    WM_SHOWPORTRAIT(0, 0x0014, 0x0534, 0)
    STAL(6)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_NarubeRiver, WM_NODE_NelerasPeak, -4, 0)
    WM_MOVECAM(-1, -1, 240, 54, 110, 75)
    TEXTCONT
    TEXTEND
    WM_WAITFORCAM
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    STAL(46)
    PUTSPRITE(WM_MU_2, CLASS_GORGONEGG, WM_FACTION_RED, WM_NODE_NelerasPeak)
    PUTSPRITE(WM_MU_3, CLASS_GORGONEGG, WM_FACTION_RED, WM_NODE_NelerasPeak)
    PUTSPRITE(WM_MU_4, CLASS_GORGONEGG, WM_FACTION_RED, WM_NODE_NelerasPeak)
    WM_PUTSPRITE(WM_MU_2, 0x168, 0x68)
    WM_PUTSPRITE(WM_MU_3, 0x158, 0x80)
    WM_PUTSPRITE(WM_MU_4, 0x178, 0x80)
    WM_FADEINSPRITE(WM_MU_2, 60)
    WM_FADEINSPRITE(WM_MU_3, 60)
    WM_FADEINSPRITE(WM_MU_4, 60)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITELOAD
    STAL(20)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    WM_REMSPRITE(WM_MU_2)
    WM_REMSPRITE(WM_MU_3)
    WM_REMSPRITE(WM_MU_4)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch19b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_NelerasPeak)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_1A)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C438[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 240, 32, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0014, 0x02BC, 0)
    STAL(6)
    WM_TEXT(0x08FA, 0)
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_SHOWPORTRAIT(0, 0x0022, 0x0534, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_NelerasPeak, WM_NODE_RaustenCourt, -4, 0)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    STAL(46)
    STAL(20)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch20b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_RaustenCourt)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(26)
    WM_MOVECAM(-1, -1, 240, 48, 26, 0)
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    WM_LOADLOCATION3(WM_NODE_LagdouRuins)
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_1C)
    STAL(70)
    STAL(26)
    WM_MOVECAM(-1, -1, 240, 0, 26, 0)
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    WM_LOADLOCATION3(WM_NODE_MelkaenCoast)
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_1D)
    STAL(70)
    STAL(26)
    WM_MOVECAM(-1, -1, 162, 0, 26, 0)
    WM_WAITFORCAM
    STAL(26)
    WM_DRAWPATH(WM_PATH_1E)
    STAL(60)
    STAL(26)
    WmEvtMoveCamToUnit(-1, -1, WM_MU_0, 26, 0) // ENOSUPP in EAstdlib
    WM_WAITFORCAM
    STAL(26)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_1B)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C604[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 240, 18, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_TEXT(0x08FB, 0)
    TEXTEND
    WM_SHOWPORTRAIT(0, 0x0014, 0x0534, 0)
    STAL(6)
    STAL(46)
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_RaustenCourt, WM_NODE_BlackTemple, -7, 0)
    STAL(20)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_FADEOUTSPRITE(WM_MU_0, 60)
    WM_WAITFORSPRITELOAD
    STAL(45)
    PUTSPRITE(WM_MU_2, CLASS_MANAKETE_2, WM_FACTION_RED, WM_NODE_BlackTemple)
    WM_FADEINSPRITE(WM_MU_2, 60)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITELOAD
    STAL(40)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    WM_REMSPRITE(WM_MU_2)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch21b_Beginning[] = {
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C6E8[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C6EC[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_BorderMulan)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_LOADLOCATION2(WM_NODE_BorderMulan)
    WmEvtSetNodeStateNot2(WM_NODE_BorderMulan) // ENOSUPP in EAstdlib
    WM_SETCAM(0, 12)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_00)
    STAL(70)
    WM_SHOWTEXTWINDOW(40, 0x0001)
    WM_WAITFORTEXT
    WM_TEXTSTART
    WM_TEXT(0x08DC, 0)
    TEXTEND
    STAL(20)
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_BorderMulan, WM_NODE_CastleFrelia, 200, 40)
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    SKIPWN
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C79C[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_Serafew)
    WM_CENTERCAMONLORD(WM_MU_0)
    WmEvtSetNodeStateNot2(WM_NODE_Serafew) // ENOSUPP in EAstdlib
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    WmEvtSetUnitOnNode(WM_MU_0, WM_NODE_Serafew) // ENOSUPP in EAstdlib
    WM_MAKELORDVISIBLE(WM_MU_0)
    WM_MOVESPRITETO(WM_MU_0, 0x0004, WM_NODE_Serafew, WM_NODE_ZahaWoods, -2, 0)
    WM_WAITFORSPRITES(WM_MU_0)
    WM_MOVESPRITETO(WM_MU_0, 0x0004, WM_NODE_ZahaWoods, WM_NODE_BorgoRidge, -2, 0)
    WM_MOVECAMTO(-1, -1, WM_NODE_CastleFrelia, 120, 0)
    WM_WAITFORSPRITES(WM_MU_0)
    WM_MOVESPRITETO(WM_MU_0, 0x0004, WM_NODE_BorgoRidge, WM_NODE_Ide, -2, 0)
    WM_WAITFORSPRITES(WM_MU_0)
    WM_MOVESPRITETO(WM_MU_0, 0x0004, WM_NODE_Ide, WM_NODE_CastleFrelia, -2, 0)
    WM_WAITFORSPRITES(WM_MU_0)
    WM_WAITFORCAM
    WmEvtSetUnitOnNode(WM_MU_0, WM_NODE_CastleFrelia) // ENOSUPP in EAstdlib
    SKIPWN
    ENDA
};

CONST_DATA EventScr EventScrWM_CastleFrelia_Beginning[] = {
    CHECK_EVENTID(136)
    BNE(0x1, EVT_SLOT_C, EVT_SLOT_0)
    CALL(EventScrWM_08A3C6EC)
    ENDB
};

CONST_DATA EventScr EventScrWM_08A3C878[] = {
LABEL(0x1)
    CALL(EventScrWM_08A3C79C)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C888[] = {
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch5x_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch5x_ChapterIntro[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch21ax_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C89C[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch21bx_Beginning[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C8A4[] = {
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch11a_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EIRIKA, WM_NODE_TerazPlateau)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_0B)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3C904[] = {
    STAL(6)
    WM_MOVECAM(-1, -1, 112, 46, 60, 0)
    WM_WAITFORCAM
    CALL(EventScr_WM_FadeCommon)
    STAL(60)
    WM_TEXTSTART
    WM_SHOWDRAWNMAP(0, -8, 0x3)
    STAL(120)
    WM_HIGHLIGHT(WM_NATION_Pokhara)
    STAL(30)
    WM_TEXT(0x08E8, 0)
    TEXTEND
    WM_HIGHLIGHTCLEAR1(WM_NATION_Pokhara)
    WM_HIGHLIGHTCLEAR2(WM_NATION_Pokhara)
    WmEvtRemoveBigMap // WM_WAITFORFXCLEAR1
    WmEvtWaitBigMapRemove // WM_WAITFORFXCLEAR2
    WM_SHOWPORTRAIT(0, 0x0002, 0x0534, 0)
    STAL(6)
    STAL(46)
    TEXTCONT
    TEXTEND
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_TerazPlateau, WM_NODE_CaerPelyn, -4, 0)
    TEXTCONT
    TEXTEND
    TEXTCONT
    TEXTEND
    WM_WAITFORSPRITES(WM_MU_ANY)
    WM_CLEARPORTRAIT(0, 0x0200, 0)
    STAL(40)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    ENDA
};

CONST_DATA EventScr EventScrWM_Ch11b_Beginning[] = {
    EVBIT_MODIFY(0x1)
    WM_SPAWNLORD(WM_MU_0, CHARACTER_EPHRAIM, WM_NODE_Bethroen)
    WM_CENTERCAMONLORD(WM_MU_0)
    WM_FADEOUT(0)
    WM_TEXTDECORATE // WaitFade
    EVBIT_MODIFY(0x0)
    STAL(20)
    WM_CREATENEXTDESTINATION
    WM_WAITFORFX
    STAL(40)
    WM_DRAWPATH(WM_PATH_10)
    STAL(70)
    WM_MAKELORDVISIBLE(WM_MU_0)
    EVBIT_MODIFY(0x1)
    CALL(EventScr_RemoveBGIfNeeded)
    ENDA
};

CONST_DATA EventScr EventScrWM_08A3CA2C[] = {
    STAL(6)
    CALL(EventScr_WM_FadeCommon)
    WM_MOVECAM(-1, -1, 0, 188, 80, 0)
    WM_WAITFORCAM
    STAL(60)
    WM_TEXTSTART
    WM_SHOWPORTRAIT(0, 0x0025, 0x02BC, 0)
    STAL(6)
    WM_TEXT(0x08F3, 0)
    TEXTEND
    STAL(46)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    WM_SHOWPORTRAIT(0, 0x0040, 0x02BC, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    STAL(46)
    WM_SHOWPORTRAIT(1, 0x0014, 0x0534, 0)
    STAL(6)
    TEXTCONT
    TEXTEND
    WM_CLEARPORTRAIT(1, 0x0200, 0)
    STAL(30)
    WM_CLEARPORTRAIT(0, 0x0100, 0)
    STAL(46)
    TEXTCONT
    TEXTEND
    WM_MOVESPRITETO(WM_MU_0, 0x0000, WM_NODE_Bethroen, WM_NODE_Taizel, -4, 0)
    STAL(110)
    WM_REMOVETEXT
    STAL(2)
    STAL(20)
    FADI(16)
    WM_WAITFORSPRITES(WM_MU_ANY)
    ENDA
};
