EVENT_COMMANDS = {
    0x00: "EV_CMD_NOP",
    0x01: "EV_CMD_END",
    0x02: "EV_CMD_EVSET",
    0x03: "EV_CMD_EVCHECK",
    0x04: "EV_CMD_RANDOMNUMBER",
    0x05: "EV_CMD_SVAL",
    0x06: "EV_CMD_SLOT_OPS",
    0x07: "EV_CMD_QUEUE_OPS",
    0x08: "EV_CMD_LABEL",
    0x09: "EV_CMD_GOTO",
    0x0A: "EV_CMD_CALL",
    0x0B: "EV_CMD_ENQUEUE_CALL",
    0x0C: "EV_CMD_BRANCH",
    0x0D: "EV_CMD_ASMC",
    0x0E: "EV_CMD_STALL",
    0x0F: "EV_CMD_COUNTER",
    0x10: "EV_CMD_EVBITMODIFY",
    0x11: "EV_CMD_IGNOREKEYS",
    0x12: "EV_CMD_BGMCHANGE_12",
    0x13: "EV_CMD_BGMCHANGE_13",
    0x14: "EV_CMD_BGMOVERWRITE",
    0x15: "EV_CMD_BGMVOLUMECHANGE",
    0x16: "EV_CMD_PLAYSE",
    0x17: "EV_CMD_FADE",
    0x18: "EV_CMD_COLORFADE",
    0x19: "EV_CMD_CHECKVARIOUS",
    0x1A: "EV_CMD_SETTEXTTYPE",
    0x1B: "EV_CMD_DISPLAYTEXT",
    0x1C: "EV_CMD_CONTINUETEXT",
    0x1D: "EV_CMD_ENDTEXT",
    0x1E: "EV_CMD_DISPLAYFACE",
    0x1F: "EV_CMD_MOVEFACE",
    0x20: "EV_CMD_CLEARTEXTBOX",
    0x21: "EV_CMD_SHOWBG",
    0x22: "EV_CMD_CLEARSCREEN",
    0x23: "EV_CMD_23",
    0x24: "EV_CMD_24",
    0x25: "EV_CMD_LOMA",
    0x26: "EV_CMD_CAMERACONTROL",
    0x27: "EV_CMD_TILE_CHANGE",
    0x28: "EV_CMD_CHANGEWEATHER",
    0x29: "EV_CMD_CHANGEFOGVISION",
    0x2A: "EV_CMD_CHANGECHAPTER",
    0x2B: "EV_CMD_LOAD_PRECONF",
    0x2C: "EV_CMD_LOADUNIT",
    0x2D: "EV_CMD_CHANGE_PAL",
    0x2E: "EV_CMD_GET_PID",
    0x2F: "EV_CMD_MOVEUNIT",
    0x30: "EV_CMD_ENUN",
    0x31: "EV_CMD_TOGGLERANGE",
    0x32: "EV_CMD_LOADSINGLEUNIT",
    0x33: "EV_CMD_CHECKSTATE",
    0x34: "EV_CMD_CHANGESTATE",
    0x35: "EV_CMD_CHANGECLASS",
    0x36: "EV_CMD_CHECKINAREA",
    0x37: "EV_CMD_GIVEITEM",
    0x38: "EV_CMD_CHANGEACTIVEUNIT",
    0x39: "EV_CMD_CHANGEAI",
    0x3A: "EV_CMD_DISPLAYPOPUP",
    0x3B: "EV_CMD_DISPLAYCURSOR",
    0x3C: "EV_CMD_MOVE_CURSOR",
    0x3D: "EV_CMD_MENUOVERRIDE",
    0x3E: "EV_CMD_PREPSCREEN",
    0x3F: "EV_CMD_SCRIPT_BATTLE",
    0x40: "EV_CMD_40",
    0x41: "EV_CMD_WARP",
    0x42: "EV_CMD_42",
    0x43: "EV_CMD_43",
    0x44: "EV_CMD_44",
    0x45: "EV_CMD_45",
}

EVENT_SLOTS = {
    0x00: "EVT_SLOT_0",
    0x01: "EVT_SLOT_1",
    0x02: "EVT_SLOT_2",
    0x03: "EVT_SLOT_3",
    0x04: "EVT_SLOT_4",
    0x05: "EVT_SLOT_5",
    0x06: "EVT_SLOT_6",
    0x07: "EVT_SLOT_7",
    0x08: "EVT_SLOT_8",
    0x09: "EVT_SLOT_9",
    0x0A: "EVT_SLOT_A",
    0x0B: "EVT_SLOT_B",
    0x0C: "EVT_SLOT_C",
    0x0D: "EVT_SLOT_D",
    0x0E: "EVT_SLOT_E",
    0x0F: "EVT_SLOT_F",
}

EVENT0B_TRIGGER_TYPE = {
    0: "TUTORIAL_EVT_TYPE_PHASECHANGE",
    1: "TUTORIAL_EVT_TYPE_POSTACTION",
    2: "TUTORIAL_EVT_TYPE_ONSELECT",
    3: "TUTORIAL_EVT_TYPE_DESTSELECTED",
    4: "TUTORIAL_EVT_TYPE_AFTERMOVE",
    5: "TUTORIAL_EVT_TYPE_FORECAST",
    6: "TUTORIAL_EVT_TYPE_PLAYERPHASE",
}

FACTION_NAMES = {
    0x00: 'FACTION_BLUE',
    0x40: 'FACTION_GREEN',
    0x80: 'FACTION_RED',
    0xC0: 'FACTION_PURPLE'}

BOOL_NAMES = { 0: 'FALSE', 1: 'TRUE' }

_PID_IDX = {
    0x01: "CHARACTER_EIRIKA",
    0x02: "CHARACTER_SETH",
    0x03: "CHARACTER_GILLIAM",
    0x04: "CHARACTER_FRANZ",
    0x05: "CHARACTER_MOULDER",
    0x06: "CHARACTER_VANESSA",
    0x07: "CHARACTER_ROSS",
    0x08: "CHARACTER_NEIMI",
    0x09: "CHARACTER_COLM",
    0x0A: "CHARACTER_GARCIA",
    0x0B: "CHARACTER_INNES",
    0x0C: "CHARACTER_LUTE",
    0x0D: "CHARACTER_NATASHA",
    0x0E: "CHARACTER_CORMAG",
    0x0F: "CHARACTER_EPHRAIM",
    0x10: "CHARACTER_FORDE",
    0x11: "CHARACTER_KYLE",
    0x12: "CHARACTER_AMELIA",
    0x13: "CHARACTER_ARTUR",
    0x14: "CHARACTER_GERIK",
    0x15: "CHARACTER_TETHYS",
    0x16: "CHARACTER_MARISA",
    0x17: "CHARACTER_SALEH",
    0x18: "CHARACTER_EWAN",
    0x19: "CHARACTER_LARACHEL",
    0x1A: "CHARACTER_DOZLA",
    0x1C: "CHARACTER_RENNAC",
    0x1D: "CHARACTER_DUESSEL",
    0x1E: "CHARACTER_MYRRH",
    0x1F: "CHARACTER_KNOLL",
    0x20: "CHARACTER_JOSHUA",
    0x21: "CHARACTER_SYRENE",
    0x22: "CHARACTER_TANA",
    0x23: "CHARACTER_LYON_CC",
    0x24: "CHARACTER_ORSON_CC",
    0x25: "CHARACTER_GLEN_CC",
    0x26: "CHARACTER_SELENA_CC",
    0x27: "CHARACTER_VALTER_CC",
    0x28: "CHARACTER_RIEV_CC",
    0x29: "CHARACTER_CAELLACH_CC",
    0x2A: "CHARACTER_FADO_CC",
    0x2B: "CHARACTER_ISMAIRE_CC",
    0x2C: "CHARACTER_HAYDEN_CC",

    # Summoned Characters
    0x3B: "CHARACTER_SUMMON_LYON",
    0x3E: "CHARACTER_SUMMON_KNOLL",
    0x3F: "CHARACTER_SUMMON_EWAN",

    # Boss/Unique Enemy Characters
    0x40: "CHARACTER_LYON",
    0x41: "CHARACTER_MORVA",
    0x42: "CHARACTER_ORSON_CH5X",
    0x43: "CHARACTER_VALTER",
    0x44: "CHARACTER_SELENA",
    0x45: "CHARACTER_VALTER_PROLOGUE",
    0x46: "CHARACTER_BREGUET",
    0x47: "CHARACTER_BONE",
    0x48: "CHARACTER_BAZBA",
    0x49: "CHARACTER_ENTOUMBED_CH4",
    0x4A: "CHARACTER_SAAR",
    0x4B: "CHARACTER_NOVALA",
    0x4C: "CHARACTER_MURRAY",
    0x4D: "CHARACTER_TIRADO",
    0x4E: "CHARACTER_BINKS",
    0x4F: "CHARACTER_PABLO",
    0x50: "CHARACTER_MAELDUIN_CHUnk",
    0x51: "CHARACTER_AIAS",
    0x52: "CHARACTER_CARLYLE",
    0x53: "CHARACTER_CAELLACH",
    0x54: "CHARACTER_PABLO_2",
    0x56: "CHARACTER_GORGON_CHUnk",
    0x57: "CHARACTER_RIEV",
    0x5A: "CHARACTER_GHEB",
    0x5B: "CHARACTER_BERAN",
    0x5C: "CHARACTER_CYCLOPS_CHUnk",
    0x5D: "CHARACTER_WIGHT_CHUnk",
    0x5E: "CHARACTER_DEATHGOYLE_CHUnk",
    0x66: "CHARACTER_BANDIT_CH5",
    0x68: "CHARACTER_ONEILL",
    0x69: "CHARACTER_GLEN",
    0x6A: "CHARACTER_ZONTA",
    0x6B: "CHARACTER_VIGARDE",
    0x6C: "CHARACTER_LYON_FINAL",
    0x6D: "CHARACTER_ORSON",

    0x83: "CHARACTER_SOLDIER_83",

    0xBA: "CHARACTER_MONSTER_BA",
    0xBE: "CHARACTER_FOMORTIIS",

    0xC0: "CHARACHER_FRELIAN",
    0xC5: "CHARACTER_FADO",

    0xC7: "CHARACTER_HAYDEN",
    0xC8: "CHARACTER_MANSEL",
    0xC9: "CHARACTER_KLIMT",
    0xCA: "CHARACTER_DARA",
    0xCB: "CHARACTER_ISMAIRE",
    0xCC: "CHARACTER_MESSENGER",

    0xFC: "CHARACTER_CITIZEN",
    0xFD: "CHARACTER_ARENA_OPPONENT",
}

def PID_IDX(pid):
    if pid in _PID_IDX:
        return _PID_IDX[pid]

    if pid == 0:
        return "CHAR_EVT_PLAYER_LEADER"

    if pid == -1:
        return "CHAR_EVT_ACTIVE_UNIT"

    if pid == -2:
        return "CHAR_EVT_POSITION_AT_SLOTB"

    if pid == -3:
        return "CHAR_EVT_SLOT2"

    return hex(pid)

DIRECTION_IDX = {
    0: "FACING_LEFT",
    1: "FACING_RIGHT",
    2: "FACING_DOWN",
    3: "FACING_UP",
}

POSITION_IDX = {
    0: "POS_L",
    1: "POS_R",
}
