#ifndef GUARD_BMTARGET_H
#define GUARD_BMTARGET_H

// ??? ForEachUnitInMovement(???);
// ??? ForEachUnitInRange(???);
// ??? ForEachPosInRange(???);
// ??? ForEachAdjacentUnit(???);
// ??? ForEachAdjacentPosition(???);
// ??? sub_8024FD8(???);
// ??? ForEachPosIn12Range(???);
// ??? ForEachUnitInMagBy2Range(???);
// ??? TryAddTrapsToTargetList(???);
// ??? AddUnitToTargetListIfNotAllied(???);
void MakeTargetListForWeapon(struct Unit* unit, int item);
// ??? TryAddUnitToTradeTargetList(???);
void MakeTradeTargetList(struct Unit* unit);
// ??? TryAddUnitToRescueTargetList(???);
void MakeRescueTargetList(struct Unit* unit);
// ??? TryAddToDropTargetList(???);
void MakeDropTargetList(struct Unit* unit);
// ??? TryAddRescuedUnitToTakeTargetList(???);
void MakeTakeTargetList(struct Unit* unit);
// ??? TryAddUnitToGiveTargetList(???);
void MakeGiveTargetList(struct Unit* unit);
// ??? TryAddUnitToTalkTargetList(???);
void MakeTalkTargetList(struct Unit* unit);
void MakeTargetListForSupport(struct Unit* unit);
// ??? AddUnitToTargetListIfAllied(???);
void FillBallistaRangeMaybe(struct Unit* unit);
// ??? TryAddClosedDoorToTargetList(???);
// ??? TryAddBridgeToTargetList(???);
void MakeTargetListForDoorAndBridges(struct Unit* unit, int terrainId);
// ??? sub_8025864(???);
void MakeTargetListForPick(struct Unit* unit);
void MakeTerrainHealTargetList(int faction);
void MakePoisonDamageTargetList(int faction);
void MakeGorgonEggHatchTargetList(int faction);
// ??? TryAddUnitToRefreshTargetList(???);
void MakeTargetListForRefresh(struct Unit* unit);
// ??? AddAsTarget_IfCanStealFrom(???);
void MakeTargetListForSteal(struct Unit* unit);
// ??? AddAsTarget_IfPositionCleanForSummon(???);
void MakeTargetListForSummon(struct Unit* unit);
// ??? sub_8025CD8(???);
// ??? sub_8025D48(???);
// ??? sub_8025D80(???);
// ??? sub_8025DB8(???);
// ??? sub_8025DF0(???);
// ??? TryAddUnitToHealTargetList(???);
void MakeTargetListForAdjacentHeal(struct Unit* unit);
void MakeTargetListForRangedHeal(struct Unit* unit);
// ??? AddToTargetListIfNotAllied(???);
void MakeTargetListForFuckingNightmare(struct Unit* unit);
// ??? TryAddUnitToRestoreTargetList(???);
void MakeTargetListForRestore(struct Unit* unit);
// ??? TryAddUnitToBarrierTargetList(???);
void MakeTargetListForBarrier(struct Unit* unit);
// ??? TryAddUnitToRescueStaffTargetList(???);
void MakeTargetListForRescueStaff(struct Unit* unit);
// ??? TryAddUnitToSilenceTargetList(???);
// ??? TryAddUnitToSleepTargetList(???);
// ??? TryAddUnitToBerserkTargetList(???);
void MakeTargetListForSilence(struct Unit* unit);
void MakeTargetListForSleep(struct Unit* unit);
void MakeTargetListForBerserk(struct Unit* unit);
// ??? TryAddUnitToWarpTargetList(???);
void MakeTargetListForWarp(struct Unit* unit);
void MakeTargetListForUnlock(struct Unit* unit);
// ??? TryAddUnitToHammerneTargetList(???);
void MakeTargetListForHammerne(struct Unit* unit);
void MakeTargetListForLatona(struct Unit* unit);
void sub_8026414(int unk);
// ??? TryAddToMineTargetList(???);
void MakeTargetListForMine(struct Unit* unit);
// ??? TryAddToLightRuneTargetList(???);
void MakeTargetListForLightRune(struct Unit* unit);
// ??? TryAddUnitToDanceRingTargetList(???);
void MakeTargetListForDanceRing(struct Unit* unit);

extern struct Unit* gSubjectUnit;

#endif // GUARD_BMTARGET_H
