#pragma once

#include "global.h"
#include "proc.h"
#include "event.h"
#include "uimenu.h"

struct UnkProc80855A0 {
    PROC_HEADER;
    /* 29 */ u8 _pad_29[0x4D - 0x29];
    /* 4D */ u8 unk4D;
};

struct Proc8085618 {
    PROC_HEADER;
    /* 29 */ u8 _pad_29[0x4C - 0x29];
    /* 4C */ s8 unk4C;
};

struct Proc89EE068 {
    PROC_HEADER;
    /* 29 */ u8 _pad_29[0x54 - 0x29];
    /* 54 */ ProcPtr unk_proc;
};

struct ProcWorldFlush {
    PROC_HEADER;
    /* 29 */ u8 _pad_29[0x2C - 0x29];
    /* 2C */ u32 count;
};

struct ProcEventMapAnim {
    PROC_HEADER;
    /* 29 */ u8 _pad_29[0x4C - 0x29];
    /* 4C */ s16 timer;
    /* 4E */ u8 _pad_4E[0x52 - 0x4E];
    /* 52 */ u16 count;
    /* 54 */ u8 _pad_54[0x64 - 0x54];
    /* 64 */ s16 mode;
};

struct Proc89EEA28 {
    PROC_HEADER;
    /* 29 */ u8 _pad_29[0x4C - 0x29];
    /* 4C */ s16 timer;
    /* 4E */ u8 _pad_4E[0x52 - 0x4E];
    /* 52 */ u16 count;
    /* 54 */ u8 _pad_54[0x64 - 0x54];
    /* 64 */ s16 mode;
};

void EventCallGameOverExt(ProcPtr proc);
void GameOver_FadeOutCurrentBgm(ProcPtr proc);
void SkilGameOverForToturialExtraMap(ProcPtr proc);
void PostGameOverHandler(ProcPtr proc);
int CheckWaitAction_unused(void);
void UnsetKeyIgnoreMask(void);
void AsnycKeyStatus_ButtonB(void);
void NewForceAsyncButtonB(ProcPtr proc);
void HideAllAlliesExceptLeader(void);
void ResetAllPlayerUnitState(void);
// ??? TryLockParentProc(???);
// ??? TryUnlockParentProc(???);
// ??? ResetAllBG(???);
// ??? SwapUnitStatsChar100(???);
// ??? sub_8085550(???);
// ??? sub_8085578(???);
// ??? sub_80855A0(???);
// ??? sub_80855D4(???);
// ??? sub_80855F8(???);
void sub_8085618(struct Proc * proc);
void sub_8085670(struct Proc * proc);
// ??? sub_80856D0(???);
// ??? sub_8085728(???);
// ??? sub_808576C(???);
// ??? sub_80857B0(???);
// ??? sub_80857F4(???);
// ??? sub_808581C(???);
// ??? sub_8085844(???);
// ??? sub_808586C(???);
void sub_8085894(struct Proc * proc);
void sub_808589C(struct Proc * proc);
// ??? sub_808591C(???);
// ??? sub_8085948(???);
void SetEventId_0x84(ProcPtr);
void UnsetEventId_0x84(ProcPtr);
void sub_8085988(struct EventEngineProc * proc);
void sub_8085990(struct EventEngineProc * proc);
void sub_80859D0(ProcPtr proc, ProcPtr parent);
void nullsub_20(ProcPtr);
void WorldFlushInit(struct ProcWorldFlush * proc);
void WorldFlushOut(struct ProcWorldFlush * proc);
void WorldFlushReload(struct ProcWorldFlush * proc);
void WorldFlushIn(struct ProcWorldFlush * proc);
// ??? WorldFlushCallBack(???);
void StartWorldFlush(struct EventEngineProc * proc);
// ??? sub_8085C10(???);
// ??? sub_8085C24(???);
// ??? sub_8085C38(???);
void sub_8085C4C(void);
void sub_8085C58(void);
void DisplayMapClearMapAnim(ProcPtr proc);
void DisplayCongratulationsMapAnim(ProcPtr proc);
void DisplayEventMapAnim(ProcPtr, int);
void DrawEventMapAnimMaskfx(int, int);
// ??? sub_8085E08(???);
// ??? sub_8085E48(???);
// ??? sub_8085E94(???);
// ??? nullsub_30(???);
// ??? sub_8085F88(???);
// ??? sub_808609C(???);
// ??? sub_8086100(???);
// ??? sub_8086134(???);
// ??? sub_808613C(???);
// ??? sub_808622C(???);
// ??? sub_80862C4(???);
// ??? sub_808635C(???);
void HandleCh5xUnits_Start();
void HandleCh5xUnits_End();
void CallRouteSplitMenu(ProcPtr proc);
int MenuCommand_DrawRouteSplit(struct MenuProc* menu, struct MenuItemProc* menu_item);
u8 Command_EirikaMode(struct MenuProc* menu, struct MenuItemProc* menu_item);
u8 Command_EphraimMode(struct MenuProc* menu, struct MenuItemProc* menu_item);
void AutolevelSecondaryLord();

extern CONST_DATA EventListScr EventScr_9EEA58[];
extern CONST_DATA EventListScr EventScr_9EEAAC[];
extern CONST_DATA EventListScr EventScr_9EEB00[];
extern CONST_DATA EventListScr EventScr_CallBreakStone[];

extern CONST_DATA EventListScr EventScr_CallOnTutorialMode[];
extern CONST_DATA EventListScr EventScr_CallOnHardMode[];
extern CONST_DATA EventListScr EventScr_CallOnChapterNumber[];
extern CONST_DATA EventListScr EventScr_CallIfCommonMode[];
extern CONST_DATA EventListScr EventScr_CallWithModeCheck[];
extern CONST_DATA EventListScr EventScr_SetFlagIfPlayedThrough[];
extern CONST_DATA EventListScr Event_TextWithBG[];
extern CONST_DATA EventListScr EventScr_UnTriggerIfNotUnit[];
extern CONST_DATA EventListScr EventScr_UnTriggerIfNotFaction[];
extern CONST_DATA EventListScr EventScr_EndAndResetTriggEvent[];
extern CONST_DATA EventListScr EventScr_LoadUnitWithRestrictionCtrl[];
extern CONST_DATA EventListScr EventScr_LoadUnitForDifferentMode[];
extern CONST_DATA EventListScr EventScr_LoadUnitForTutorial[];
extern CONST_DATA EventListScr EventScr_LoadReinforce[];
extern CONST_DATA EventListScr EventScr_LoadReinforceHardMode[];
extern CONST_DATA EventListScr EventScr_TextShowWithFadeIn[];
extern CONST_DATA EventListScr EventScr_SetBackground[];
extern CONST_DATA EventListScr Event_TextWithBG[];
extern CONST_DATA EventListScr EventScr_ApplyActiveUnitTileChange[];
extern CONST_DATA EventListScr EventScr_ApplyTileChangeForFactionIfAlly[];
extern CONST_DATA EventListScr EventScr_ApplyTileChangeForFactionIfEnemy[];
extern CONST_DATA EventListScr EventScr_ApplyTileChangeForFactionIfNPC[];
extern CONST_DATA EventListScr EventScr_ApplyTileChangeForFaction[];
extern CONST_DATA EventListScr EventScr_FormatFlashingCursor[];
extern CONST_DATA EventListScr EventScr_MoveUnitS2ToLeader[];
extern CONST_DATA EventListScr EventScr_FormatMoveUnit[];
extern CONST_DATA EventListScr EventScr_LoadUniqueAlly[];
extern CONST_DATA EventListScr EventScr_UnitWarpIN[];
extern CONST_DATA EventListScr EventScr_UnitWarpOUT[];
extern CONST_DATA EventListScr EventScr_UnitFlushingIN[];
extern CONST_DATA EventListScr EventScr_UnitFlushingOUT[];
extern CONST_DATA EventListScr EventScr_9EE5BC[];
extern CONST_DATA EventListScr EventScr_GiveTreasureToLuckyDog[];
extern CONST_DATA EventListScr EventScr_ChangeAIinQueue[];
extern CONST_DATA EventListScr EventScr_9EE6A0[];
extern CONST_DATA EventListScr EventScr_9EE6C8[];
extern CONST_DATA EventListScr EventScr_Tutorial_Exec0[];
extern CONST_DATA EventListScr EventScr_Tutorial_Exec1[];
extern CONST_DATA EventListScr EventScr_ConfigHardModeLoadUnitHard[];
extern CONST_DATA EventListScr EventScr_9EE84C[];
extern CONST_DATA EventListScr EventScr_9EE8F0[];
extern CONST_DATA EventListScr EventScr_FloorClearInTower[];
extern CONST_DATA EventListScr EventScr_WholeTowerClear[];

extern CONST_DATA EventListScr EventScr_Prologue_BeginingScene[];
extern CONST_DATA EventListScr EventScr_Prologue_RenaisThroneCutscene[];
extern CONST_DATA EventListScr EventScr_Prologue_GiveRapier[];
extern CONST_DATA EventListScr EventScr_Prologue_ONeillSpawn[];
extern CONST_DATA EventListScr EventScr_Prologue_OneEmimyLeft[];
extern CONST_DATA EventListScr EventScr_Prologue_ONeillAttack[];
extern CONST_DATA EventListScr EventScr_Prologue_EndingScene[];
extern CONST_DATA EventListScr EventScr_Prologue_EirikaAttacked[];
extern CONST_DATA EventListScr EventScr_Prologue_Turn1[];
extern CONST_DATA EventListScr EventScr_Prologue_Turn2[];
extern CONST_DATA EventListScr EventScr_Prologue_Turn3[];
extern CONST_DATA EventListScr EventScr_Prologue_ExecTut[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial0[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial1[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial2[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial3[];
extern CONST_DATA EventListScr EventScr_Prologue_TutMessageTurn1[];
extern CONST_DATA EventListScr EventScr_Prologue_TutMessageTurn2[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial4[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial5[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial6[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial7[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial8[];
extern CONST_DATA EventListScr EventScr_Prologue_Tutorial9[];
extern CONST_DATA EventListScr EventScr_Prologue_OneillSethBattle[];
extern CONST_DATA EventListScr EventScr_Prologue_TutEirikaAttack[];
extern CONST_DATA EventListScr EventScr_Prologue_TutorialA[];
extern CONST_DATA EventListScr EventScr_Prologue_TutorialB[];
extern CONST_DATA EventListScr EventScr_Prologue_TutorialC[];
extern CONST_DATA EventListScr EventScr_Prologue_TutorialD[];
extern CONST_DATA EventListScr EventScr_Prologue_TutorialE[];
extern CONST_DATA EventListScr EventScr_Prologue_9EF828[];
extern CONST_DATA EventListScr EventScr_Ch1_BeginingScene[];
extern CONST_DATA EventListScr EventScr_Ch1_Turn1Player[];
extern CONST_DATA EventListScr EventScr_Ch1_Turn1Enemy[];
extern CONST_DATA EventListScr EventScr_Ch1_Turn_AllyReinforceArrive[];
extern CONST_DATA EventListScr EventScr_Ch1_Misc_DefeatBoss[];
extern CONST_DATA EventListScr EventScr_Ch1_EndingScene[];
extern CONST_DATA EventListScr EventScr_Ch1_Talk_SethFranz[];
extern CONST_DATA EventListScr EventScr_Ch1_Talk_EirikaFranz[];
extern CONST_DATA EventListScr EventScr_Ch1_Loca_Visit1[];
extern CONST_DATA EventListScr EventScr_Ch1_Loca_Visit2[];
extern CONST_DATA EventListScr EventScr_Ch1_Misc_Area[];
extern CONST_DATA EventListScr EventScr_Ch1_Turn_EnemyReinforceArrive[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_GuideWTA[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_EirikaVisitHouseIdle1[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_EirikaVisitHouseIdle2[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_EirikaVisitHouseEnd[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_GuideTerrainHeal[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_OnBeginning[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_GuideMsg944[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_GilliamBattle[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_TradeSelectGalliamIdle1[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_TradeSelectGalliamIdle2[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_TradeSelectGalliamEnd[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_AfterTrade[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_PostTradeAndItemUseAction[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_GuideMsgSeize[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_ChooseSethTurn1[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_SethMoveToEnemy[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_BeforeSethMoveToEnemy[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_AfterSethMoveToEnemy[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_GuideOnBKSEL[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_AfterSethBattleEirikaVisit[];
extern CONST_DATA EventListScr EventScr_Ch1Tut_MsgOnGuideOption[];

extern CONST_DATA EventListScr EventScr_Ch2_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089F0484[];
extern CONST_DATA EventListScr EventScr_089F049C[];
extern CONST_DATA EventListScr EventScr_089F04B4[];
extern CONST_DATA EventListScr EventScr_089F05FC[];
extern CONST_DATA EventListScr EventScr_089F0628[];
extern CONST_DATA EventListScr EventScr_089F0650[];
extern CONST_DATA EventListScr EventScr_089F06D0[];
extern CONST_DATA EventListScr EventScr_089F070C[];
extern CONST_DATA EventListScr EventScr_089F0748[];
extern CONST_DATA EventListScr EventScr_089F0770[];
extern CONST_DATA EventListScr EventScr_089F0790[];
extern CONST_DATA EventListScr EventScr_089F07B0[];
extern CONST_DATA EventListScr EventScr_089F07D0[];
extern CONST_DATA EventListScr EventScr_089F0808[];
extern CONST_DATA EventListScr EventScr_089F0880[];
extern CONST_DATA EventListScr EventScr_089F08E0[];
extern CONST_DATA EventListScr EventScr_089F0910[];
extern CONST_DATA EventListScr EventScr_089F096C[];
extern CONST_DATA EventListScr EventScr_089F09C8[];
extern CONST_DATA EventListScr EventScr_089F09D8[];
extern CONST_DATA EventListScr EventScr_089F09F0[];
extern CONST_DATA EventListScr EventScr_089F0A28[];
extern CONST_DATA EventListScr EventScr_089F0AA0[];
extern CONST_DATA EventListScr EventScr_089F0B00[];
extern CONST_DATA EventListScr EventScr_089F0B10[];
extern CONST_DATA EventListScr EventScr_089F0B68[];
extern CONST_DATA EventListScr EventScr_089F0BE0[];
extern CONST_DATA EventListScr EventScr_089F0C40[];
extern CONST_DATA EventListScr EventScr_089F0C70[];
extern CONST_DATA EventListScr EventScr_089F0C98[];
extern CONST_DATA EventListScr EventScr_089F0CCC[];
extern CONST_DATA EventListScr EventScr_089F0D48[];
extern CONST_DATA EventListScr EventScr_089F0DA8[];
extern CONST_DATA EventListScr EventScr_089F0DB8[];
extern CONST_DATA EventListScr EventScr_089F0E14[];
extern CONST_DATA EventListScr EventScr_089F0E70[];
extern CONST_DATA EventListScr EventScr_089F0E80[];
extern CONST_DATA EventListScr EventScr_089F0E98[];
extern CONST_DATA EventListScr EventScr_089F0ED4[];
extern CONST_DATA EventListScr EventScr_089F0F54[];
extern CONST_DATA EventListScr EventScr_089F0F74[];
extern CONST_DATA EventListScr EventScr_089F0FA4[];
extern CONST_DATA EventListScr EventScr_089F0FEC[];
extern CONST_DATA EventListScr EventScr_089F1028[];
extern CONST_DATA EventListScr EventScr_089F10A4[];
extern CONST_DATA EventListScr EventScr_089F1104[];
extern CONST_DATA EventListScr EventScr_089F1134[];
extern CONST_DATA EventListScr EventScr_089F1154[];
extern CONST_DATA EventListScr EventScr_089F1194[];
extern CONST_DATA EventListScr EventScr_089F11B8[];
extern CONST_DATA EventListScr EventScr_Ch3_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089F134C[];
extern CONST_DATA EventListScr EventScr_089F13B4[];
extern CONST_DATA EventListScr EventScr_089F13CC[];
extern CONST_DATA EventListScr EventScr_089F1568[];
extern CONST_DATA EventListScr EventScr_089F15A0[];
extern CONST_DATA EventListScr EventScr_089F1658[];
extern CONST_DATA EventListScr EventScr_089F1690[];
extern CONST_DATA EventListScr EventScr_089F16B0[];
extern CONST_DATA EventListScr EventScr_089F16CC[];
extern CONST_DATA EventListScr EventScr_089F16EC[];
extern CONST_DATA EventListScr EventScr_089F1760[];
extern CONST_DATA EventListScr EventScr_089F1784[];
extern CONST_DATA EventListScr EventScr_Ch4_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089F199C[];
extern CONST_DATA EventListScr EventScr_089F19F8[];
extern CONST_DATA EventListScr EventScr_089F1B38[];
extern CONST_DATA EventListScr EventScr_089F1BD8[];
extern CONST_DATA EventListScr EventScr_089F1C14[];
extern CONST_DATA EventListScr EventScr_089F1C2C[];
extern CONST_DATA EventListScr EventScr_089F1C48[];
extern CONST_DATA EventListScr EventScr_089F1C60[];
extern CONST_DATA EventListScr EventScr_089F1C80[];
extern CONST_DATA EventListScr EventScr_089F1CA4[];
extern CONST_DATA EventListScr EventScr_089F1CC4[];
extern CONST_DATA EventListScr EventScr_Ch5_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089F2090[];
extern CONST_DATA EventListScr EventScr_089F2170[];
extern CONST_DATA EventListScr EventScr_089F21BC[];
extern CONST_DATA EventListScr EventScr_089F21F8[];
extern CONST_DATA EventListScr EventScr_089F2234[];
extern CONST_DATA EventListScr EventScr_089F2270[];
extern CONST_DATA EventListScr EventScr_089F22A4[];
extern CONST_DATA EventListScr EventScr_089F22EC[];
extern CONST_DATA EventListScr EventScr_089F2304[];
extern CONST_DATA EventListScr EventScr_089F231C[];
extern CONST_DATA EventListScr EventScr_089F2340[];
extern CONST_DATA EventListScr EventScr_089F2360[];
extern CONST_DATA EventListScr EventScr_089F23B4[];
extern CONST_DATA EventListScr EventScr_Ch5x_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089F25FC[];
extern CONST_DATA EventListScr EventScr_Ch6_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089F2940[];
extern CONST_DATA EventListScr EventScr_089F29FC[];
extern CONST_DATA EventListScr EventScr_089F2A98[];
extern CONST_DATA EventListScr EventScr_089F2AE4[];
extern CONST_DATA EventListScr EventScr_089F2B54[];
extern CONST_DATA EventListScr EventScr_089F2B74[];
extern CONST_DATA EventListScr EventScr_Ch7_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089F2CFC[];
extern CONST_DATA EventListScr EventScr_089F2D28[];
extern CONST_DATA EventListScr EventScr_089F2E6C[];
extern CONST_DATA EventListScr EventScr_089F2E94[];
extern CONST_DATA EventListScr EventScr_089F2EBC[];
extern CONST_DATA EventListScr EventScr_Ch8_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089F3124[];
extern CONST_DATA EventListScr EventScr_089F318C[];
extern CONST_DATA EventListScr EventScr_089F31B8[];
extern CONST_DATA EventListScr EventScr_089F31D4[];
extern CONST_DATA EventListScr EventScr_089F31F4[];
extern CONST_DATA EventListScr EventScr_089F3214[];
extern CONST_DATA EventListScr EventScr_Ch8_MiscThiefRainforce[];
extern CONST_DATA EventListScr EventScr_089F3250[];
extern CONST_DATA EventListScr EventScr_089F3268[];
extern CONST_DATA EventListScr EventScr_089F3280[];
extern CONST_DATA EventListScr EventScr_SplitMenu[];
extern CONST_DATA EventListScr EventScr_089F35FC[];
extern CONST_DATA EventListScr EventScr_Ch8_TowerFall[];
extern CONST_DATA EventListScr EventScr_089F36FC[];
extern CONST_DATA EventListScr EventScr_089F3880[];
extern CONST_DATA EventListScr EventScr_Ch9_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089F3C34[];
extern CONST_DATA EventListScr EventScr_089F3DB8[];
extern CONST_DATA EventListScr EventScr_089F3F4C[];
extern CONST_DATA EventListScr EventScr_089F3F74[];
extern CONST_DATA EventListScr EventScr_089F3F9C[];
extern CONST_DATA EventListScr EventScr_089F3FDC[];
extern CONST_DATA EventListScr EventScr_089F4018[];
extern CONST_DATA EventListScr EventScr_089F40AC[];
extern CONST_DATA EventListScr EventScr_089F40B8[];
extern CONST_DATA EventListScr EventScr_089F40D0[];
extern CONST_DATA EventListScr EventScr_089F40E8[];
extern CONST_DATA EventListScr EventScr_089F4100[];
extern CONST_DATA EventListScr EventScr_089F4118[];
extern CONST_DATA EventListScr EventScr_089F4130[];
extern CONST_DATA EventListScr EventScr_089F4148[];
extern CONST_DATA EventListScr EventScr_089F4184[];
extern CONST_DATA EventListScr EventScr_089F419C[];
extern CONST_DATA EventListScr EventScr_089F43A0[];
extern CONST_DATA EventListScr EventScr_089F43F8[];
extern CONST_DATA EventListScr EventScr_089F4634[];
extern CONST_DATA EventListScr EventScr_089F465C[];
extern CONST_DATA EventListScr EventScr_089F4684[];
extern CONST_DATA EventListScr EventScr_089F46AC[];
extern CONST_DATA EventListScr EventScr_089F46D4[];
extern CONST_DATA EventListScr EventScr_089F46FC[];
extern CONST_DATA EventListScr EventScr_089F4724[];
extern CONST_DATA EventListScr EventScr_089F4750[];
extern CONST_DATA EventListScr EventScr_089F47A8[];
extern CONST_DATA EventListScr EventScr_089F47D0[];
extern CONST_DATA EventListScr EventScr_089F47F8[];
extern CONST_DATA EventListScr EventScr_089F4820[];
extern CONST_DATA EventListScr EventScr_089F4838[];
extern CONST_DATA EventListScr EventScr_089F48CC[];
extern CONST_DATA EventListScr EventScr_089F48F8[];
extern CONST_DATA EventListScr EventScr_089F4A7C[];
extern CONST_DATA EventListScr EventScr_089F4E54[];
extern CONST_DATA EventListScr EventScr_089F4E7C[];
extern CONST_DATA EventListScr EventScr_089F4EA4[];
extern CONST_DATA EventListScr EventScr_089F4EBC[];
extern CONST_DATA EventListScr EventScr_089F4EE0[];
extern CONST_DATA EventListScr EventScr_089F4F1C[];
extern CONST_DATA EventListScr EventScr_089F4F40[];
extern CONST_DATA EventListScr EventScr_089F4F58[];
extern CONST_DATA EventListScr EventScr_089F4F70[];
extern CONST_DATA EventListScr EventScr_089F4F88[];
extern CONST_DATA EventListScr EventScr_089F51B0[];
extern CONST_DATA EventListScr EventScr_089F536C[];
extern CONST_DATA EventListScr EventScr_089F53AC[];
extern CONST_DATA EventListScr EventScr_089F5484[];
extern CONST_DATA EventListScr EventScr_089F54A0[];
extern CONST_DATA EventListScr EventScr_089F54C8[];
extern CONST_DATA EventListScr EventScr_089F54E4[];
extern CONST_DATA EventListScr EventScr_089F552C[];
extern CONST_DATA EventListScr EventScr_089F5798[];
extern CONST_DATA EventListScr EventScr_089F59CC[];
extern CONST_DATA EventListScr EventScr_089F59F8[];
extern CONST_DATA EventListScr EventScr_089F5A20[];
extern CONST_DATA EventListScr EventScr_089F5A48[];
extern CONST_DATA EventListScr EventScr_089F5A90[];
extern CONST_DATA EventListScr EventScr_089F5AD4[];
extern CONST_DATA EventListScr EventScr_089F5AEC[];
extern CONST_DATA EventListScr EventScr_089F5B04[];
extern CONST_DATA EventListScr EventScr_089F5B3C[];
extern CONST_DATA EventListScr EventScr_089F5CC4[];
extern CONST_DATA EventListScr EventScr_089F5DB8[];
extern CONST_DATA EventListScr EventScr_089F619C[];
extern CONST_DATA EventListScr EventScr_089F61C4[];
extern CONST_DATA EventListScr EventScr_089F6238[];
extern CONST_DATA EventListScr EventScr_089F6250[];
extern CONST_DATA EventListScr EventScr_089F6268[];
extern CONST_DATA EventListScr EventScr_089F6284[];
extern CONST_DATA EventListScr EventScr_089F629C[];
extern CONST_DATA EventListScr EventScr_089F62BC[];
extern CONST_DATA EventListScr EventScr_089F62F0[];
extern CONST_DATA EventListScr EventScr_089F6344[];
extern CONST_DATA EventListScr EventScr_089F6404[];
extern CONST_DATA EventListScr EventScr_089F6470[];
extern CONST_DATA EventListScr EventScr_089F6484[];
extern CONST_DATA EventListScr EventScr_089F65C8[];
extern CONST_DATA EventListScr EventScr_089F6604[];
extern CONST_DATA EventListScr EventScr_089F662C[];
extern CONST_DATA EventListScr EventScr_089F6654[];
extern CONST_DATA EventListScr EventScr_089F6678[];
extern CONST_DATA EventListScr EventScr_089F6698[];
extern CONST_DATA EventListScr EventScr_089F66B8[];
extern CONST_DATA EventListScr EventScr_089F66D8[];
extern CONST_DATA EventListScr EventScr_089F66F8[];
extern CONST_DATA EventListScr EventScr_089F6718[];
extern CONST_DATA EventListScr EventScr_089F6730[];
extern CONST_DATA EventListScr EventScr_089F6748[];
extern CONST_DATA EventListScr EventScr_089F6770[];
extern CONST_DATA EventListScr EventScr_089F6788[];
extern CONST_DATA EventListScr EventScr_089F67A0[];
extern CONST_DATA EventListScr EventScr_089F67D0[];
extern CONST_DATA EventListScr EventScr_089F6814[];
extern CONST_DATA EventListScr EventScr_089F6858[];
extern CONST_DATA EventListScr EventScr_089F689C[];
extern CONST_DATA EventListScr EventScr_089F68E0[];
extern CONST_DATA EventListScr EventScr_089F6924[];
extern CONST_DATA EventListScr EventScr_089F6968[];
extern CONST_DATA EventListScr EventScr_089F69AC[];
extern CONST_DATA EventListScr EventScr_089F69F0[];
extern CONST_DATA EventListScr EventScr_089F6A34[];
extern CONST_DATA EventListScr EventScr_089F6A8C[];
extern CONST_DATA EventListScr EventScr_089F6E40[];
extern CONST_DATA EventListScr EventScr_089F6E50[];
extern CONST_DATA EventListScr EventScr_089F731C[];
extern CONST_DATA EventListScr EventScr_089F7378[];
extern CONST_DATA EventListScr EventScr_089F73F0[];
extern CONST_DATA EventListScr EventScr_089F7470[];
extern CONST_DATA EventListScr EventScr_089F74F0[];
extern CONST_DATA EventListScr EventScr_089F7524[];
extern CONST_DATA EventListScr EventScr_089F7558[];
extern CONST_DATA EventListScr EventScr_089F7570[];
extern CONST_DATA EventListScr EventScr_089F75A4[];
extern CONST_DATA EventListScr EventScr_089F75F0[];
extern CONST_DATA EventListScr EventScr_089F7608[];
extern CONST_DATA EventListScr EventScr_089F7620[];
extern CONST_DATA EventListScr EventScr_089F782C[];
extern CONST_DATA EventListScr EventScr_089F79C4[];
extern CONST_DATA EventListScr EventScr_089F79D4[];
extern CONST_DATA EventListScr EventScr_089F7CAC[];
extern CONST_DATA EventListScr EventScr_089F7CD4[];
extern CONST_DATA EventListScr EventScr_089F7CFC[];
extern CONST_DATA EventListScr EventScr_089F7D24[];
extern CONST_DATA EventListScr EventScr_089F7D3C[];
extern CONST_DATA EventListScr EventScr_089F7D54[];
extern CONST_DATA EventListScr EventScr_089F7D6C[];
extern CONST_DATA EventListScr EventScr_089F7D84[];
extern CONST_DATA EventListScr EventScr_089F7DA4[];
extern CONST_DATA EventListScr EventScr_089F7DD8[];
extern CONST_DATA EventListScr EventScr_089F7E3C[];
extern CONST_DATA EventListScr EventScr_089F7E6C[];
extern CONST_DATA EventListScr EventScr_089F7F88[];
extern CONST_DATA EventListScr EventScr_089F81BC[];
extern CONST_DATA EventListScr EventScr_089F81D8[];
extern CONST_DATA EventListScr EventScr_089F81E4[];
extern CONST_DATA EventListScr EventScr_089F8200[];
extern CONST_DATA EventListScr EventScr_089F8218[];
extern CONST_DATA EventListScr EventScr_089F8234[];
extern CONST_DATA EventListScr EventScr_089F824C[];
extern CONST_DATA EventListScr EventScr_089F8268[];
extern CONST_DATA EventListScr EventScr_089F8290[];
extern CONST_DATA EventListScr EventScr_089F82AC[];
extern CONST_DATA EventListScr EventScr_089F82D4[];
extern CONST_DATA EventListScr EventScr_089F82FC[];
extern CONST_DATA EventListScr EventScr_089F8644[];
extern CONST_DATA EventListScr EventScr_089F8678[];
extern CONST_DATA EventListScr EventScr_089F8688[];
extern CONST_DATA EventListScr EventScr_089F893C[];
extern CONST_DATA EventListScr EventScr_089F8954[];
extern CONST_DATA EventListScr EventScr_089F896C[];
extern CONST_DATA EventListScr EventScr_089F89A0[];
extern CONST_DATA EventListScr EventScr_089F89D4[];
extern CONST_DATA EventListScr EventScr_089F8A08[];
extern CONST_DATA EventListScr EventScr_089F8A3C[];
extern CONST_DATA EventListScr EventScr_089F8A54[];
extern CONST_DATA EventListScr EventScr_089F8A6C[];
extern CONST_DATA EventListScr EventScr_089F8AC8[];
extern CONST_DATA EventListScr EventScr_089F8C60[];
extern CONST_DATA EventListScr EventScr_089F8C8C[];
extern CONST_DATA EventListScr EventScr_089F8CCC[];
extern CONST_DATA EventListScr EventScr_089F8D9C[];
extern CONST_DATA EventListScr EventScr_089F8DE0[];
extern CONST_DATA EventListScr EventScr_089F8E24[];
extern CONST_DATA EventListScr EventScr_089F8E44[];
extern CONST_DATA EventListScr EventScr_089F8E78[];
extern CONST_DATA EventListScr EventScr_089F8E98[];
extern CONST_DATA EventListScr EventScr_089F8F00[];
extern CONST_DATA EventListScr EventScr_089F8F20[];
extern CONST_DATA EventListScr EventScr_089F8F88[];
extern CONST_DATA EventListScr EventScr_089F8FA8[];
extern CONST_DATA EventListScr EventScr_089F9064[];
extern CONST_DATA EventListScr EventScr_089F90C8[];
extern CONST_DATA EventListScr EventScr_089F90E0[];
extern CONST_DATA EventListScr EventScr_089F9144[];
extern CONST_DATA EventListScr EventScr_089F92A0[];
extern CONST_DATA EventListScr EventScr_089F9314[];
extern CONST_DATA EventListScr EventScr_089F9380[];
extern CONST_DATA EventListScr EventScr_089F93A0[];
extern CONST_DATA EventListScr EventScr_089F93D4[];
extern CONST_DATA EventListScr EventScr_089F93F4[];
extern CONST_DATA EventListScr EventScr_089F9428[];
extern CONST_DATA EventListScr EventScr_089F9448[];
extern CONST_DATA EventListScr EventScr_089F947C[];
extern CONST_DATA EventListScr EventScr_089F94A0[];
extern CONST_DATA EventListScr EventScr_089F94AC[];
extern CONST_DATA EventListScr EventScr_089F9F10[];
extern CONST_DATA EventListScr EventScr_089F9F20[];
extern CONST_DATA EventListScr EventScr_089FA138[];
extern CONST_DATA EventListScr EventScr_089FA4E0[];
extern CONST_DATA EventListScr EventScr_089FA634[];
extern CONST_DATA EventListScr EventScr_089FA65C[];
extern CONST_DATA EventListScr EventScr_089FA690[];
extern CONST_DATA EventListScr EventScr_089FA6B4[];
extern CONST_DATA EventListScr EventScr_089FA6E0[];
extern CONST_DATA EventListScr EventScr_089FA714[];
extern CONST_DATA EventListScr EventScr_089FA734[];
extern CONST_DATA EventListScr EventScr_089FA768[];
extern CONST_DATA EventListScr EventScr_089FA778[];
extern CONST_DATA EventListScr EventScr_089FA7AC[];
extern CONST_DATA EventListScr EventScr_089FA7EC[];
extern CONST_DATA EventListScr EventScr_089FA820[];
extern CONST_DATA EventListScr EventScr_089FAAC4[];
extern CONST_DATA EventListScr EventScr_089FAB7C[];
extern CONST_DATA EventListScr EventScr_089FABD0[];
extern CONST_DATA EventListScr EventScr_089FAC20[];
extern CONST_DATA EventListScr EventScr_089FAEDC[];
extern CONST_DATA EventListScr EventScr_089FAF04[];
extern CONST_DATA EventListScr EventScr_089FAF2C[];
extern CONST_DATA EventListScr EventScr_089FAF54[];
extern CONST_DATA EventListScr EventScr_089FAF90[];
extern CONST_DATA EventListScr EventScr_089FAFCC[];
extern CONST_DATA EventListScr EventScr_089FAFF4[];
extern CONST_DATA EventListScr EventScr_089FB01C[];
extern CONST_DATA EventListScr EventScr_089FB034[];
extern CONST_DATA EventListScr EventScr_089FB05C[];
extern CONST_DATA EventListScr EventScr_089FB084[];
extern CONST_DATA EventListScr EventScr_089FB1E4[];
extern CONST_DATA EventListScr EventScr_089FB250[];
extern CONST_DATA EventListScr EventScr_089FB294[];
extern CONST_DATA EventListScr EventScr_089FB318[];
extern CONST_DATA EventListScr EventScr_089FB394[];
extern CONST_DATA EventListScr EventScr_089FB3BC[];
extern CONST_DATA EventListScr EventScr_089FB3E4[];
extern CONST_DATA EventListScr EventScr_089FB3FC[];
extern CONST_DATA EventListScr EventScr_089FB444[];
extern CONST_DATA EventListScr EventScr_089FB458[];
extern CONST_DATA EventListScr EventScr_089FB480[];
extern CONST_DATA EventListScr EventScr_089FB4A8[];
extern CONST_DATA EventListScr EventScr_089FB4D4[];
extern CONST_DATA EventListScr EventScr_089FB64C[];
extern CONST_DATA EventListScr EventScr_089FB678[];
extern CONST_DATA EventListScr EventScr_089FB770[];
extern CONST_DATA EventListScr EventScr_089FB90C[];
extern CONST_DATA EventListScr EventScr_089FB934[];
extern CONST_DATA EventListScr EventScr_089FB970[];
extern CONST_DATA EventListScr EventScr_089FB998[];
extern CONST_DATA EventListScr EventScr_089FB9B0[];
extern CONST_DATA EventListScr EventScr_089FB9C8[];
extern CONST_DATA EventListScr EventScr_089FB9E0[];
extern CONST_DATA EventListScr EventScr_089FB9F8[];
extern CONST_DATA EventListScr EventScr_089FBC0C[];
extern CONST_DATA EventListScr EventScr_089FBC8C[];
extern CONST_DATA EventListScr EventScr_089FBCDC[];
extern CONST_DATA EventListScr EventScr_089FBD2C[];
extern CONST_DATA EventListScr EventScr_089FBD50[];
extern CONST_DATA EventListScr EventScr_089FBD70[];
extern CONST_DATA EventListScr EventScr_089FBD90[];
extern CONST_DATA EventListScr EventScr_089FBDCC[];
extern CONST_DATA EventListScr EventScr_089FBE08[];
extern CONST_DATA EventListScr EventScr_089FBE20[];
extern CONST_DATA EventListScr EventScr_089FBE38[];
extern CONST_DATA EventListScr EventScr_089FBE50[];
extern CONST_DATA EventListScr EventScr_089FBE68[];
extern CONST_DATA EventListScr EventScr_089FBE7C[];
extern CONST_DATA EventListScr EventScr_089FC04C[];
extern CONST_DATA EventListScr EventScr_089FC06C[];
extern CONST_DATA EventListScr EventScr_089FC520[];
extern CONST_DATA EventListScr EventScr_089FC52C[];
extern CONST_DATA EventListScr EventScr_089FC5A0[];
extern CONST_DATA EventListScr EventScr_089FC5C0[];
extern CONST_DATA EventListScr EventScr_089FC5E8[];
extern CONST_DATA EventListScr EventScr_089FC610[];
extern CONST_DATA EventListScr EventScr_089FC638[];
extern CONST_DATA EventListScr EventScr_089FC660[];
extern CONST_DATA EventListScr EventScr_089FC690[];
extern CONST_DATA EventListScr EventScr_089FC6C4[];
extern CONST_DATA EventListScr EventScr_089FC6EC[];
extern CONST_DATA EventListScr EventScr_089FC6FC[];
extern CONST_DATA EventListScr EventScr_089FC740[];
extern CONST_DATA EventListScr EventScr_089FC8F0[];
extern CONST_DATA EventListScr EventScr_089FC904[];
extern CONST_DATA EventListScr EventScr_089FC940[];
extern CONST_DATA EventListScr EventScr_089FC968[];
extern CONST_DATA EventListScr EventScr_089FC990[];
extern CONST_DATA EventListScr EventScr_089FC9B4[];
extern CONST_DATA EventListScr EventScr_089FC9D4[];
extern CONST_DATA EventListScr EventScr_089FC9F4[];
extern CONST_DATA EventListScr EventScr_089FCA14[];
extern CONST_DATA EventListScr EventScr_089FCA34[];
extern CONST_DATA EventListScr EventScr_089FCA4C[];
extern CONST_DATA EventListScr EventScr_089FCA64[];
extern CONST_DATA EventListScr EventScr_089FCA7C[];
extern CONST_DATA EventListScr EventScr_089FCA94[];
extern CONST_DATA EventListScr EventScr_089FCAAC[];
extern CONST_DATA EventListScr EventScr_089FCADC[];
extern CONST_DATA EventListScr EventScr_089FCB20[];
extern CONST_DATA EventListScr EventScr_089FCB64[];
extern CONST_DATA EventListScr EventScr_089FCBA8[];
extern CONST_DATA EventListScr EventScr_089FCBEC[];
extern CONST_DATA EventListScr EventScr_089FCC30[];
extern CONST_DATA EventListScr EventScr_089FCC74[];
extern CONST_DATA EventListScr EventScr_089FCCB8[];
extern CONST_DATA EventListScr EventScr_089FCCFC[];
extern CONST_DATA EventListScr EventScr_089FCD40[];
extern CONST_DATA EventListScr EventScr_089FCD98[];
extern CONST_DATA EventListScr EventScr_089FCDA8[];
extern CONST_DATA EventListScr EventScr_089FCDC0[];
extern CONST_DATA EventListScr EventScr_089FCDD8[];
extern CONST_DATA EventListScr EventScr_089FCE04[];
extern CONST_DATA EventListScr EventScr_089FCE48[];
extern CONST_DATA EventListScr EventScr_089FCE80[];
extern CONST_DATA EventListScr EventScr_089FCEC4[];
extern CONST_DATA EventListScr EventScr_089FCEDC[];
extern CONST_DATA EventListScr EventScr_089FCEEC[];
extern CONST_DATA EventListScr EventScr_089FCEF8[];
extern CONST_DATA EventListScr EventScr_089FCF04[];
extern CONST_DATA EventListScr EventScr_089FCF10[];
extern CONST_DATA EventListScr EventScr_089FCF28[];
extern CONST_DATA EventListScr EventScr_089FCF40[];
extern CONST_DATA EventListScr EventScr_089FCF58[];
extern CONST_DATA EventListScr EventScr_089FCF70[];
extern CONST_DATA EventListScr EventScr_089FCF90[];
extern CONST_DATA EventListScr EventScr_089FCFC4[];
extern CONST_DATA EventListScr EventScr_089FD028[];
extern CONST_DATA EventListScr EventScr_089FD068[];
extern CONST_DATA EventListScr EventScr_089FD268[];
extern CONST_DATA EventListScr EventScr_089FD284[];
extern CONST_DATA EventListScr EventScr_089FD290[];
extern CONST_DATA EventListScr EventScr_089FD2AC[];
extern CONST_DATA EventListScr EventScr_089FD2C4[];
extern CONST_DATA EventListScr EventScr_089FD2E0[];
extern CONST_DATA EventListScr EventScr_089FD2F8[];
extern CONST_DATA EventListScr EventScr_089FD314[];
extern CONST_DATA EventListScr EventScr_089FD33C[];
extern CONST_DATA EventListScr EventScr_089FD358[];
extern CONST_DATA EventListScr EventScr_089FD380[];
extern CONST_DATA EventListScr EventScr_089FD3A8[];
extern CONST_DATA EventListScr EventScr_089FD3DC[];
extern CONST_DATA EventListScr EventScr_089FD3EC[];
extern CONST_DATA EventListScr EventScr_089FD404[];
extern CONST_DATA EventListScr EventScr_089FD41C[];
extern CONST_DATA EventListScr EventScr_089FD450[];
extern CONST_DATA EventListScr EventScr_089FD484[];
extern CONST_DATA EventListScr EventScr_089FD4B8[];
extern CONST_DATA EventListScr EventScr_089FD4EC[];
extern CONST_DATA EventListScr EventScr_089FD504[];
extern CONST_DATA EventListScr EventScr_089FD51C[];
extern CONST_DATA EventListScr EventScr_089FD578[];
extern CONST_DATA EventListScr EventScr_089FD584[];
extern CONST_DATA EventListScr EventScr_089FD630[];
extern CONST_DATA EventListScr EventScr_089FD674[];
extern CONST_DATA EventListScr EventScr_089FD6B8[];
extern CONST_DATA EventListScr EventScr_089FD6D8[];
extern CONST_DATA EventListScr EventScr_089FD70C[];
extern CONST_DATA EventListScr EventScr_089FD72C[];
extern CONST_DATA EventListScr EventScr_089FD794[];
extern CONST_DATA EventListScr EventScr_089FD7B4[];
extern CONST_DATA EventListScr EventScr_089FD81C[];
extern CONST_DATA EventListScr EventScr_089FD83C[];
extern CONST_DATA EventListScr EventScr_089FD8F8[];
extern CONST_DATA EventListScr EventScr_089FD95C[];
extern CONST_DATA EventListScr EventScr_089FD974[];
extern CONST_DATA EventListScr EventScr_089FD9B8[];
extern CONST_DATA EventListScr EventScr_089FDA2C[];
extern CONST_DATA EventListScr EventScr_089FDA4C[];
extern CONST_DATA EventListScr EventScr_089FDA80[];
extern CONST_DATA EventListScr EventScr_089FDAA0[];
extern CONST_DATA EventListScr EventScr_089FDAD4[];
extern CONST_DATA EventListScr EventScr_089FDAF4[];
extern CONST_DATA EventListScr EventScr_089FDB28[];
extern CONST_DATA EventListScr EventScr_Ch21x_BeginingScene[];
extern CONST_DATA EventListScr EventScr_089FDB58[];
extern CONST_DATA EventListScr EventScr_089FDB68[];
extern CONST_DATA EventListScr EventScr_089FDBE4[];
extern CONST_DATA EventListScr EventScr_089FDC18[];
extern CONST_DATA EventListScr EventScr_089FDC90[];
extern CONST_DATA EventListScr EventScr_089FDCC4[];
extern CONST_DATA EventListScr EventScr_089FDCF8[];
extern CONST_DATA EventListScr EventScr_089FDD10[];
extern CONST_DATA EventListScr EventScr_089FDD84[];
extern CONST_DATA EventListScr EventScr_089FDDC8[];
extern CONST_DATA EventListScr EventScr_089FDE3C[];
extern CONST_DATA EventListScr EventScr_089FDE70[];
extern CONST_DATA EventListScr EventScr_089FDEE4[];
extern CONST_DATA EventListScr EventScr_089FDF18[];
extern CONST_DATA EventListScr EventScr_089FDF30[];
extern CONST_DATA EventListScr EventScr_089FDFA4[];
extern CONST_DATA EventListScr EventScr_089FDFE8[];
extern CONST_DATA EventListScr EventScr_089FE068[];
extern CONST_DATA EventListScr EventScr_089FE09C[];
extern CONST_DATA EventListScr EventScr_089FE0C4[];
extern CONST_DATA EventListScr EventScr_089FE0EC[];
extern CONST_DATA EventListScr EventScr_089FE118[];
extern CONST_DATA EventListScr EventScr_089FE144[];
extern CONST_DATA EventListScr EventScr_089FE170[];
extern CONST_DATA EventListScr EventScr_089FE188[];
extern CONST_DATA EventListScr EventScr_089FE1A0[];
extern CONST_DATA EventListScr EventScr_089FE1B8[];
extern CONST_DATA EventListScr EventScr_089FE22C[];
extern CONST_DATA EventListScr EventScr_089FE250[];
extern CONST_DATA EventListScr EventScr_089FE2CC[];
extern CONST_DATA EventListScr EventScr_089FE2E8[];
extern CONST_DATA EventListScr EventScr_089FE300[];
extern CONST_DATA EventListScr EventScr_089FE318[];
extern CONST_DATA EventListScr EventScr_089FE348[];
extern CONST_DATA EventListScr EventScr_089FE3BC[];
extern CONST_DATA EventListScr EventScr_089FE3D8[];
extern CONST_DATA EventListScr EventScr_089FE414[];
extern CONST_DATA EventListScr EventScr_089FE488[];
extern CONST_DATA EventListScr EventScr_089FE4A4[];
extern CONST_DATA EventListScr EventScr_089FE4BC[];
extern CONST_DATA EventListScr EventScr_089FE4D4[];
extern CONST_DATA EventListScr EventScr_089FE4EC[];
extern CONST_DATA EventListScr EventScr_089FE504[];
extern CONST_DATA EventListScr EventScr_089FE51C[];
extern CONST_DATA EventListScr EventScr_089FE590[];
extern CONST_DATA EventListScr EventScr_089FE5A8[];
extern CONST_DATA EventListScr EventScr_089FE5C0[];
extern CONST_DATA EventListScr EventScr_089FE5DC[];
extern CONST_DATA EventListScr EventScr_089FE650[];
extern CONST_DATA EventListScr EventScr_089FE67C[];
extern CONST_DATA EventListScr EventScr_089FE694[];
extern CONST_DATA EventListScr EventScr_089FE6AC[];
extern CONST_DATA EventListScr EventScr_089FE6C4[];
extern CONST_DATA EventListScr EventScr_089FE738[];
extern CONST_DATA EventListScr EventScr_089FE754[];
extern CONST_DATA EventListScr EventScr_089FE76C[];
extern CONST_DATA EventListScr EventScr_089FE784[];
extern CONST_DATA EventListScr EventScr_089FE79C[];
extern CONST_DATA EventListScr EventScr_089FE7B4[];
extern CONST_DATA EventListScr EventScr_089FE834[];
extern CONST_DATA EventListScr EventScr_089FE860[];
extern CONST_DATA EventListScr EventScr_089FE878[];
extern CONST_DATA EventListScr EventScr_089FE890[];
extern CONST_DATA EventListScr EventScr_089FE8A8[];
extern CONST_DATA EventListScr EventScr_089FE8C0[];
extern CONST_DATA EventListScr EventScr_089FE8E0[];
extern CONST_DATA EventListScr EventScr_089FE914[];
extern CONST_DATA EventListScr EventScr_089FE934[];
extern CONST_DATA EventListScr EventScr_089FE968[];
extern CONST_DATA EventListScr EventScr_089FE988[];
extern CONST_DATA EventListScr EventScr_089FE9BC[];
extern CONST_DATA EventListScr EventScr_089FE9D4[];
extern CONST_DATA EventListScr EventScr_089FEA58[];
extern CONST_DATA EventListScr EventScr_089FEA74[];
extern CONST_DATA EventListScr EventScr_089FEA94[];
extern CONST_DATA EventListScr EventScr_089FEAC8[];
extern CONST_DATA EventListScr EventScr_089FEAE8[];
extern CONST_DATA EventListScr EventScr_089FEB1C[];
extern CONST_DATA EventListScr EventScr_089FEB3C[];
extern CONST_DATA EventListScr EventScr_089FEB70[];
extern CONST_DATA EventListScr EventScr_089FEB9C[];
extern CONST_DATA EventListScr EventScr_089FEBD0[];
extern CONST_DATA EventListScr EventScr_089FEC40[];
extern CONST_DATA EventListScr EventScr_089FEC9C[];
extern CONST_DATA EventListScr EventScr_089FED30[];
extern CONST_DATA EventListScr EventScr_089FEDB0[];
extern CONST_DATA EventListScr EventScr_089FEE20[];
extern CONST_DATA EventListScr EventScr_089FEE7C[];
extern CONST_DATA EventListScr EventScr_089FEF14[];
extern CONST_DATA EventListScr EventScr_089FEF98[];
extern CONST_DATA EventListScr EventScr_089FF044[];
extern CONST_DATA EventListScr EventScr_089FF0DC[];
extern CONST_DATA EventListScr EventScr_089FF150[];
extern CONST_DATA EventListScr EventScr_089FF1B0[];
extern CONST_DATA EventListScr EventScr_089FF228[];
extern CONST_DATA EventListScr EventScr_089FF244[];
extern CONST_DATA EventListScr EventScr_089FF268[];
extern CONST_DATA EventListScr EventScr_089FF288[];
extern CONST_DATA EventListScr EventScr_089FF2BC[];
extern CONST_DATA EventListScr EventScr_089FF330[];
extern CONST_DATA EventListScr EventScr_089FF354[];
extern CONST_DATA EventListScr EventScr_089FF430[];
extern CONST_DATA EventListScr EventScr_089FF434[];
extern CONST_DATA EventListScr EventScr_089FF450[];
extern CONST_DATA EventListScr EventScr_089FF458[];
extern CONST_DATA EventListScr EventScr_089FF474[];
extern CONST_DATA EventListScr EventScr_089FF478[];
// extern CONST_DATA EventListScr gUnknown_089FF480[];
extern CONST_DATA EventListScr EventScr_089FF4B8[];
extern CONST_DATA EventListScr EventScr_089FF4D8[];
extern CONST_DATA EventListScr EventScr_089FF4E4[];
extern CONST_DATA EventListScr EventScr_089FF4F4[];
extern CONST_DATA EventListScr EventScr_089FFB38[];
extern CONST_DATA EventListScr EventScr_089FFB48[];
extern CONST_DATA EventListScr EventScr_089FFBA8[];
extern CONST_DATA EventListScr EventScr_089FFBB8[];
extern CONST_DATA EventListScr EventScr_089FFC0C[];
// extern CONST_DATA EventListScr EventScr_SkirmishCommonBeginning[];
// extern CONST_DATA EventListScr EventScr_SkirmishCommonEnd[];
extern CONST_DATA EventListScr EventScr_089FFE84[];
extern CONST_DATA EventListScr EventScr_089FFF08[];
extern CONST_DATA EventListScr EventScr_089FFF14[];
extern CONST_DATA EventListScr EventScr_089FFF80[];
extern CONST_DATA EventListScr EventScr_089FFF8C[];
extern CONST_DATA EventListScr EventScr_08A00028[];
extern CONST_DATA EventListScr EventScr_08A00034[];
extern CONST_DATA EventListScr EventScr_08A00094[];
extern CONST_DATA EventListScr EventScr_08A000A0[];
extern CONST_DATA EventListScr EventScr_08A00130[];
extern CONST_DATA EventListScr EventScr_08A0013C[];
extern CONST_DATA EventListScr EventScr_08A001A0[];
extern CONST_DATA EventListScr EventScr_08A001AC[];
extern CONST_DATA EventListScr EventScr_08A00254[];
extern CONST_DATA EventListScr EventScr_08A00260[];
extern CONST_DATA EventListScr EventScr_08A002E4[];
extern CONST_DATA EventListScr EventScr_08A002F0[];
extern CONST_DATA EventListScr EventScr_08A00350[];
// extern CONST_DATA EventListScr EventScr_8A0035C[];
// extern CONST_DATA EventListScr EventScr_8A00364[];
extern CONST_DATA EventListScr EventScr_08A0036C[];
// extern CONST_DATA EventListScr EventScr_EirikaModeGameEnd[];
// extern CONST_DATA EventListScr EventScr_EphraimModeGameEnd[];
extern CONST_DATA EventListScr EventScr_08A00544[];
extern CONST_DATA EventListScr EventScr_08A005B4[];
extern CONST_DATA EventListScr EventScr_08A0062C[];
extern CONST_DATA EventListScr EventScr_08A00680[];

extern CONST_DATA EventListScr EventScr_9FF488[];
extern CONST_DATA EventListScr EventScr_089FF4B8[];
extern CONST_DATA EventListScr EventScr_089FF4D8[];
extern CONST_DATA EventListScr EventScr_089FF4E4[];
extern CONST_DATA EventListScr EventScr_089FF4F4[];
extern CONST_DATA EventListScr EventScr_089FFB38[];
extern CONST_DATA EventListScr EventScr_089FFB48[];
extern CONST_DATA EventListScr EventScr_089FFBA8[];
extern CONST_DATA EventListScr EventScr_089FFBB8[];
extern CONST_DATA EventListScr EventScr_089FFC0C[];
extern CONST_DATA EventListScr EventScr_SkirmishCommonBeginning[];
extern CONST_DATA EventListScr EventScr_SkirmishCommonEnd[];
extern CONST_DATA EventListScr EventScr_089FFE84[];
extern CONST_DATA EventListScr EventScr_089FFF08[];
extern CONST_DATA EventListScr EventScr_089FFF14[];
extern CONST_DATA EventListScr EventScr_089FFF80[];
extern CONST_DATA EventListScr EventScr_089FFF8C[];
extern CONST_DATA EventListScr EventScr_08A00028[];
extern CONST_DATA EventListScr EventScr_08A00034[];
extern CONST_DATA EventListScr EventScr_08A00094[];
extern CONST_DATA EventListScr EventScr_08A000A0[];
extern CONST_DATA EventListScr EventScr_08A00130[];
extern CONST_DATA EventListScr EventScr_08A0013C[];
extern CONST_DATA EventListScr EventScr_08A001A0[];
extern CONST_DATA EventListScr EventScr_08A001AC[];
extern CONST_DATA EventListScr EventScr_08A00254[];
extern CONST_DATA EventListScr EventScr_08A00260[];
extern CONST_DATA EventListScr EventScr_08A002E4[];
extern CONST_DATA EventListScr EventScr_08A002F0[];
extern CONST_DATA EventListScr EventScr_08A00350[];
extern CONST_DATA EventListScr EventScr_8A0035C[];
extern CONST_DATA EventListScr EventScr_8A00364[];
extern CONST_DATA EventListScr EventScr_08A0036C[];
extern CONST_DATA EventListScr EventScr_EirikaModeGameEnd[];
extern CONST_DATA EventListScr EventScr_EphraimModeGameEnd[];
extern CONST_DATA EventListScr EventScr_08A00544[];
extern CONST_DATA EventListScr EventScr_08A005B4[];
extern CONST_DATA EventListScr EventScr_08A0062C[];
extern CONST_DATA EventListScr EventScr_08A00680[];


extern struct UnitDefinition UnitDef_Event_PrologueAlly[];
extern struct UnitDefinition UnitDef_Event_PrologueEnemy[];
extern struct UnitDefinition UnitDef_Event_PrologueThroneRoomUnits[];
extern struct UnitDefinition UnitDef_Event_PrologueMessager[];
extern struct UnitDefinition UnitDef_Event_PrologueGradoRoyals[];
extern struct UnitDefinition UnitDef_Event_PrologueGradoShamans[];
extern struct UnitDefinition UnitDef_Event_PrologueGradoCavalry[];
extern struct UnitDefinition UnitDef_Event_PrologueEscapees[];
extern struct UnitDefinition UnitDef_Event_PrologueValterGroup[];
extern struct UnitDefinition UnitDef_Event_Ch1Ally[];
extern struct UnitDefinition UnitDef_Event_Ch1Enemy[];
extern struct UnitDefinition UnitDef_Event_Ch1AllyReinforce[];
extern struct UnitDefinition UnitDef_Event_Ch1EnemyReinforce[];
extern struct UnitDefinition UnitDef_Event_Ch1NPC[];
