OBJ_ROT_SCALE_ON        = (1<<8)
OBJ_DISABLE             = (1<<9)
OBJ_MODE_1              = (1<<10)
OBJ_MODE_2              = (2<<10)
OBJ_MODE_3              = (3<<10)
ATTR0_MOSAIC            = (1<<12)
ATTR0_COLOR_256         = (1<<13)
ATTR0_COLOR_16          = (0<<13)
ATTR0_TYPE_NORMAL       = (0<<10)
ATTR0_TYPE_BLENDED      = (1<<10)
ATTR0_TYPE_WINDOWED     = (2<<10)
ATTR0_NORMAL            = (0<<8)
ATTR0_ROTSCALE          = (1<<8)
ATTR0_DISABLED          = (2<<8)
ATTR0_ROTSCALE_DOUBLE   = (3<<8)

SQUARE = 0
WIDE   = 1
TALL   = 2

ATTR0_SQUARE = (SQUARE << 14)
ATTR0_WIDE   = (WIDE   << 14)
ATTR0_TALL   = (TALL   << 14)

/* ATTR1 */
ATTR1_FLIP_X  = (1<<12)
ATTR1_FLIP_Y  = (1<<13)
ATTR1_SIZE_8  = (0<<14)
ATTR1_SIZE_16 = (1<<14)
ATTR1_SIZE_32 = (2<<14)
ATTR1_SIZE_64 = (3<<14)
