#include "banim_data.h"
__attribute__((section(".data.banim_array")))
BattleAnim banim_data[] = {
	{"lorm_sp1", &banim_lorm_sp1_modes_bin, &banim_lorm_sp1_motion_o, &banim_lorm_sp1_oam_r_bin, &banim_lorm_sp1_oam_l_bin, &banim_lorm_sp1_agbpal}, // 0x0
	{"lorm_sp1", &banim_lorm_sp1_2_modes_bin, &banim_lorm_sp1_2_motion_o, &banim_lorm_sp1_2_oam_r_bin, &banim_lorm_sp1_2_oam_l_bin, &banim_lorm_sp1_2_agbpal}, // 0x1
	{"lorf_sw1", &banim_lorf_sw1_modes_bin, &banim_lorf_sw1_motion_o, &banim_lorf_sw1_oam_r_bin, &banim_lorf_sw1_oam_l_bin, &banim_lorf_sw1_agbpal}, // 0x2
	{"lorf_sw1", &banim_lorf_sw1_2_modes_bin, &banim_lorf_sw1_2_motion_o, &banim_lorf_sw1_2_oam_r_bin, &banim_lorf_sw1_2_oam_l_bin, &banim_lorf_sw1_2_agbpal}, // 0x3
	{"lomm_sp1", &banim_lomm_sp1_modes_bin, &banim_lomm_sp1_motion_o, &banim_lomm_sp1_oam_r_bin, &banim_lomm_sp1_oam_l_bin, &banim_lomm_sp1_agbpal}, // 0x4
	{"lorf_sw1", &banim_lorf_sw1_3_modes_bin, &banim_lorf_sw1_3_motion_o, &banim_lorf_sw1_3_oam_r_bin, &banim_lorf_sw1_3_oam_l_bin, &banim_lorf_sw1_3_agbpal}, // 0x5
	{"lomm_sp1", &banim_lomm_sp1_2_modes_bin, &banim_lomm_sp1_2_motion_o, &banim_lomm_sp1_2_oam_r_bin, &banim_lomm_sp1_2_oam_l_bin, &banim_lomm_sp1_2_agbpal}, // 0x6
	{"lomf_sw1", &banim_lomf_sw1_modes_bin, &banim_lomf_sw1_motion_o, &banim_lomf_sw1_oam_r_bin, &banim_lomf_sw1_oam_l_bin, &banim_lomf_sw1_agbpal}, // 0x7
	{"lorf_sw1", &banim_lorf_sw1_4_modes_bin, &banim_lorf_sw1_4_motion_o, &banim_lorf_sw1_4_oam_r_bin, &banim_lorf_sw1_4_oam_l_bin, &banim_lorf_sw1_4_agbpal}, // 0x8
	{"lomf_sw1", &banim_lomf_sw1_2_modes_bin, &banim_lomf_sw1_2_motion_o, &banim_lomf_sw1_2_oam_r_bin, &banim_lomf_sw1_2_oam_l_bin, &banim_lomf_sw1_2_agbpal}, // 0x9
	{"merm_sw1", &banim_merm_sw1_modes_bin, &banim_merm_sw1_motion_o, &banim_merm_sw1_oam_r_bin, &banim_merm_sw1_oam_l_bin, &banim_merm_sw1_agbpal}, // 0xA
	{"merm_sw1", &banim_merm_sw1_2_modes_bin, &banim_merm_sw1_2_motion_o, &banim_merm_sw1_2_oam_r_bin, &banim_merm_sw1_2_oam_l_bin, &banim_merm_sw1_2_agbpal}, // 0xB
	{"bram_sw1", &banim_bram_sw1_modes_bin, &banim_bram_sw1_motion_o, &banim_bram_sw1_oam_r_bin, &banim_bram_sw1_oam_l_bin, &banim_bram_sw1_agbpal}, // 0xC
	{"bram_sw1", &banim_bram_sw1_2_modes_bin, &banim_bram_sw1_2_motion_o, &banim_bram_sw1_2_oam_r_bin, &banim_bram_sw1_2_oam_l_bin, &banim_bram_sw1_2_agbpal}, // 0xD
	{"bram_sw1", &banim_bram_sw1_3_modes_bin, &banim_bram_sw1_3_motion_o, &banim_bram_sw1_3_oam_r_bin, &banim_bram_sw1_3_oam_l_bin, &banim_bram_sw1_3_agbpal}, // 0xE
	{"bram_sw1", &banim_bram_sw1_4_modes_bin, &banim_bram_sw1_4_motion_o, &banim_bram_sw1_4_oam_r_bin, &banim_bram_sw1_4_oam_l_bin, &banim_bram_sw1_4_agbpal}, // 0xF
	{"myrm_sw1", &banim_myrm_sw1_modes_bin, &banim_myrm_sw1_motion_o, &banim_myrm_sw1_oam_r_bin, &banim_myrm_sw1_oam_l_bin, &banim_myrm_sw1_agbpal}, // 0x10
	{"myrm_sw1", &banim_myrm_sw1_2_modes_bin, &banim_myrm_sw1_2_motion_o, &banim_myrm_sw1_2_oam_r_bin, &banim_myrm_sw1_2_oam_l_bin, &banim_myrm_sw1_2_agbpal}, // 0x11
	{"myrf_sw1", &banim_myrf_sw1_modes_bin, &banim_myrf_sw1_motion_o, &banim_myrf_sw1_oam_r_bin, &banim_myrf_sw1_oam_l_bin, &banim_myrf_sw1_agbpal}, // 0x12
	{"myrf_sw1", &banim_myrf_sw1_2_modes_bin, &banim_myrf_sw1_2_motion_o, &banim_myrf_sw1_2_oam_r_bin, &banim_myrf_sw1_2_oam_l_bin, &banim_myrf_sw1_2_agbpal}, // 0x13
	{"swmm_sw1", &banim_swmm_sw1_modes_bin, &banim_swmm_sw1_motion_o, &banim_swmm_sw1_oam_r_bin, &banim_swmm_sw1_oam_l_bin, &banim_swmm_sw1_agbpal}, // 0x14
	{"swmm_sw1", &banim_swmm_sw1_2_modes_bin, &banim_swmm_sw1_2_motion_o, &banim_swmm_sw1_2_oam_r_bin, &banim_swmm_sw1_2_oam_l_bin, &banim_swmm_sw1_2_agbpal}, // 0x15
	{"swmf_sw1", &banim_swmf_sw1_modes_bin, &banim_swmf_sw1_motion_o, &banim_swmf_sw1_oam_r_bin, &banim_swmf_sw1_oam_l_bin, &banim_swmf_sw1_agbpal}, // 0x16
	{"swmf_sw1", &banim_swmf_sw1_2_modes_bin, &banim_swmf_sw1_2_motion_o, &banim_swmf_sw1_2_oam_r_bin, &banim_swmf_sw1_2_oam_l_bin, &banim_swmf_sw1_2_agbpal}, // 0x17
	{"figm_ax1", &banim_figm_ax1_modes_bin, &banim_figm_ax1_motion_o, &banim_figm_ax1_oam_r_bin, &banim_figm_ax1_oam_l_bin, &banim_figm_ax1_agbpal}, // 0x18
	{"figm_ax1", &banim_figm_ax1_2_modes_bin, &banim_figm_ax1_2_motion_o, &banim_figm_ax1_2_oam_r_bin, &banim_figm_ax1_2_oam_l_bin, &banim_figm_ax1_2_agbpal}, // 0x19
	{"figm_ax1", &banim_figm_ax1_3_modes_bin, &banim_figm_ax1_3_motion_o, &banim_figm_ax1_3_oam_r_bin, &banim_figm_ax1_3_oam_l_bin, &banim_figm_ax1_3_agbpal}, // 0x1A
	{"warm_ax1", &banim_warm_ax1_modes_bin, &banim_warm_ax1_motion_o, &banim_warm_ax1_oam_r_bin, &banim_warm_ax1_oam_l_bin, &banim_warm_ax1_agbpal}, // 0x1B
	{"warm_ax1", &banim_warm_ax1_2_modes_bin, &banim_warm_ax1_2_motion_o, &banim_warm_ax1_2_oam_r_bin, &banim_warm_ax1_2_oam_l_bin, &banim_warm_ax1_2_agbpal}, // 0x1C
	{"warm_ar1", &banim_warm_ar1_modes_bin, &banim_warm_ar1_motion_o, &banim_warm_ar1_oam_r_bin, &banim_warm_ar1_oam_l_bin, &banim_warm_ar1_agbpal}, // 0x1D
	{"warm_ax1", &banim_warm_ax1_3_modes_bin, &banim_warm_ax1_3_motion_o, &banim_warm_ax1_3_oam_r_bin, &banim_warm_ax1_3_oam_l_bin, &banim_warm_ax1_3_agbpal}, // 0x1E
	{"banm_ax1", &banim_banm_ax1_modes_bin, &banim_banm_ax1_motion_o, &banim_banm_ax1_oam_r_bin, &banim_banm_ax1_oam_l_bin, &banim_banm_ax1_agbpal}, // 0x1F
	{"banm_ax1", &banim_banm_ax1_2_modes_bin, &banim_banm_ax1_2_motion_o, &banim_banm_ax1_2_oam_r_bin, &banim_banm_ax1_2_oam_l_bin, &banim_banm_ax1_2_agbpal}, // 0x20
	{"banm_ax1", &banim_banm_ax1_3_modes_bin, &banim_banm_ax1_3_motion_o, &banim_banm_ax1_3_oam_r_bin, &banim_banm_ax1_3_oam_l_bin, &banim_banm_ax1_3_agbpal}, // 0x21
	{"brsm_ax1", &banim_brsm_ax1_modes_bin, &banim_brsm_ax1_motion_o, &banim_brsm_ax1_oam_r_bin, &banim_brsm_ax1_oam_l_bin, &banim_brsm_ax1_agbpal}, // 0x22
	{"brsm_ax1", &banim_brsm_ax1_2_modes_bin, &banim_brsm_ax1_2_motion_o, &banim_brsm_ax1_2_oam_r_bin, &banim_brsm_ax1_2_oam_l_bin, &banim_brsm_ax1_2_agbpal}, // 0x23
	{"brsm_ax1", &banim_brsm_ax1_3_modes_bin, &banim_brsm_ax1_3_motion_o, &banim_brsm_ax1_3_oam_r_bin, &banim_brsm_ax1_3_oam_l_bin, &banim_brsm_ax1_3_agbpal}, // 0x24
	{"arcm_ar1", &banim_arcm_ar1_modes_bin, &banim_arcm_ar1_motion_o, &banim_arcm_ar1_oam_r_bin, &banim_arcm_ar1_oam_l_bin, &banim_arcm_ar1_agbpal}, // 0x25
	{"arcm_ar1", &banim_arcm_ar1_2_modes_bin, &banim_arcm_ar1_2_motion_o, &banim_arcm_ar1_2_oam_r_bin, &banim_arcm_ar1_2_oam_l_bin, &banim_arcm_ar1_2_agbpal}, // 0x26
	{"arcf_ar1", &banim_arcf_ar1_modes_bin, &banim_arcf_ar1_motion_o, &banim_arcf_ar1_oam_r_bin, &banim_arcf_ar1_oam_l_bin, &banim_arcf_ar1_agbpal}, // 0x27
	{"arcf_ar1", &banim_arcf_ar1_2_modes_bin, &banim_arcf_ar1_2_motion_o, &banim_arcf_ar1_2_oam_r_bin, &banim_arcf_ar1_2_oam_l_bin, &banim_arcf_ar1_2_agbpal}, // 0x28
	{"snim_ar1", &banim_snim_ar1_modes_bin, &banim_snim_ar1_motion_o, &banim_snim_ar1_oam_r_bin, &banim_snim_ar1_oam_l_bin, &banim_snim_ar1_agbpal}, // 0x29
	{"snim_ar1", &banim_snim_ar1_2_modes_bin, &banim_snim_ar1_2_motion_o, &banim_snim_ar1_2_oam_r_bin, &banim_snim_ar1_2_oam_l_bin, &banim_snim_ar1_2_agbpal}, // 0x2A
	{"snif_ar1", &banim_snif_ar1_modes_bin, &banim_snif_ar1_motion_o, &banim_snif_ar1_oam_r_bin, &banim_snif_ar1_oam_l_bin, &banim_snif_ar1_agbpal}, // 0x2B
	{"snif_ar1", &banim_snif_ar1_2_modes_bin, &banim_snif_ar1_2_motion_o, &banim_snif_ar1_2_oam_r_bin, &banim_snif_ar1_2_oam_l_bin, &banim_snif_ar1_2_agbpal}, // 0x2C
	{"form_sw1", &banim_form_sw1_modes_bin, &banim_form_sw1_motion_o, &banim_form_sw1_oam_r_bin, &banim_form_sw1_oam_l_bin, &banim_form_sw1_agbpal}, // 0x2D
	{"form_ar1", &banim_form_ar1_modes_bin, &banim_form_ar1_motion_o, &banim_form_ar1_oam_r_bin, &banim_form_ar1_oam_l_bin, &banim_form_ar1_agbpal}, // 0x2E
	{"form_sw1", &banim_form_sw1_2_modes_bin, &banim_form_sw1_2_motion_o, &banim_form_sw1_2_oam_r_bin, &banim_form_sw1_2_oam_l_bin, &banim_form_sw1_2_agbpal}, // 0x2F
	{"forf_sw1", &banim_forf_sw1_modes_bin, &banim_forf_sw1_motion_o, &banim_forf_sw1_oam_r_bin, &banim_forf_sw1_oam_l_bin, &banim_forf_sw1_agbpal}, // 0x30
	{"forf_ar1", &banim_forf_ar1_modes_bin, &banim_forf_ar1_motion_o, &banim_forf_ar1_oam_r_bin, &banim_forf_ar1_oam_l_bin, &banim_forf_ar1_agbpal}, // 0x31
	{"forf_sw1", &banim_forf_sw1_2_modes_bin, &banim_forf_sw1_2_motion_o, &banim_forf_sw1_2_oam_r_bin, &banim_forf_sw1_2_oam_l_bin, &banim_forf_sw1_2_agbpal}, // 0x32
	{"sokm_sp1", &banim_sokm_sp1_modes_bin, &banim_sokm_sp1_motion_o, &banim_sokm_sp1_oam_r_bin, &banim_sokm_sp1_oam_l_bin, &banim_sokm_sp1_agbpal}, // 0x33
	{"sokm_sp1", &banim_sokm_sp1_2_modes_bin, &banim_sokm_sp1_2_motion_o, &banim_sokm_sp1_2_oam_r_bin, &banim_sokm_sp1_2_oam_l_bin, &banim_sokm_sp1_2_agbpal}, // 0x34
	{"sokm_sp1", &banim_sokm_sp1_3_modes_bin, &banim_sokm_sp1_3_motion_o, &banim_sokm_sp1_3_oam_r_bin, &banim_sokm_sp1_3_oam_l_bin, &banim_sokm_sp1_3_agbpal}, // 0x35
	{"sokf_sp1", &banim_sokf_sp1_modes_bin, &banim_sokf_sp1_motion_o, &banim_sokf_sp1_oam_r_bin, &banim_sokf_sp1_oam_l_bin, &banim_sokf_sp1_agbpal}, // 0x36
	{"sokf_sp1", &banim_sokf_sp1_2_modes_bin, &banim_sokf_sp1_2_motion_o, &banim_sokf_sp1_2_oam_r_bin, &banim_sokf_sp1_2_oam_l_bin, &banim_sokf_sp1_2_agbpal}, // 0x37
	{"sokf_sp1", &banim_sokf_sp1_3_modes_bin, &banim_sokf_sp1_3_motion_o, &banim_sokf_sp1_3_oam_r_bin, &banim_sokf_sp1_3_oam_l_bin, &banim_sokf_sp1_3_agbpal}, // 0x38
	{"pakm_sw1", &banim_pakm_sw1_modes_bin, &banim_pakm_sw1_motion_o, &banim_pakm_sw1_oam_r_bin, &banim_pakm_sw1_oam_l_bin, &banim_pakm_sw1_agbpal}, // 0x39
	{"pakm_sw1", &banim_pakm_sw1_2_modes_bin, &banim_pakm_sw1_2_motion_o, &banim_pakm_sw1_2_oam_r_bin, &banim_pakm_sw1_2_oam_l_bin, &banim_pakm_sw1_2_agbpal}, // 0x3A
	{"pakm_sw1", &banim_pakm_sw1_3_modes_bin, &banim_pakm_sw1_3_motion_o, &banim_pakm_sw1_3_oam_r_bin, &banim_pakm_sw1_3_oam_l_bin, &banim_pakm_sw1_3_agbpal}, // 0x3B
	{"paif_sw1", &banim_paif_sw1_modes_bin, &banim_paif_sw1_motion_o, &banim_paif_sw1_oam_r_bin, &banim_paif_sw1_oam_l_bin, &banim_paif_sw1_agbpal}, // 0x3C
	{"paif_sw1", &banim_paif_sw1_2_modes_bin, &banim_paif_sw1_2_motion_o, &banim_paif_sw1_2_oam_r_bin, &banim_paif_sw1_2_oam_l_bin, &banim_paif_sw1_2_agbpal}, // 0x3D
	{"paif_sw1", &banim_paif_sw1_3_modes_bin, &banim_paif_sw1_3_motion_o, &banim_paif_sw1_3_oam_r_bin, &banim_paif_sw1_3_oam_l_bin, &banim_paif_sw1_3_agbpal}, // 0x3E
	{"armm_sp1", &banim_armm_sp1_modes_bin, &banim_armm_sp1_motion_o, &banim_armm_sp1_oam_r_bin, &banim_armm_sp1_oam_l_bin, &banim_armm_sp1_agbpal}, // 0x3F
	{"armm_sp1", &banim_armm_sp1_2_modes_bin, &banim_armm_sp1_2_motion_o, &banim_armm_sp1_2_oam_r_bin, &banim_armm_sp1_2_oam_l_bin, &banim_armm_sp1_2_agbpal}, // 0x40
	{"armm_sp1", &banim_armm_sp1_3_modes_bin, &banim_armm_sp1_3_motion_o, &banim_armm_sp1_3_oam_r_bin, &banim_armm_sp1_3_oam_l_bin, &banim_armm_sp1_3_agbpal}, // 0x41
	{"armm_sp1", &banim_armm_sp1_4_modes_bin, &banim_armm_sp1_4_motion_o, &banim_armm_sp1_4_oam_r_bin, &banim_armm_sp1_4_oam_l_bin, &banim_armm_sp1_4_agbpal}, // 0x42
	{"genm_sw1", &banim_genm_sw1_modes_bin, &banim_genm_sw1_motion_o, &banim_genm_sw1_oam_r_bin, &banim_genm_sw1_oam_l_bin, &banim_genm_sw1_agbpal}, // 0x43
	{"genm_al1", &banim_genm_al1_modes_bin, &banim_genm_al1_motion_o, &banim_genm_al1_oam_r_bin, &banim_genm_al1_oam_l_bin, &banim_genm_al1_agbpal}, // 0x44
	{"genm_al1", &banim_genm_al1_2_modes_bin, &banim_genm_al1_2_motion_o, &banim_genm_al1_2_oam_r_bin, &banim_genm_al1_2_oam_l_bin, &banim_genm_al1_2_agbpal}, // 0x45
	{"genm_al1", &banim_genm_al1_3_modes_bin, &banim_genm_al1_3_motion_o, &banim_genm_al1_3_oam_r_bin, &banim_genm_al1_3_oam_l_bin, &banim_genm_al1_3_agbpal}, // 0x46
	{"genm_al1", &banim_genm_al1_4_modes_bin, &banim_genm_al1_4_motion_o, &banim_genm_al1_4_oam_r_bin, &banim_genm_al1_4_oam_l_bin, &banim_genm_al1_4_agbpal}, // 0x47
	{"genm_sw1", &banim_genm_sw1_2_modes_bin, &banim_genm_sw1_2_motion_o, &banim_genm_sw1_2_oam_r_bin, &banim_genm_sw1_2_oam_l_bin, &banim_genm_sw1_2_agbpal}, // 0x48
	{"genm_al1", &banim_genm_al1_5_modes_bin, &banim_genm_al1_5_motion_o, &banim_genm_al1_5_oam_r_bin, &banim_genm_al1_5_oam_l_bin, &banim_genm_al1_5_agbpal}, // 0x49
	{"genm_al1", &banim_genm_al1_6_modes_bin, &banim_genm_al1_6_motion_o, &banim_genm_al1_6_oam_r_bin, &banim_genm_al1_6_oam_l_bin, &banim_genm_al1_6_agbpal}, // 0x4A
	{"genm_al1", &banim_genm_al1_7_modes_bin, &banim_genm_al1_7_motion_o, &banim_genm_al1_7_oam_r_bin, &banim_genm_al1_7_oam_l_bin, &banim_genm_al1_7_agbpal}, // 0x4B
	{"genm_al1", &banim_genm_al1_8_modes_bin, &banim_genm_al1_8_motion_o, &banim_genm_al1_8_oam_r_bin, &banim_genm_al1_8_oam_l_bin, &banim_genm_al1_8_agbpal}, // 0x4C
	{"grkm_sw1", &banim_grkm_sw1_modes_bin, &banim_grkm_sw1_motion_o, &banim_grkm_sw1_oam_r_bin, &banim_grkm_sw1_oam_l_bin, &banim_grkm_sw1_agbpal}, // 0x4D
	{"grkm_sp1", &banim_grkm_sp1_modes_bin, &banim_grkm_sp1_motion_o, &banim_grkm_sp1_oam_r_bin, &banim_grkm_sp1_oam_l_bin, &banim_grkm_sp1_agbpal}, // 0x4E
	{"grkm_ax1", &banim_grkm_ax1_modes_bin, &banim_grkm_ax1_motion_o, &banim_grkm_ax1_oam_r_bin, &banim_grkm_ax1_oam_l_bin, &banim_grkm_ax1_agbpal}, // 0x4F
	{"grkm_ax1", &banim_grkm_ax1_2_modes_bin, &banim_grkm_ax1_2_motion_o, &banim_grkm_ax1_2_oam_r_bin, &banim_grkm_ax1_2_oam_l_bin, &banim_grkm_ax1_2_agbpal}, // 0x50
	{"grkm_sw1", &banim_grkm_sw1_2_modes_bin, &banim_grkm_sw1_2_motion_o, &banim_grkm_sw1_2_oam_r_bin, &banim_grkm_sw1_2_oam_l_bin, &banim_grkm_sw1_2_agbpal}, // 0x51
	{"grkm_sw1", &banim_grkm_sw1_3_modes_bin, &banim_grkm_sw1_3_motion_o, &banim_grkm_sw1_3_oam_r_bin, &banim_grkm_sw1_3_oam_l_bin, &banim_grkm_sw1_3_agbpal}, // 0x52
	{"grkm_sp1", &banim_grkm_sp1_2_modes_bin, &banim_grkm_sp1_2_motion_o, &banim_grkm_sp1_2_oam_r_bin, &banim_grkm_sp1_2_oam_l_bin, &banim_grkm_sp1_2_agbpal}, // 0x53
	{"grkm_ax1", &banim_grkm_ax1_3_modes_bin, &banim_grkm_ax1_3_motion_o, &banim_grkm_ax1_3_oam_r_bin, &banim_grkm_ax1_3_oam_l_bin, &banim_grkm_ax1_3_agbpal}, // 0x54
	{"grkm_ax1", &banim_grkm_ax1_4_modes_bin, &banim_grkm_ax1_4_motion_o, &banim_grkm_ax1_4_oam_r_bin, &banim_grkm_ax1_4_oam_l_bin, &banim_grkm_ax1_4_agbpal}, // 0x55
	{"grkm_sw1", &banim_grkm_sw1_4_modes_bin, &banim_grkm_sw1_4_motion_o, &banim_grkm_sw1_4_oam_r_bin, &banim_grkm_sw1_4_oam_l_bin, &banim_grkm_sw1_4_agbpal}, // 0x56
	{"drkm_sp1", &banim_drkm_sp1_modes_bin, &banim_drkm_sp1_motion_o, &banim_drkm_sp1_oam_r_bin, &banim_drkm_sp1_oam_l_bin, &banim_drkm_sp1_agbpal}, // 0x57
	{"drkm_sp1", &banim_drkm_sp1_2_modes_bin, &banim_drkm_sp1_2_motion_o, &banim_drkm_sp1_2_oam_r_bin, &banim_drkm_sp1_2_oam_l_bin, &banim_drkm_sp1_2_agbpal}, // 0x58
	{"drkm_sp1", &banim_drkm_sp1_3_modes_bin, &banim_drkm_sp1_3_motion_o, &banim_drkm_sp1_3_oam_r_bin, &banim_drkm_sp1_3_oam_l_bin, &banim_drkm_sp1_3_agbpal}, // 0x59
	{"drkm_sp1", &banim_drkm_sp1_4_modes_bin, &banim_drkm_sp1_4_motion_o, &banim_drkm_sp1_4_oam_r_bin, &banim_drkm_sp1_4_oam_l_bin, &banim_drkm_sp1_4_agbpal}, // 0x5A
	{"drmm_sp1", &banim_drmm_sp1_modes_bin, &banim_drmm_sp1_motion_o, &banim_drmm_sp1_oam_r_bin, &banim_drmm_sp1_oam_l_bin, &banim_drmm_sp1_agbpal}, // 0x5B
	{"drmm_sp1", &banim_drmm_sp1_2_modes_bin, &banim_drmm_sp1_2_motion_o, &banim_drmm_sp1_2_oam_r_bin, &banim_drmm_sp1_2_oam_l_bin, &banim_drmm_sp1_2_agbpal}, // 0x5C
	{"drmm_sp1", &banim_drmm_sp1_3_modes_bin, &banim_drmm_sp1_3_motion_o, &banim_drmm_sp1_3_oam_r_bin, &banim_drmm_sp1_3_oam_l_bin, &banim_drmm_sp1_3_agbpal}, // 0x5D
	{"drmm_sp1", &banim_drmm_sp1_4_modes_bin, &banim_drmm_sp1_4_motion_o, &banim_drmm_sp1_4_oam_r_bin, &banim_drmm_sp1_4_oam_l_bin, &banim_drmm_sp1_4_agbpal}, // 0x5E
	{"drmm_sp1", &banim_drmm_sp1_5_modes_bin, &banim_drmm_sp1_5_motion_o, &banim_drmm_sp1_5_oam_r_bin, &banim_drmm_sp1_5_oam_l_bin, &banim_drmm_sp1_5_agbpal}, // 0x5F
	{"drmm_sp1", &banim_drmm_sp1_6_modes_bin, &banim_drmm_sp1_6_motion_o, &banim_drmm_sp1_6_oam_r_bin, &banim_drmm_sp1_6_oam_l_bin, &banim_drmm_sp1_6_agbpal}, // 0x60
	{"wykm_sp1", &banim_wykm_sp1_modes_bin, &banim_wykm_sp1_motion_o, &banim_wykm_sp1_oam_r_bin, &banim_wykm_sp1_oam_l_bin, &banim_wykm_sp1_agbpal}, // 0x61
	{"wykm_sp1", &banim_wykm_sp1_2_modes_bin, &banim_wykm_sp1_2_motion_o, &banim_wykm_sp1_2_oam_r_bin, &banim_wykm_sp1_2_oam_l_bin, &banim_wykm_sp1_2_agbpal}, // 0x62
	{"wykm_sp1", &banim_wykm_sp1_3_modes_bin, &banim_wykm_sp1_3_motion_o, &banim_wykm_sp1_3_oam_r_bin, &banim_wykm_sp1_3_oam_l_bin, &banim_wykm_sp1_3_agbpal}, // 0x63
	{"wykm_sp1", &banim_wykm_sp1_4_modes_bin, &banim_wykm_sp1_4_motion_o, &banim_wykm_sp1_4_oam_r_bin, &banim_wykm_sp1_4_oam_l_bin, &banim_wykm_sp1_4_agbpal}, // 0x64
	{"pekf_sp1", &banim_pekf_sp1_modes_bin, &banim_pekf_sp1_motion_o, &banim_pekf_sp1_oam_r_bin, &banim_pekf_sp1_oam_l_bin, &banim_pekf_sp1_agbpal}, // 0x65
	{"pekf_sp1", &banim_pekf_sp1_2_modes_bin, &banim_pekf_sp1_2_motion_o, &banim_pekf_sp1_2_oam_r_bin, &banim_pekf_sp1_2_oam_l_bin, &banim_pekf_sp1_2_agbpal}, // 0x66
	{"fakf_sp1", &banim_fakf_sp1_modes_bin, &banim_fakf_sp1_motion_o, &banim_fakf_sp1_oam_r_bin, &banim_fakf_sp1_oam_l_bin, &banim_fakf_sp1_agbpal}, // 0x67
	{"fakf_sp1", &banim_fakf_sp1_2_modes_bin, &banim_fakf_sp1_2_motion_o, &banim_fakf_sp1_2_oam_r_bin, &banim_fakf_sp1_2_oam_l_bin, &banim_fakf_sp1_2_agbpal}, // 0x68
	{"fakf_sp1", &banim_fakf_sp1_3_modes_bin, &banim_fakf_sp1_3_motion_o, &banim_fakf_sp1_3_oam_r_bin, &banim_fakf_sp1_3_oam_l_bin, &banim_fakf_sp1_3_agbpal}, // 0x69
	{"magm_mg1", &banim_magm_mg1_modes_bin, &banim_magm_mg1_motion_o, &banim_magm_mg1_oam_r_bin, &banim_magm_mg1_oam_l_bin, &banim_magm_mg1_agbpal}, // 0x6A
	{"magf_mg1", &banim_magf_mg1_modes_bin, &banim_magf_mg1_motion_o, &banim_magf_mg1_oam_r_bin, &banim_magf_mg1_oam_l_bin, &banim_magf_mg1_agbpal}, // 0x6B
	{"sagm_mg1", &banim_sagm_mg1_modes_bin, &banim_sagm_mg1_motion_o, &banim_sagm_mg1_oam_r_bin, &banim_sagm_mg1_oam_l_bin, &banim_sagm_mg1_agbpal}, // 0x6C
	{"sagm_mg1", &banim_sagm_mg1_2_modes_bin, &banim_sagm_mg1_2_motion_o, &banim_sagm_mg1_2_oam_r_bin, &banim_sagm_mg1_2_oam_l_bin, &banim_sagm_mg1_2_agbpal}, // 0x6D
	{"sagf_mg1", &banim_sagf_mg1_modes_bin, &banim_sagf_mg1_motion_o, &banim_sagf_mg1_oam_r_bin, &banim_sagf_mg1_oam_l_bin, &banim_sagf_mg1_agbpal}, // 0x6E
	{"sagf_mg1", &banim_sagf_mg1_2_modes_bin, &banim_sagf_mg1_2_motion_o, &banim_sagf_mg1_2_oam_r_bin, &banim_sagf_mg1_2_oam_l_bin, &banim_sagf_mg1_2_agbpal}, // 0x6F
	{"mgkm_mg1", &banim_mgkm_mg1_modes_bin, &banim_mgkm_mg1_motion_o, &banim_mgkm_mg1_oam_r_bin, &banim_mgkm_mg1_oam_l_bin, &banim_mgkm_mg1_agbpal}, // 0x70
	{"mgkm_mg1", &banim_mgkm_mg1_2_modes_bin, &banim_mgkm_mg1_2_motion_o, &banim_mgkm_mg1_2_oam_r_bin, &banim_mgkm_mg1_2_oam_l_bin, &banim_mgkm_mg1_2_agbpal}, // 0x71
	{"mgkf_mg1", &banim_mgkf_mg1_modes_bin, &banim_mgkf_mg1_motion_o, &banim_mgkf_mg1_oam_r_bin, &banim_mgkf_mg1_oam_l_bin, &banim_mgkf_mg1_agbpal}, // 0x72
	{"mgkf_mg1", &banim_mgkf_mg1_2_modes_bin, &banim_mgkf_mg1_2_motion_o, &banim_mgkf_mg1_2_oam_r_bin, &banim_mgkf_mg1_2_oam_l_bin, &banim_mgkf_mg1_2_agbpal}, // 0x73
	{"sham_mg1", &banim_sham_mg1_modes_bin, &banim_sham_mg1_motion_o, &banim_sham_mg1_oam_r_bin, &banim_sham_mg1_oam_l_bin, &banim_sham_mg1_agbpal}, // 0x74
	{"shaf_mg1", &banim_shaf_mg1_modes_bin, &banim_shaf_mg1_motion_o, &banim_shaf_mg1_oam_r_bin, &banim_shaf_mg1_oam_l_bin, &banim_shaf_mg1_agbpal}, // 0x75
	{"drum_mg1", &banim_drum_mg1_modes_bin, &banim_drum_mg1_motion_o, &banim_drum_mg1_oam_r_bin, &banim_drum_mg1_oam_l_bin, &banim_drum_mg1_agbpal}, // 0x76
	{"drum_mg1", &banim_drum_mg1_2_modes_bin, &banim_drum_mg1_2_motion_o, &banim_drum_mg1_2_oam_r_bin, &banim_drum_mg1_2_oam_l_bin, &banim_drum_mg1_2_agbpal}, // 0x77
	{"druf_mg1", &banim_druf_mg1_modes_bin, &banim_druf_mg1_motion_o, &banim_druf_mg1_oam_r_bin, &banim_druf_mg1_oam_l_bin, &banim_druf_mg1_agbpal}, // 0x78
	{"druf_mg1", &banim_druf_mg1_2_modes_bin, &banim_druf_mg1_2_motion_o, &banim_druf_mg1_2_oam_r_bin, &banim_druf_mg1_2_oam_l_bin, &banim_druf_mg1_2_agbpal}, // 0x79
	{"smnm_ro1", &banim_smnm_ro1_modes_bin, &banim_smnm_ro1_motion_o, &banim_smnm_ro1_oam_r_bin, &banim_smnm_ro1_oam_l_bin, &banim_smnm_ro1_agbpal}, // 0x7A
	{"smnm_ro1", &banim_smnm_ro1_2_modes_bin, &banim_smnm_ro1_2_motion_o, &banim_smnm_ro1_2_oam_r_bin, &banim_smnm_ro1_2_oam_l_bin, &banim_smnm_ro1_2_agbpal}, // 0x7B
	{"monm_mg1", &banim_monm_mg1_modes_bin, &banim_monm_mg1_motion_o, &banim_monm_mg1_oam_r_bin, &banim_monm_mg1_oam_l_bin, &banim_monm_mg1_agbpal}, // 0x7C
	{"prim_ro1", &banim_prim_ro1_modes_bin, &banim_prim_ro1_motion_o, &banim_prim_ro1_oam_r_bin, &banim_prim_ro1_oam_l_bin, &banim_prim_ro1_agbpal}, // 0x7D
	{"prim_ro1", &banim_prim_ro1_2_modes_bin, &banim_prim_ro1_2_motion_o, &banim_prim_ro1_2_oam_r_bin, &banim_prim_ro1_2_oam_l_bin, &banim_prim_ro1_2_agbpal}, // 0x7E
	{"prif_ro1", &banim_prif_ro1_modes_bin, &banim_prif_ro1_motion_o, &banim_prif_ro1_oam_r_bin, &banim_prif_ro1_oam_l_bin, &banim_prif_ro1_agbpal}, // 0x7F
	{"bism_mg1", &banim_bism_mg1_modes_bin, &banim_bism_mg1_motion_o, &banim_bism_mg1_oam_r_bin, &banim_bism_mg1_oam_l_bin, &banim_bism_mg1_agbpal}, // 0x80
	{"bism_mg1", &banim_bism_mg1_2_modes_bin, &banim_bism_mg1_2_motion_o, &banim_bism_mg1_2_oam_r_bin, &banim_bism_mg1_2_oam_l_bin, &banim_bism_mg1_2_agbpal}, // 0x81
	{"bisf_mg1", &banim_bisf_mg1_modes_bin, &banim_bisf_mg1_motion_o, &banim_bisf_mg1_oam_r_bin, &banim_bisf_mg1_oam_l_bin, &banim_bisf_mg1_agbpal}, // 0x82
	{"bisf_mg1", &banim_bisf_mg1_2_modes_bin, &banim_bisf_mg1_2_motion_o, &banim_bisf_mg1_2_oam_r_bin, &banim_bisf_mg1_2_oam_l_bin, &banim_bisf_mg1_2_agbpal}, // 0x83
	{"trof_ro1", &banim_trof_ro1_modes_bin, &banim_trof_ro1_motion_o, &banim_trof_ro1_oam_r_bin, &banim_trof_ro1_oam_l_bin, &banim_trof_ro1_agbpal}, // 0x84
	{"trof_ro1", &banim_trof_ro1_2_modes_bin, &banim_trof_ro1_2_motion_o, &banim_trof_ro1_2_oam_r_bin, &banim_trof_ro1_2_oam_l_bin, &banim_trof_ro1_2_agbpal}, // 0x85
	{"valf_mg1", &banim_valf_mg1_modes_bin, &banim_valf_mg1_motion_o, &banim_valf_mg1_oam_r_bin, &banim_valf_mg1_oam_l_bin, &banim_valf_mg1_agbpal}, // 0x86
	{"valf_mg1", &banim_valf_mg1_2_modes_bin, &banim_valf_mg1_2_motion_o, &banim_valf_mg1_2_oam_r_bin, &banim_valf_mg1_2_oam_l_bin, &banim_valf_mg1_2_agbpal}, // 0x87
	{"thim_sw1", &banim_thim_sw1_modes_bin, &banim_thim_sw1_motion_o, &banim_thim_sw1_oam_r_bin, &banim_thim_sw1_oam_l_bin, &banim_thim_sw1_agbpal}, // 0x88
	{"thim_sw1", &banim_thim_sw1_2_modes_bin, &banim_thim_sw1_2_motion_o, &banim_thim_sw1_2_oam_r_bin, &banim_thim_sw1_2_oam_l_bin, &banim_thim_sw1_2_agbpal}, // 0x89
	{"asnm_sw1", &banim_asnm_sw1_modes_bin, &banim_asnm_sw1_motion_o, &banim_asnm_sw1_oam_r_bin, &banim_asnm_sw1_oam_l_bin, &banim_asnm_sw1_agbpal}, // 0x8A
	{"asnm_sw1", &banim_asnm_sw1_2_modes_bin, &banim_asnm_sw1_2_motion_o, &banim_asnm_sw1_2_oam_r_bin, &banim_asnm_sw1_2_oam_l_bin, &banim_asnm_sw1_2_agbpal}, // 0x8B
	{"asnm_sw1", &banim_asnm_sw1_3_modes_bin, &banim_asnm_sw1_3_motion_o, &banim_asnm_sw1_3_oam_r_bin, &banim_asnm_sw1_3_oam_l_bin, &banim_asnm_sw1_3_agbpal}, // 0x8C
	{"asnm_sw1", &banim_asnm_sw1_4_modes_bin, &banim_asnm_sw1_4_motion_o, &banim_asnm_sw1_4_oam_r_bin, &banim_asnm_sw1_4_oam_l_bin, &banim_asnm_sw1_4_agbpal}, // 0x8D
	{"rogm_sw1", &banim_rogm_sw1_modes_bin, &banim_rogm_sw1_motion_o, &banim_rogm_sw1_oam_r_bin, &banim_rogm_sw1_oam_l_bin, &banim_rogm_sw1_agbpal}, // 0x8E
	{"rogm_sw1", &banim_rogm_sw1_2_modes_bin, &banim_rogm_sw1_2_motion_o, &banim_rogm_sw1_2_oam_r_bin, &banim_rogm_sw1_2_oam_l_bin, &banim_rogm_sw1_2_agbpal}, // 0x8F
	{"danf_da1", &banim_danf_da1_modes_bin, &banim_danf_da1_motion_o, &banim_danf_da1_oam_r_bin, &banim_danf_da1_oam_l_bin, &banim_danf_da1_agbpal}, // 0x90
	{"pbfm_ax1", &banim_pbfm_ax1_modes_bin, &banim_pbfm_ax1_motion_o, &banim_pbfm_ax1_oam_r_bin, &banim_pbfm_ax1_oam_l_bin, &banim_pbfm_ax1_agbpal}, // 0x91
	{"pbfm_ax1", &banim_pbfm_ax1_2_modes_bin, &banim_pbfm_ax1_2_motion_o, &banim_pbfm_ax1_2_oam_r_bin, &banim_pbfm_ax1_2_oam_l_bin, &banim_pbfm_ax1_2_agbpal}, // 0x92
	{"pbfm_ax1", &banim_pbfm_ax1_3_modes_bin, &banim_pbfm_ax1_3_motion_o, &banim_pbfm_ax1_3_oam_r_bin, &banim_pbfm_ax1_3_oam_l_bin, &banim_pbfm_ax1_3_agbpal}, // 0x93
	{"pbmm_mg1", &banim_pbmm_mg1_modes_bin, &banim_pbmm_mg1_motion_o, &banim_pbmm_mg1_oam_r_bin, &banim_pbmm_mg1_oam_l_bin, &banim_pbmm_mg1_agbpal}, // 0x94
	{"pbrf_sp1", &banim_pbrf_sp1_modes_bin, &banim_pbrf_sp1_motion_o, &banim_pbrf_sp1_oam_r_bin, &banim_pbrf_sp1_oam_l_bin, &banim_pbrf_sp1_agbpal}, // 0x95
	{"pbrf_sp1", &banim_pbrf_sp1_2_modes_bin, &banim_pbrf_sp1_2_motion_o, &banim_pbrf_sp1_2_oam_r_bin, &banim_pbrf_sp1_2_oam_l_bin, &banim_pbrf_sp1_2_agbpal}, // 0x96
	{"solm_sp1", &banim_solm_sp1_modes_bin, &banim_solm_sp1_motion_o, &banim_solm_sp1_oam_r_bin, &banim_solm_sp1_oam_l_bin, &banim_solm_sp1_agbpal}, // 0x97
	{"solm_sp1", &banim_solm_sp1_2_modes_bin, &banim_solm_sp1_2_motion_o, &banim_solm_sp1_2_oam_r_bin, &banim_solm_sp1_2_oam_l_bin, &banim_solm_sp1_2_agbpal}, // 0x98
	{"pirm_ax1", &banim_pirm_ax1_modes_bin, &banim_pirm_ax1_motion_o, &banim_pirm_ax1_oam_r_bin, &banim_pirm_ax1_oam_l_bin, &banim_pirm_ax1_agbpal}, // 0x99
	{"pirm_ax1", &banim_pirm_ax1_2_modes_bin, &banim_pirm_ax1_2_motion_o, &banim_pirm_ax1_2_oam_r_bin, &banim_pirm_ax1_2_oam_l_bin, &banim_pirm_ax1_2_agbpal}, // 0x9A
	{"pirm_ax1", &banim_pirm_ax1_3_modes_bin, &banim_pirm_ax1_3_motion_o, &banim_pirm_ax1_3_oam_r_bin, &banim_pirm_ax1_3_oam_l_bin, &banim_pirm_ax1_3_agbpal}, // 0x9B
	{"necm_mg1", &banim_necm_mg1_modes_bin, &banim_necm_mg1_motion_o, &banim_necm_mg1_oam_r_bin, &banim_necm_mg1_oam_l_bin, &banim_necm_mg1_agbpal}, // 0x9C
	{"necm_ro1", &banim_necm_ro1_modes_bin, &banim_necm_ro1_motion_o, &banim_necm_ro1_oam_r_bin, &banim_necm_ro1_oam_l_bin, &banim_necm_ro1_agbpal}, // 0x9D
	{"stam_ar1", &banim_stam_ar1_modes_bin, &banim_stam_ar1_motion_o, &banim_stam_ar1_oam_r_bin, &banim_stam_ar1_oam_l_bin, &banim_stam_ar1_agbpal}, // 0x9E
	{"zom_at1", &banim_zom_at1_modes_bin, &banim_zom_at1_motion_o, &banim_zom_at1_oam_r_bin, &banim_zom_at1_oam_l_bin, &banim_zom_at1_agbpal}, // 0x9F
	{"zom_at1", &banim_zom_at1_2_modes_bin, &banim_zom_at1_2_motion_o, &banim_zom_at1_2_oam_r_bin, &banim_zom_at1_2_oam_l_bin, &banim_zom_at1_2_agbpal}, // 0xA0
	{"sks_sw1", &banim_sks_sw1_modes_bin, &banim_sks_sw1_motion_o, &banim_sks_sw1_oam_r_bin, &banim_sks_sw1_oam_l_bin, &banim_sks_sw1_agbpal}, // 0xA1
	{"sks_sp1", &banim_sks_sp1_modes_bin, &banim_sks_sp1_motion_o, &banim_sks_sp1_oam_r_bin, &banim_sks_sp1_oam_l_bin, &banim_sks_sp1_agbpal}, // 0xA2
	{"sks_sw1", &banim_sks_sw1_2_modes_bin, &banim_sks_sw1_2_motion_o, &banim_sks_sw1_2_oam_r_bin, &banim_sks_sw1_2_oam_l_bin, &banim_sks_sw1_2_agbpal}, // 0xA3
	{"ska_ar1", &banim_ska_ar1_modes_bin, &banim_ska_ar1_motion_o, &banim_ska_ar1_oam_r_bin, &banim_ska_ar1_oam_l_bin, &banim_ska_ar1_agbpal}, // 0xA4
	{"sks_sw1", &banim_sks_sw1_3_modes_bin, &banim_sks_sw1_3_motion_o, &banim_sks_sw1_3_oam_r_bin, &banim_sks_sw1_3_oam_l_bin, &banim_sks_sw1_3_agbpal}, // 0xA5
	{"sks_sw1", &banim_sks_sw1_4_modes_bin, &banim_sks_sw1_4_motion_o, &banim_sks_sw1_4_oam_r_bin, &banim_sks_sw1_4_oam_l_bin, &banim_sks_sw1_4_agbpal}, // 0xA6
	{"sks_sp1", &banim_sks_sp1_2_modes_bin, &banim_sks_sp1_2_motion_o, &banim_sks_sp1_2_oam_r_bin, &banim_sks_sp1_2_oam_l_bin, &banim_sks_sp1_2_agbpal}, // 0xA7
	{"sks_sw1", &banim_sks_sw1_5_modes_bin, &banim_sks_sw1_5_motion_o, &banim_sks_sw1_5_oam_r_bin, &banim_sks_sw1_5_oam_l_bin, &banim_sks_sw1_5_agbpal}, // 0xA8
	{"ska_ar1", &banim_ska_ar1_2_modes_bin, &banim_ska_ar1_2_motion_o, &banim_ska_ar1_2_oam_r_bin, &banim_ska_ar1_2_oam_l_bin, &banim_ska_ar1_2_agbpal}, // 0xA9
	{"sks_sw1", &banim_sks_sw1_6_modes_bin, &banim_sks_sw1_6_motion_o, &banim_sks_sw1_6_oam_r_bin, &banim_sks_sw1_6_oam_l_bin, &banim_sks_sw1_6_agbpal}, // 0xAA
	{"bae_at1", &banim_bae_at1_modes_bin, &banim_bae_at1_motion_o, &banim_bae_at1_oam_r_bin, &banim_bae_at1_oam_l_bin, &banim_bae_at1_agbpal}, // 0xAB
	{"bae_at1", &banim_bae_at1_2_modes_bin, &banim_bae_at1_2_motion_o, &banim_bae_at1_2_oam_r_bin, &banim_bae_at1_2_oam_l_bin, &banim_bae_at1_2_agbpal}, // 0xAC
	{"cyc_ax1", &banim_cyc_ax1_modes_bin, &banim_cyc_ax1_motion_o, &banim_cyc_ax1_oam_r_bin, &banim_cyc_ax1_oam_l_bin, &banim_cyc_ax1_agbpal}, // 0xAD
	{"cyc_ax1", &banim_cyc_ax1_2_modes_bin, &banim_cyc_ax1_2_motion_o, &banim_cyc_ax1_2_oam_r_bin, &banim_cyc_ax1_2_oam_l_bin, &banim_cyc_ax1_2_agbpal}, // 0xAE
	{"cyc_ax1", &banim_cyc_ax1_3_modes_bin, &banim_cyc_ax1_3_motion_o, &banim_cyc_ax1_3_oam_r_bin, &banim_cyc_ax1_3_oam_l_bin, &banim_cyc_ax1_3_agbpal}, // 0xAF
	{"mdg_at1", &banim_mdg_at1_modes_bin, &banim_mdg_at1_motion_o, &banim_mdg_at1_oam_r_bin, &banim_mdg_at1_oam_l_bin, &banim_mdg_at1_agbpal}, // 0xB0
	{"cer_at1", &banim_cer_at1_modes_bin, &banim_cer_at1_motion_o, &banim_cer_at1_oam_r_bin, &banim_cer_at1_oam_l_bin, &banim_cer_at1_agbpal}, // 0xB1
	{"mcd_ax1", &banim_mcd_ax1_modes_bin, &banim_mcd_ax1_motion_o, &banim_mcd_ax1_oam_r_bin, &banim_mcd_ax1_oam_l_bin, &banim_mcd_ax1_agbpal}, // 0xB2
	{"mcd_ax1", &banim_mcd_ax1_2_modes_bin, &banim_mcd_ax1_2_motion_o, &banim_mcd_ax1_2_oam_r_bin, &banim_mcd_ax1_2_oam_l_bin, &banim_mcd_ax1_2_agbpal}, // 0xB3
	{"mcd_ax1", &banim_mcd_ax1_3_modes_bin, &banim_mcd_ax1_3_motion_o, &banim_mcd_ax1_3_oam_r_bin, &banim_mcd_ax1_3_oam_l_bin, &banim_mcd_ax1_3_agbpal}, // 0xB4
	{"mcd_ax1", &banim_mcd_ax1_4_modes_bin, &banim_mcd_ax1_4_motion_o, &banim_mcd_ax1_4_oam_r_bin, &banim_mcd_ax1_4_oam_l_bin, &banim_mcd_ax1_4_agbpal}, // 0xB5
	{"mcd_ax1", &banim_mcd_ax1_5_modes_bin, &banim_mcd_ax1_5_motion_o, &banim_mcd_ax1_5_oam_r_bin, &banim_mcd_ax1_5_oam_l_bin, &banim_mcd_ax1_5_agbpal}, // 0xB6
	{"mcd_ar1", &banim_mcd_ar1_modes_bin, &banim_mcd_ar1_motion_o, &banim_mcd_ar1_oam_r_bin, &banim_mcd_ar1_oam_l_bin, &banim_mcd_ar1_agbpal}, // 0xB7
	{"mcd_ax1", &banim_mcd_ax1_6_modes_bin, &banim_mcd_ax1_6_motion_o, &banim_mcd_ax1_6_oam_r_bin, &banim_mcd_ax1_6_oam_l_bin, &banim_mcd_ax1_6_agbpal}, // 0xB8
	{"bgl_mg1", &banim_bgl_mg1_modes_bin, &banim_bgl_mg1_motion_o, &banim_bgl_mg1_oam_r_bin, &banim_bgl_mg1_oam_l_bin, &banim_bgl_mg1_agbpal}, // 0xB9
	{"bgl_mg1", &banim_bgl_mg1_2_modes_bin, &banim_bgl_mg1_2_motion_o, &banim_bgl_mg1_2_oam_r_bin, &banim_bgl_mg1_2_oam_l_bin, &banim_bgl_mg1_2_agbpal}, // 0xBA
	{"gog_mg1", &banim_gog_mg1_modes_bin, &banim_gog_mg1_motion_o, &banim_gog_mg1_oam_r_bin, &banim_gog_mg1_oam_l_bin, &banim_gog_mg1_agbpal}, // 0xBB
	{"gar_sp1", &banim_gar_sp1_modes_bin, &banim_gar_sp1_motion_o, &banim_gar_sp1_oam_r_bin, &banim_gar_sp1_oam_l_bin, &banim_gar_sp1_agbpal}, // 0xBC
	{"gar_sp1", &banim_gar_sp1_2_modes_bin, &banim_gar_sp1_2_motion_o, &banim_gar_sp1_2_oam_r_bin, &banim_gar_sp1_2_oam_l_bin, &banim_gar_sp1_2_agbpal}, // 0xBD
	{"gar_sp1", &banim_gar_sp1_3_modes_bin, &banim_gar_sp1_3_motion_o, &banim_gar_sp1_3_oam_r_bin, &banim_gar_sp1_3_oam_l_bin, &banim_gar_sp1_3_agbpal}, // 0xBE
	{"gar_sp1", &banim_gar_sp1_4_modes_bin, &banim_gar_sp1_4_motion_o, &banim_gar_sp1_4_oam_r_bin, &banim_gar_sp1_4_oam_l_bin, &banim_gar_sp1_4_agbpal}, // 0xBF
	{"drz_mg1", &banim_drz_mg1_modes_bin, &banim_drz_mg1_motion_o, &banim_drz_mg1_oam_r_bin, &banim_drz_mg1_oam_l_bin, &banim_drz_mg1_agbpal}, // 0xC0
	{"bos_at1", &banim_bos_at1_modes_bin, &banim_bos_at1_motion_o, &banim_bos_at1_oam_r_bin, &banim_bos_at1_oam_l_bin, &banim_bos_at1_agbpal}, // 0xC1
	{"bos_at1", &banim_bos_at1_2_modes_bin, &banim_bos_at1_2_motion_o, &banim_bos_at1_2_oam_r_bin, &banim_bos_at1_2_oam_l_bin, &banim_bos_at1_2_agbpal}, // 0xC2
	{"fifd_mg1", &banim_fifd_mg1_modes_bin, &banim_fifd_mg1_motion_o, &banim_fifd_mg1_oam_r_bin, &banim_fifd_mg1_oam_l_bin, &banim_fifd_mg1_agbpal}, // 0xC3
	{"fifd_he1", &banim_fifd_he1_modes_bin, &banim_fifd_he1_motion_o, &banim_fifd_he1_oam_r_bin, &banim_fifd_he1_oam_l_bin, &banim_fifd_he1_agbpal}, // 0xC4
	{"fifd_hk1", &banim_fifd_hk1_modes_bin, &banim_fifd_hk1_motion_o, &banim_fifd_hk1_oam_r_bin, &banim_fifd_hk1_oam_l_bin, &banim_fifd_hk1_agbpal}, // 0xC5
	{"mf_mi1", &banim_mf_mi1_modes_bin, &banim_mf_mi1_motion_o, &banim_mf_mi1_oam_r_bin, &banim_mf_mi1_oam_l_bin, &banim_mf_mi1_agbpal}, // 0xC6
	{"prif_ro1", &banim_prif_ro1_2_modes_bin, &banim_prif_ro1_2_motion_o, &banim_prif_ro1_2_oam_r_bin, &banim_prif_ro1_2_oam_l_bin, &banim_prif_ro1_2_agbpal}, // 0xC7
	{"fifd_mg1", &banim_fifd_mg1_2_modes_bin, &banim_fifd_mg1_2_motion_o, &banim_fifd_mg1_2_oam_r_bin, &banim_fifd_mg1_2_oam_l_bin, &banim_fifd_mg1_2_agbpal}, // 0xC8
};
__attribute__((section(".data.banim_array_len")))
long long banim_number = sizeof(banim_data) / sizeof(banim_data[0]);
