#include "global.h"
#include "eventinfo.h"
#include "constants/characters.h"
#include "constants/event-flags.h"

CONST_DATA struct BattleTalkExtEnt gBattleTalkList[] = {
    {
        .pidA     = CHARACTER_VALTER_PROLOGUE,
        .pidB     = CHARACTER_SETH,
        .chapter = 0x40,
        .msg     = 0x090A,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_ONEILL,
        .chapter = 0x00,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0916,
    },
    {
        .pidA     = CHARACTER_ONEILL,
        .chapter = 0x00,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0916,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_BREGUET,
        .chapter = 0x01,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0935,
    },
    {
        .pidA     = CHARACTER_BREGUET,
        .chapter = 0x01,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0935,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_BONE,
        .chapter = 0x02,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0960,
    },
    {
        .pidA     = CHARACTER_BONE,
        .chapter = 0x02,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0960,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_BAZBA,
        .chapter = 0x03,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0993,
    },
    {
        .pidA     = CHARACTER_BAZBA,
        .chapter = 0x03,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0993,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_SAAR,
        .chapter = 0x06,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x09C7,
    },
    {
        .pidA     = CHARACTER_SAAR,
        .chapter = 0x06,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x09C7,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_ZONTA,
        .chapter = 0x05,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x09DF,
    },
    {
        .pidA     = CHARACTER_ZONTA,
        .chapter = 0x05,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x09DF,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_NOVALA,
        .chapter = 0x07,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x09EF,
    },
    {
        .pidA     = CHARACTER_NOVALA,
        .chapter = 0x07,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x09EF,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_MURRAY,
        .chapter = 0x08,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A02,
    },
    {
        .pidA     = CHARACTER_MURRAY,
        .chapter = 0x08,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A02,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_TIRADO,
        .chapter = 0x09,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A0E,
    },
    {
        .pidA     = CHARACTER_TIRADO,
        .chapter = 0x09,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A0E,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_BINKS,
        .chapter = 0x0A,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A20,
    },
    {
        .pidA     = CHARACTER_BINKS,
        .chapter = 0x0A,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A20,
    },
    {
        .pidA     = CHARACTER_AMELIA,
        .pidB     = CHARACTER_GHEB,
        .chapter = 0x17,
        .flag    = 0x0009,
        .msg     = 0x0AA9,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_GHEB,
        .chapter = 0x17,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0AAA,
    },
    {
        .pidA     = CHARACTER_GHEB,
        .chapter = 0x17,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0AAA,
    },
    {
        .pidA     = CHARACTER_INNES,
        .pidB     = CHARACTER_PABLO,
        .chapter = 0x0B,
        .flag    = 0x000C,
        .msg     = 0x0A33,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_PABLO,
        .chapter = 0x0B,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A34,
    },
    {
        .pidA     = CHARACTER_PABLO,
        .chapter = 0x0B,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A34,
    },
    {
        .pidA     = CHARACTER_DUESSEL,
        .pidB     = CHARACTER_CORMAG,
        .chapter = 0x18,
        .flag    = 0x0009,
        .msg     = 0x0ABD,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_BERAN,
        .chapter = 0x18,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0ABE,
    },
    {
        .pidA     = CHARACTER_BERAN,
        .chapter = 0x18,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0ABE,
    },
    {
        .pidA     = CHARACTER_EIRIKA,
        .pidB     = CHARACTER_AIAS,
        .chapter = 0x0D,
        .flag    = 0x0009,
        .msg     = 0x0A70,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_AIAS,
        .chapter = 0x0D,
        .flag    = 0x000A,
        .msg     = 0x0A71,
    },
    {
        .pidA     = CHARACTER_AIAS,
        .chapter = 0x0D,
        .flag    = 0x000A,
        .msg     = 0x0A71,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_PABLO,
        .chapter = 0x0D,
        .flag    = 0x000B,
        .msg     = 0x0A73,
    },
    {
        .pidA     = CHARACTER_PABLO,
        .chapter = 0x0D,
        .flag    = 0x000B,
        .msg     = 0x0A73,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_SELENA,
        .chapter = 0x1A,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0AF0,
    },
    {
        .pidA     = CHARACTER_SELENA,
        .chapter = 0x1A,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0AF0,
    },
    {
        .pidA     = CHARACTER_JOSHUA,
        .pidB     = CHARACTER_CARLYLE,
        .chapter = 0x0E,
        .flag    = 0x0007,
        .msg     = 0x0A88,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_CARLYLE,
        .chapter = 0x0E,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A89,
    },
    {
        .pidA     = CHARACTER_CARLYLE,
        .chapter = 0x0E,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0A89,
    },
    {
        .pidA     = CHARACTER_EPHRAIM,
        .pidB     = CHARACTER_VIGARDE,
        .chapter = 0x1B,
        .flag    = 0x0007,
        .msg     = 0x0B01,
    },
    {
        .pidA     = CHARACTER_DUESSEL,
        .pidB     = CHARACTER_VIGARDE,
        .chapter = 0x1B,
        .flag    = 0x0008,
        .msg     = 0x0B02,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_VIGARDE,
        .chapter = 0x1B,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B03,
    },
    {
        .pidA     = CHARACTER_VIGARDE,
        .chapter = 0x1B,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B03,
    },
    {
        .pidA     = CHARACTER_GLEN,
        .pidB     = CHARACTER_VALTER,
        .chapter = 0x41,
        .msg     = 0x0A51,
    },
    {
        .pidA     = CHARACTER_EIRIKA,
        .pidB     = CHARACTER_VALTER,
        .chapter = 0x0F,
        .flag    = 0x0007,
        .msg     = 0x0B1D,
    },
    {
        .pidA     = CHARACTER_EPHRAIM,
        .pidB     = CHARACTER_VALTER,
        .chapter = 0x0F,
        .flag    = 0x0008,
        .msg     = 0x0B1E,
    },
    {
        .pidA     = CHARACTER_CORMAG,
        .pidB     = CHARACTER_VALTER,
        .chapter = 0x0F,
        .flag    = 0x0009,
        .msg     = 0x0B1F,
    },
    {
        .pidA     = CHARACTER_JOSHUA,
        .pidB     = CHARACTER_CAELLACH,
        .chapter = 0x0F,
        .flag    = 0x000A,
        .msg     = 0x0B21,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_VALTER,
        .chapter = 0x0F,
        .flag    = 0x000B,
        .msg     = 0x0B23,
    },
    {
        .pidA     = CHARACTER_VALTER,
        .chapter = 0x0F,
        .flag    = 0x000B,
        .msg     = 0x0B23,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_CAELLACH,
        .chapter = 0x0F,
        .flag    = 0x000C,
        .msg     = 0x0B25,
    },
    {
        .pidA     = CHARACTER_CAELLACH,
        .chapter = 0x0F,
        .flag    = 0x000C,
        .msg     = 0x0B25,
    },
    {
        .pidA     = CHARACTER_EIRIKA,
        .pidB     = CHARACTER_VALTER,
        .chapter = 0x1C,
        .flag    = 0x0007,
        .msg     = 0x0B1D,
    },
    {
        .pidA     = CHARACTER_EPHRAIM,
        .pidB     = CHARACTER_VALTER,
        .chapter = 0x1C,
        .flag    = 0x0008,
        .msg     = 0x0B1E,
    },
    {
        .pidA     = CHARACTER_CORMAG,
        .pidB     = CHARACTER_VALTER,
        .chapter = 0x1C,
        .flag    = 0x0009,
        .msg     = 0x0B20,
    },
    {
        .pidA     = CHARACTER_JOSHUA,
        .pidB     = CHARACTER_CAELLACH,
        .chapter = 0x1C,
        .flag    = 0x000A,
        .msg     = 0x0B22,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_VALTER,
        .chapter = 0x1C,
        .flag    = 0x000B,
        .msg     = 0x0B23,
    },
    {
        .pidA     = CHARACTER_VALTER,
        .chapter = 0x1C,
        .flag    = 0x000B,
        .msg     = 0x0B23,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_CAELLACH,
        .chapter = 0x1C,
        .flag    = 0x000C,
        .msg     = 0x0B25,
    },
    {
        .pidA     = CHARACTER_CAELLACH,
        .chapter = 0x1C,
        .flag    = 0x000C,
        .msg     = 0x0B25,
    },
    {
        .pidA     = CHARACTER_EIRIKA,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x10,
        .flag    = 0x0007,
        .msg     = 0x0B42,
    },
    {
        .pidA     = CHARACTER_SETH,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x10,
        .flag    = 0x0008,
        .msg     = 0x0B44,
    },
    {
        .pidA     = CHARACTER_KYLE,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x10,
        .flag    = 0x0009,
        .msg     = 0x0B45,
    },
    {
        .pidA     = CHARACTER_FORDE,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x10,
        .flag    = 0x000A,
        .msg     = 0x0B46,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x10,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B47,
    },
    {
        .pidA     = CHARACTER_ORSON,
        .chapter = 0x10,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B47,
    },
    {
        .pidA     = CHARACTER_EPHRAIM,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x1D,
        .flag    = 0x0007,
        .msg     = 0x0B43,
    },
    {
        .pidA     = CHARACTER_SETH,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x1D,
        .flag    = 0x0008,
        .msg     = 0x0B44,
    },
    {
        .pidA     = CHARACTER_KYLE,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x1D,
        .flag    = 0x0009,
        .msg     = 0x0B45,
    },
    {
        .pidA     = CHARACTER_FORDE,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x1D,
        .flag    = 0x000A,
        .msg     = 0x0B46,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_ORSON,
        .chapter = 0x1D,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B47,
    },
    {
        .pidA     = CHARACTER_ORSON,
        .chapter = 0x1D,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B47,
    },
    {
        .pidA     = CHARACTER_EIRIKA,
        .pidB     = CHARACTER_LYON,
        .chapter = 0x11,
        .flag    = 0x0007,
        .msg     = 0x0B68,
    },
    {
        .pidA     = CHARACTER_EPHRAIM,
        .pidB     = CHARACTER_LYON,
        .chapter = 0x11,
        .flag    = 0x0008,
        .msg     = 0x0B69,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_LYON,
        .chapter = 0x11,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B6C,
    },
    {
        .pidA     = CHARACTER_LYON,
        .chapter = 0x11,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B6C,
    },
    {
        .pidA     = CHARACTER_EIRIKA,
        .pidB     = CHARACTER_LYON,
        .chapter = 0x1E,
        .flag    = 0x0007,
        .msg     = 0x0B6A,
    },
    {
        .pidA     = CHARACTER_EPHRAIM,
        .pidB     = CHARACTER_LYON,
        .chapter = 0x1E,
        .flag    = 0x0008,
        .msg     = 0x0B6B,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_LYON,
        .chapter = 0x1E,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B6C,
    },
    {
        .pidA     = CHARACTER_LYON,
        .chapter = 0x1E,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B6C,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_RIEV,
        .chapter = 0x13,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B9A,
    },
    {
        .pidA     = CHARACTER_RIEV,
        .chapter = 0x13,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B9A,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_RIEV,
        .chapter = 0x20,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B9A,
    },
    {
        .pidA     = CHARACTER_RIEV,
        .chapter = 0x20,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0B9A,
    },
    {
        .pidA     = CHARACTER_MYRRH,
        .pidB     = CHARACTER_MORVA,
        .chapter = 0x14,
        .flag    = 0x0007,
        .msg     = 0x0BAF,
    },
    {
        .pidA     = CHARACTER_LARACHEL,
        .pidB     = CHARACTER_RIEV,
        .chapter = 0x14,
        .flag    = 0x0008,
        .msg     = 0x0BB0,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_RIEV,
        .chapter = 0x14,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0BB1,
    },
    {
        .pidA     = CHARACTER_RIEV,
        .chapter = 0x14,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0BB1,
    },
    {
        .pidA     = CHARACTER_MYRRH,
        .pidB     = CHARACTER_MORVA,
        .chapter = 0x21,
        .flag    = 0x0007,
        .msg     = 0x0BAF,
    },
    {
        .pidA     = CHARACTER_LARACHEL,
        .pidB     = CHARACTER_RIEV,
        .chapter = 0x21,
        .flag    = 0x0008,
        .msg     = 0x0BB0,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_RIEV,
        .chapter = 0x21,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0BB1,
    },
    {
        .pidA     = CHARACTER_RIEV,
        .chapter = 0x21,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0BB1,
    },
    {
        .pidA     = CHARACTER_EIRIKA,
        .pidB     = CHARACTER_LYON_FINAL,
        .chapter = 0x15,
        .flag    = 0x0007,
        .msg     = 0x0BBF,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_LYON_FINAL,
        .chapter = 0x15,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0BC1,
    },
    {
        .pidA     = CHARACTER_LYON_FINAL,
        .chapter = 0x15,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0BC1,
    },
    {
        .pidA     = CHARACTER_EPHRAIM,
        .pidB     = CHARACTER_LYON_FINAL,
        .chapter = 0x22,
        .flag    = 0x0007,
        .msg     = 0x0BC0,
    },
    {
        .pidA     = CHAR_EVT_PLAYER_LEADER,
        .pidB     = CHARACTER_LYON_FINAL,
        .chapter = 0x22,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0BC3,
    },
    {
        .pidA     = CHARACTER_LYON_FINAL,
        .chapter = 0x22,
        .flag    = EVFLAG_BATTLE_QUOTES,
        .msg     = 0x0BC3,
    },
    {
        .pidA     = CHARACTER_EIRIKA,
        .pidB     = CHARACTER_FOMORTIIS,
        .chapter = 0x16,
        .flag    = 0x0007,
        .msg     = 0x0BF3,
    },
    {
        .pidA     = CHARACTER_EPHRAIM,
        .pidB     = CHARACTER_FOMORTIIS,
        .chapter = 0x23,
        .flag    = 0x0007,
        .msg     = 0x0BF4,
    },
    {
        .pidA     = CHARACTER_VANESSA,
        .chapter = 0xFE,
        .flag    = 0x007F,
        .msg     = 0x0900,
    },
    {
        .pidA     = CHARACTER_TANA,
        .chapter = 0xFE,
        .flag    = 0x0080,
        .msg     = 0x0901,
    },
    {
        .pidA     = CHARACTER_SYRENE,
        .chapter = 0xFE,
        .flag    = 0x0081,
        .msg     = 0x0902,
    },
    {
        .pidA     = 0xffff,
        .chapter = 0x00,
        .msg     = 0x0000,
    },
};

CONST_DATA struct DefeatTalkEnt gDefeatTalkList[] = {
    {
        .pid     = CHARACTER_ONEILL,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x00,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0917,
    },
    {
        .pid     = CHARACTER_BREGUET,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x01,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0936,
    },
    {
        .pid     = CHARACTER_BONE,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x02,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0961,
    },
    {
        .pid     = CHARACTER_BAZBA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x03,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0994,
    },
    {
        .pid     = CHARACTER_ENTOUMBED_CH4,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x04,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0000,
    },
    {
        .pid     = CHARACTER_NATASHA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x06,
        .msg     = 0x09C6,
    },
    {
        .pid     = CHARACTER_SAAR,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x06,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x09C8,
    },
    {
        .pid     = CHARACTER_ZONTA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x05,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x09E0,
    },
    {
        .pid     = CHARACTER_FORDE,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x05,
        .msg     = 0x09DC,
    },
    {
        .pid     = CHARACTER_KYLE,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x05,
        .msg     = 0x09DD,
    },
    {
        .pid     = CHARACTER_ORSON_CH5X,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x05,
        .msg     = 0x09DE,
    },
    {
        .pid     = CHARACTER_NOVALA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x07,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x09F0,
    },
    {
        .pid     = CHARACTER_MURRAY,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x08,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0A03,
    },
    {
        .pid     = CHARACTER_TIRADO,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x09,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0A0F,
    },
    {
        .pid     = CHARACTER_BINKS,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x0A,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0A21,
    },
    {
        .pid     = CHARACTER_GHEB,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x17,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0AAB,
    },
    {
        .pid     = CHARACTER_PABLO,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x0B,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0A35,
    },
    {
        .pid     = CHARACTER_DUESSEL,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x18,
        .flag    = EVFLAG_GAMEOVER,
        .msg     = 0x0C40,
    },
    {
        .pid     = CHARACTER_BERAN,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x18,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0ABF,
    },
    {
        .pid     = CHARACTER_CYCLOPS_CHUnk,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x19,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0000,
    },
    {
        .pid     = CHARACTER_AIAS,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x0D,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0A72,
    },
    {
        .pid     = CHARACTER_PABLO,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x0D,
        .msg     = 0x0A74,
    },
    {
        .pid     = CHARACTER_SELENA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x1A,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0AF1,
    },
    {
        .pid     = CHARACTER_CARLYLE,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x0E,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0A8A,
    },
    {
        .pid     = CHARACTER_VIGARDE,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x1B,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0B04,
    },
    {
        .pid     = CHARACTER_VALTER,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x0F,
        .msg     = 0x0B24,
    },
    {
        .pid     = CHARACTER_CAELLACH,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x0F,
        .msg     = 0x0B26,
    },
    {
        .pid     = CHARACTER_VALTER,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x1C,
        .msg     = 0x0B24,
    },
    {
        .pid     = CHARACTER_CAELLACH,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x1C,
        .msg     = 0x0B26,
    },
    {
        .pid     = CHARACTER_ORSON,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x10,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0B48,
    },
    {
        .pid     = CHARACTER_ORSON,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x1D,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0B48,
    },
    {
        .pid     = CHARACTER_LYON,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x11,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0B6D,
    },
    {
        .pid     = CHARACTER_LYON,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x1E,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0B6D,
    },
    {
        .pid     = CHARACTER_GORGON_CHUnk,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x12,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0000,
    },
    {
        .pid     = CHARACTER_GORGON_CHUnk,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x1F,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0000,
    },
    {
        .pid     = CHARACTER_MANSEL,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x13,
        .flag    = EVFLAG_GAMEOVER,
        .msg     = 0x0B99,
    },
    {
        .pid     = CHARACTER_RIEV,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x13,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0B9B,
    },
    {
        .pid     = CHARACTER_TANA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x20,
        .flag    = 0x0007,
        .msg     = 0x0C34,
    },
    {
        .pid     = CHARACTER_MANSEL,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x20,
        .flag    = EVFLAG_GAMEOVER,
        .msg     = 0x0B99,
    },
    {
        .pid     = CHARACTER_RIEV,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x20,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0B9B,
    },
    {
        .pid     = CHARACTER_RIEV,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x14,
        .msg     = 0x0BB2,
    },
    {
        .pid     = CHARACTER_RIEV,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x21,
        .msg     = 0x0BB2,
    },
    {
        .pid     = CHARACTER_LYON_FINAL,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x15,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0BC2,
    },
    {
        .pid     = CHARACTER_LYON_FINAL,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x22,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0BC4,
    },
    {
        .pid     = CHARACTER_FOMORTIIS,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x16,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0000,
    },
    {
        .pid     = CHARACTER_FOMORTIIS,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0x23,
        .flag    = EVFLAG_DEFEAT_BOSS,
        .msg     = 0x0000,
    },
    {
        .pid     = CHARACTER_EIRIKA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .flag    = EVFLAG_GAMEOVER,
        .msg     = 0x0C23,
    },
    {
        .pid     = CHARACTER_EPHRAIM,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .flag    = EVFLAG_GAMEOVER,
        .msg     = 0x0C24,
    },
    {
        .pid     = CHARACTER_SETH,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C25,
    },
    {
        .pid     = CHARACTER_FRANZ,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C26,
    },
    {
        .pid     = CHARACTER_GILLIAM,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C27,
    },
    {
        .pid     = CHARACTER_MOULDER,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C28,
    },
    {
        .pid     = CHARACTER_VANESSA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C29,
    },
    {
        .pid     = CHARACTER_GARCIA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C2A,
    },
    {
        .pid     = CHARACTER_ROSS,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C2B,
    },
    {
        .pid     = CHARACTER_COLM,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C2C,
    },
    {
        .pid     = CHARACTER_NEIMI,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C2D,
    },
    {
        .pid     = CHARACTER_ARTUR,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C2E,
    },
    {
        .pid     = CHARACTER_LUTE,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C2F,
    },
    {
        .pid     = CHARACTER_NATASHA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C30,
    },
    {
        .pid     = CHARACTER_JOSHUA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C31,
    },
    {
        .pid     = CHARACTER_KYLE,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C32,
    },
    {
        .pid     = CHARACTER_FORDE,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C33,
    },
    {
        .pid     = CHARACTER_TANA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C34,
    },
    {
        .pid     = CHARACTER_INNES,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C35,
    },
    {
        .pid     = CHARACTER_GERIK,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C36,
    },
    {
        .pid     = CHARACTER_TETHYS,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C37,
    },
    {
        .pid     = CHARACTER_MARISA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C38,
    },
    {
        .pid     = CHARACTER_SALEH,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C39,
    },
    {
        .pid     = CHARACTER_EWAN,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C3A,
    },
    {
        .pid     = CHARACTER_LARACHEL,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C3B,
    },
    {
        .pid     = CHARACTER_DOZLA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C3C,
    },
    {
        .pid     = CHARACTER_CORMAG,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C3D,
    },
    {
        .pid     = CHARACTER_AMELIA,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .flag    = 0x0086,
        .msg     = 0x0C3E,
    },
    {
        .pid     = CHARACTER_RENNAC,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C3F,
    },
    {
        .pid     = CHARACTER_DUESSEL,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C40,
    },
    {
        .pid     = CHARACTER_MYRRH,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C41,
    },
    {
        .pid     = CHARACTER_KNOLL,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C42,
    },
    {
        .pid     = CHARACTER_SYRENE,
        .route   = CHAPTER_MODE_ANY,
        .chapter = 0xFF,
        .msg     = 0x0C43,
    },

    {
        .pid = -1
    }
};
