#include "global.h"
#include "bmunit.h"
#include "bmitem.h"
#include "bmreliance.h"
#include "constants/characters.h"
#include "constants/classes.h"
#include "constants/items.h"


CONST_DATA struct CharacterData gCharacterData[] = {
    [CHARACTER_EIRIKA - 1] = {
        .nameTextId   = 0x212,
        .descTextId   = 0x26E,
        .number       = CHARACTER_EIRIKA,
        .defaultClass = CLASS_EIRIKA_LORD,
        .portraitId   = 0x02,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_LIGHT,
        .sort_order   = 0x01,

        .baseLevel = 1,
        .baseHP =  0,
        .basePow = 0,
        .baseSkl = 0,
        .baseSpd = 0,
        .baseDef = 0,
        .baseRes = 0,
        .baseLck = 5,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_E,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 70,
        .growthPow = 40,
        .growthSkl = 60,
        .growthSpd = 60,
        .growthDef = 30,
        .growthRes = 30,
        .growthLck = 60,

        .attributes = CA_FEMALE,
        .pSupportData = &gSupportData[0],
        .visit_group = 0x07,
    },

    [CHARACTER_SETH - 1] = {
        .nameTextId   = 0x213,
        .descTextId   = 0x26F,
        .number       = CHARACTER_SETH,
        .defaultClass = CLASS_PALADIN,
        .portraitId   = 0x04,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x03,
        .baseLevel    = 1,

        .baseHP  = 7,
        .basePow = 7,
        .baseSkl = 9,
        .baseSpd = 5,
        .baseDef = 3,
        .baseRes = 5,
        .baseLck = 13,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_A,
            [ITYPE_LANCE] = WPN_EXP_A,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 90,
        .growthPow = 50,
        .growthSkl = 45,
        .growthSpd = 45,
        .growthDef = 40,
        .growthRes = 30,
        .growthLck = 25,

        .attributes = 0,
        .pSupportData = &gSupportData[2],
        .visit_group = 0x03,
    },

    [CHARACTER_GILLIAM - 1] = {
        .nameTextId   = 0x214,
        .descTextId   = 0x270,
        .number       = CHARACTER_GILLIAM,
        .defaultClass = CLASS_ARMOR_KNIGHT,
        .portraitId   = 0x05,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_THUNDER,
        .sort_order   = 0x07,
        .baseLevel    = 4,

        .baseHP  = 8,
        .basePow = 4,
        .baseSkl = 4,
        .baseSpd = 3,
        .baseDef = 0,
        .baseRes = 3,
        .baseLck = 3,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_C,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 90,
        .growthPow = 45,
        .growthSkl = 35,
        .growthSpd = 30,
        .growthDef = 55,
        .growthRes = 20,
        .growthLck = 30,

        .attributes   = 0,
        .pSupportData = &gSupportData[4],
        .visit_group  = 0x04,
    },

    [CHARACTER_FRANZ - 1] = {
        .nameTextId   = 0x215,
        .descTextId   = 0x271,
        .number       = CHARACTER_FRANZ,
        .defaultClass = CHARACTER_MOULDER,
        .portraitId   = 0x06,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_LIGHT,
        .sort_order   = 0x06,
        .baseLevel    = 1,

        .baseHP  = 0,
        .basePow = 2,
        .baseSkl = 3,
        .baseSpd = 2,
        .baseDef = 0,
        .baseRes = 1,
        .baseLck = 2,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_E,
            [ITYPE_LANCE] = WPN_EXP_D,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 80,
        .growthPow = 40,
        .growthSkl = 40,
        .growthSpd = 50,
        .growthDef = 25,
        .growthRes = 20,
        .growthLck = 40,

        .attributes   = 0,
        .pSupportData = &gSupportData[3],
        .visit_group  = 0x03,
    },

    [CHARACTER_MOULDER - 1] = {
        .nameTextId   = 0x216,
        .descTextId   = 0x272,
        .number       = CHARACTER_MOULDER,
        .defaultClass = CLASS_PRIEST,
        .portraitId   = 0x07,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x08,
        .baseLevel    = 3,

        .baseHP  = 2,
        .basePow = 3,
        .baseSkl = 5,
        .baseSpd = 7,
        .baseDef = 1,
        .baseRes = 0,
        .baseLck = 1,
        .baseCon = 4,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_C,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 70,
        .growthPow = 40,
        .growthSkl = 50,
        .growthSpd = 40,
        .growthDef = 25,
        .growthRes = 25,
        .growthLck = 20,

        .attributes   = 0,
        .pSupportData = &gSupportData[5],
        .visit_group  = 0x04,
    },
    
    [CHARACTER_VANESSA - 1] = {
        .nameTextId   = 0x217,
        .descTextId   = 0x273,
        .number       = CHARACTER_VANESSA,
        .defaultClass = CLASS_PEGASUS_KNIGHT,
        .portraitId   = 0x08,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x09,
        .baseLevel    = 1,

        .baseHP  = 3,
        .basePow = 1,
        .baseSkl = 2,
        .baseSpd = 6,
        .baseDef = 3,
        .baseRes = 3,
        .baseLck = 4,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_D,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 50,
        .growthPow = 35,
        .growthSkl = 55,
        .growthSpd = 60,
        .growthDef = 20,
        .growthRes = 30,
        .growthLck = 50,

        .attributes   = CA_FEMALE | CA_TRIANGLEATTACK_PEGASI,
        .pSupportData = &gSupportData[6],
        .visit_group  = 0x0A,
    },

    [CHARACTER_ROSS - 1] = {
        .nameTextId   = 0x218,
        .descTextId   = 0x274,
        .number       = CHARACTER_ROSS,
        .defaultClass = CLASS_JOURNEYMAN,
        .portraitId   = 0x09,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x0A,
        .baseLevel    = 1,

        .baseHP  = 1,
        .basePow = 2,
        .baseSkl = 2,
        .baseSpd = 2,
        .baseDef = 2,
        .baseRes = 0,
        .baseLck = 8,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_E,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 70,
        .growthPow = 50,
        .growthSkl = 35,
        .growthSpd = 30,
        .growthDef = 25,
        .growthRes = 20,
        .growthLck = 40,

        .attributes   = 0,
        .pSupportData = &gSupportData[8],
        .visit_group  = 0x05,
    },

    [CHARACTER_NEIMI - 1] = {
        .nameTextId   = 0x219,
        .descTextId   = 0x275,
        .number       = CHARACTER_NEIMI,
        .defaultClass = CLASS_ARCHER_F,
        .portraitId   = 0x0A,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x0B,
        .baseLevel    = 1,

        .baseHP  = 0,
        .basePow = 1,
        .baseSkl = 2,
        .baseSpd = 2,
        .baseDef = 0,
        .baseRes = 2,
        .baseLck = 4,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_D,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 55,
        .growthPow = 45,
        .growthSkl = 50,
        .growthSpd = 60,
        .growthDef = 15,
        .growthRes = 35,
        .growthLck = 50,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[0xA],
        .visit_group  = 0x07,
    },

    [CHARACTER_COLM - 1] = {
        .nameTextId   = 0x21A,
        .descTextId   = 0x276,
        .number       = CHARACTER_COLM,
        .defaultClass = CLASS_THIEF,
        .portraitId   = 0x0C,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_LIGHT,
        .sort_order   = 0x0C,
        .baseLevel    = 2,

        .baseHP  = 2,
        .basePow = 1,
        .baseSkl = 3,
        .baseSpd = 1,
        .baseDef = 1,
        .baseRes = 1,
        .baseLck = 8,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_E,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 75,
        .growthPow = 40,
        .growthSkl = 40,
        .growthSpd = 65,
        .growthDef = 25,
        .growthRes = 20,
        .growthLck = 45,

        .attributes   = 0,
        .pSupportData = &gSupportData[9],
        .visit_group  = 0x00,
    },

    [CHARACTER_GARCIA - 1] = {
        .nameTextId   = 0x21B,
        .descTextId   = 0x277,
        .number       = CHARACTER_GARCIA,
        .defaultClass = CLASS_FIGHTER,
        .portraitId   = 0x0E,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x0D,
        .baseLevel    = 4,

        .baseHP  = 8,
        .basePow = 3,
        .baseSkl = 5,
        .baseSpd = 3,
        .baseDef = 3,
        .baseRes = 1,
        .baseLck = 3,
        .baseCon = 3,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_C,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 80,
        .growthPow = 65,
        .growthSkl = 40,
        .growthSpd = 20,
        .growthDef = 25,
        .growthRes = 15,
        .growthLck = 40,

        .attributes   = 0,
        .pSupportData = &gSupportData[7],
        .visit_group  = 0x01,
    },

    [CHARACTER_INNES - 1] = {
        .nameTextId   = 0x21C,
        .descTextId   = 0x278,
        .number       = CHARACTER_INNES,
        .defaultClass = CLASS_SNIPER,
        .portraitId   = 0x0F,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x14,
        .baseLevel    = 1,

        .baseHP  = 10,
        .basePow = 7,
        .baseSkl = 7,
        .baseSpd = 10,
        .baseDef = 5,
        .baseRes = 7,
        .baseLck = 14,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_A,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 75,
        .growthPow = 40,
        .growthSkl = 40,
        .growthSpd = 45,
        .growthDef = 20,
        .growthRes = 25,
        .growthLck = 45,

        .attributes   = 0,
        .pSupportData = &gSupportData[18],
        .visit_group  = 0x00,
    },

    [CHARACTER_LUTE - 1] = {
        .nameTextId   = 0x21D,
        .descTextId   = 0x279,
        .number       = CHARACTER_LUTE,
        .defaultClass = CLASS_MAGE_F,
        .portraitId   = 0x10,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x0F,
        .baseLevel    = 1,

        .baseHP  = 1,
        .basePow = 5,
        .baseSkl = 3,
        .baseSpd = 5,
        .baseDef = 1,
        .baseRes = 1,
        .baseLck = 8,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_C,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 45,
        .growthPow = 65,
        .growthSkl = 30,
        .growthSpd = 45,
        .growthDef = 15,
        .growthRes = 40,
        .growthLck = 45,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[0x0C],
        .visit_group  = 0x07,
    },

    [CHARACTER_NATASHA - 1] = {
        .nameTextId   = 0x21E,
        .descTextId   = 0x27A,
        .number       = CHARACTER_NATASHA,
        .defaultClass = CLASS_CLERIC,
        .portraitId   = 0x11,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x10,
        .baseLevel    = 1,

        .baseHP  = 2,
        .basePow = 1,
        .baseSkl = 2,
        .baseSpd = 6,
        .baseDef = 2,
        .baseRes = 0,
        .baseLck = 6,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_D,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 50,
        .growthPow = 60,
        .growthSkl = 25,
        .growthSpd = 40,
        .growthDef = 15,
        .growthRes = 55,
        .growthLck = 60,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[0x0D],
        .visit_group  = 0x0A,
    },

    [CHARACTER_CORMAG - 1] = {
        .nameTextId   = 0x21F,
        .descTextId   = 0x27B,
        .number       = CHARACTER_CORMAG,
        .defaultClass = CLASS_WYVERN_RIDER,
        .portraitId   = 0x13,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x1F,
        .baseLevel    = 9,

        .baseHP  = 10,
        .basePow = 7,
        .baseSkl = 6,
        .baseSpd = 5,
        .baseDef = 4,
        .baseRes = 2,
        .baseLck = 4,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_C,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 55,
        .growthSkl = 40,
        .growthSpd = 45,
        .growthDef = 25,
        .growthRes = 15,
        .growthLck = 35,

        .attributes   = 0,
        .pSupportData = &gSupportData[26],
        .visit_group  = 0x00,
    },

    [CHARACTER_EPHRAIM - 1] = {
        .nameTextId   = 0x220,
        .descTextId   = 0x27C,
        .number       = CHARACTER_EPHRAIM,
        .defaultClass = CLASS_EPHRAIM_LORD,
        .portraitId   = 0x14,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x01,
        .baseLevel    = 4,

        .baseHP  = 5,
        .basePow = 2,
        .baseSkl = 3,
        .baseSpd = 4,
        .baseDef = 1,
        .baseRes = 2,
        .baseLck = 8,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_D,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 80,
        .growthPow = 55,
        .growthSkl = 55,
        .growthSpd = 45,
        .growthDef = 35,
        .growthRes = 25,
        .growthLck = 50,

        .attributes   = 0,
        .pSupportData = &gSupportData[1],
        .visit_group  = 0x03,
    },

    [CHARACTER_FORDE - 1] = {
        .nameTextId   = 0x221,
        .descTextId   = 0x27D,
        .number       = CHARACTER_FORDE,
        .defaultClass = CLASS_CAVALIER,
        .portraitId   = 0x16,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_WIND,
        .sort_order   = 0x05,
        .baseLevel    = 5,

        .baseHP  = 4,
        .basePow = 2,
        .baseSkl = 6,
        .baseSpd = 3,
        .baseDef = 2,
        .baseRes = 2,
        .baseLck = 7,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_D,
            [ITYPE_LANCE] = WPN_EXP_C,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 40,
        .growthSkl = 50,
        .growthSpd = 45,
        .growthDef = 20,
        .growthRes = 25,
        .growthLck = 35,

        .attributes   = 0,
        .pSupportData = &gSupportData[16],
        .visit_group  = 0x03,
    },

    [CHARACTER_KYLE - 1] = {
        .nameTextId   = 0x222,
        .descTextId   = 0x27E,
        .number       = CHARACTER_KYLE,
        .defaultClass = CLASS_CAVALIER,
        .portraitId   = 0x18,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x04,
        .baseLevel    = 6,

        .baseHP  = 5,
        .basePow = 4,
        .baseSkl = 4,
        .baseSpd = 2,
        .baseDef = 3,
        .baseRes = 1,
        .baseLck = 6,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_D,
            [ITYPE_LANCE] = WPN_EXP_C,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 90,
        .growthPow = 50,
        .growthSkl = 40,
        .growthSpd = 40,
        .growthDef = 25,
        .growthRes = 20,
        .growthLck = 20,

        .attributes   = 0,
        .pSupportData = &gSupportData[15],
        .visit_group  = 0x03,
    },

    [CHARACTER_AMELIA - 1] = {
        .nameTextId   = 0x223,
        .descTextId   = 0x27F,
        .number       = CHARACTER_AMELIA,
        .defaultClass = CLASS_RECRUIT,
        .portraitId   = 0x19,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_THUNDER,
        .sort_order   = 0x13,
        .baseLevel    = 1,

        .baseHP  = 3,
        .basePow = 1,
        .baseSkl = 3,
        .baseSpd = 3,
        .baseDef = 2,
        .baseRes = 2,
        .baseLck = 6,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_E,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 60,
        .growthPow = 35,
        .growthSkl = 40,
        .growthSpd = 40,
        .growthDef = 30,
        .growthRes = 15,
        .growthLck = 50,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[27],
        .visit_group  = 0x07,
    },

    [CHARACTER_ARTUR - 1] = {
        .nameTextId   = 0x224,
        .descTextId   = 0x280,
        .number       = CHARACTER_ARTUR,
        .defaultClass = CLASS_MONK,
        .portraitId   = 0x1A,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x0E,
        .baseLevel    = 2,

        .baseHP  = 1,
        .basePow = 5,
        .baseSkl = 5,
        .baseSpd = 6,
        .baseDef = 1,
        .baseRes = 1,
        .baseLck = 2,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_E,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 55,
        .growthPow = 50,
        .growthSkl = 50,
        .growthSpd = 40,
        .growthDef = 15,
        .growthRes = 55,
        .growthLck = 25,

        .attributes   = 0,
        .pSupportData = &gSupportData[0x0B],
        .visit_group  = 0x00,
    },

    [CHARACTER_GERIK - 1] = {
        .nameTextId   = 0x225,
        .descTextId   = 0x281,
        .number       = CHARACTER_GERIK,
        .defaultClass = CLASS_MERCENARY,
        .portraitId   = 0x1B,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_THUNDER,
        .sort_order   = 0x15,
        .baseLevel    = 10,

        .baseHP  = 14,
        .basePow = 10,
        .baseSkl = 5,
        .baseSpd = 5,
        .baseDef = 6,
        .baseRes = 4,
        .baseLck = 8,
        .baseCon = 4,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_C,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 90,
        .growthPow = 45,
        .growthSkl = 40,
        .growthSpd = 30,
        .growthDef = 35,
        .growthRes = 25,
        .growthLck = 30,

        .attributes   = 0,
        .pSupportData = &gSupportData[0x13],
        .visit_group  = 0x04,
    },

    [CHARACTER_TETHYS - 1] = {
        .nameTextId   = 0x226,
        .descTextId   = 0x282,
        .number       = CHARACTER_TETHYS,
        .defaultClass = CLASS_DANCER,
        .portraitId   = 0x1C,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x16,
        .baseLevel    = 1,

        .baseHP  = 4,
        .basePow = 0,
        .baseSkl = 0,
        .baseSpd = 5,
        .baseDef = 5,
        .baseRes = 3,
        .baseLck = 10,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 5,
        .growthSkl = 10,
        .growthSpd = 70,
        .growthDef = 30,
        .growthRes = 75,
        .growthLck = 80,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[0x14],
        .visit_group  = 0x07,
    },

    [CHARACTER_MARISA - 1] = {
        .nameTextId   = 0x227,
        .descTextId   = 0x283,
        .number       = CHARACTER_MARISA,
        .defaultClass = CLASS_MYRMIDON_F,
        .portraitId   = 0x1E,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x17,
        .baseLevel    = 5,

        .baseHP  = 8,
        .basePow = 4,
        .baseSkl = 3,
        .baseSpd = 3,
        .baseDef = 3,
        .baseRes = 2,
        .baseLck = 9,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_D,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 75,
        .growthPow = 30,
        .growthSkl = 55,
        .growthSpd = 60,
        .growthDef = 15,
        .growthRes = 25,
        .growthLck = 50,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[0x15],
        .visit_group  = 0x0C,
    },

    [CHARACTER_SALEH - 1] = {
        .nameTextId   = 0x228,
        .descTextId   = 0x284,
        .number       = CHARACTER_SALEH,
        .defaultClass = CLASS_SAGE,
        .portraitId   = 0x20,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_WIND,
        .sort_order   = 0x18,
        .baseLevel    = 2,

        .baseHP  = 10,
        .basePow = 11,
        .baseSkl = 14,
        .baseSpd = 10,
        .baseDef = 3,
        .baseRes = 8,
        .baseLck = 11,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_C,
            [ITYPE_ANIMA] = WPN_EXP_A,
            [ITYPE_LIGHT] = WPN_EXP_B,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 50,
        .growthPow = 30,
        .growthSkl = 25,
        .growthSpd = 40,
        .growthDef = 30,
        .growthRes = 35,
        .growthLck = 40,

        .attributes   = 0,
        .pSupportData = &gSupportData[0x16],
        .visit_group  = 0x06,
    },

    [CHARACTER_EWAN - 1] = {
        .nameTextId   = 0x229,
        .descTextId   = 0x285,
        .number       = CHARACTER_EWAN,
        .defaultClass = CLASS_PUPIL,
        .portraitId   = 0x21,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_LIGHT,
        .sort_order   = 0x19,
        .baseLevel    = 2,

        .baseHP  = 2,
        .basePow = 2,
        .baseSkl = 2,
        .baseSpd = 4,
        .baseDef = 0,
        .baseRes = 0,
        .baseLck = 5,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_E,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 50,
        .growthPow = 45,
        .growthSkl = 40,
        .growthSpd = 35,
        .growthDef = 15,
        .growthRes = 40,
        .growthLck = 50,

        .attributes   = 0,
        .pSupportData = &gSupportData[0x17],
        .visit_group  = 0x05,
    },

    [CHARACTER_LARACHEL - 1] = {
        .nameTextId   = 0x22A,
        .descTextId   = 0x286,
        .number       = CHARACTER_LARACHEL,
        .defaultClass = CLASS_TROUBADOUR,
        .portraitId   = 0x22,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_LIGHT,
        .sort_order   = 0x1B,
        .baseLevel    = 3,

        .baseHP  = 3,
        .basePow = 5,
        .baseSkl = 5,
        .baseSpd = 7,
        .baseDef = 3,
        .baseRes = 3,
        .baseLck = 12,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_D,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 45,
        .growthPow = 50,
        .growthSkl = 45,
        .growthSpd = 45,
        .growthDef = 15,
        .growthRes = 50,
        .growthLck = 65,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[0x18],
        .visit_group  = 0x0B,
    },

    [CHARACTER_DOZLA - 1] = {
        .nameTextId   = 0x22B,
        .descTextId   = 0x287,
        .number       = CHARACTER_DOZLA,
        .defaultClass = CLASS_BERSERKER,
        .portraitId   = 0x23,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_THUNDER,
        .sort_order   = 0x1C,
        .baseLevel    = 1,

        .baseHP  = 19,
        .basePow = 9,
        .baseSkl = 5,
        .baseSpd = 2,
        .baseDef = 5,
        .baseRes = 6,
        .baseLck = 4,
        .baseCon = 3,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_B,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 50,
        .growthSkl = 35,
        .growthSpd = 40,
        .growthDef = 30,
        .growthRes = 25,
        .growthLck = 30,

        .attributes   = 0,
        .pSupportData = &gSupportData[0x19],
        .visit_group  = 0x04,
    },

    [CHARACTER_RENNAC - 1] = {
        .nameTextId   = 0x22D,
        .descTextId   = 0x288,
        .number       = CHARACTER_RENNAC,
        .defaultClass = CLASS_ROGUE,
        .portraitId   = 0x24,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_DARK,
        .sort_order   = 0x1D,
        .baseLevel    = 1,

        .baseHP  = 12,
        .basePow = 7,
        .baseSkl = 15,
        .baseSpd = 8,
        .baseDef = 7,
        .baseRes = 11,
        .baseLck = 5,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_B,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 65,
        .growthPow = 25,
        .growthSkl = 45,
        .growthSpd = 60,
        .growthDef = 25,
        .growthRes = 30,
        .growthLck = 25,

        .attributes   = 0,
        .pSupportData = &gSupportData[28],
        .visit_group  = 0x00,
    },

    [CHARACTER_DUESSEL - 1] = {
        .nameTextId   = 0x22E,
        .descTextId   = 0x289,
        .number       = CHARACTER_DUESSEL,
        .defaultClass = CLASS_GREAT_KNIGHT,
        .portraitId   = 0x25,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x1E,
        .baseLevel    = 8,

        .baseHP  = 20,
        .basePow = 9,
        .baseSkl = 8,
        .baseSpd = 6,
        .baseDef = 6,
        .baseRes = 6,
        .baseLck = 8,
        .baseCon = 2,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_A,
            [ITYPE_LANCE] = WPN_EXP_A,
            [ITYPE_AXE]   = WPN_EXP_A,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 55,
        .growthSkl = 40,
        .growthSpd = 30,
        .growthDef = 45,
        .growthRes = 30,
        .growthLck = 20,

        .attributes   = 0,
        .pSupportData = &gSupportData[29],
        .visit_group  = 0x04,
    },

    [CHARACTER_MYRRH - 1] = {
        .nameTextId   = 0x22F,
        .descTextId   = 0x28A,
        .number       = CHARACTER_MYRRH,
        .defaultClass = CLASS_MANAKETE_MYRRH,
        .portraitId   = 0x26,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_WIND,
        .sort_order   = 0x22,
        .baseLevel    = 1,

        .baseHP  = 3,
        .basePow = 3,
        .baseSkl = 1,
        .baseSpd = 3,
        .baseDef = 0,
        .baseRes = 5,
        .baseLck = 3,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 130,
        .growthPow = 90,
        .growthSkl = 85,
        .growthSpd = 65,
        .growthDef = 150,
        .growthRes = 30,
        .growthLck = 30,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[30],
        .visit_group  = 0x0C,
    },

    [CHARACTER_KNOLL - 1] = {
        .nameTextId   = 0x230,
        .descTextId   = 0x28B,
        .number       = CHARACTER_KNOLL,
        .defaultClass = CLASS_SHAMAN,
        .portraitId   = 0x29,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_DARK,
        .sort_order   = 0x20,
        .baseLevel    = 9,

        .baseHP  = 5,
        .basePow = 10,
        .baseSkl = 8,
        .baseSpd = 6,
        .baseDef = 0,
        .baseRes = 6,
        .baseLck = 0,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_C,
        },

        .growthHP  = 70,
        .growthPow = 50,
        .growthSkl = 40,
        .growthSpd = 35,
        .growthDef = 10,
        .growthRes = 45,
        .growthLck = 20,

        .attributes   = 0,
        .pSupportData = &gSupportData[31],
        .visit_group  = 0x03,
    },

    [CHARACTER_JOSHUA - 1] = {
        .nameTextId   = 0x231,
        .descTextId   = 0x28C,
        .number       = CHARACTER_JOSHUA,
        .defaultClass = CLASS_MYRMIDON,
        .portraitId   = 0x2A,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_WIND,
        .sort_order   = 0x11,
        .baseLevel    = 5,

        .baseHP  = 8,
        .basePow = 4,
        .baseSkl = 4,
        .baseSpd = 5,
        .baseDef = 3,
        .baseRes = 2,
        .baseLck = 7,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_C,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 80,
        .growthPow = 35,
        .growthSkl = 55,
        .growthSpd = 55,
        .growthDef = 20,
        .growthRes = 20,
        .growthLck = 30,

        .attributes   = 0,
        .pSupportData = &gSupportData[0x0E],
        .visit_group  = 0x03,
    },

    [CHARACTER_SYRENE - 1] = {
        .nameTextId   = 0x232,
        .descTextId   = 0x28D,
        .number       = CHARACTER_SYRENE,
        .defaultClass = CLASS_FALCON_KNIGHT,
        .portraitId   = 0x2B,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_THUNDER,
        .sort_order   = 0x23,
        .baseLevel    = 1,

        .baseHP  = 7,
        .basePow = 6,
        .baseSkl = 6,
        .baseSpd = 8,
        .baseDef = 5,
        .baseRes = 8,
        .baseLck = 12,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_C,
            [ITYPE_LANCE] = WPN_EXP_A,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 70,
        .growthPow = 40,
        .growthSkl = 50,
        .growthSpd = 60,
        .growthDef = 20,
        .growthRes = 50,
        .growthLck = 30,

        .attributes   = CA_FEMALE | CA_TRIANGLEATTACK_PEGASI,
        .pSupportData = &gSupportData[32],
        .visit_group  = 0x0A,
    },

    [CHARACTER_TANA - 1] = {
        .nameTextId   = 0x233,
        .descTextId   = 0x28E,
        .number       = CHARACTER_TANA,
        .defaultClass = CLASS_PEGASUS_KNIGHT,
        .portraitId   = 0x2C,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_WIND,
        .sort_order   = 0x12,
        .baseLevel    = 4,

        .baseHP  = 6,
        .basePow = 3,
        .baseSkl = 4,
        .baseSpd = 8,
        .baseDef = 3,
        .baseRes = 5,
        .baseLck = 8,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_D,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 65,
        .growthPow = 45,
        .growthSkl = 40,
        .growthSpd = 65,
        .growthDef = 20,
        .growthRes = 25,
        .growthLck = 60,

        .attributes   = CA_FEMALE | CA_TRIANGLEATTACK_PEGASI,
        .pSupportData = &gSupportData[17],
        .visit_group  = 0xA,
    },

    [CHARACTER_LYON_CC - 1] = {
        .nameTextId   = 0x234,
        .descTextId   = 0x28F,
        .number       = CHARACTER_LYON_CC,
        .defaultClass = CLASS_NECROMANCER,
        .portraitId   = 0x46,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x24,
        .baseLevel    = 14,

        .baseHP  = 26,
        .basePow = 13,
        .baseSkl = 9,
        .baseSpd = 6,
        .baseDef = 14,
        .baseRes = 11,
        .baseLck = 4,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_A,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_S,
        },

        .growthHP  = 85,
        .growthPow = 50,
        .growthSkl = 55,
        .growthSpd = 55,
        .growthDef = 45,
        .growthRes = 55,
        .growthLck = 30,

        .attributes   = 0,
    },

    [CHARACTER_ORSON_CC - 1] = {
        .nameTextId   = 0x236,
        .descTextId   = 0x291,
        .number       = CHARACTER_ORSON_CC,
        .defaultClass = CLASS_PALADIN,
        .portraitId   = 0x45,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_DARK,
        .sort_order   = 0x28,
        .baseLevel    = 13,

        .baseHP  = 25,
        .basePow = 11,
        .baseSkl = 11,
        .baseSpd = 7,
        .baseDef = 6,
        .baseRes = 8,
        .baseLck = 6,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_A,
            [ITYPE_LANCE] = WPN_EXP_A,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 80,
        .growthPow = 55,
        .growthSkl = 45,
        .growthSpd = 40,
        .growthDef = 45,
        .growthRes = 30,
        .growthLck = 25,

        .attributes   = 0,
    },

    [CHARACTER_GLEN_CC - 1] = {
        .nameTextId   = 0x24A,
        .descTextId   = 0x2A4,
        .number       = CHARACTER_GLEN_CC,
        .defaultClass = CLASS_WYVERN_LORD,
        .portraitId   = 0x4B,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_WIND,
        .sort_order   = 0x27,
        .baseLevel    = 12,

        .baseHP  = 21,
        .basePow = 11,
        .baseSkl = 12,
        .baseSpd = 6,
        .baseDef = 8,
        .baseRes = 4,
        .baseLck = 7,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_A,
            [ITYPE_LANCE] = WPN_EXP_A,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 45,
        .growthSkl = 50,
        .growthSpd = 45,
        .growthDef = 35,
        .growthRes = 40,
        .growthLck = 20,

        .attributes   = 0,
    },

    [CHARACTER_SELENA_CC - 1] = {
        .nameTextId   = 0x238,
        .descTextId   = 0x293,
        .number       = CHARACTER_SELENA_CC,
        .defaultClass = CLASS_MAGE_KNIGHT_F,
        .portraitId   = 0x3F,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_THUNDER,
        .sort_order   = 0x26,
        .baseLevel    = 11,

        .baseHP  = 19,
        .basePow = 10,
        .baseSkl = 8,
        .baseSpd = 10,
        .baseDef = 8,
        .baseRes = 11,
        .baseLck = 10,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_B,
            [ITYPE_ANIMA] = WPN_EXP_A,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 40,
        .growthSkl = 55,
        .growthSpd = 40,
        .growthDef = 20,
        .growthRes = 30,
        .growthLck = 25,

        .attributes   = CA_FEMALE,
    },

    [CHARACTER_VALTER_CC - 1] = {
        .nameTextId   = 0x237,
        .descTextId   = 0x292,
        .number       = CHARACTER_VALTER_CC,
        .defaultClass = CLASS_WYVERN_KNIGHT,
        .portraitId   = 0x42,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x29,
        .baseLevel    = 13,

        .baseHP  = 25,
        .basePow = 12,
        .baseSkl = 10,
        .baseSpd = 9,
        .baseDef = 6,
        .baseRes = 11,
        .baseLck = 3,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_S,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 80,
        .growthPow = 40,
        .growthSkl = 55,
        .growthSpd = 50,
        .growthDef = 20,
        .growthRes = 20,
        .growthLck = 15,

        .attributes   = 0,
    },

    [CHARACTER_RIEV_CC - 1] = {
        .nameTextId   = 0x246,
        .descTextId   = 0x2A0,
        .number       = CHARACTER_RIEV_CC,
        .defaultClass = CLASS_BISHOP,
        .portraitId   = 0x48,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_DARK,
        .sort_order   = 0x2B,
        .baseLevel    = 16,

        .baseHP  = 28,
        .basePow = 10,
        .baseSkl = 17,
        .baseSpd = 15,
        .baseDef = 13,
        .baseRes = 10,
        .baseLck = 9,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_A,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_S,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 75,
        .growthPow = 45,
        .growthSkl = 50,
        .growthSpd = 40,
        .growthDef = 20,
        .growthRes = 45,
        .growthLck = 15,

        .attributes   = 0,
    },

    [CHARACTER_CAELLACH_CC - 1] = {
        .nameTextId   = 0x244,
        .descTextId   = 0x29F,
        .number       = CHARACTER_CAELLACH_CC,
        .defaultClass = CLASS_HERO,
        .portraitId   = 0x43,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_THUNDER,
        .sort_order   = 0x2A,
        .baseLevel    = 12,

        .baseHP  = 25,
        .basePow = 13,
        .baseSkl = 5,
        .baseSpd = 3,
        .baseDef = 7,
        .baseRes = 11,
        .baseLck = 14,
        .baseCon = 2,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_A,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_A,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 50,
        .growthSkl = 45,
        .growthSpd = 45,
        .growthDef = 30,
        .growthRes = 20,
        .growthLck = 20,

        .attributes   = 0,
    },

    [CHARACTER_FADO_CC - 1] = {
        .nameTextId   = 0x25B,
        .descTextId   = 0x2B3,
        .number       = CHARACTER_FADO_CC,
        .defaultClass = CLASS_GENERAL,
        .portraitId   = 0x51,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x2C,
        .baseLevel    = 11,

        .baseHP  = 25,
        .basePow = 12,
        .baseSkl = 10,
        .baseSpd = 9,
        .baseDef = 5,
        .baseRes = 8,
        .baseLck = 5,
        .baseCon = 3,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_A,
            [ITYPE_LANCE] = WPN_EXP_A,
            [ITYPE_AXE]   = WPN_EXP_A,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 55,
        .growthSkl = 40,
        .growthSpd = 30,
        .growthDef = 45,
        .growthRes = 25,
        .growthLck = 25,

        .attributes   = 0,
    },

    [CHARACTER_ISMAIRE_CC - 1] = {
        .nameTextId   = 0x260,
        .descTextId   = 0x2B8,
        .number       = CHARACTER_ISMAIRE_CC,
        .defaultClass = CLASS_SWORDMASTER_F,
        .portraitId   = 0x56,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_WIND,
        .sort_order   = 0x2E,
        .baseLevel    = 9,

        .baseHP  = 14,
        .basePow = 10,
        .baseSkl = 9,
        .baseSpd = 11,
        .baseDef = 4,
        .baseRes = 12,
        .baseLck = 12,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_A,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 75,
        .growthPow = 30,
        .growthSkl = 60,
        .growthSpd = 55,
        .growthDef = 20,
        .growthRes = 25,
        .growthLck = 30,

        .attributes   = CA_FEMALE,
    },

    [CHARACTER_HAYDEN_CC - 1] = {
        .nameTextId   = 0x25C,
        .descTextId   = 0x2B4,
        .number       = CHARACTER_HAYDEN_CC,
        .defaultClass = CLASS_RANGER,
        .portraitId   = 0x52,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x2D,
        .baseLevel    = 10,

        .baseHP  = 16,
        .basePow = 10,
        .baseSkl = 8,
        .baseSpd = 8,
        .baseDef = 6,
        .baseRes = 9,
        .baseLck = 17,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_A,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_A,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 70,
        .growthPow = 40,
        .growthSkl = 45,
        .growthSpd = 45,
        .growthDef = 25,
        .growthRes = 25,
        .growthLck = 40,

        .attributes   = 0,
    },

#define CHAR_ENIMY_BRIGAND1(char_index) {   \
    .nameTextId   = 0x267,                  \
    .number       = char_index,             \
    .defaultClass = CLASS_BRIGAND,          \
                                            \
    .growthHP  = 85,                        \
    .growthPow = 50,                        \
    .growthSkl = 10,                        \
    .growthSpd = 10,                        \
    .growthDef = 10,                        \
    .growthRes = 15,                        \
    .growthLck = 30,                        \
}

    [0x1A] = CHAR_ENIMY_BRIGAND1(0x1B),

    [0x2C] = CHAR_ENIMY_BRIGAND1(0x2D),
    [0x2D] = CHAR_ENIMY_BRIGAND1(0x2E),
    [0x2E] = CHAR_ENIMY_BRIGAND1(0x2F),
    [0x2F] = CHAR_ENIMY_BRIGAND1(0x30),
    [0x30] = CHAR_ENIMY_BRIGAND1(0x31),
    [0x31] = CHAR_ENIMY_BRIGAND1(0x32),
    [0x32] = CHAR_ENIMY_BRIGAND1(0x33),
    [0x33] = CHAR_ENIMY_BRIGAND1(0x34),
    [0x34] = CHAR_ENIMY_BRIGAND1(0x35),
    [0x35] = CHAR_ENIMY_BRIGAND1(0x36),
    [0x36] = CHAR_ENIMY_BRIGAND1(0x37),
    [0x37] = CHAR_ENIMY_BRIGAND1(0x38),
    [0x38] = CHAR_ENIMY_BRIGAND1(0x39),
    [0x39] = CHAR_ENIMY_BRIGAND1(0x3A),

#undef CHAR_ENIMY_BRIGAND1


    [CHARACTER_SUMMON_LYON - 1] = {
        .nameTextId   = 0x2F1,
        .descTextId   = 0x33D,
        .number       = CHARACTER_SUMMON_LYON,
        .defaultClass = CLASS_PALADIN,
        .portraitId   = 0x00,
        .miniPortrait = 0x07,
        .affinity     = UNIT_AFFIN_DARK,
        .sort_order   = 0x25,
        .baseLevel    = 1,

        .baseHP  = 0,
        .basePow = 3,
        .baseSkl = 2,
        .baseSpd = 3,
        .baseDef = 0,
        .baseRes = 0,
        .baseLck = 20,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_C,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 0,
        .growthPow = 60,
        .growthSkl = 45,
        .growthSpd = 30,
        .growthDef = 0,
        .growthRes = 0,
        .growthLck = 60,

        .attributes   = 0,
    },

    // CHARACTER_ENIY_SUMMONER_UNUSED
    [0x3C - 1] = {
        .nameTextId   = 0x26D,
        .descTextId   = 0x32E,
        .number       = 0x3C,
        .defaultClass = CLASS_SUMMONER,
        .baseLevel    = 18,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_E,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_C,
        },

        .growthHP  = 50,
        .growthPow = 30,
        .growthSkl = 35,
        .growthSpd = 32,
        .growthDef = 8,
        .growthRes = 40,
        .growthLck = 45,
    },
    
    // CHARACTER_ENIY_SUMMONER2_UNUSED
    [0x3D - 1] = {
        .nameTextId   = 0x26C,
        .descTextId   = 0x32E,
        .number       = 0x3D,
        .defaultClass = CLASS_SUMMONER,
        .baseLevel    = 9,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_E,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_C,
        },

        .growthHP  = 50,
        .growthPow = 30,
        .growthSkl = 35,
        .growthSpd = 32,
        .growthDef = 8,
        .growthRes = 40,
        .growthLck = 45,
    },

    [CHARACTER_SUMMON_KNOLL - 1] = {
        .nameTextId   = 0x2F1,
        .descTextId   = 0x33D,
        .number       = CHARACTER_SUMMON_KNOLL,
        .defaultClass = CLASS_PALADIN,
        .portraitId   = 0x00,
        .miniPortrait = 0x07,
        .affinity     = UNIT_AFFIN_DARK,
        .sort_order   = 0x21,
        .baseLevel    = 1,

        .baseHP  = 0,
        .basePow = 2,
        .baseSkl = 1,
        .baseSpd = 2,
        .baseDef = 0,
        .baseRes = 0,
        .baseLck = 10,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_C,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 0,
        .growthPow = 50,
        .growthSkl = 50,
        .growthSpd = 40,
        .growthDef = 0,
        .growthRes = 0,
        .growthLck = 55,
    },

    [CHARACTER_SUMMON_EWAN - 1] = {
        .nameTextId   = 0x2F1,
        .descTextId   = 0x33D,
        .number       = CHARACTER_SUMMON_EWAN,
        .defaultClass = CLASS_PALADIN,
        .portraitId   = 0x00,
        .miniPortrait = 0x07,
        .affinity     = UNIT_AFFIN_DARK,
        .sort_order   = 0x1A,
        .baseLevel    = 1,

        .baseHP  = 0,
        .basePow = 1,
        .baseSkl = 2,
        .baseSpd = 1,
        .baseDef = 0,
        .baseRes = 0,
        .baseLck = 0,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_C,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 0,
        .growthPow = 70,
        .growthSkl = 40,
        .growthSpd = 20,
        .growthDef = 0,
        .growthRes = 0,
        .growthLck = 40,
    },

};


