#include "global.h"
#include "bmunit.h"
#include "bmitem.h"
#include "bmreliance.h"
#include "constants/characters.h"
#include "constants/classes.h"
#include "constants/items.h"


CONST_DATA struct CharacterData gCharacterData[] = {
    [CHARACTER_EIRIKA - 1] = {
        .nameTextId   = 0x212,
        .descTextId   = 0x26E,
        .number       = CHARACTER_EIRIKA,
        .defaultClass = CLASS_EIRIKA_LORD,
        .portraitId   = 0x02,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_LIGHT,
        .sort_order   = 0x01,

        .baseLevel = 1,
        .baseHP =  0,
        .basePow = 0,
        .baseSkl = 0,
        .baseSpd = 0,
        .baseDef = 0,
        .baseRes = 0,
        .baseLck = 5,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_E,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 70,
        .growthPow = 40,
        .growthSkl = 60,
        .growthSpd = 60,
        .growthDef = 30,
        .growthRes = 30,
        .growthLck = 60,

        .attributes = CA_FEMALE,
        .pSupportData = &gSupportData[0],
        .visit_group = 0x07,
    },

    [CHARACTER_SETH - 1] = {
        .nameTextId   = 0x213,
        .descTextId   = 0x26F,
        .number       = CHARACTER_SETH,
        .defaultClass = CLASS_PALADIN,
        .portraitId   = 0x04,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x03,
        .baseLevel    = 1,

        .baseHP  = 7,
        .basePow = 7,
        .baseSkl = 9,
        .baseSpd = 5,
        .baseDef = 3,
        .baseRes = 5,
        .baseLck = 13,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_A,
            [ITYPE_LANCE] = WPN_EXP_A,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 90,
        .growthPow = 50,
        .growthSkl = 45,
        .growthSpd = 45,
        .growthDef = 40,
        .growthRes = 30,
        .growthLck = 25,

        .attributes = 0,
        .pSupportData = &gSupportData[2],
        .visit_group = 0x03,
    },

    [CHARACTER_GILLIAM - 1] = {
        .nameTextId   = 0x214,
        .descTextId   = 0x270,
        .number       = CHARACTER_GILLIAM,
        .defaultClass = CLASS_ARMOR_KNIGHT,
        .portraitId   = 0x05,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_THUNDER,
        .sort_order   = 0x07,
        .baseLevel    = 4,

        .baseHP  = 8,
        .basePow = 4,
        .baseSkl = 4,
        .baseSpd = 3,
        .baseDef = 0,
        .baseRes = 3,
        .baseLck = 3,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_C,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 90,
        .growthPow = 45,
        .growthSkl = 35,
        .growthSpd = 30,
        .growthDef = 55,
        .growthRes = 20,
        .growthLck = 30,

        .attributes   = 0,
        .pSupportData = &gSupportData[4],
        .visit_group  = 0x04,
    },

    [CHARACTER_FRANZ - 1] = {
        .nameTextId   = 0x215,
        .descTextId   = 0x271,
        .number       = CHARACTER_FRANZ,
        .defaultClass = CHARACTER_MOULDER,
        .portraitId   = 0x06,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_LIGHT,
        .sort_order   = 0x06,
        .baseLevel    = 1,

        .baseHP  = 0,
        .basePow = 2,
        .baseSkl = 3,
        .baseSpd = 2,
        .baseDef = 0,
        .baseRes = 1,
        .baseLck = 2,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_E,
            [ITYPE_LANCE] = WPN_EXP_D,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 80,
        .growthPow = 40,
        .growthSkl = 40,
        .growthSpd = 50,
        .growthDef = 25,
        .growthRes = 20,
        .growthLck = 40,

        .attributes   = 0,
        .pSupportData = &gSupportData[3],
        .visit_group  = 0x03,
    },

    [CHARACTER_MOULDER - 1] = {
        .nameTextId   = 0x216,
        .descTextId   = 0x272,
        .number       = CHARACTER_MOULDER,
        .defaultClass = CLASS_PRIEST,
        .portraitId   = 0x07,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x08,
        .baseLevel    = 3,

        .baseHP  = 2,
        .basePow = 3,
        .baseSkl = 5,
        .baseSpd = 7,
        .baseDef = 1,
        .baseRes = 0,
        .baseLck = 1,
        .baseCon = 4,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_C,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 70,
        .growthPow = 40,
        .growthSkl = 50,
        .growthSpd = 40,
        .growthDef = 25,
        .growthRes = 25,
        .growthLck = 20,

        .attributes   = 0,
        .pSupportData = &gSupportData[5],
        .visit_group  = 0x04,
    },
    
    [CHARACTER_VANESSA - 1] = {
        .nameTextId   = 0x217,
        .descTextId   = 0x273,
        .number       = CHARACTER_VANESSA,
        .defaultClass = CLASS_PEGASUS_KNIGHT,
        .portraitId   = 0x08,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x09,
        .baseLevel    = 1,

        .baseHP  = 3,
        .basePow = 1,
        .baseSkl = 2,
        .baseSpd = 6,
        .baseDef = 3,
        .baseRes = 3,
        .baseLck = 4,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_D,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 50,
        .growthPow = 35,
        .growthSkl = 55,
        .growthSpd = 60,
        .growthDef = 20,
        .growthRes = 30,
        .growthLck = 50,

        .attributes   = CA_FEMALE | CA_TRIANGLEATTACK_PEGASI,
        .pSupportData = &gSupportData[6],
        .visit_group  = 0x0A,
    },

    [CHARACTER_ROSS - 1] = {
        .nameTextId   = 0x218,
        .descTextId   = 0x274,
        .number       = CHARACTER_ROSS,
        .defaultClass = CLASS_JOURNEYMAN,
        .portraitId   = 0x09,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x0A,
        .baseLevel    = 1,

        .baseHP  = 1,
        .basePow = 2,
        .baseSkl = 2,
        .baseSpd = 2,
        .baseDef = 2,
        .baseRes = 0,
        .baseLck = 8,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_E,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 70,
        .growthPow = 50,
        .growthSkl = 35,
        .growthSpd = 30,
        .growthDef = 25,
        .growthRes = 20,
        .growthLck = 40,

        .attributes   = 0,
        .pSupportData = &gSupportData[8],
        .visit_group  = 0x05,
    },

    [CHARACTER_NEIMI - 1] = {
        .nameTextId   = 0x219,
        .descTextId   = 0x275,
        .number       = CHARACTER_NEIMI,
        .defaultClass = CLASS_ARCHER_F,
        .portraitId   = 0x0A,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x0B,
        .baseLevel    = 1,

        .baseHP  = 0,
        .basePow = 1,
        .baseSkl = 2,
        .baseSpd = 2,
        .baseDef = 0,
        .baseRes = 2,
        .baseLck = 4,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_D,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 55,
        .growthPow = 45,
        .growthSkl = 50,
        .growthSpd = 60,
        .growthDef = 15,
        .growthRes = 35,
        .growthLck = 50,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[0xA],
        .visit_group  = 0x07,
    },

    [CHARACTER_COLM - 1] = {
        .nameTextId   = 0x21A,
        .descTextId   = 0x276,
        .number       = CHARACTER_COLM,
        .defaultClass = CLASS_THIEF,
        .portraitId   = 0x0C,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_LIGHT,
        .sort_order   = 0x0C,
        .baseLevel    = 2,

        .baseHP  = 2,
        .basePow = 1,
        .baseSkl = 3,
        .baseSpd = 1,
        .baseDef = 1,
        .baseRes = 1,
        .baseLck = 8,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_E,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 75,
        .growthPow = 40,
        .growthSkl = 40,
        .growthSpd = 65,
        .growthDef = 25,
        .growthRes = 20,
        .growthLck = 45,

        .attributes   = 0,
        .pSupportData = &gSupportData[9],
        .visit_group  = 0x00,
    },

    [CHARACTER_GARCIA - 1] = {
        .nameTextId   = 0x21B,
        .descTextId   = 0x277,
        .number       = CHARACTER_GARCIA,
        .defaultClass = CLASS_FIGHTER,
        .portraitId   = 0x0E,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x0D,
        .baseLevel    = 4,

        .baseHP  = 8,
        .basePow = 3,
        .baseSkl = 5,
        .baseSpd = 3,
        .baseDef = 3,
        .baseRes = 1,
        .baseLck = 3,
        .baseCon = 3,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_C,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 80,
        .growthPow = 65,
        .growthSkl = 40,
        .growthSpd = 20,
        .growthDef = 25,
        .growthRes = 15,
        .growthLck = 40,

        .attributes   = 0,
        .pSupportData = &gSupportData[7],
        .visit_group  = 0x01,
    },

    [CHARACTER_INNES - 1] = {
        .nameTextId   = 0x21C,
        .descTextId   = 0x278,
        .number       = CHARACTER_INNES,
        .defaultClass = CLASS_SNIPER,
        .portraitId   = 0x0F,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x14,
        .baseLevel    = 1,

        .baseHP  = 10,
        .basePow = 7,
        .baseSkl = 7,
        .baseSpd = 10,
        .baseDef = 5,
        .baseRes = 7,
        .baseLck = 14,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_A,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 75,
        .growthPow = 40,
        .growthSkl = 40,
        .growthSpd = 45,
        .growthDef = 20,
        .growthRes = 25,
        .growthLck = 45,

        .attributes   = 0,
        .pSupportData = &gSupportData[18],
        .visit_group  = 0x00,
    },

    [CHARACTER_LUTE - 1] = {
        .nameTextId   = 0x21D,
        .descTextId   = 0x279,
        .number       = CHARACTER_LUTE,
        .defaultClass = CLASS_MAGE_F,
        .portraitId   = 0x10,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ANIMA,
        .sort_order   = 0x0F,
        .baseLevel    = 1,

        .baseHP  = 1,
        .basePow = 5,
        .baseSkl = 3,
        .baseSpd = 5,
        .baseDef = 1,
        .baseRes = 1,
        .baseLck = 8,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_C,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 45,
        .growthPow = 65,
        .growthSkl = 30,
        .growthSpd = 45,
        .growthDef = 15,
        .growthRes = 40,
        .growthLck = 45,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[0x0C],
        .visit_group  = 0x07,
    },

    [CHARACTER_NATASHA - 1] = {
        .nameTextId   = 0x21E,
        .descTextId   = 0x27A,
        .number       = CHARACTER_NATASHA,
        .defaultClass = CLASS_CLERIC,
        .portraitId   = 0x11,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x10,
        .baseLevel    = 1,

        .baseHP  = 2,
        .basePow = 1,
        .baseSkl = 2,
        .baseSpd = 6,
        .baseDef = 2,
        .baseRes = 0,
        .baseLck = 6,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_0,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_D,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 50,
        .growthPow = 60,
        .growthSkl = 25,
        .growthSpd = 40,
        .growthDef = 15,
        .growthRes = 55,
        .growthLck = 60,

        .attributes   = CA_FEMALE,
        .pSupportData = &gSupportData[0x0D],
        .visit_group  = 0x0A,
    },

    [CHARACTER_CORMAG - 1] = {
        .nameTextId   = 0x21F,
        .descTextId   = 0x27B,
        .number       = CHARACTER_CORMAG,
        .defaultClass = CLASS_WYVERN_RIDER,
        .portraitId   = 0x13,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x1F,
        .baseLevel    = 9,

        .baseHP  = 10,
        .basePow = 7,
        .baseSkl = 6,
        .baseSpd = 5,
        .baseDef = 4,
        .baseRes = 2,
        .baseLck = 4,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_C,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 55,
        .growthSkl = 40,
        .growthSpd = 45,
        .growthDef = 25,
        .growthRes = 15,
        .growthLck = 35,

        .attributes   = 0,
        .pSupportData = &gSupportData[26],
        .visit_group  = 0x00,
    },

    [CHARACTER_EPHRAIM - 1] = {
        .nameTextId   = 0x220,
        .descTextId   = 0x27C,
        .number       = CHARACTER_EPHRAIM,
        .defaultClass = CLASS_EPHRAIM_LORD,
        .portraitId   = 0x14,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_FIRE,
        .sort_order   = 0x01,
        .baseLevel    = 4,

        .baseHP  = 5,
        .basePow = 2,
        .baseSkl = 3,
        .baseSpd = 4,
        .baseDef = 1,
        .baseRes = 2,
        .baseLck = 8,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_0,
            [ITYPE_LANCE] = WPN_EXP_D,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 80,
        .growthPow = 55,
        .growthSkl = 55,
        .growthSpd = 45,
        .growthDef = 35,
        .growthRes = 25,
        .growthLck = 50,

        .attributes   = 0,
        .pSupportData = &gSupportData[1],
        .visit_group  = 0x03,
    },

    [CHARACTER_FORDE - 1] = {
        .nameTextId   = 0x221,
        .descTextId   = 0x27D,
        .number       = CHARACTER_FORDE,
        .defaultClass = CLASS_CAVALIER,
        .portraitId   = 0x16,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_WIND,
        .sort_order   = 0x05,
        .baseLevel    = 5,

        .baseHP  = 4,
        .basePow = 2,
        .baseSkl = 6,
        .baseSpd = 3,
        .baseDef = 2,
        .baseRes = 2,
        .baseLck = 7,
        .baseCon = 0,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_D,
            [ITYPE_LANCE] = WPN_EXP_C,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 85,
        .growthPow = 40,
        .growthSkl = 50,
        .growthSpd = 45,
        .growthDef = 20,
        .growthRes = 25,
        .growthLck = 35,

        .attributes   = 0,
        .pSupportData = &gSupportData[16],
        .visit_group  = 0x03,
    },

    [CHARACTER_KYLE - 1] = {
        .nameTextId   = 0x222,
        .descTextId   = 0x27E,
        .number       = CHARACTER_KYLE,
        .defaultClass = CLASS_CAVALIER,
        .portraitId   = 0x18,
        .miniPortrait = 0x00,
        .affinity     = UNIT_AFFIN_ICE,
        .sort_order   = 0x04,
        .baseLevel    = 6,

        .baseHP  = 5,
        .basePow = 4,
        .baseSkl = 4,
        .baseSpd = 2,
        .baseDef = 3,
        .baseRes = 1,
        .baseLck = 6,
        .baseCon = 1,

        .baseRanks = {
            [ITYPE_SWORD] = WPN_EXP_D,
            [ITYPE_LANCE] = WPN_EXP_C,
            [ITYPE_AXE]   = WPN_EXP_0,
            [ITYPE_BOW]   = WPN_EXP_0,
            [ITYPE_STAFF] = WPN_EXP_0,
            [ITYPE_ANIMA] = WPN_EXP_0,
            [ITYPE_LIGHT] = WPN_EXP_0,
            [ITYPE_DARK]  = WPN_EXP_0,
        },

        .growthHP  = 90,
        .growthPow = 50,
        .growthSkl = 40,
        .growthSpd = 40,
        .growthDef = 25,
        .growthRes = 20,
        .growthLck = 20,

        .attributes   = 0,
        .pSupportData = &gSupportData[15],
        .visit_group  = 0x03,
    },
};

