#include "global.h"
#include "constants/items.h"
#include "eventinfo.h"

// 0x89ED70C
CONST_DATA u8 ChestItemList_Event_089ED70C[] = {
    ITEM_SWORD_KILLER, 22,
    ITEM_LANCE_KILLER, 22,
    ITEM_AXE_KILLER, 22,
    ITEM_BOW_KILLER, 22,
    ITEM_BLUEGEM, 4,
    ITEM_REDGEM, 8,
    ITEM_NONE, 0,
};

// 0x89ED71A
CONST_DATA u8 ChestItemList_Event_089ED71A[] = {
    ITEM_ANIMA_THUNDER, 22,
    ITEM_LIGHT_SHINE, 22,
    ITEM_DARK_LUNA, 22,
    ITEM_STAFF_RECOVER, 22,
    ITEM_BLUEGEM, 4,
    ITEM_REDGEM, 8,
    ITEM_NONE, 0,
};

// 0x89ED728
CONST_DATA u8 ChestItemList_Event_089ED728[] = {
    ITEM_STAFF_PHYSIC, 40,
    ITEM_STAFF_FORTIFY, 20,
    ITEM_STAFF_SILENCE, 20,
    ITEM_STAFF_RESTORE, 20,
    ITEM_NONE, 0,
};

// 0x89ED732
CONST_DATA u8 ChestItemList_Event_089ED732[] = {
    ITEM_SWORD_STEEL, 10,
    ITEM_BLADE_STEEL, 10,
    ITEM_SWORD_BRAVE, 5,
    ITEM_LANCE_STEEL, 20,
    ITEM_LANCE_BRAVE, 5,
    ITEM_AXE_STEEL, 20,
    ITEM_AXE_BRAVE, 5,
    ITEM_BOW_STEEL, 20,
    ITEM_BOW_BRAVE, 5,
    ITEM_NONE, 0,
};

// 0x89ED746
CONST_DATA u8 ChestItemList_Event_089ED746[] = {
    ITEM_ANIMA_ELFIRE, 25,
    ITEM_ANIMA_BOLTING, 9,
    ITEM_LIGHT_DIVINE, 25,
    ITEM_LIGHT_PURGE, 8,
    ITEM_DARK_NOSFERATU, 25,
    ITEM_DARK_ECLIPSE, 8,
    ITEM_NONE, 0,
};

// 0x89ED754
CONST_DATA u8 ChestItemList_Event_089ED754[] = {
    ITEM_ANIMA_ELFIRE, 27,
    ITEM_LIGHT_DIVINE, 28,
    ITEM_DARK_NOSFERATU, 28,
    ITEM_WHITEGEM, 2,
    ITEM_BLUEGEM, 5,
    ITEM_REDGEM, 10,
    ITEM_NONE, 0,
};

// 0x89ED762
CONST_DATA u8 ChestItemList_Event_089ED762[] = {
    ITEM_BLADE_STEEL, 23,
    ITEM_LANCE_STEEL, 20,
    ITEM_AXE_STEEL, 20,
    ITEM_BOW_STEEL, 20,
    ITEM_WHITEGEM, 2,
    ITEM_BLUEGEM, 5,
    ITEM_REDGEM, 10,
    ITEM_NONE, 0,
};

// 0x89ED772
CONST_DATA u8 ChestItemList_Event_089ED772[] = {
    ITEM_SWORD_KILLER, 25,
    ITEM_LANCE_KILLER, 25,
    ITEM_AXE_KILLER, 25,
    ITEM_BOW_KILLER, 25,
    ITEM_NONE, 0,
};

// 0x89ED77C
CONST_DATA u8 ChestItemList_Event_089ED77C[] = {
    ITEM_SWORD_ARMORSLAYER, 10,
    ITEM_SWORD_WYRMSLAYER, 10,
    ITEM_SWORD_ZANBATO, 10,
    ITEM_LANCE_HEAVYSPEAR, 10,
    ITEM_LANCE_DRAGON, 10,
    ITEM_LANCE_HORSESLAYER, 10,
    ITEM_AXE_SWORDSLAYER, 10,
    ITEM_AXE_HALBERD, 10,
    ITEM_AXE_DRAGON, 10,
    ITEM_BOW_LONGBOW, 10,
    ITEM_NONE, 0,
};

// 0x89ED792
CONST_DATA u8 ChestItemList_Event_089ED792[] = {
    ITEM_SWORD_SILVER, 25,
    ITEM_LANCE_SILVER, 25,
    ITEM_AXE_SILVER, 25,
    ITEM_BOW_SILVER, 25,
    ITEM_NONE, 0,
};

// 0x89ED79C
CONST_DATA u8 ChestItemList_Event_089ED79C[] = {
    ITEM_STAFF_RESTORE, 20,
    ITEM_STAFF_SILENCE, 20,
    ITEM_STAFF_PHYSIC, 20,
    ITEM_STAFF_FORTIFY, 20,
    ITEM_STAFF_MEND, 20,
    ITEM_NONE, 0,
};

// 0x89ED7A8
CONST_DATA u8 ChestItemList_Event_089ED7A8[] = {
    ITEM_ANIMA_ELFIRE, 25,
    ITEM_ANIMA_FIMBULVETR, 9,
    ITEM_LIGHT_DIVINE, 25,
    ITEM_LIGHT_AURA, 8,
    ITEM_DARK_NOSFERATU, 25,
    ITEM_DARK_FENRIR, 8,
    ITEM_NONE, 0,
};

// 0x89ED7B6
CONST_DATA u8 ChestItemList_Event_089ED7B6[] = {
    ITEM_WHITEGEM, 20,
    ITEM_BLUEGEM, 50,
    ITEM_REDGEM, 30,
    ITEM_NONE, 0,
};

// 0x89ED7BE
CONST_DATA u8 ChestItemList_Event_089ED7BE[] = {
    ITEM_SWORD_WYRMSLAYER, 30,
    ITEM_LANCE_DRAGON, 30,
    ITEM_AXE_DRAGON, 40,
    ITEM_NONE, 0,
};

// 0x89ED7C6
CONST_DATA u8 ChestItemList_Event_089ED7C6[] = {
    ITEM_WHITEGEM, 90,
    ITEM_MEMBERCARD, 10,
    ITEM_NONE, 0,
};

// 0x89ED7CC
CONST_DATA u16 ShopList_Event_Ch2Armory[] = {
    ITEM_SWORD_SLIM,
    ITEM_SWORD_IRON,
    ITEM_LANCE_SLIM,
    ITEM_LANCE_IRON,
    ITEM_AXE_IRON,

    ITEM_NONE,
};

// 0x89ED7D8
CONST_DATA u16 ShopList_Event_Ch5Armory[] = {
    ITEM_SWORD_SLIM,
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_LANCE_SLIM,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,

    ITEM_NONE,
};

// 0x89ED7EE
CONST_DATA u16 ShopList_Event_Ch5Vendor[] = {
    ITEM_ANIMA_FIRE,
    ITEM_LIGHT_LIGHTNING,
    ITEM_STAFF_HEAL,
    ITEM_VULNERARY,

    ITEM_NONE,
};

// 0x89ED7F8
CONST_DATA u16 ShopList_Event_Ch9aVendor[] = {
    ITEM_ANIMA_FIRE,
    ITEM_ANIMA_THUNDER,
    ITEM_LIGHT_LIGHTNING,
    ITEM_LIGHT_SHINE,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_UNLOCK,
    ITEM_VULNERARY,
    ITEM_ANTITOXIN,
    ITEM_TORCH,

    ITEM_NONE,
};

// 0x89ED80E
CONST_DATA u16 ShopList_Event_Ch9aArmory[] = {
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_BLADE_IRON,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_LANCE_JAVELIN,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_AXE_HANDAXE,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,

    ITEM_NONE,
};

// 0x89ED826
CONST_DATA u16 ShopList_Event_089ED826[] = {
    ITEM_ANIMA_FIRE,
    ITEM_ANIMA_THUNDER,
    ITEM_LIGHT_LIGHTNING,
    ITEM_LIGHT_SHINE,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_VULNERARY,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED83E
CONST_DATA u16 ShopList_Event_089ED83E[] = {
    ITEM_BLADE_STEEL,
    ITEM_BLADE_SILVER,
    ITEM_SWORD_KILLER,
    ITEM_LANCE_KILLER,
    ITEM_AXE_BATTLEAXE,
    ITEM_AXE_KILLER,
    ITEM_BOW_KILLER,
    ITEM_STAFF_BARRIER,
    ITEM_STAFF_PHYSIC,
    ITEM_LOCKPICK,
    ITEM_HEROCREST,
    ITEM_KNIGHTCREST,
    ITEM_ORIONSBOLT,
    ITEM_ELYSIANWHIP,
    ITEM_GUIDINGRING,
    ITEM_OCEANSEAL,

    ITEM_NONE,
};

// 0x89ED860
CONST_DATA u16 ShopList_Event_089ED860[] = {
    ITEM_ANIMA_THUNDER,
    ITEM_ANIMA_ELFIRE,
    ITEM_LIGHT_SHINE,
    ITEM_LIGHT_DIVINE,
    ITEM_DARK_FLUX,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_VULNERARY,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED87A
CONST_DATA u16 ShopList_Event_089ED87A[] = {
    ITEM_ANIMA_THUNDER,
    ITEM_ANIMA_ELFIRE,
    ITEM_LIGHT_SHINE,
    ITEM_LIGHT_DIVINE,
    ITEM_DARK_FLUX,
    ITEM_DARK_NOSFERATU,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED894
CONST_DATA u16 ShopList_Event_089ED894[] = {
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_SWORD_LANCEREAVER,
    ITEM_SWORD_KILLER,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_LANCE_AXEREAVER,
    ITEM_LANCE_KILLER,
    ITEM_LANCE_JAVELIN,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_AXE_SWORDREAVER,
    ITEM_AXE_KILLER,
    ITEM_AXE_HANDAXE,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,
    ITEM_BOW_KILLER,

    ITEM_NONE,
};

// 0x89ED8B8
CONST_DATA u16 ShopList_Event_089ED8B8[] = {
    ITEM_STAFF_BARRIER,
    ITEM_STAFF_PHYSIC,
    ITEM_HEROCREST,
    ITEM_KNIGHTCREST,
    ITEM_ORIONSBOLT,
    ITEM_ELYSIANWHIP,
    ITEM_GUIDINGRING,
    ITEM_OCEANSEAL,

    ITEM_NONE,
};

// 0x89ED8CA
CONST_DATA u16 ShopList_Event_089ED8CA[] = {
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_BLADE_IRON,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_LANCE_JAVELIN,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_AXE_HANDAXE,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,

    ITEM_NONE,
};

// 0x89ED8E2
CONST_DATA u16 ShopList_Event_089ED8E2[] = {
    ITEM_ANIMA_FIRE,
    ITEM_ANIMA_THUNDER,
    ITEM_LIGHT_LIGHTNING,
    ITEM_LIGHT_SHINE,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_STAFF_UNLOCK,
    ITEM_VULNERARY,
    ITEM_ANTITOXIN,
    ITEM_TORCH,

    ITEM_NONE,
};

// 0x89ED8FA
CONST_DATA u16 ShopList_Event_089ED8FA[] = {
    ITEM_ANIMA_FIRE,
    ITEM_ANIMA_THUNDER,
    ITEM_LIGHT_LIGHTNING,
    ITEM_LIGHT_SHINE,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_VULNERARY,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED912
CONST_DATA u16 ShopList_Event_089ED912[] = {
    ITEM_BLADE_STEEL,
    ITEM_BLADE_SILVER,
    ITEM_SWORD_KILLER,
    ITEM_LANCE_KILLER,
    ITEM_AXE_BATTLEAXE,
    ITEM_AXE_KILLER,
    ITEM_BOW_KILLER,
    ITEM_STAFF_BARRIER,
    ITEM_STAFF_PHYSIC,
    ITEM_LOCKPICK,
    ITEM_HEROCREST,
    ITEM_KNIGHTCREST,
    ITEM_ORIONSBOLT,
    ITEM_ELYSIANWHIP,
    ITEM_GUIDINGRING,
    ITEM_OCEANSEAL,

    ITEM_NONE,
};

// 0x89ED934
CONST_DATA u16 ShopList_Event_089ED934[] = {
    ITEM_ANIMA_THUNDER,
    ITEM_ANIMA_ELFIRE,
    ITEM_LIGHT_SHINE,
    ITEM_LIGHT_DIVINE,
    ITEM_DARK_FLUX,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_VULNERARY,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED94E
CONST_DATA u16 ShopList_Event_089ED94E[] = {
    ITEM_ANIMA_THUNDER,
    ITEM_ANIMA_ELFIRE,
    ITEM_LIGHT_SHINE,
    ITEM_LIGHT_DIVINE,
    ITEM_DARK_FLUX,
    ITEM_DARK_NOSFERATU,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED968
CONST_DATA u16 ShopList_Event_089ED968[] = {
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_SWORD_LANCEREAVER,
    ITEM_SWORD_KILLER,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_LANCE_AXEREAVER,
    ITEM_LANCE_KILLER,
    ITEM_LANCE_JAVELIN,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_AXE_SWORDREAVER,
    ITEM_AXE_KILLER,
    ITEM_AXE_HANDAXE,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,
    ITEM_BOW_KILLER,

    ITEM_NONE,
};

// 0x89ED98C
CONST_DATA u16 ShopList_Event_089ED98C[] = {
    ITEM_STAFF_BARRIER,
    ITEM_STAFF_PHYSIC,
    ITEM_HEROCREST,
    ITEM_KNIGHTCREST,
    ITEM_ORIONSBOLT,
    ITEM_ELYSIANWHIP,
    ITEM_GUIDINGRING,
    ITEM_OCEANSEAL,

    ITEM_NONE,
};

// 0x89ED99E
CONST_DATA u16 ShopList_Event_089ED99E[] = {
    ITEM_SWORD_WINDSWORD,

    ITEM_NONE,
};

// 0x89ED9A2
CONST_DATA u16 ShopList_Event_089ED9A2[] = {
    ITEM_OCEANSEAL,

    ITEM_NONE,
};
