#include "global.h"
#include "constants/items.h"
#include "eventinfo.h"

// 0x89ED7CC
CONST_DATA u16 ShopList_Event_Ch2Armory[] = {
    ITEM_SWORD_SLIM,
    ITEM_SWORD_IRON,
    ITEM_LANCE_SLIM,
    ITEM_LANCE_IRON,
    ITEM_AXE_IRON,

    ITEM_NONE,
};

// 0x89ED7D8
CONST_DATA u16 ShopList_Event_Ch5Armory[] = {
    ITEM_SWORD_SLIM,
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_LANCE_SLIM,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,

    ITEM_NONE,
};

// 0x89ED7EE
CONST_DATA u16 ShopList_Event_Ch5Vendor[] = {
    ITEM_ANIMA_FIRE,
    ITEM_LIGHT_LIGHTNING,
    ITEM_STAFF_HEAL,
    ITEM_VULNERARY,

    ITEM_NONE,
};

// 0x89ED7F8
CONST_DATA u16 ShopList_Event_Ch9aVendor[] = {
    ITEM_ANIMA_FIRE,
    ITEM_ANIMA_THUNDER,
    ITEM_LIGHT_LIGHTNING,
    ITEM_LIGHT_SHINE,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_UNLOCK,
    ITEM_VULNERARY,
    ITEM_ANTITOXIN,
    ITEM_TORCH,

    ITEM_NONE,
};

// 0x89ED80E
CONST_DATA u16 ShopList_Event_Ch9aArmory[] = {
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_BLADE_IRON,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_LANCE_JAVELIN,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_AXE_HANDAXE,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,

    ITEM_NONE,
};

// 0x89ED826
CONST_DATA u16 ShopList_Event_089ED826[] = {
    ITEM_ANIMA_FIRE,
    ITEM_ANIMA_THUNDER,
    ITEM_LIGHT_LIGHTNING,
    ITEM_LIGHT_SHINE,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_VULNERARY,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED83E
CONST_DATA u16 ShopList_Event_089ED83E[] = {
    ITEM_BLADE_STEEL,
    ITEM_BLADE_SILVER,
    ITEM_SWORD_KILLER,
    ITEM_LANCE_KILLER,
    ITEM_AXE_BATTLEAXE,
    ITEM_AXE_KILLER,
    ITEM_BOW_KILLER,
    ITEM_STAFF_BARRIER,
    ITEM_STAFF_PHYSIC,
    ITEM_LOCKPICK,
    ITEM_HEROCREST,
    ITEM_KNIGHTCREST,
    ITEM_ORIONSBOLT,
    ITEM_ELYSIANWHIP,
    ITEM_GUIDINGRING,
    ITEM_OCEANSEAL,

    ITEM_NONE,
};

// 0x89ED860
CONST_DATA u16 ShopList_Event_089ED860[] = {
    ITEM_ANIMA_THUNDER,
    ITEM_ANIMA_ELFIRE,
    ITEM_LIGHT_SHINE,
    ITEM_LIGHT_DIVINE,
    ITEM_DARK_FLUX,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_VULNERARY,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED87A
CONST_DATA u16 ShopList_Event_089ED87A[] = {
    ITEM_ANIMA_THUNDER,
    ITEM_ANIMA_ELFIRE,
    ITEM_LIGHT_SHINE,
    ITEM_LIGHT_DIVINE,
    ITEM_DARK_FLUX,
    ITEM_DARK_NOSFERATU,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED894
CONST_DATA u16 ShopList_Event_089ED894[] = {
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_SWORD_LANCEREAVER,
    ITEM_SWORD_KILLER,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_LANCE_AXEREAVER,
    ITEM_LANCE_KILLER,
    ITEM_LANCE_JAVELIN,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_AXE_SWORDREAVER,
    ITEM_AXE_KILLER,
    ITEM_AXE_HANDAXE,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,
    ITEM_BOW_KILLER,

    ITEM_NONE,
};

// 0x89ED8B8
CONST_DATA u16 ShopList_Event_089ED8B8[] = {
    ITEM_STAFF_BARRIER,
    ITEM_STAFF_PHYSIC,
    ITEM_HEROCREST,
    ITEM_KNIGHTCREST,
    ITEM_ORIONSBOLT,
    ITEM_ELYSIANWHIP,
    ITEM_GUIDINGRING,
    ITEM_OCEANSEAL,

    ITEM_NONE,
};

// 0x89ED8CA
CONST_DATA u16 ShopList_Event_089ED8CA[] = {
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_BLADE_IRON,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_LANCE_JAVELIN,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_AXE_HANDAXE,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,

    ITEM_NONE,
};

// 0x89ED8E2
CONST_DATA u16 ShopList_Event_089ED8E2[] = {
    ITEM_ANIMA_FIRE,
    ITEM_ANIMA_THUNDER,
    ITEM_LIGHT_LIGHTNING,
    ITEM_LIGHT_SHINE,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_STAFF_UNLOCK,
    ITEM_VULNERARY,
    ITEM_ANTITOXIN,
    ITEM_TORCH,

    ITEM_NONE,
};

// 0x89ED8FA
CONST_DATA u16 ShopList_Event_089ED8FA[] = {
    ITEM_ANIMA_FIRE,
    ITEM_ANIMA_THUNDER,
    ITEM_LIGHT_LIGHTNING,
    ITEM_LIGHT_SHINE,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_VULNERARY,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED912
CONST_DATA u16 ShopList_Event_089ED912[] = {
    ITEM_BLADE_STEEL,
    ITEM_BLADE_SILVER,
    ITEM_SWORD_KILLER,
    ITEM_LANCE_KILLER,
    ITEM_AXE_BATTLEAXE,
    ITEM_AXE_KILLER,
    ITEM_BOW_KILLER,
    ITEM_STAFF_BARRIER,
    ITEM_STAFF_PHYSIC,
    ITEM_LOCKPICK,
    ITEM_HEROCREST,
    ITEM_KNIGHTCREST,
    ITEM_ORIONSBOLT,
    ITEM_ELYSIANWHIP,
    ITEM_GUIDINGRING,
    ITEM_OCEANSEAL,

    ITEM_NONE,
};

// 0x89ED934
CONST_DATA u16 ShopList_Event_089ED934[] = {
    ITEM_ANIMA_THUNDER,
    ITEM_ANIMA_ELFIRE,
    ITEM_LIGHT_SHINE,
    ITEM_LIGHT_DIVINE,
    ITEM_DARK_FLUX,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_VULNERARY,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED94E
CONST_DATA u16 ShopList_Event_089ED94E[] = {
    ITEM_ANIMA_THUNDER,
    ITEM_ANIMA_ELFIRE,
    ITEM_LIGHT_SHINE,
    ITEM_LIGHT_DIVINE,
    ITEM_DARK_FLUX,
    ITEM_DARK_NOSFERATU,
    ITEM_STAFF_HEAL,
    ITEM_STAFF_MEND,
    ITEM_STAFF_RESTORE,
    ITEM_ELIXIR,
    ITEM_PUREWATER,
    ITEM_ANTITOXIN,

    ITEM_NONE,
};

// 0x89ED968
CONST_DATA u16 ShopList_Event_089ED968[] = {
    ITEM_SWORD_IRON,
    ITEM_SWORD_STEEL,
    ITEM_SWORD_LANCEREAVER,
    ITEM_SWORD_KILLER,
    ITEM_LANCE_IRON,
    ITEM_LANCE_STEEL,
    ITEM_LANCE_AXEREAVER,
    ITEM_LANCE_KILLER,
    ITEM_LANCE_JAVELIN,
    ITEM_AXE_IRON,
    ITEM_AXE_STEEL,
    ITEM_AXE_SWORDREAVER,
    ITEM_AXE_KILLER,
    ITEM_AXE_HANDAXE,
    ITEM_BOW_IRON,
    ITEM_BOW_STEEL,
    ITEM_BOW_KILLER,

    ITEM_NONE,
};

// 0x89ED98C
CONST_DATA u16 ShopList_Event_089ED98C[] = {
    ITEM_STAFF_BARRIER,
    ITEM_STAFF_PHYSIC,
    ITEM_HEROCREST,
    ITEM_KNIGHTCREST,
    ITEM_ORIONSBOLT,
    ITEM_ELYSIANWHIP,
    ITEM_GUIDINGRING,
    ITEM_OCEANSEAL,

    ITEM_NONE,
};

// 0x89ED99E
CONST_DATA u16 ShopList_Event_089ED99E[] = {
    ITEM_SWORD_WINDSWORD,

    ITEM_NONE,
};

// 0x89ED9A2
CONST_DATA u16 ShopList_Event_089ED9A2[] = {
    ITEM_OCEANSEAL,

    ITEM_NONE,
};
