#include "global.h"
#include "event.h"
#include "eventinfo.h"
#include "eventcall.h"
#include "eventscript.h"
#include "EAstdlib.h"
#include "chapterdata.h"
#include "constants/event-flags.h"
#include "bmunit.h"
#include "bmtrap.h"
#include "ending_credits.h"

/* Event scripts */
#include "events/common-events.h"
#include "events/prologue-eventscript.h"
#include "events/prologue-tutorials.h"
#include "events/ch1-eventscript.h"
#include "events/ch1-tutorials.h"
#include "events/ch2-eventscript.h"
#include "events/ch3-eventscript.h"
#include "events/ch4-eventscript.h"
#include "events/ch5-eventscript.h"
#include "events/ch5x-eventscript.h"
#include "events/ch6-eventscript.h"
#include "events/ch7-eventscript.h"
#include "events/ch8-eventscript.h"

#include "events/ch9a-eventscript.h"
#include "events/ch10a-eventscript.h"
#include "events/ch11a-eventscript.h"
#include "events/ch12a-eventscript.h"
#include "events/ch13a-eventscript.h"
#include "events/ch14a-eventscript.h"
#include "events/ch15a-eventscript.h"
#include "events/ch16a-eventscript.h"
#include "events/ch17a-eventscript.h"
#include "events/ch18a-eventscript.h"
#include "events/ch19a-eventscript.h"
#include "events/ch20a-eventscript.h"
#include "events/ch21a-eventscript.h"
#include "events/ch21xa-eventscript.h"

#include "events/ch9b-eventscript.h"
#include "events/ch10b-eventscript.h"
#include "events/ch11b-eventscript.h"
#include "events/ch12b-eventscript.h"
#include "events/ch13b-eventscript.h"
#include "events/ch14b-eventscript.h"
#include "events/ch15b-eventscript.h"
#include "events/ch16b-eventscript.h"
#include "events/ch17b-eventscript.h"
#include "events/ch18b-eventscript.h"
#include "events/ch19b-eventscript.h"
#include "events/ch20b-eventscript.h"
#include "events/ch21b-eventscript.h"
#include "events/ch21xb-eventscript.h"

#include "events/tower-eventscript.h"
#include "events/ruin-eventscript.h"

#include "events/lordsplit-eventscript.h"
#include "events/MelkaenCoast-eventscript.h"
#include "events/unused-eventscript.h"
#include "events/messed-eventscr.h"
