#include "global.h"

#include "soundroom.h"

struct SoundRoomEnt CONST_DATA gSoundRoomTable[] =
{
    {
        .bgmId = 0x01,
        .songLength = 2640,
        .displayCondFunc = NULL,
        .nameTextId = 0x078B,
    },
    {
        .bgmId = 0x02,
        .songLength = 5880,
        .displayCondFunc = NULL,
        .nameTextId = 0x078C,
    },
    {
        .bgmId = 0x03,
        .songLength = 4140,
        .displayCondFunc = NULL,
        .nameTextId = 0x078D,
    },
    {
        .bgmId = 0x04,
        .songLength = 3720,
        .displayCondFunc = NULL,
        .nameTextId = 0x078E,
    },
    {
        .bgmId = 0x05,
        .songLength = 4560,
        .displayCondFunc = NULL,
        .nameTextId = 0x078F,
    },
    {
        .bgmId = 0x06,
        .songLength = 4440,
        .displayCondFunc = NULL,
        .nameTextId = 0x0790,
    },
    {
        .bgmId = 0x07,
        .songLength = 3840,
        .displayCondFunc = NULL,
        .nameTextId = 0x0791,
    },
    {
        .bgmId = 0x08,
        .songLength = 3900,
        .displayCondFunc = NULL,
        .nameTextId = 0x0792,
    },
    {
        .bgmId = 0x09,
        .songLength = 6420,
        .displayCondFunc = NULL,
        .nameTextId = 0x0793,
    },
    {
        .bgmId = 0x0A,
        .songLength = 5640,
        .displayCondFunc = NULL,
        .nameTextId = 0x0794,
    },
    {
        .bgmId = 0x0B,
        .songLength = 4980,
        .displayCondFunc = NULL,
        .nameTextId = 0x0795,
    },
    {
        .bgmId = 0x0C,
        .songLength = 4560,
        .displayCondFunc = NULL,
        .nameTextId = 0x0796,
    },
    {
        .bgmId = 0x0D,
        .songLength = 5820,
        .displayCondFunc = NULL,
        .nameTextId = 0x0797,
    },
    {
        .bgmId = 0x0E,
        .songLength = 4680,
        .displayCondFunc = NULL,
        .nameTextId = 0x0798,
    },
    {
        .bgmId = 0x0F,
        .songLength = 3840,
        .displayCondFunc = NULL,
        .nameTextId = 0x0799,
    },
    {
        .bgmId = 0x10,
        .songLength = 2460,
        .displayCondFunc = NULL,
        .nameTextId = 0x079A,
    },
    {
        .bgmId = 0x12,
        .songLength = 4980,
        .displayCondFunc = NULL,
        .nameTextId = 0x079B,
    },
    {
        .bgmId = 0x11,
        .songLength = 5640,
        .displayCondFunc = NULL,
        .nameTextId = 0x079C,
    },
    {
        .bgmId = 0x13,
        .songLength = 2820,
        .displayCondFunc = NULL,
        .nameTextId = 0x079D,
    },
    {
        .bgmId = 0x14,
        .songLength = 5100,
        .displayCondFunc = NULL,
        .nameTextId = 0x079E,
    },
    {
        .bgmId = 0x15,
        .songLength = 4380,
        .displayCondFunc = NULL,
        .nameTextId = 0x079F,
    },
    {
        .bgmId = 0x16,
        .songLength = 4440,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A0,
    },
    {
        .bgmId = 0x17,
        .songLength = 4440,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A1,
    },
    {
        .bgmId = 0x18,
        .songLength = 4980,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A2,
    },
    {
        .bgmId = 0x19,
        .songLength = 1500,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A3,
    },
    {
        .bgmId = 0x1A,
        .songLength = 1680,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A4,
    },
    {
        .bgmId = 0x1B,
        .songLength = 1680,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A5,
    },
    {
        .bgmId = 0x1C,
        .songLength = 1440,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A6,
    },
    {
        .bgmId = 0x1D,
        .songLength = 2040,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A7,
    },
    {
        .bgmId = 0x1E,
        .songLength = 3840,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A8,
    },
    {
        .bgmId = 0x1F,
        .songLength = 660,
        .displayCondFunc = NULL,
        .nameTextId = 0x07A9,
    },
    {
        .bgmId = 0x20,
        .songLength = 1440,
        .displayCondFunc = NULL,
        .nameTextId = 0x07AA,
    },
    {
        .bgmId = 0x21,
        .songLength = 840,
        .displayCondFunc = NULL,
        .nameTextId = 0x07AB,
    },
    {
        .bgmId = 0x22,
        .songLength = 660,
        .displayCondFunc = NULL,
        .nameTextId = 0x07AC,
    },
    {
        .bgmId = 0x23,
        .songLength = 1800,
        .displayCondFunc = NULL,
        .nameTextId = 0x07AD,
    },
    {
        .bgmId = 0x24,
        .songLength = 3180,
        .displayCondFunc = NULL,
        .nameTextId = 0x07AE,
    },
    {
        .bgmId = 0x25,
        .songLength = 2040,
        .displayCondFunc = NULL,
        .nameTextId = 0x07AF,
    },
    {
        .bgmId = 0x26,
        .songLength = 2520,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B0,
    },
    {
        .bgmId = 0x27,
        .songLength = 2700,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B1,
    },
    {
        .bgmId = 0x28,
        .songLength = 2940,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B2,
    },
    {
        .bgmId = 0x29,
        .songLength = 3180,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B3,
    },
    {
        .bgmId = 0x2A,
        .songLength = 2160,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B4,
    },
    {
        .bgmId = 0x2B,
        .songLength = 4200,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B5,
    },
    {
        .bgmId = 0x2C,
        .songLength = 2880,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B6,
    },
    {
        .bgmId = 0x2D,
        .songLength = 3720,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B7,
    },
    {
        .bgmId = 0x44,
        .songLength = 3900,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B8,
    },
    {
        .bgmId = 0x45,
        .songLength = 2880,
        .displayCondFunc = NULL,
        .nameTextId = 0x07B9,
    },
    {
        .bgmId = 0x2E,
        .songLength = 3300,
        .displayCondFunc = NULL,
        .nameTextId = 0x07BA,
    },
    {
        .bgmId = 0x2F,
        .songLength = 3420,
        .displayCondFunc = NULL,
        .nameTextId = 0x07BB,
    },
    {
        .bgmId = 0x30,
        .songLength = 2160,
        .displayCondFunc = NULL,
        .nameTextId = 0x07BC,
    },
    {
        .bgmId = 0x31,
        .songLength = 3120,
        .displayCondFunc = NULL,
        .nameTextId = 0x07BD,
    },
    {
        .bgmId = 0x32,
        .songLength = 2220,
        .displayCondFunc = NULL,
        .nameTextId = 0x07BE,
    },
    {
        .bgmId = 0x33,
        .songLength = 3960,
        .displayCondFunc = NULL,
        .nameTextId = 0x07BF,
    },
    {
        .bgmId = 0x34,
        .songLength = 3960,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C0,
    },
    {
        .bgmId = 0x35,
        .songLength = 1260,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C1,
    },
    {
        .bgmId = 0x36,
        .songLength = 1080,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C2,
    },
    {
        .bgmId = 0x37,
        .songLength = 900,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C3,
    },
    {
        .bgmId = 0x38,
        .songLength = 2520,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C4,
    },
    {
        .bgmId = 0x39,
        .songLength = 1740,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C5,
    },
    {
        .bgmId = 0x3A,
        .songLength = 360,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C6,
    },
    {
        .bgmId = 0x3B,
        .songLength = 1320,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C7,
    },
    {
        .bgmId = 0x3C,
        .songLength = 420,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C8,
    },
    {
        .bgmId = 0x3D,
        .songLength = 420,
        .displayCondFunc = NULL,
        .nameTextId = 0x07C9,
    },
    {
        .bgmId = 0x3E,
        .songLength = 2160,
        .displayCondFunc = NULL,
        .nameTextId = 0x07CA,
    },
    {
        .bgmId = 0x3F,
        .songLength = 1620,
        .displayCondFunc = NULL,
        .nameTextId = 0x07CB,
    },
    {
        .bgmId = 0x40,
        .songLength = 2760,
        .displayCondFunc = NULL,
        .nameTextId = 0x07CC,
    },
    {
        .bgmId = 0x41,
        .songLength = 6240,
        .displayCondFunc = NULL,
        .nameTextId = 0x07CD,
    },
    {
        .bgmId = 0x42,
        .songLength = 9120,
        .displayCondFunc = NULL,
        .nameTextId = 0x07CE,
    },
    {
        .bgmId = 0x46,
        .songLength = 9360,
        .displayCondFunc = NULL,
        .nameTextId = 0x07CF,
    },
    {
        .bgmId = -1,
    },
};
