#include "global.h"
#include "bmitem.h"
#include "mapanim.h"
#include "mu.h"
#include "fontgrp.h"
#include "constants/items.h"
#include "spellassoc.h"

#define SPELL_ASSOC_DATA(_item, _count, _efx, _pcmd, _stat, _facing, _color)   \
{                                                                               \
    .item           = _item,                                                    \
    .count          = _count,                                                   \
    .efx            = _efx,                                                    \
    .pcmd_manim     = _pcmd,                                                    \
    .stat           = _stat,                                                    \
    .facing         = _facing,                                                  \
    .flash_color    = _color,                                                   \
}

#define SPELL_ASSOC_DATA_WPN(_item, _efx)  \
    SPELL_ASSOC_DATA(_item, 2, _efx, NULL, true, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL)

#define SPELL_ASSOC_DATA_WPN_MAGIC(_item, _efx, flash_color)   \
    SPELL_ASSOC_DATA(_item, 2, _efx, NULL, true, MA_FACING_OPPONENT, flash_color)

#define SPELL_ASSOC_DATA_WPN_DEFAULT(_item) SPELL_ASSOC_DATA_WPN(_item, -1)
#define SPELL_ASSOC_DATA_ITEM(_item) SPELL_ASSOC_DATA_WPN(_item, 0x32)

CONST_DATA struct SpellAssoc gSpellAssocData[] = {
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_IRON),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_BLADE_IRON),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_STEEL),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_SILVER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_SLIM),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_VENIN),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_BRAVE),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_SWORD_LIGHTBRAND, 0x1F, SPELL_ASSOC_MCOLOR_LIGHT),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_UNK_BC),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_ARMORSLAYER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_RAPIER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_MKATTI),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_UNK_C0),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_KILLER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_LANCEREAVER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_ZANBATO),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_IRON),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_STEEL),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_SILVER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_SLIM),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_VENIN),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_BRAVE),
    SPELL_ASSOC_DATA_WPN(ITEM_LANCE_JAVELIN, 3),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_HORSESLAYER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_KILLER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_AXEREAVER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_HEAVYSPEAR),
    SPELL_ASSOC_DATA_WPN(ITEM_LANCE_SHORTSPEAR, 3),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_UNK_C3),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_IRON),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_STEEL),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_SILVER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_VENIN),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_BRAVE),
    SPELL_ASSOC_DATA_WPN(ITEM_AXE_HANDAXE, 1),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_UNK_BD),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_HAMMER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_KILLER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_SWORDSLAYER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_SWORDREAVER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_DEVIL),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_HALBERD),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_UNK_C4),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_UNK_C5),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_UNK_C6),

    SPELL_ASSOC_DATA_WPN(ITEM_BOW_IRON, 2),
    SPELL_ASSOC_DATA_WPN(ITEM_BOW_STEEL, 2),
    SPELL_ASSOC_DATA_WPN(ITEM_BOW_SILVER, 2),
    SPELL_ASSOC_DATA_WPN(ITEM_BOW_VENIN, 2),
    SPELL_ASSOC_DATA_WPN(ITEM_BOW_KILLER, 2),
    SPELL_ASSOC_DATA_WPN(ITEM_BOW_BRAVE, 2),
    SPELL_ASSOC_DATA_WPN(ITEM_BOW_SHORTBOW, 2),
    SPELL_ASSOC_DATA_WPN(ITEM_BOW_LONGBOW, 2),
    SPELL_ASSOC_DATA_WPN(ITEM_UNK_C7, 2),

    SPELL_ASSOC_DATA_WPN(ITEM_BALLISTA_REGULAR, 0x10),
    SPELL_ASSOC_DATA_WPN(ITEM_BALLISTA_LONG, 0x10),
    SPELL_ASSOC_DATA_WPN(ITEM_BALLISTA_KILLER, 0x10),

    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_ANIMA_FIRE, 0x16, SPELL_ASSOC_MCOLOR_FIRE),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_ANIMA_THUNDER, 0x19, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_ANIMA_FIMBULVETR, 0x1B, SPELL_ASSOC_MCOLOR_WIND),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_ANIMA_ELFIRE, 0x17, SPELL_ASSOC_MCOLOR_FIRE),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_DARK_FENRIR, 0x25, SPELL_ASSOC_MCOLOR_DARK),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_ANIMA_BOLTING, 0x1A, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_UNK_BF, 0x18, SPELL_ASSOC_MCOLOR_FIRE),

    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_LIGHT_LIGHTNING, 0x1F, SPELL_ASSOC_MCOLOR_LIGHT),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_LIGHT_DIVINE, 0x22, SPELL_ASSOC_MCOLOR_LIGHT),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_LIGHT_PURGE, 0x20, SPELL_ASSOC_MCOLOR_LIGHT),

    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_DARK_FLUX, 0x1D, SPELL_ASSOC_MCOLOR_DARK),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_DARK_NOSFERATU, 0x1E, SPELL_ASSOC_MCOLOR_DARK),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_DARK_ECLIPSE, 0x24, SPELL_ASSOC_MCOLOR_DARK),

    SPELL_ASSOC_DATA(ITEM_STAFF_HEAL, 2, 0x26, ProcScr_SpellAssocHeal, true, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_MEND, 2, 0x27, ProcScr_SpellAssocMend, true, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_RECOVER, 2, 0x28, ProcScr_SpellAssocRecover, true, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_PHYSIC, 2, 0x29, ProcScr_SpellAssocPhysic, true, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_FORTIFY, 1, 0x2A, ProcScr_SpellAssocLatona, false, MA_FACING_DEFAULT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_WARP, 2, -2, ProcScr_SpellAssocWarp, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_RESCUE, 2, -2, ProcScr_SpellAssocWarp, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_RESTORE, 2, 0x2C, ProcScr_SpellAssocRestore, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_SILENCE, 2, 0x2D, ProcScr_SpellAssocSilence, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_SLEEP, 2, 0x2E, ProcScr_SpellAssocSleep, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_TORCH, 1, -2, ProcScr_SpellAssocTorch, false, MA_FACING_DEFAULT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_REPAIR, 2, 0x2F, ProcScr_SpellAssocRepair, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_BERSERK, 2, 0x30, ProcScr_SpellAssocBerserk, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_UNLOCK, 1, -2, ProcScr_SpellAssocUnlock, false, MA_FACING_UNK, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_STAFF_BARRIER, 2, 0x31, ProcScr_SpellAssocBarrier, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),

    SPELL_ASSOC_DATA_ITEM(ITEM_HEROCREST),
    SPELL_ASSOC_DATA_ITEM(ITEM_KNIGHTCREST),
    SPELL_ASSOC_DATA_ITEM(ITEM_ORIONSBOLT),
    SPELL_ASSOC_DATA_ITEM(ITEM_ELYSIANWHIP),
    SPELL_ASSOC_DATA_ITEM(ITEM_GUIDINGRING),
    SPELL_ASSOC_DATA_ITEM(ITEM_MASTERSEAL),
    SPELL_ASSOC_DATA_ITEM(ITEM_HEAVENSEAL),
    SPELL_ASSOC_DATA_ITEM(ITEM_UNK_C1),
    SPELL_ASSOC_DATA_ITEM(ITEM_OCEANSEAL),
    SPELL_ASSOC_DATA_ITEM(ITEM_LUNARBRACE),
    SPELL_ASSOC_DATA_ITEM(ITEM_SOLARBRACE),

    SPELL_ASSOC_DATA(ITEM_VULNERARY, 1, -2, ProcScr_SpellAssocVulenrary, true, MA_FACING_DEFAULT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_VULNERARY_2, 1, -2, ProcScr_SpellAssocVulenrary, true, MA_FACING_DEFAULT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_ELIXIR, 1, -2, ProcScr_SpellAssocElixir, true, MA_FACING_DEFAULT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_PUREWATER, 1, -2, ProcScr_SpellAssocPureWater, false, MA_FACING_DEFAULT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_TORCH, 1, -2, ProcScr_SpellAssocTorch, false, MA_FACING_DEFAULT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_ANTITOXIN, 1, -2, ProcScr_SpellAssocAntitoxin, false, MA_FACING_DEFAULT, SPELL_ASSOC_MCOLOR_NORMAL),

    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_BLADE_STEEL),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_BLADE_SILVER),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_WYRMSLAYER),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_SWORD_RUNESWORD, 0x1E, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_LANCE_SPEAR, 0x3, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_UNK_C8, 0x3, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_AXE_TOMAHAWK, 0x1, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_ANIMA_EXCALIBUR, 0x35, SPELL_ASSOC_MCOLOR_WIND),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_ANIMA_AIRCALIBUR, 0x1C, SPELL_ASSOC_MCOLOR_WIND),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_LIGHT_SHINE, 0x33, SPELL_ASSOC_MCOLOR_LIGHT),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_LIGHT_AURA, 0x37, SPELL_ASSOC_MCOLOR_LIGHT),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_UNK_C9, 0x38, SPELL_ASSOC_MCOLOR_LIGHT),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_DARK_LUNA, 0x34, SPELL_ASSOC_MCOLOR_DARK),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_UNK_CB, 0x36, SPELL_ASSOC_MCOLOR_DARK),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_UNK_BE, 0x21, SPELL_ASSOC_MCOLOR_LIGHT),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_MONSTER_WRETCHAIR, 0x47, SPELL_ASSOC_MCOLOR_FIRE),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_UNK_CA, 0x39, SPELL_ASSOC_MCOLOR_DARK),

    SPELL_ASSOC_DATA(ITEM_FILLAS_MIGHT, 2, 0x3A, NULL, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_FIRE),
    SPELL_ASSOC_DATA(ITEM_NINISS_GRACE, 2, 0x3B, NULL, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_WIND),
    SPELL_ASSOC_DATA(ITEM_THORS_IRE, 2, 0x3C, NULL, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_WIND),
    SPELL_ASSOC_DATA(ITEM_SETS_LITANY, 2, 0x3D, NULL, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_ICE),

    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_SHADOWKILLR),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_BRIGHTLANCE),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_FIENDCLEAVER),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_BOW_BEACONBOW, 0x2, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_SWORD_WINDSWORD, 0x35, SPELL_ASSOC_MCOLOR_WIND),

    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_DRAGON),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_DEMONSTONE),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_MONSTER_ROTTENCLW),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_MONSTER_FETIDCLW),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_MONSTER_VENINCLW),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_MONSTER_LTHLTALON),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_MONSTER_SHARPCLAW),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_MONSTER_FIREFANG),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_MONSTER_HELLFANG),

    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_MONSTER_EVILEYE, 0x43, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_MONSTER_CRIMSNEYE, 0x42, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_MONSTER_STONE, 2, 0x3E, ProcScr_SpellAssocMonsterStone, true, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_MONSTER_DEMONSURG, 0x45, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_LIGHT_IVALDI, 0x3F, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_DARK_GLEIPNIR, 0x41, SPELL_ASSOC_MCOLOR_DARK),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_MONSTER_SHADOWSHT, 0x44, SPELL_ASSOC_MCOLOR_DARK),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_DARK_NAGLFAR, 0x46, SPELL_ASSOC_MCOLOR_DARK),

    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_SHAMSIR),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_SIEGLINDE),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_REGINLEIF),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_DRAGON),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_VIDOFNIR),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_SWORD_AUDHULMA),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_LANCE_SIEGMUND),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_GARM),

    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_BOW_NIDHOGG, 0x2, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_AXE_HATCHET, 0x1, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_AXE_BATTLEAXE),

    SPELL_ASSOC_DATA(ITEM_STAFF_LATONA, 1, 0x2B, ProcScr_SpellAssocLatona, false, MA_FACING_DEFAULT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA(ITEM_NIGHTMARE, 2, -1, ProcScr_SpellAssocNightMare, false, MA_FACING_OPPONENT, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_DEMONLIGHT, 0x40, SPELL_ASSOC_MCOLOR_NORMAL),
    SPELL_ASSOC_DATA_WPN_DEFAULT(ITEM_RAVAGER),
    SPELL_ASSOC_DATA_WPN_MAGIC(ITEM_DIVINESTONE, 0x13, SPELL_ASSOC_MCOLOR_NORMAL),

    SPELL_ASSOC_DATA_WPN_DEFAULT(0xFFFF),
};
