// unit icon move animation pointer table

#include "unit_icon_data.h"

UnitIconMove unit_icon_move_table[] = {
	{unit_icon_move_Ephraim_Lord_sheet, unit_icon_move_Ephraim_Lord_motion}, // 0
	{unit_icon_move_Eirika_Lord_sheet, unit_icon_move_Eirika_Lord_motion}, // 1
	{unit_icon_move_Ephraim_Master_Lord_sheet, unit_icon_move_Ephraim_Master_Lord_motion}, // 2
	{unit_icon_move_Eirika_Master_Lord_sheet, unit_icon_move_Eirika_Master_Lord_motion}, // 3
	{unit_icon_move_Cavalier_sheet, unit_icon_move_Cavalier_motion}, // 4
	{unit_icon_move_Cavalier_sheet, unit_icon_move_Cavalier_motion}, // 5
	{unit_icon_move_Paladin_sheet, unit_icon_move_Paladin_motion}, // 6
	{unit_icon_move_Paladin_sheet, unit_icon_move_Paladin_motion}, // 7
	{unit_icon_move_Armor_Knight_sheet, unit_icon_move_Armor_Knight_motion}, // 8
	{unit_icon_move_Armor_Knight_sheet, unit_icon_move_Armor_Knight_motion}, // 9
	{unit_icon_move_General_sheet, unit_icon_move_General_motion}, // 10
	{unit_icon_move_General_sheet, unit_icon_move_General_motion}, // 11
	{unit_icon_move_Thief_sheet, unit_icon_move_Thief_motion}, // 12
	{unit_icon_move_Manakete_sheet, unit_icon_move_Manakete_motion}, // 13
	{unit_icon_move_Mercenary_sheet, unit_icon_move_Mercenary_motion}, // 14
	{unit_icon_move_Mercenary_F_sheet, unit_icon_move_Mercenary_F_motion}, // 15
	{unit_icon_move_Hero_sheet, unit_icon_move_Hero_motion}, // 16
	{unit_icon_move_Hero_F_sheet, unit_icon_move_Hero_F_motion}, // 17
	{unit_icon_move_Myrmidon_sheet, unit_icon_move_Myrmidon_motion}, // 18
	{unit_icon_move_Myrmidon_F_sheet, unit_icon_move_Myrmidon_F_motion}, // 19
	{unit_icon_move_Swordmaster_sheet, unit_icon_move_Swordmaster_motion}, // 20
	{unit_icon_move_Swordmaster_F_sheet, unit_icon_move_Swordmaster_F_motion}, // 21
	{unit_icon_move_Assassin_sheet, unit_icon_move_Assassin_motion}, // 22
	{unit_icon_move_Assassin_F_sheet, unit_icon_move_Assassin_F_motion}, // 23
	{unit_icon_move_Archer_sheet, unit_icon_move_Archer_motion}, // 24
	{unit_icon_move_Archer_F_sheet, unit_icon_move_Archer_F_motion}, // 25
	{unit_icon_move_Sniper_sheet, unit_icon_move_Sniper_motion}, // 26
	{unit_icon_move_Sniper_F_sheet, unit_icon_move_Sniper_F_motion}, // 27
	{unit_icon_move_Ranger_sheet, unit_icon_move_Ranger_motion}, // 28
	{unit_icon_move_Ranger_sheet, unit_icon_move_Ranger_motion}, // 29
	{unit_icon_move_Wyvern_Rider_sheet, unit_icon_move_Wyvern_Rider_motion}, // 30
	{unit_icon_move_Wyvern_Lord_sheet, unit_icon_move_Wyvern_Lord_motion}, // 31
	{unit_icon_move_Wyvern_Lord_F_sheet, unit_icon_move_Wyvern_Lord_F_motion}, // 32
	{unit_icon_move_Wyvern_Knight_sheet, unit_icon_move_Wyvern_Knight_motion}, // 33
	{unit_icon_move_Wyvern_Knight_F_sheet, unit_icon_move_Wyvern_Knight_F_motion}, // 34
	{unit_icon_move_Wyvern_Knight_F_sheet, unit_icon_move_Wyvern_Knight_F_motion}, // 35
	{unit_icon_move_Mage_sheet, unit_icon_move_Mage_motion}, // 36
	{unit_icon_move_Mage_F_sheet, unit_icon_move_Mage_F_motion}, // 37
	{unit_icon_move_Sage_sheet, unit_icon_move_Sage_motion}, // 38
	{unit_icon_move_Sage_F_sheet, unit_icon_move_Sage_F_motion}, // 39
	{unit_icon_move_Mage_Knight_sheet, unit_icon_move_Mage_Knight_motion}, // 40
	{unit_icon_move_Mage_Knight_F_sheet, unit_icon_move_Mage_Knight_F_motion}, // 41
	{unit_icon_move_Bishop_sheet, unit_icon_move_Bishop_motion}, // 42
	{unit_icon_move_Bishop_F_sheet, unit_icon_move_Bishop_F_motion}, // 43
	{unit_icon_move_Shaman_sheet, unit_icon_move_Shaman_motion}, // 44
	{unit_icon_move_Shaman_sheet, unit_icon_move_Shaman_motion}, // 45
	{unit_icon_move_Druid_sheet, unit_icon_move_Druid_motion}, // 46
	{unit_icon_move_Druid_sheet, unit_icon_move_Druid_motion}, // 47
	{unit_icon_move_Summoner_sheet, unit_icon_move_Summoner_motion}, // 48
	{unit_icon_move_Summoner_sheet, unit_icon_move_Summoner_motion}, // 49
	{unit_icon_move_Rogue_sheet, unit_icon_move_Rogue_motion}, // 50
	{unit_icon_move_Gorgonegg2_sheet, unit_icon_move_Gorgonegg2_motion}, // 51
	{unit_icon_move_Great_Knight_sheet, unit_icon_move_Great_Knight_motion}, // 52
	{unit_icon_move_Great_Knight_sheet, unit_icon_move_Great_Knight_motion}, // 53
	{unit_icon_move_Recruit_T1_sheet, unit_icon_move_Recruit_T1_motion}, // 54
	{unit_icon_move_Journeyman_T2_sheet, unit_icon_move_Journeyman_T2_motion}, // 55
	{unit_icon_move_Pupil_T2_sheet, unit_icon_move_Pupil_T2_motion}, // 56
	{unit_icon_move_Recruit_T1_sheet, unit_icon_move_Recruit_T1_motion}, // 57
	{unit_icon_move_Manakete_2_sheet, unit_icon_move_Manakete_2_motion}, // 58
	{unit_icon_move_Manakete_Myrrh_sheet, unit_icon_move_Manakete_Myrrh_motion}, // 59
	{unit_icon_move_Journeyman_T2_sheet, unit_icon_move_Journeyman_T2_motion}, // 60
	{unit_icon_move_Pupil_T2_sheet, unit_icon_move_Pupil_T2_motion}, // 61
	{unit_icon_move_Fighter_sheet, unit_icon_move_Fighter_motion}, // 62
	{unit_icon_move_Warrior_sheet, unit_icon_move_Warrior_motion}, // 63
	{unit_icon_move_Brigand_sheet, unit_icon_move_Brigand_motion}, // 64
	{unit_icon_move_Pirate_sheet, unit_icon_move_Pirate_motion}, // 65
	{unit_icon_move_Berserker_sheet, unit_icon_move_Berserker_motion}, // 66
	{unit_icon_move_Monk_sheet, unit_icon_move_Monk_motion}, // 67
	{unit_icon_move_Priest_sheet, unit_icon_move_Priest_motion}, // 68
	{unit_icon_move_Bard_sheet, unit_icon_move_Bard_motion}, // 69
	{unit_icon_move_Recruit_T1_sheet, unit_icon_move_Recruit_T1_motion}, // 70
	{unit_icon_move_Pegasus_Knight_sheet, unit_icon_move_Pegasus_Knight_motion}, // 71
	{unit_icon_move_Falcon_Knight_sheet, unit_icon_move_Falcon_Knight_motion}, // 72
	{unit_icon_move_Cleric_sheet, unit_icon_move_Cleric_motion}, // 73
	{unit_icon_move_Troubadour_sheet, unit_icon_move_Troubadour_motion}, // 74
	{unit_icon_move_Valkyrie_sheet, unit_icon_move_Valkyrie_motion}, // 75
	{unit_icon_move_Dancer_sheet, unit_icon_move_Dancer_motion}, // 76
	{unit_icon_move_Soldier_sheet, unit_icon_move_Soldier_motion}, // 77
	{unit_icon_move_Necromancer_sheet, unit_icon_move_Necromancer_motion}, // 78
	{unit_icon_move_Fleet_sheet, unit_icon_move_Fleet_motion}, // 79
	{unit_icon_move_Phantom_sheet, unit_icon_move_Phantom_motion}, // 80
	{unit_icon_move_Revenant_sheet, unit_icon_move_Revenant_motion}, // 81
	{unit_icon_move_Entoumbed_sheet, unit_icon_move_Entoumbed_motion}, // 82
	{unit_icon_move_Bonewalker_sheet, unit_icon_move_Bonewalker_motion}, // 83
	{unit_icon_move_Bonewalker_Bow_sheet, unit_icon_move_Bonewalker_Bow_motion}, // 84
	{unit_icon_move_Wight_sheet, unit_icon_move_Wight_motion}, // 85
	{unit_icon_move_Wight_Bow_sheet, unit_icon_move_Wight_Bow_motion}, // 86
	{unit_icon_move_Bael_sheet, unit_icon_move_Bael_motion}, // 87
	{unit_icon_move_Elder_Bael_sheet, unit_icon_move_Elder_Bael_motion}, // 88
	{unit_icon_move_Cyclops_sheet, unit_icon_move_Cyclops_motion}, // 89
	{unit_icon_move_Mauthedoog_sheet, unit_icon_move_Mauthedoog_motion}, // 90
	{unit_icon_move_Gwyllgi_sheet, unit_icon_move_Gwyllgi_motion}, // 91
	{unit_icon_move_Tarvos_sheet, unit_icon_move_Tarvos_motion}, // 92
	{unit_icon_move_Maelduin_sheet, unit_icon_move_Maelduin_motion}, // 93
	{unit_icon_move_Mogall_sheet, unit_icon_move_Mogall_motion}, // 94
	{unit_icon_move_Arch_Mogall_sheet, unit_icon_move_Arch_Mogall_motion}, // 95
	{unit_icon_move_Gorgon_sheet, unit_icon_move_Gorgon_motion}, // 96
	{unit_icon_move_Gorgonegg_sheet, unit_icon_move_Gorgonegg_motion}, // 97
	{unit_icon_move_Gargoyle_sheet, unit_icon_move_Gargoyle_motion}, // 98
	{unit_icon_move_Deathgoyle_sheet, unit_icon_move_Deathgoyle_motion}, // 99
	{unit_icon_move_Draco_Zombie_sheet, unit_icon_move_Draco_Zombie_motion}, // 100
	{unit_icon_move_Demon_King_sheet, unit_icon_move_Demon_King_motion}, // 101
	{unit_icon_move_Blst_Regular_Used_sheet, unit_icon_move_Blst_Regular_Used_motion}, // 102
	{unit_icon_move_Blst_Long_Used_sheet, unit_icon_move_Blst_Long_Used_motion}, // 103
	{unit_icon_move_Blst_Killer_Used_sheet, unit_icon_move_Blst_Killer_Used_motion}, // 104
	{unit_icon_move_Blst_Long_Empty_sheet, unit_icon_move_Blst_Long_Empty_motion}, // 105
	{unit_icon_move_Blst_Used_Empty_sheet, unit_icon_move_Blst_Used_Empty_motion}, // 106
	{unit_icon_move_Blst_Killer_Empty_sheet, unit_icon_move_Blst_Killer_Empty_motion}, // 107
	{unit_icon_move_Civilian_M1_sheet, unit_icon_move_Civilian_M1_motion}, // 108
	{unit_icon_move_Civilian_F1_sheet, unit_icon_move_Civilian_F1_motion}, // 109
	{unit_icon_move_Civilian_M2_sheet, unit_icon_move_Civilian_M2_motion}, // 110
	{unit_icon_move_Civilian_F2_sheet, unit_icon_move_Civilian_F2_motion}, // 111
	{unit_icon_move_Civilian_M2_sheet, unit_icon_move_Civilian_M2_motion}, // 112
	{unit_icon_move_Civilian_F2_sheet, unit_icon_move_Civilian_F2_motion}, // 113
	{unit_icon_move_Peer_sheet, unit_icon_move_Peer_motion}, // 114
	{unit_icon_move_Queen_sheet, unit_icon_move_Queen_motion}, // 115
	{unit_icon_move_Prince_sheet, unit_icon_move_Prince_motion}, // 116
	{unit_icon_move_Queen_2_sheet, unit_icon_move_Queen_2_motion}, // 117
	{unit_icon_move_Unk77_sheet, unit_icon_move_Unk77_motion}, // 118
	{unit_icon_move_Fallen_Prince_sheet, unit_icon_move_Fallen_Prince_motion}, // 119
	{unit_icon_move_Tent_sheet, unit_icon_move_Tent_motion}, // 120
	{unit_icon_move_Pontifex_sheet, unit_icon_move_Pontifex_motion}, // 121
	{unit_icon_move_Fallen_Peer_sheet, unit_icon_move_Fallen_Peer_motion}, // 122
	{unit_icon_move_Cyclops_sheet, unit_icon_move_Cyclops_motion}, // 123
	{unit_icon_move_Elder_Bael_sheet, unit_icon_move_Elder_Bael_motion}, // 124
	{unit_icon_move_Journeyman_T2_sheet, unit_icon_move_Journeyman_T2_motion}, // 125
	{unit_icon_move_Pupil_T2_sheet, unit_icon_move_Pupil_T2_motion}, // 126
};
