#include "global.h"

#include "ctc.h"
#include "worldmap.h"

#include "constants/worldmap.h"

const struct NodeIcon gWMNodeIconData[] =
{
    {
        .sheetTileId = 0x0080,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 19,
        .yFlagOrigin = 1,
    },
    {
        .sheetTileId = 0x0084,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 15,
        .yFlagOrigin = 8,
    },
    {
        .sheetTileId = 0x0088,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 15,
        .yFlagOrigin = 8,
    },
    {
        .sheetTileId = 0x0088,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 15,
        .yFlagOrigin = 8,
    },
    {
        .sheetTileId = 0x0088,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 15,
        .yFlagOrigin = 8,
    },
    {
        .sheetTileId = 0x0092,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 8,
        .yFlagOrigin = 1,
    },
    {
        .sheetTileId = 0x009A,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 5,
    },
    {
        .sheetTileId = 0x0014,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 4,
    },
    {
        .sheetTileId = 0x0018,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 4,
    },
    {
        .sheetTileId = 0x0098,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 8,
        .yFlagOrigin = 3,
    },
    {
        .sheetTileId = 0x00D2,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 6,
        .yFlagOrigin = 2,
    },
    {
        .sheetTileId = 0x0094,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 10,
        .yFlagOrigin = 2,
    },
    {
        .sheetTileId = 0x001C,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 11,
    },
    {
        .sheetTileId = 0x0090,
        .pSpriteData = gObject_16x32,
        .xCenter = 8,
        .yCenter = 24,
        .width = 16,
        .height = 32,
        .xFlagOrigin = 8,
        .yFlagOrigin = 24,
    },
    {
        .sheetTileId = 0x008C,
        .pSpriteData = gObject_32x32,
        .xCenter = 16,
        .yCenter = 24,
        .width = 32,
        .height = 32,
        .xFlagOrigin = 16,
        .yFlagOrigin = 24,
    },
    {
        .sheetTileId = 0x00D4,
        .pSpriteData = gObject_8x8,
        .xCenter = 4,
        .yCenter = 4,
        .width = 8,
        .height = 8,
        .xFlagOrigin = 4,
        .yFlagOrigin = 4,
    },
    {
        .sheetTileId = 0x0092,
        .pSpriteData = gObject_16x16,
        .xCenter = 8,
        .yCenter = 8,
        .width = 16,
        .height = 16,
        .xFlagOrigin = 8,
        .yFlagOrigin = 8,
    },
};

const struct GMapNodeData gWMNodeData[] =
{
    [NODE_BORDER_MULAN] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x0B,
        .iconPostClear = 0x0B,
        .chapteridx_eirika = 0x00,
        .chapteridx_ephram = 0x00,
        .unk_06 = 0x0089,
        .unk_08 = { 0x00, 0x00, 0x01, 0x01, },
        .armory = (u16 *) 0x08A3EFB4,
        .vendor = (u16 *) 0x08A3F078,
        .secretShop = (u16 *) 0x08A3F16A,
        .x = 152,
        .y = 88,
        .nameTextId = 0x0650, // TODO: msgid "Border Mulan"
        .shipTravelFlag = 0,
    },
    [NODE_CASTLE_FRELIA] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_FRELIA,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x02,
        .iconPostClear = 0x02,
        .chapteridx_eirika = 0x38,
        .chapteridx_ephram = 0x38,
        .unk_06 = 0x0088,
        .unk_08 = { 0x02, 0x02, 0x09, 0x0E, },
        .armory = (u16 *) 0x08A3EFB6,
        .vendor = (u16 *) 0x08A3F07A,
        .secretShop = (u16 *) 0x08A3F16C,
        .x = 88,
        .y = 72,
        .nameTextId = 0x0651, // TODO: msgid "Castle Frelia[.]"
        .shipTravelFlag = 0,
    },
    [NODE_IDE] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0A,
        .iconPostClear = 0x0A,
        .chapteridx_eirika = 0x02,
        .chapteridx_ephram = 0x02,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x03, 0x03, 0x03, 0x03, },
        .armory = (u16 *) 0x08A3EFB8,
        .vendor = (u16 *) 0x08A3F07C,
        .secretShop = (u16 *) 0x08A3F16E,
        .x = 120,
        .y = 120,
        .nameTextId = 0x0652, // TODO: msgid "Ide[.]"
        .shipTravelFlag = 0,
    },
    [NODE_BORGO_RIDGE] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0B,
        .iconPostClear = 0x0B,
        .chapteridx_eirika = 0x03,
        .chapteridx_ephram = 0x03,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x04, 0x04, 0x04, 0x04, },
        .armory = (u16 *) 0x08A3EFCA,
        .vendor = (u16 *) 0x08A3F07E,
        .secretShop = (u16 *) 0x08A3F170,
        .x = 120,
        .y = 152,
        .nameTextId = 0x0653, // TODO: msgid "Borgo Ridge[.]"
        .shipTravelFlag = 0,
    },
    [NODE_ZAHA_WOODS] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0x04,
        .chapteridx_ephram = 0x04,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x05, 0x05, 0x05, 0x05, },
        .armory = (u16 *) 0x08A3EFCC,
        .vendor = (u16 *) 0x08A3F080,
        .secretShop = (u16 *) 0x08A3F172,
        .x = 152,
        .y = 152,
        .nameTextId = 0x0654, // TODO: msgid "Za'ha Woods[.]"
        .shipTravelFlag = 0,
    },
    [NODE_SERAFEW] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x0A,
        .iconPostClear = 0x0A,
        .chapteridx_eirika = 0x06,
        .chapteridx_ephram = 0x06,
        .unk_06 = 0x0088,
        .unk_08 = { 0x06, 0x06, 0x01, 0x01, },
        .armory = (u16 *) 0x08A3EFCE,
        .vendor = (u16 *) 0x08A3F082,
        .secretShop = (u16 *) 0x08A3F174,
        .x = 152,
        .y = 183,
        .nameTextId = 0x0655, // TODO: msgid "Serafew[.]"
        .shipTravelFlag = 0,
    },
    [NODE_ADLAS_PLAINS] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0x07,
        .chapteridx_ephram = 0x07,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x07, 0x07, 0x07, 0x07, },
        .armory = (u16 *) 0x08A3EFE4,
        .vendor = (u16 *) 0x08A3F090,
        .secretShop = (u16 *) 0x08A3F176,
        .x = 184,
        .y = 200,
        .nameTextId = 0x0656, // TODO: msgid "Adlas Plains"
        .shipTravelFlag = 0,
    },
    [NODE_RENVALL_07] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x05,
        .iconPostClear = 0x05,
        .chapteridx_eirika = 0x08,
        .chapteridx_ephram = 0x08,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x08, 0x08, 0x08, 0x08, },
        .armory = (u16 *) 0x08A3EFE6,
        .vendor = (u16 *) 0x08A3F092,
        .secretShop = (u16 *) 0x08A3F178,
        .x = 216,
        .y = 216,
        .nameTextId = 0x0657, // TODO: msgid "Renvall[.]"
        .shipTravelFlag = 0,
    },
    [NODE_RENVALL_08] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x05,
        .iconPostClear = 0x05,
        .chapteridx_eirika = 0x09,
        .chapteridx_ephram = 0x09,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x05, 0x05, 0x05, 0x05, },
        .armory = (u16 *) 0x08A3EFE8,
        .vendor = (u16 *) 0x08A3F094,
        .secretShop = (u16 *) 0x08A3F17A,
        .x = 216,
        .y = 216,
        .nameTextId = 0x0658, // TODO: msgid "Renvall[.]"
        .shipTravelFlag = 0,
    },
    [NODE_PORT_KIRIS] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x0A,
        .iconPostClear = 0x0A,
        .chapteridx_eirika = 0x0A,
        .chapteridx_ephram = 0x0A,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x0A, 0x0A, 0x0A, 0x0A, },
        .armory = (u16 *) 0x08A3EFEA,
        .vendor = (u16 *) 0x08A3F096,
        .secretShop = (u16 *) 0x08A3F17C,
        .x = 216,
        .y = 56,
        .nameTextId = 0x0659, // TODO: msgid "Port Kiris"
        .shipTravelFlag = 1,
    },
    [NODE_TERAZ_PLATEAU] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0x0B,
        .chapteridx_ephram = 0x0B,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x0B, 0x0B, 0x0B, 0x0B, },
        .armory = (u16 *) 0x08A3F004,
        .vendor = (u16 *) 0x08A3F0B2,
        .secretShop = (u16 *) 0x08A3F17E,
        .x = 216,
        .y = 104,
        .nameTextId = 0x065A, // TODO: msgid "Teraz Plateau[.]"
        .shipTravelFlag = 0,
    },
    [NODE_CAER_PELYN] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x09,
        .iconPostClear = 0x09,
        .chapteridx_eirika = 0x3D,
        .chapteridx_ephram = 0x3D,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x0C, 0x0C, 0x0C, 0x0C, },
        .armory = (u16 *) 0x08A3F006,
        .vendor = (u16 *) 0x08A3F0B4,
        .secretShop = (u16 *) 0x08A3F180,
        .x = 264,
        .y = 104,
        .nameTextId = 0x065B, // TODO: msgid "Caer Pelyn"
        .shipTravelFlag = 0,
    },
    [NODE_HAMILL_CANYON] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0x0D,
        .chapteridx_ephram = 0x0D,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x0D, 0x0D, 0x0D, 0x0D, },
        .armory = (u16 *) 0x08A3F008,
        .vendor = (u16 *) 0x08A3F0CC,
        .secretShop = (u16 *) 0x08A3F182,
        .x = 312,
        .y = 136,
        .nameTextId = 0x065C, // TODO: msgid "Hamill Canyon[.]"
        .shipTravelFlag = 0,
    },
    [NODE_JEHANNA_HALL_0D] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x07,
        .iconPostClear = 0x07,
        .chapteridx_eirika = 0x0E,
        .chapteridx_ephram = 0x0E,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x13, 0x13, 0x13, 0x13, },
        .armory = (u16 *) 0x08A3F00A,
        .vendor = (u16 *) 0x08A3F0CE,
        .secretShop = (u16 *) 0x08A3F184,
        .x = 312,
        .y = 200,
        .nameTextId = 0x065D, // TODO: msgid "Jehanna Hall"
        .shipTravelFlag = 0,
    },
    [NODE_FORT_RIGWALD] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0B,
        .iconPostClear = 0x0B,
        .chapteridx_eirika = 0x17,
        .chapteridx_ephram = 0x17,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x0F, 0x0F, 0x0F, 0x0F, },
        .armory = (u16 *) 0x08A3F00C,
        .vendor = (u16 *) 0x08A3F0D0,
        .secretShop = (u16 *) 0x08A3F186,
        .x = 72,
        .y = 152,
        .nameTextId = 0x065E, // TODO: msgid "Fort Rigwald"
        .shipTravelFlag = 0,
    },
    [NODE_BETHROEN] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0x18,
        .chapteridx_ephram = 0x18,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x10, 0x10, 0x10, 0x10, },
        .armory = (u16 *) 0x08A3F00E,
        .vendor = (u16 *) 0x08A3F0D2,
        .secretShop = (u16 *) 0x08A3F188,
        .x = 72,
        .y = 232,
        .nameTextId = 0x065F, // TODO: msgid "Bethroen"
        .shipTravelFlag = 1,
    },
    [NODE_TAIZEL] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x0A,
        .iconPostClear = 0x0A,
        .chapteridx_eirika = 0x3E,
        .chapteridx_ephram = 0x3E,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x11, 0x11, 0x11, 0x11, },
        .armory = (u16 *) 0x08A3F028,
        .vendor = (u16 *) 0x08A3F0EE,
        .secretShop = (u16 *) 0x08A3F18A,
        .x = 152,
        .y = 248,
        .nameTextId = 0x0660, // TODO: msgid "Taizel"
        .shipTravelFlag = 1,
    },
    [NODE_ZAALBUL_MARSH] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0x1A,
        .chapteridx_ephram = 0x1A,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x12, 0x12, 0x12, 0x12, },
        .armory = (u16 *) 0x08A3F02A,
        .vendor = (u16 *) 0x08A3F106,
        .secretShop = (u16 *) 0x08A3F18C,
        .x = 200,
        .y = 264,
        .nameTextId = 0x0661, // TODO: msgid "Za'albul Marsh"
        .shipTravelFlag = 0,
    },
    [NODE_GRADO_KEEP] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x08,
        .iconPostClear = 0x08,
        .chapteridx_eirika = 0x1B,
        .chapteridx_ephram = 0x1B,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x13, 0x13, 0x13, 0x13, },
        .armory = (u16 *) 0x08A3F02C,
        .vendor = (u16 *) 0x08A3F108,
        .secretShop = (u16 *) 0x08A3F18E,
        .x = 264,
        .y = 264,
        .nameTextId = 0x0662, // TODO: msgid "Grado Keep"
        .shipTravelFlag = 0,
    },
    [NODE_JEHANNA_HALL_13] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x07,
        .iconPostClear = 0x07,
        .chapteridx_eirika = 0x0F,
        .chapteridx_ephram = 0x1C,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x14, 0x14, 0x14, 0x14, },
        .armory = (u16 *) 0x08A3F02E,
        .vendor = (u16 *) 0x08A3F10A,
        .secretShop = (u16 *) 0x08A3F1B8,
        .x = 312,
        .y = 200,
        .nameTextId = 0x0663, // TODO: msgid "Jehanna Hall"
        .shipTravelFlag = 0,
    },
    [NODE_RENAIS_CASTLE] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x06,
        .iconPostClear = 0x06,
        .chapteridx_eirika = 0x10,
        .chapteridx_ephram = 0x1D,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x15, 0x15, 0x15, 0x15, },
        .armory = (u16 *) 0x08A3F030,
        .vendor = (u16 *) 0x08A3F128,
        .secretShop = (u16 *) 0x08A3F1E2,
        .x = 216,
        .y = 152,
        .nameTextId = 0x0664, // TODO: msgid "Renais Castle[.]"
        .shipTravelFlag = 0,
    },
    [NODE_NARUBE_RIVER] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0x11,
        .chapteridx_ephram = 0x1E,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x16, 0x16, 0x16, 0x16, },
        .armory = (u16 *) 0x08A3F032,
        .vendor = (u16 *) 0x08A3F12A,
        .secretShop = (u16 *) 0x08A3F1E4,
        .x = 360,
        .y = 168,
        .nameTextId = 0x0665, // TODO: msgid "Narube River"
        .shipTravelFlag = 0,
    },
    [NODE_NELERAS_PEAK] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0x12,
        .chapteridx_ephram = 0x1F,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x17, 0x17, 0x17, 0x17, },
        .armory = (u16 *) 0x08A3F04E,
        .vendor = (u16 *) 0x08A3F142,
        .secretShop = (u16 *) 0x08A3F1E6,
        .x = 360,
        .y = 120,
        .nameTextId = 0x0666, // TODO: msgid "Neleras Peak"
        .shipTravelFlag = 0,
    },
    [NODE_RAUSTEN_COURT] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x03,
        .iconPostClear = 0x03,
        .chapteridx_eirika = 0x13,
        .chapteridx_ephram = 0x20,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0x19, 0x19, 0x19, 0x19, },
        .armory = (u16 *) 0x08A3F050,
        .vendor = (u16 *) 0x08A3F144,
        .secretShop = (u16 *) 0x08A3F1E8,
        .x = 392,
        .y = 88,
        .nameTextId = 0x0667, // TODO: msgid "Rausten Court[.]"
        .shipTravelFlag = 0,
    },
    [NODE_DARKLING_WOODS] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0xFF,
        .chapteridx_ephram = 0xFF,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0xFF, 0xFF, 0xFF, 0xFF, },
        .armory = (u16 *) 0x08A3F06E,
        .vendor = (u16 *) 0x08A3F160,
        .secretShop = (u16 *) 0x08A3F212,
        .x = 344,
        .y = 72,
        .nameTextId = 0x0668, // TODO: msgid "Darkling Woods"
        .shipTravelFlag = 0,
    },
    [NODE_BLACK_TEMPLE] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_PROGRESSION,
        .encounters = GMAP_ENCOUNTERS_NONE,
        .iconPreClear = 0x0C,
        .iconPostClear = 0x0C,
        .chapteridx_eirika = 0x14,
        .chapteridx_ephram = 0x21,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0xFF, 0xFF, 0xFF, 0xFF, },
        .armory = (u16 *) 0x08A3F070,
        .vendor = (u16 *) 0x08A3F162,
        .secretShop = (u16 *) 0x08A3F214,
        .x = 312,
        .y = 88,
        .nameTextId = 0x0669, // TODO: msgid "Black Temple"
        .shipTravelFlag = 0,
    },
    [NODE_TOWER_OF_VALNI] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_DUNGEON,
        .encounters = GMAP_ENCOUNTERS_DUNGEON,
        .iconPreClear = 0x0D,
        .iconPostClear = 0x0D,
        .chapteridx_eirika = 0x24,
        .chapteridx_ephram = 0x24,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0xFF, 0xFF, 0xFF, 0xFF, },
        .armory = (u16 *) 0x08A3F072,
        .vendor = (u16 *) 0x08A3F164,
        .secretShop = (u16 *) 0x08A3F216,
        .x = 152,
        .y = 56,
        .nameTextId = 0x066A, // TODO: msgid "Tower of Valni"
        .shipTravelFlag = 0,
    },
    [NODE_LAGDOU_RUINS] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_DUNGEON,
        .encounters = GMAP_ENCOUNTERS_DUNGEON,
        .iconPreClear = 0x0E,
        .iconPostClear = 0x0E,
        .chapteridx_eirika = 0x2E,
        .chapteridx_ephram = 0x2E,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0xFF, 0xFF, 0xFF, 0xFF, },
        .armory = (u16 *) 0x08A3F074,
        .vendor = (u16 *) 0x08A3F166,
        .secretShop = (u16 *) 0x08A3F218,
        .x = 408,
        .y = 184,
        .nameTextId = 0x066B, // TODO: msgid "Lagdou Ruins"
        .shipTravelFlag = 0,
    },
    [NODE_MELKAEN_COAST] =
    {
        .placementFlag = GMAP_NODE_PLACEMENT_MONSTERSPAWN,
        .encounters = GMAP_ENCOUNTERS_MONSTERS,
        .iconPreClear = 0x0F,
        .iconPostClear = 0x0F,
        .chapteridx_eirika = 0x39,
        .chapteridx_ephram = 0x39,
        .unk_06 = 0xFFFF,
        .unk_08 = { 0xFF, 0xFF, 0xFF, 0xFF, },
        .armory = (u16 *) 0x08A3F076,
        .vendor = (u16 *) 0x08A3F168,
        .secretShop = (u16 *) 0x08A3F21A,
        .x = 344,
        .y = 40,
        .nameTextId = 0x066C, // TODO: msgid "Melkaen Coast[.]"
        .shipTravelFlag = 1,
    },
};